-- =============================================================
-- ACUMULADO - Diagnostico de filas exclusivas ANTES vs DESPUES
-- Uso:
--   1. Ejecutar despues de 06_COMPARAR_EQUIVALENCIA_ACUMULADO.sql
--   2. Solo inspecciona llaves exclusivas de PR_REPRESTAMOS
-- =============================================================

DEFINE RUN_LABEL_BASE = ANTES
DEFINE RUN_LABEL_TEST = DESPUES

PROMPT
PROMPT === 1. Llaves exclusivas en PR_REPRESTAMOS ===
WITH A AS (
    SELECT CODIGO_EMPRESA,
           CODIGO_CLIENTE,
           NO_CREDITO,
           FECHA_CORTE,
           ESTADO
      FROM OPTACUM_SNAP_REPRESTAMOS
     WHERE RUN_LABEL = UPPER('&RUN_LABEL_BASE')
),
D AS (
    SELECT CODIGO_EMPRESA,
           CODIGO_CLIENTE,
           NO_CREDITO,
           FECHA_CORTE,
           ESTADO
      FROM OPTACUM_SNAP_REPRESTAMOS
     WHERE RUN_LABEL = UPPER('&RUN_LABEL_TEST')
)
SELECT 'SOLO_EN_' || UPPER('&RUN_LABEL_TEST') AS ORIGEN,
       D.CODIGO_EMPRESA,
       D.CODIGO_CLIENTE,
       D.NO_CREDITO,
       D.FECHA_CORTE,
       D.ESTADO
  FROM D
 WHERE NOT EXISTS (
           SELECT 1
             FROM A
            WHERE A.CODIGO_EMPRESA = D.CODIGO_EMPRESA
              AND A.CODIGO_CLIENTE = D.CODIGO_CLIENTE
              AND A.NO_CREDITO = D.NO_CREDITO
              AND A.FECHA_CORTE = D.FECHA_CORTE
       )
UNION ALL
SELECT 'SOLO_EN_' || UPPER('&RUN_LABEL_BASE'),
       A.CODIGO_EMPRESA,
       A.CODIGO_CLIENTE,
       A.NO_CREDITO,
       A.FECHA_CORTE,
       A.ESTADO
  FROM A
 WHERE NOT EXISTS (
           SELECT 1
             FROM D
            WHERE D.CODIGO_EMPRESA = A.CODIGO_EMPRESA
              AND D.CODIGO_CLIENTE = A.CODIGO_CLIENTE
              AND D.NO_CREDITO = A.NO_CREDITO
              AND D.FECHA_CORTE = A.FECHA_CORTE
       )
 ORDER BY 1, 2, 3, 4;

PROMPT
PROMPT === 2. Detalle de PR_REPRESTAMOS para llaves exclusivas ===
WITH EXCLUSIVOS AS (
    SELECT CODIGO_EMPRESA,
           CODIGO_CLIENTE,
           NO_CREDITO,
           FECHA_CORTE
      FROM OPTACUM_SNAP_REPRESTAMOS A
     WHERE RUN_LABEL = UPPER('&RUN_LABEL_BASE')
       AND NOT EXISTS (
               SELECT 1
                 FROM OPTACUM_SNAP_REPRESTAMOS D
                WHERE D.RUN_LABEL = UPPER('&RUN_LABEL_TEST')
                  AND D.CODIGO_EMPRESA = A.CODIGO_EMPRESA
                  AND D.CODIGO_CLIENTE = A.CODIGO_CLIENTE
                  AND D.NO_CREDITO = A.NO_CREDITO
                  AND D.FECHA_CORTE = A.FECHA_CORTE
           )
    UNION
    SELECT CODIGO_EMPRESA,
           CODIGO_CLIENTE,
           NO_CREDITO,
           FECHA_CORTE
      FROM OPTACUM_SNAP_REPRESTAMOS D
     WHERE RUN_LABEL = UPPER('&RUN_LABEL_TEST')
       AND NOT EXISTS (
               SELECT 1
                 FROM OPTACUM_SNAP_REPRESTAMOS A
                WHERE A.RUN_LABEL = UPPER('&RUN_LABEL_BASE')
                  AND A.CODIGO_EMPRESA = D.CODIGO_EMPRESA
                  AND A.CODIGO_CLIENTE = D.CODIGO_CLIENTE
                  AND A.NO_CREDITO = D.NO_CREDITO
                  AND A.FECHA_CORTE = D.FECHA_CORTE
           )
)
SELECT R.RUN_LABEL,
       R.CODIGO_EMPRESA,
       R.CODIGO_CLIENTE,
       R.NO_CREDITO,
       R.FECHA_CORTE,
       R.ID_REPRESTAMO,
       R.ESTADO,
       R.CODIGO_PRECALIFICACION,
       R.DIAS_ATRASO,
       R.MTO_CREDITO_ACTUAL,
       R.ES_FIADOR,
       NVL(R.OBSERVACIONES, '#') AS OBSERVACIONES
  FROM OPTACUM_SNAP_REPRESTAMOS R
  JOIN EXCLUSIVOS X
    ON X.CODIGO_EMPRESA = R.CODIGO_EMPRESA
   AND X.CODIGO_CLIENTE = R.CODIGO_CLIENTE
   AND X.NO_CREDITO = R.NO_CREDITO
   AND X.FECHA_CORTE = R.FECHA_CORTE
 WHERE R.RUN_LABEL IN (UPPER('&RUN_LABEL_BASE'), UPPER('&RUN_LABEL_TEST'))
 ORDER BY R.CODIGO_EMPRESA, R.CODIGO_CLIENTE, R.NO_CREDITO, R.RUN_LABEL;

PROMPT
PROMPT === 3. Conteos relacionados por llave exclusiva y run ===
WITH EXCLUSIVOS AS (
    SELECT CODIGO_EMPRESA,
           CODIGO_CLIENTE,
           NO_CREDITO,
           FECHA_CORTE
      FROM OPTACUM_SNAP_REPRESTAMOS A
     WHERE RUN_LABEL = UPPER('&RUN_LABEL_BASE')
       AND NOT EXISTS (
               SELECT 1
                 FROM OPTACUM_SNAP_REPRESTAMOS D
                WHERE D.RUN_LABEL = UPPER('&RUN_LABEL_TEST')
                  AND D.CODIGO_EMPRESA = A.CODIGO_EMPRESA
                  AND D.CODIGO_CLIENTE = A.CODIGO_CLIENTE
                  AND D.NO_CREDITO = A.NO_CREDITO
                  AND D.FECHA_CORTE = A.FECHA_CORTE
           )
    UNION
    SELECT CODIGO_EMPRESA,
           CODIGO_CLIENTE,
           NO_CREDITO,
           FECHA_CORTE
      FROM OPTACUM_SNAP_REPRESTAMOS D
     WHERE RUN_LABEL = UPPER('&RUN_LABEL_TEST')
       AND NOT EXISTS (
               SELECT 1
                 FROM OPTACUM_SNAP_REPRESTAMOS A
                WHERE A.RUN_LABEL = UPPER('&RUN_LABEL_BASE')
                  AND A.CODIGO_EMPRESA = D.CODIGO_EMPRESA
                  AND A.CODIGO_CLIENTE = D.CODIGO_CLIENTE
                  AND A.NO_CREDITO = D.NO_CREDITO
                  AND A.FECHA_CORTE = D.FECHA_CORTE
           )
),
MAPEO AS (
    SELECT R.RUN_LABEL,
           R.CODIGO_EMPRESA,
           R.CODIGO_CLIENTE,
           R.NO_CREDITO,
           R.FECHA_CORTE,
           R.ID_REPRESTAMO
      FROM OPTACUM_SNAP_REPRESTAMOS R
      JOIN EXCLUSIVOS X
        ON X.CODIGO_EMPRESA = R.CODIGO_EMPRESA
       AND X.CODIGO_CLIENTE = R.CODIGO_CLIENTE
       AND X.NO_CREDITO = R.NO_CREDITO
       AND X.FECHA_CORTE = R.FECHA_CORTE
)
SELECT M.RUN_LABEL,
       M.CODIGO_EMPRESA,
       M.CODIGO_CLIENTE,
       M.NO_CREDITO,
       M.FECHA_CORTE,
       (SELECT COUNT(*)
          FROM OPTACUM_SNAP_SOLICITUD S
         WHERE S.RUN_LABEL = M.RUN_LABEL
           AND S.CODIGO_EMPRESA = M.CODIGO_EMPRESA
           AND S.ID_REPRESTAMO = M.ID_REPRESTAMO) AS CNT_SOLICITUD,
       (SELECT COUNT(*)
          FROM OPTACUM_SNAP_CANALES C
         WHERE C.RUN_LABEL = M.RUN_LABEL
           AND C.CODIGO_EMPRESA = M.CODIGO_EMPRESA
           AND C.ID_REPRESTAMO = M.ID_REPRESTAMO) AS CNT_CANALES,
       (SELECT COUNT(*)
          FROM OPTACUM_SNAP_OPCIONES O
         WHERE O.RUN_LABEL = M.RUN_LABEL
           AND O.CODIGO_EMPRESA = M.CODIGO_EMPRESA
           AND O.ID_REPRESTAMO = M.ID_REPRESTAMO) AS CNT_OPCIONES,
       (SELECT COUNT(*)
          FROM OPTACUM_SNAP_BITACORA B
         WHERE B.RUN_LABEL = M.RUN_LABEL
           AND B.CODIGO_EMPRESA = M.CODIGO_EMPRESA
           AND B.ID_REPRESTAMO = M.ID_REPRESTAMO) AS CNT_BITACORA
  FROM MAPEO M
 ORDER BY M.CODIGO_EMPRESA, M.CODIGO_CLIENTE, M.NO_CREDITO, M.RUN_LABEL;

PROMPT
PROMPT === 4. Bitacora por llave exclusiva y run ===
WITH EXCLUSIVOS AS (
    SELECT CODIGO_EMPRESA,
           CODIGO_CLIENTE,
           NO_CREDITO,
           FECHA_CORTE
      FROM OPTACUM_SNAP_REPRESTAMOS A
     WHERE RUN_LABEL = UPPER('&RUN_LABEL_BASE')
       AND NOT EXISTS (
               SELECT 1
                 FROM OPTACUM_SNAP_REPRESTAMOS D
                WHERE D.RUN_LABEL = UPPER('&RUN_LABEL_TEST')
                  AND D.CODIGO_EMPRESA = A.CODIGO_EMPRESA
                  AND D.CODIGO_CLIENTE = A.CODIGO_CLIENTE
                  AND D.NO_CREDITO = A.NO_CREDITO
                  AND D.FECHA_CORTE = A.FECHA_CORTE
           )
    UNION
    SELECT CODIGO_EMPRESA,
           CODIGO_CLIENTE,
           NO_CREDITO,
           FECHA_CORTE
      FROM OPTACUM_SNAP_REPRESTAMOS D
     WHERE RUN_LABEL = UPPER('&RUN_LABEL_TEST')
       AND NOT EXISTS (
               SELECT 1
                 FROM OPTACUM_SNAP_REPRESTAMOS A
                WHERE A.RUN_LABEL = UPPER('&RUN_LABEL_BASE')
                  AND A.CODIGO_EMPRESA = D.CODIGO_EMPRESA
                  AND A.CODIGO_CLIENTE = D.CODIGO_CLIENTE
                  AND A.NO_CREDITO = D.NO_CREDITO
                  AND A.FECHA_CORTE = D.FECHA_CORTE
           )
),
MAPEO AS (
    SELECT R.RUN_LABEL,
           R.CODIGO_EMPRESA,
           R.CODIGO_CLIENTE,
           R.NO_CREDITO,
           R.FECHA_CORTE,
           R.ID_REPRESTAMO
      FROM OPTACUM_SNAP_REPRESTAMOS R
      JOIN EXCLUSIVOS X
        ON X.CODIGO_EMPRESA = R.CODIGO_EMPRESA
       AND X.CODIGO_CLIENTE = R.CODIGO_CLIENTE
       AND X.NO_CREDITO = R.NO_CREDITO
       AND X.FECHA_CORTE = R.FECHA_CORTE
)
SELECT M.RUN_LABEL,
       M.CODIGO_EMPRESA,
       M.CODIGO_CLIENTE,
       M.NO_CREDITO,
       M.FECHA_CORTE,
       B.CODIGO_ESTADO,
       NVL(B.STEP, '#') AS STEP_NORM,
       NVL(B.CANAL, '#') AS CANAL_NORM,
       NVL(B.OBSERVACIONES, '#') AS OBS_NORM
  FROM MAPEO M
  JOIN OPTACUM_SNAP_BITACORA B
    ON B.RUN_LABEL = M.RUN_LABEL
   AND B.CODIGO_EMPRESA = M.CODIGO_EMPRESA
   AND B.ID_REPRESTAMO = M.ID_REPRESTAMO
 ORDER BY M.CODIGO_EMPRESA, M.CODIGO_CLIENTE, M.NO_CREDITO, M.RUN_LABEL, B.CODIGO_ESTADO, B.STEP;
