-- =============================================================
-- ACUMULADO - Comparacion por etapas ANTES vs DESPUES
-- Requiere snapshots generados con 03A_TRAZAR_ETAPAS_ACUMULADO.sql
--
-- Objetivo:
--   Identificar en cual etapa cambia el universo de PR_REPRESTAMOS
--   y seguir la evolucion de las llaves exclusivas finales.
-- =============================================================

DEFINE RUN_LABEL_BASE = ANTES
DEFINE RUN_LABEL_TEST = DESPUES
DEFINE FINAL_STAGE = 06_POST_ACTUALIZA_PRECALIFICACION

PROMPT
PROMPT === 1. Conteo de filas por etapa y run ===
WITH S AS (
    SELECT RUN_LABEL,
           STAGE_NAME,
           COUNT(*) AS CNT
      FROM OPTACUM_SNAP_ETAPAS_REPRESTAMOS
     WHERE RUN_LABEL IN (UPPER('&RUN_LABEL_BASE'), UPPER('&RUN_LABEL_TEST'))
     GROUP BY RUN_LABEL, STAGE_NAME
)
SELECT STAGE_NAME,
       MAX(CASE WHEN RUN_LABEL = UPPER('&RUN_LABEL_BASE') THEN CNT END) AS CNT_BASE,
       MAX(CASE WHEN RUN_LABEL = UPPER('&RUN_LABEL_TEST') THEN CNT END) AS CNT_TEST
  FROM S
 GROUP BY STAGE_NAME
 ORDER BY STAGE_NAME;

PROMPT
PROMPT === 2. Conteo de exclusivas por etapa ===
WITH A AS (
    SELECT STAGE_NAME,
           CODIGO_EMPRESA,
           CODIGO_CLIENTE,
           NO_CREDITO,
           FECHA_CORTE,
           ESTADO
      FROM OPTACUM_SNAP_ETAPAS_REPRESTAMOS
     WHERE RUN_LABEL = UPPER('&RUN_LABEL_BASE')
),
D AS (
    SELECT STAGE_NAME,
           CODIGO_EMPRESA,
           CODIGO_CLIENTE,
           NO_CREDITO,
           FECHA_CORTE,
           ESTADO
      FROM OPTACUM_SNAP_ETAPAS_REPRESTAMOS
     WHERE RUN_LABEL = UPPER('&RUN_LABEL_TEST')
),
DIFF AS (
    SELECT NVL(A.STAGE_NAME, D.STAGE_NAME) AS STAGE_NAME,
           CASE
               WHEN A.CODIGO_EMPRESA IS NULL THEN 'SOLO_EN_' || UPPER('&RUN_LABEL_TEST')
               WHEN D.CODIGO_EMPRESA IS NULL THEN 'SOLO_EN_' || UPPER('&RUN_LABEL_BASE')
           END AS ORIGEN
      FROM A
      FULL OUTER JOIN D
        ON D.STAGE_NAME = A.STAGE_NAME
       AND D.CODIGO_EMPRESA = A.CODIGO_EMPRESA
       AND D.CODIGO_CLIENTE = A.CODIGO_CLIENTE
       AND D.NO_CREDITO = A.NO_CREDITO
       AND D.FECHA_CORTE = A.FECHA_CORTE
     WHERE A.CODIGO_EMPRESA IS NULL
        OR D.CODIGO_EMPRESA IS NULL
)
SELECT STAGE_NAME,
       SUM(CASE WHEN ORIGEN = 'SOLO_EN_' || UPPER('&RUN_LABEL_BASE') THEN 1 ELSE 0 END) AS SOLO_BASE,
       SUM(CASE WHEN ORIGEN = 'SOLO_EN_' || UPPER('&RUN_LABEL_TEST') THEN 1 ELSE 0 END) AS SOLO_TEST
  FROM DIFF
 GROUP BY STAGE_NAME
 ORDER BY STAGE_NAME;

PROMPT
PROMPT === 3. Llaves exclusivas por etapa ===
WITH A AS (
    SELECT STAGE_NAME,
           CODIGO_EMPRESA,
           CODIGO_CLIENTE,
           NO_CREDITO,
           FECHA_CORTE,
           ESTADO,
           DIAS_ATRASO,
           MTO_CREDITO_ACTUAL
      FROM OPTACUM_SNAP_ETAPAS_REPRESTAMOS
     WHERE RUN_LABEL = UPPER('&RUN_LABEL_BASE')
),
D AS (
    SELECT STAGE_NAME,
           CODIGO_EMPRESA,
           CODIGO_CLIENTE,
           NO_CREDITO,
           FECHA_CORTE,
           ESTADO,
           DIAS_ATRASO,
           MTO_CREDITO_ACTUAL
      FROM OPTACUM_SNAP_ETAPAS_REPRESTAMOS
     WHERE RUN_LABEL = UPPER('&RUN_LABEL_TEST')
)
SELECT NVL(A.STAGE_NAME, D.STAGE_NAME) AS STAGE_NAME,
       CASE
           WHEN A.CODIGO_EMPRESA IS NULL THEN 'SOLO_EN_' || UPPER('&RUN_LABEL_TEST')
           WHEN D.CODIGO_EMPRESA IS NULL THEN 'SOLO_EN_' || UPPER('&RUN_LABEL_BASE')
       END AS ORIGEN,
       NVL(D.CODIGO_EMPRESA, A.CODIGO_EMPRESA) AS CODIGO_EMPRESA,
       NVL(D.CODIGO_CLIENTE, A.CODIGO_CLIENTE) AS CODIGO_CLIENTE,
       NVL(D.NO_CREDITO, A.NO_CREDITO) AS NO_CREDITO,
       NVL(D.FECHA_CORTE, A.FECHA_CORTE) AS FECHA_CORTE,
       NVL(D.ESTADO, A.ESTADO) AS ESTADO,
       NVL(D.DIAS_ATRASO, A.DIAS_ATRASO) AS DIAS_ATRASO,
       NVL(D.MTO_CREDITO_ACTUAL, A.MTO_CREDITO_ACTUAL) AS MTO_CREDITO_ACTUAL
  FROM A
  FULL OUTER JOIN D
    ON D.STAGE_NAME = A.STAGE_NAME
   AND D.CODIGO_EMPRESA = A.CODIGO_EMPRESA
   AND D.CODIGO_CLIENTE = A.CODIGO_CLIENTE
   AND D.NO_CREDITO = A.NO_CREDITO
   AND D.FECHA_CORTE = A.FECHA_CORTE
 WHERE A.CODIGO_EMPRESA IS NULL
    OR D.CODIGO_EMPRESA IS NULL
 ORDER BY 1, 2, 3, 4, 5;

PROMPT
PROMPT === 4. Evolucion de llaves exclusivas finales por etapa ===
WITH A_FIN AS (
    SELECT CODIGO_EMPRESA,
           CODIGO_CLIENTE,
           NO_CREDITO,
           FECHA_CORTE
      FROM OPTACUM_SNAP_ETAPAS_REPRESTAMOS
     WHERE RUN_LABEL = UPPER('&RUN_LABEL_BASE')
       AND STAGE_NAME = '&FINAL_STAGE'
),
D_FIN AS (
    SELECT CODIGO_EMPRESA,
           CODIGO_CLIENTE,
           NO_CREDITO,
           FECHA_CORTE
      FROM OPTACUM_SNAP_ETAPAS_REPRESTAMOS
     WHERE RUN_LABEL = UPPER('&RUN_LABEL_TEST')
       AND STAGE_NAME = '&FINAL_STAGE'
),
EXCL_FINALES AS (
    SELECT NVL(A_FIN.CODIGO_EMPRESA, D_FIN.CODIGO_EMPRESA) AS CODIGO_EMPRESA,
           NVL(A_FIN.CODIGO_CLIENTE, D_FIN.CODIGO_CLIENTE) AS CODIGO_CLIENTE,
           NVL(A_FIN.NO_CREDITO, D_FIN.NO_CREDITO) AS NO_CREDITO,
           NVL(A_FIN.FECHA_CORTE, D_FIN.FECHA_CORTE) AS FECHA_CORTE
      FROM A_FIN
      FULL OUTER JOIN D_FIN
        ON D_FIN.CODIGO_EMPRESA = A_FIN.CODIGO_EMPRESA
       AND D_FIN.CODIGO_CLIENTE = A_FIN.CODIGO_CLIENTE
       AND D_FIN.NO_CREDITO = A_FIN.NO_CREDITO
       AND D_FIN.FECHA_CORTE = A_FIN.FECHA_CORTE
     WHERE A_FIN.CODIGO_EMPRESA IS NULL
        OR D_FIN.CODIGO_EMPRESA IS NULL
)
SELECT T.RUN_LABEL,
       T.STAGE_NAME,
       T.CODIGO_EMPRESA,
       T.CODIGO_CLIENTE,
       T.NO_CREDITO,
       T.FECHA_CORTE,
       T.ESTADO,
       T.DIAS_ATRASO,
       T.MTO_CREDITO_ACTUAL
  FROM OPTACUM_SNAP_ETAPAS_REPRESTAMOS T
  JOIN EXCL_FINALES E
    ON E.CODIGO_EMPRESA = T.CODIGO_EMPRESA
   AND E.CODIGO_CLIENTE = T.CODIGO_CLIENTE
   AND E.NO_CREDITO = T.NO_CREDITO
   AND E.FECHA_CORTE = T.FECHA_CORTE
 WHERE T.RUN_LABEL IN (UPPER('&RUN_LABEL_BASE'), UPPER('&RUN_LABEL_TEST'))
 ORDER BY T.CODIGO_EMPRESA,
          T.CODIGO_CLIENTE,
          T.NO_CREDITO,
          T.RUN_LABEL,
          T.STAGE_NAME;
