-- =============================================================
-- ACUMULADO - Restaura LOTE_DE_CARAGA_REPRESTAMO
-- Usa el respaldo guardado en OPTACUM_PARAM_BACKUP.
-- =============================================================

SET SERVEROUTPUT ON SIZE UNLIMITED;

DECLARE
    v_valor_original VARCHAR2(4000);
BEGIN
    SELECT VALOR_ORIGINAL
      INTO v_valor_original
      FROM OPTACUM_PARAM_BACKUP
     WHERE CODIGO_EMPRESA = PR.PR_PKG_REPRESTAMOS.F_OBT_EMPRESA_REPRESTAMO
       AND CODIGO_MVP = 'REPRESTAMOS'
       AND CODIGO_PARAMETRO = 'LOTE_DE_CARAGA_REPRESTAMO';

    UPDATE PA.PA_PARAMETROS_MVP
       SET VALOR = v_valor_original,
           MODIFICADO_POR = USER
     WHERE CODIGO_EMPRESA = PR.PR_PKG_REPRESTAMOS.F_OBT_EMPRESA_REPRESTAMO
       AND CODIGO_MVP = 'REPRESTAMOS'
       AND CODIGO_PARAMETRO = 'LOTE_DE_CARAGA_REPRESTAMO';

    COMMIT;

    DBMS_OUTPUT.PUT_LINE('LOTE_DE_CARAGA_REPRESTAMO restaurado a: ' || v_valor_original);
END;
/

SELECT CODIGO_EMPRESA,
       CODIGO_MVP,
       CODIGO_PARAMETRO,
       VALOR
  FROM PA.PA_PARAMETROS_MVP
 WHERE CODIGO_EMPRESA = PR.PR_PKG_REPRESTAMOS.F_OBT_EMPRESA_REPRESTAMO
   AND CODIGO_MVP = 'REPRESTAMOS'
   AND CODIGO_PARAMETRO = 'LOTE_DE_CARAGA_REPRESTAMO';
