CREATE TABLE VALORES_TASAS_INTERES (
  COD_EMPRESA       VARCHAR2(5)    NOT NULL,
  COD_TASA          VARCHAR2(5)    NOT NULL,
  FEC_INICIO        DATE           NOT NULL,
  VAL_TASA          NUMBER(10,6)   NOT NULL,
  INCLUIDO_POR      VARCHAR2(30)   NOT NULL,
  FEC_INCLUSION     DATE           NOT NULL,
  MODIFICADO_POR    VARCHAR2(30),  -- Puede ser NULL
  FEC_MODIFICACION  DATE,          -- Puede ser NULL

  CONSTRAINT PK_VALORES_TASAS
    PRIMARY KEY (COD_EMPRESA, COD_TASA, FEC_INICIO)
);

-- Valores de ejemplo

INSERT INTO VALORES_TASAS_INTERES (
  COD_EMPRESA, COD_TASA, FEC_INICIO, VAL_TASA, INCLUIDO_POR, FEC_INCLUSION,
  MODIFICADO_POR, FEC_MODIFICACION
) VALUES (
  '1', 'TCDD', 
  TO_DATE('23/02/2014','DD/MM/YYYY'),
  11.750000, 
  'MIGRACION', 
  TO_DATE('06/10/2015 16:35:07','DD/MM/YYYY HH24:MI:SS'),
  NULL, NULL
);

INSERT INTO VALORES_TASAS_INTERES (
  COD_EMPRESA, COD_TASA, FEC_INICIO, VAL_TASA, INCLUIDO_POR, FEC_INCLUSION,
  MODIFICADO_POR, FEC_MODIFICACION
) VALUES (
  '1', 'TACD', 
  TO_DATE('01/01/1999','DD/MM/YYYY'),
  8.250000, 
  'MIGRACION', 
  TO_DATE('06/10/2015 16:35:13','DD/MM/YYYY HH24:MI:SS'),
  NULL, NULL
);

INSERT INTO VALORES_TASAS_INTERES (
  COD_EMPRESA, COD_TASA, FEC_INICIO, VAL_TASA, INCLUIDO_POR, FEC_INCLUSION,
  MODIFICADO_POR, FEC_MODIFICACION
) VALUES (
  '1', 'TACE', 
  TO_DATE('02/02/1999','DD/MM/YYYY'),
  7.250000, 
  'MIGRACION', 
  TO_DATE('06/10/2015 16:35:13','DD/MM/YYYY HH24:MI:SS'),
  NULL, NULL
);

INSERT INTO VALORES_TASAS_INTERES (
  COD_EMPRESA, COD_TASA, FEC_INICIO, VAL_TASA, INCLUIDO_POR, FEC_INCLUSION,
  MODIFICADO_POR, FEC_MODIFICACION
) VALUES (
  '1', 'TACP', 
  TO_DATE('02/01/1999','DD/MM/YYYY'),
  7.000000, 
  'MIGRACION', 
  TO_DATE('06/10/2015 16:35:13','DD/MM/YYYY HH24:MI:SS'),
  NULL, NULL
);

INSERT INTO VALORES_TASAS_INTERES (
  COD_EMPRESA, COD_TASA, FEC_INICIO, VAL_TASA, INCLUIDO_POR, FEC_INCLUSION,
  MODIFICADO_POR, FEC_MODIFICACION
) VALUES (
  '1', 'TCCP', 
  TO_DATE('02/02/1999','DD/MM/YYYY'),
  5.000000, 
  'MIGRACION', 
  TO_DATE('06/10/2015 16:35:13','DD/MM/YYYY HH24:MI:SS'),
  NULL, NULL
);

INSERT INTO VALORES_TASAS_INTERES (
  COD_EMPRESA, COD_TASA, FEC_INICIO, VAL_TASA, INCLUIDO_POR, FEC_INCLUSION,
  MODIFICADO_POR, FEC_MODIFICACION
) VALUES (
  '1', 'TCDSR', 
  TO_DATE('02/02/1999','DD/MM/YYYY'),
  5.000000, 
  'MIGRACION', 
  TO_DATE('06/10/2015 16:35:13','DD/MM/YYYY HH24:MI:SS'),
  NULL, NULL
);

INSERT INTO VALORES_TASAS_INTERES (
  COD_EMPRESA, COD_TASA, FEC_INICIO, VAL_TASA, INCLUIDO_POR, FEC_INCLUSION,
  MODIFICADO_POR, FEC_MODIFICACION
) VALUES (
  '1', 'TCPP', 
  TO_DATE('02/02/1999','DD/MM/YYYY'),
  6.000000, 
  'MIGRACION', 
  TO_DATE('06/10/2015 16:35:13','DD/MM/YYYY HH24:MI:SS'),
  NULL, NULL
);
