  CREATE TABLE "PA"."LISTA_NEGRA" 
   (	"COD_PERSONA" VARCHAR2(15 BYTE), 
	"CONSECUTIVO" NUMBER(6,0), 
	"ORIGEN" VARCHAR2(20 BYTE) CONSTRAINT "NN_LISTA_NEGRA_ORIGEN" NOT NULL ENABLE, 
	"REFERENCIA" VARCHAR2(20 BYTE), 
	"FEC_INGRESO" DATE CONSTRAINT "NN_LISTA_FEC_INGRESO" NOT NULL ENABLE, 
	"FEC_VENCIMIENTO" DATE CONSTRAINT "NN_LISTA_NEGRA_FEC_VENCIMIENTO" NOT NULL ENABLE, 
	"COD_MOTIVO" VARCHAR2(5 BYTE) CONSTRAINT "NN_LISTA_NEGRA_COD_MOTIVO" NOT NULL ENABLE, 
	"COD_BANCO" VARCHAR2(5 BYTE), 
	"NUM_CUENTA" VARCHAR2(20 BYTE), 
	"MON_MULTA" NUMBER(18,2), 
	"DETALLE" VARCHAR2(500 BYTE), 
	"ADICIONADO_POR" VARCHAR2(10 BYTE), 
	"FECHA_ADICION" DATE, 
	"MODIFICADO_POR" VARCHAR2(10 BYTE), 
	"FECHA_MODIFICACION" DATE, 
	"INCLUIDO" VARCHAR2(1 BYTE) DEFAULT 'S', 
	"ESTADO_ANTERIOR" VARCHAR2(1 BYTE), 
	 CONSTRAINT "FK_LISTA_NEGRA_MOT_LISTA" FOREIGN KEY ("COD_MOTIVO")
	  REFERENCES "PA"."MOT_LISTA_NEGRA" ("COD_MOTIVO") ENABLE, 
	 CONSTRAINT "FK_LISTA_NEGRA_PERSONAS" FOREIGN KEY ("COD_PERSONA")
	  REFERENCES "PA"."PERSONAS" ("COD_PERSONA") ENABLE, 
	 CONSTRAINT "FK_LISTA_NEGRA_ENTES_EXTERNOS" FOREIGN KEY ("COD_BANCO")
	  REFERENCES "PA"."ENTES_EXTERNOS" ("COD_ENTE") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 80 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PA_DAT" ;
  CREATE UNIQUE INDEX "PA"."PK_LISTA_NEGRA" ON "PA"."LISTA_NEGRA" ("COD_PERSONA", "CONSECUTIVO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PA_IDX" ;
ALTER TABLE "PA"."LISTA_NEGRA" ADD CONSTRAINT "PK_LISTA_NEGRA" PRIMARY KEY ("COD_PERSONA", "CONSECUTIVO")
  USING INDEX "PA"."PK_LISTA_NEGRA"  ENABLE;

   COMMENT ON COLUMN "PA"."LISTA_NEGRA"."COD_PERSONA" IS 'codigo de persona.';
   COMMENT ON COLUMN "PA"."LISTA_NEGRA"."CONSECUTIVO" IS 'consecutivo de la lista negra';
   COMMENT ON COLUMN "PA"."LISTA_NEGRA"."ORIGEN" IS 'Origen de la persona';
   COMMENT ON COLUMN "PA"."LISTA_NEGRA"."REFERENCIA" IS 'Referencia del porque la persona esta en lista negra';
   COMMENT ON COLUMN "PA"."LISTA_NEGRA"."FEC_INGRESO" IS 'Fecha de Ingreso a la lista negra';
   COMMENT ON COLUMN "PA"."LISTA_NEGRA"."FEC_VENCIMIENTO" IS 'Fecha de vencimiento en la lista negra';
   COMMENT ON COLUMN "PA"."LISTA_NEGRA"."COD_MOTIVO" IS 'codigo del motivo de la mala referencia';
   COMMENT ON COLUMN "PA"."LISTA_NEGRA"."COD_BANCO" IS 'codigo de la entidad externa';
   COMMENT ON COLUMN "PA"."LISTA_NEGRA"."NUM_CUENTA" IS 'numera de la cuenta en el ente externo';
   COMMENT ON COLUMN "PA"."LISTA_NEGRA"."MON_MULTA" IS 'monto de la multa';
   COMMENT ON COLUMN "PA"."LISTA_NEGRA"."DETALLE" IS 'Detalle del porque esta en la lista negra';
   COMMENT ON COLUMN "PA"."LISTA_NEGRA"."ADICIONADO_POR" IS 'Usuario agrego';
   COMMENT ON COLUMN "PA"."LISTA_NEGRA"."FECHA_ADICION" IS 'Fecha de adicion';
   COMMENT ON COLUMN "PA"."LISTA_NEGRA"."MODIFICADO_POR" IS 'Usuario modifico';
   COMMENT ON COLUMN "PA"."LISTA_NEGRA"."FECHA_MODIFICACION" IS 'Fecha de modificacion';
   COMMENT ON COLUMN "PA"."LISTA_NEGRA"."INCLUIDO" IS 'Indica si la persona esta activa en la lista. Si su valor es N, es como si no estuviera en la lista.';
   COMMENT ON COLUMN "PA"."LISTA_NEGRA"."ESTADO_ANTERIOR" IS 'Indica el estado que tenia el cliente antes de entrar a lista negra';
   COMMENT ON TABLE "PA"."LISTA_NEGRA"  IS ' Lista negra de clientes';

  CREATE INDEX "PA"."LISTA_NEGRA_FK4" ON "PA"."LISTA_NEGRA" ("COD_MOTIVO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PA_IND" ;

  CREATE INDEX "PA"."LISTA_NEGRA_FK5" ON "PA"."LISTA_NEGRA" ("COD_BANCO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PA_IND" ;


  GRANT REFERENCES ON "PA"."LISTA_NEGRA" TO PUBLIC;
  GRANT SELECT ON "PA"."LISTA_NEGRA" TO "CONGEN";
  GRANT DELETE ON "PA"."LISTA_NEGRA" TO "BPA";
  GRANT INSERT ON "PA"."LISTA_NEGRA" TO "BPA";
  GRANT SELECT ON "PA"."LISTA_NEGRA" TO "BPA";
  GRANT UPDATE ON "PA"."LISTA_NEGRA" TO "BPA";
  GRANT ALTER ON "PA"."LISTA_NEGRA" TO "BPA";
  GRANT ALTER ON "PA"."LISTA_NEGRA" TO "CONGEN";
  GRANT DELETE ON "PA"."LISTA_NEGRA" TO "CONGEN";
  GRANT INSERT ON "PA"."LISTA_NEGRA" TO "CONGEN";
  GRANT UPDATE ON "PA"."LISTA_NEGRA" TO "CONGEN";
  GRANT ALTER ON "PA"."LISTA_NEGRA" TO PUBLIC;
  GRANT DELETE ON "PA"."LISTA_NEGRA" TO PUBLIC;
  GRANT INSERT ON "PA"."LISTA_NEGRA" TO PUBLIC;
  GRANT SELECT ON "PA"."LISTA_NEGRA" TO PUBLIC;
  GRANT UPDATE ON "PA"."LISTA_NEGRA" TO PUBLIC;
  GRANT SELECT ON "PA"."LISTA_NEGRA" TO "SII";
