CREATE TABLE "IA"."IA_HTTP_STATUS_CATALOG"
(
    "STATUS_CODE"        NUMBER CONSTRAINT "PK_HTTP_STATUS" PRIMARY KEY,
    "STATUS_CATEGORY"    VARCHAR2(20 BYTE) NOT NULL,
    "STATUS_NAME"        VARCHAR2(50 BYTE) NOT NULL,
    "STATUS_DESCRIPTION" VARCHAR2(200 BYTE),
    "IS_RETRIABLE"       CHAR(1 BYTE) DEFAULT 'N' NOT NULL,
    "SEVERITY_LEVEL"     VARCHAR2(10 BYTE) DEFAULT 'INFO' NOT NULL,
    CONSTRAINT "CHK_HTTP_STATUS_CATEGORY" CHECK (STATUS_CATEGORY IN ('INFORMATIONAL','SUCCESS','REDIRECTION','CLIENT_ERROR','SERVER_ERROR','UNKNOWN')),
    CONSTRAINT "CHK_HTTP_STATUS_RETRY" CHECK (IS_RETRIABLE IN ('Y','N')),
    CONSTRAINT "CHK_HTTP_STATUS_SEVERITY" CHECK (SEVERITY_LEVEL IN ('DEBUG','INFO','WARN','ERROR','FATAL'))
)
TABLESPACE "IA_DAT";

COMMENT ON TABLE "IA"."IA_HTTP_STATUS_CATALOG" IS 'Catálogo institucional de códigos HTTP con metadatos de clasificación y severidad.';
COMMENT ON COLUMN "IA"."IA_HTTP_STATUS_CATALOG"."STATUS_CODE" IS 'Código de estado HTTP.';
COMMENT ON COLUMN "IA"."IA_HTTP_STATUS_CATALOG"."STATUS_CATEGORY" IS 'Agrupación lógica del código (SUCCESS, CLIENT_ERROR, etc.).';
COMMENT ON COLUMN "IA"."IA_HTTP_STATUS_CATALOG"."STATUS_NAME" IS 'Nombre corto que describe el código.';
COMMENT ON COLUMN "IA"."IA_HTTP_STATUS_CATALOG"."STATUS_DESCRIPTION" IS 'Descripción funcional del código.';
COMMENT ON COLUMN "IA"."IA_HTTP_STATUS_CATALOG"."IS_RETRIABLE" IS 'Indica si el cliente debería reintentar la petición.';
COMMENT ON COLUMN "IA"."IA_HTTP_STATUS_CATALOG"."SEVERITY_LEVEL" IS 'Nivel de severidad sugerido para el log.';

INSERT INTO "IA"."IA_HTTP_STATUS_CATALOG" (STATUS_CODE, STATUS_CATEGORY, STATUS_NAME, STATUS_DESCRIPTION, IS_RETRIABLE, SEVERITY_LEVEL)
VALUES (200, 'SUCCESS', 'OK', 'La solicitud se procesó correctamente.', 'N', 'INFO');

INSERT INTO "IA"."IA_HTTP_STATUS_CATALOG" (STATUS_CODE, STATUS_CATEGORY, STATUS_NAME, STATUS_DESCRIPTION, IS_RETRIABLE, SEVERITY_LEVEL)
VALUES (201, 'SUCCESS', 'CREATED', 'Recurso creado exitosamente.', 'N', 'INFO');

INSERT INTO "IA"."IA_HTTP_STATUS_CATALOG" (STATUS_CODE, STATUS_CATEGORY, STATUS_NAME, STATUS_DESCRIPTION, IS_RETRIABLE, SEVERITY_LEVEL)
VALUES (400, 'CLIENT_ERROR', 'BAD_REQUEST', 'El servidor no pudo interpretar la solicitud por sintaxis inválida.', 'N', 'WARN');

INSERT INTO "IA"."IA_HTTP_STATUS_CATALOG" (STATUS_CODE, STATUS_CATEGORY, STATUS_NAME, STATUS_DESCRIPTION, IS_RETRIABLE, SEVERITY_LEVEL)
VALUES (401, 'CLIENT_ERROR', 'UNAUTHORIZED', 'Se requiere autenticación válida.', 'N', 'WARN');

INSERT INTO "IA"."IA_HTTP_STATUS_CATALOG" (STATUS_CODE, STATUS_CATEGORY, STATUS_NAME, STATUS_DESCRIPTION, IS_RETRIABLE, SEVERITY_LEVEL)
VALUES (404, 'CLIENT_ERROR', 'NOT_FOUND', 'El recurso solicitado no existe.', 'N', 'WARN');

INSERT INTO "IA"."IA_HTTP_STATUS_CATALOG" (STATUS_CODE, STATUS_CATEGORY, STATUS_NAME, STATUS_DESCRIPTION, IS_RETRIABLE, SEVERITY_LEVEL)
VALUES (500, 'SERVER_ERROR', 'INTERNAL_SERVER_ERROR', 'Error inesperado en el servidor.', 'N', 'ERROR');

INSERT INTO "IA"."IA_HTTP_STATUS_CATALOG" (STATUS_CODE, STATUS_CATEGORY, STATUS_NAME, STATUS_DESCRIPTION, IS_RETRIABLE, SEVERITY_LEVEL)
VALUES (503, 'SERVER_ERROR', 'SERVICE_UNAVAILABLE', 'Servicio temporalmente no disponible.', 'Y', 'ERROR');

COMMIT;