SELECT B.ROWID ID, b.id_represtamo, NVL(A.CLASIFICACION,'NULA') CLASIFICACION
FROM PA.PA_DE08_SIB A,
     PR.PR_REPRESTAMOS B
WHERE A.FECHA_CORTE = (SELECT MAX(FECHA_CORTE) FROM PA.PA_DE08_SIB)
AND PA.OBT_IDENTIFICACION_PERSONA(B.CODIGO_CLIENTE,'1') = A.ID_DEUDOR
AND B.ESTADO = 'RE';

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY(NULL,'DESPUES_IDX_DE08_SIB','ALL'));