SET TIMING ON

SELECT COUNT(*)
  FROM PR.PR_V_ENVIO_REPRESTAMOS;

SELECT ID_REPRESTAMO, CANAL, CANAL_DESC, NOMBRES, FECHA_PROCESO
  FROM PR.PR_V_ENVIO_REPRESTAMOS
 WHERE ROWNUM <= 20;

SELECT ID_REPRESTAMO,
       CANAL,
       CANAL_DESC,
       SUBSTR(TEXTO_MENSAJE, 1, 120) TEXTO_MENSAJE
  FROM PR.PR_V_ENVIO_REPRESTAMOS
 WHERE ROWNUM <= 20;

SELECT OWNER, OBJECT_TYPE, OBJECT_NAME, STATUS, LAST_DDL_TIME
  FROM ALL_OBJECTS
 WHERE OWNER = 'PR'
   AND OBJECT_NAME = 'PR_V_ENVIO_REPRESTAMOS';

SELECT DBMS_METADATA.GET_DDL('VIEW', 'PR_V_ENVIO_REPRESTAMOS', 'PR')
  FROM DUAL;
