CREATE TABLE "IA"."IA_API_LOGS"
(
    "ID_LOG"        NUMBER GENERATED ALWAYS AS IDENTITY,
    "FECHA_HORA"    TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    "ENDPOINT"      VARCHAR2(200 BYTE) NOT NULL,
    "METODO"        VARCHAR2(10 BYTE) NOT NULL,
    "USUARIO"       VARCHAR2(100 BYTE),
    "IP_ORIGEN"     VARCHAR2(50 BYTE),
    "SERVICE_NAME"  VARCHAR2(200 BYTE),
    "PARAMETROS"    CLOB,
    "STATUS_CODE"   NUMBER,
    "TIEMPO_MS"     NUMBER,
    "ERROR_MSG"     VARCHAR2(4000 BYTE),
    "RESPONSE_MSG"  CLOB,
    CONSTRAINT "PK_IA_API_LOGS" PRIMARY KEY ("ID_LOG")
        USING INDEX
            PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
            STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
                    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
                    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
            TABLESPACE "IA_IDX" ENABLE
)
SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
        PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
        BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "IA_DAT"
LOB ("PARAMETROS") STORE AS BASICFILE
(
    TABLESPACE "IA_DAT" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION
    NOCACHE LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
            PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
            BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
)
LOB ("RESPONSE_MSG") STORE AS BASICFILE
(
    TABLESPACE "IA_DAT" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION
    NOCACHE LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
            PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
            BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
);

CREATE INDEX "IA"."IDX_API_LOGS_FECHA" ON "IA"."IA_API_LOGS" ("FECHA_HORA")
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
            PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 MAXSIZE UNLIMITED
            BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "IA_IDX";

CREATE INDEX "IA"."IDX_API_LOGS_ENDPOINT" ON "IA"."IA_API_LOGS" ("ENDPOINT", "METODO", "STATUS_CODE")
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
            PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 MAXSIZE UNLIMITED
            BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "IA_IDX";

COMMENT ON TABLE "IA"."IA_API_LOGS" IS 'Bitácora centralizada de invocaciones a API''s expuestas mediante ORDS.';
COMMENT ON COLUMN "IA"."IA_API_LOGS"."ID_LOG" IS 'Identificador único del registro de log.';
COMMENT ON COLUMN "IA"."IA_API_LOGS"."FECHA_HORA" IS 'Fecha y hora exacta de la invocación.';
COMMENT ON COLUMN "IA"."IA_API_LOGS"."ENDPOINT" IS 'Nombre del endpoint ORDS o ruta del servicio.';
COMMENT ON COLUMN "IA"."IA_API_LOGS"."METODO" IS 'Método HTTP invocado (GET, POST, etc.).';
COMMENT ON COLUMN "IA"."IA_API_LOGS"."USUARIO" IS 'Usuario autenticado o sistema consumidor de la API.';
COMMENT ON COLUMN "IA"."IA_API_LOGS"."IP_ORIGEN" IS 'Dirección IP de origen reportada por ORDS.';
COMMENT ON COLUMN "IA"."IA_API_LOGS"."SERVICE_NAME" IS 'Nombre del procedimiento ORDS / paquete que atiende la solicitud.';
COMMENT ON COLUMN "IA"."IA_API_LOGS"."PARAMETROS" IS 'Carga o parámetros recibidos en la invocación.';
COMMENT ON COLUMN "IA"."IA_API_LOGS"."STATUS_CODE" IS 'Código de estado HTTP o interno devuelto al consumidor.';
COMMENT ON COLUMN "IA"."IA_API_LOGS"."TIEMPO_MS" IS 'Tiempo total de ejecución medido en milisegundos.';
COMMENT ON COLUMN "IA"."IA_API_LOGS"."ERROR_MSG" IS 'Mensaje resumido asociado a la ejecución (éxito o error).';
COMMENT ON COLUMN "IA"."IA_API_LOGS"."RESPONSE_MSG" IS 'Mensaje detallado o payload devuelto al consumidor.';

GRANT SELECT ON "IA"."IA_API_LOGS" TO PUBLIC;
GRANT INSERT ON "IA"."IA_API_LOGS" TO PUBLIC;
GRANT UPDATE ON "IA"."IA_API_LOGS" TO PUBLIC;
GRANT DELETE ON "IA"."IA_API_LOGS" TO PUBLIC;
GRANT ALTER ON "IA"."IA_API_LOGS" TO PUBLIC;
