PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "IA_DAT"  ENABLE, 
  CONSTRAINT "FK_LOG_ERROR_PARAM" FOREIGN KEY ("IDERROR")
  REFERENCES "IA"."LOG_ERROR" ("IDERROR") ENABLE
  ) SEGMENT CREATION IMMEDIATE 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "IA_DAT" 
LOB ("PARAMVALUE") STORE AS BASICFILE (
TABLESPACE "IA_DAT" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
NOCACHE LOGGING 
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

  COMMENT ON COLUMN "IA"."LOG_ERROR_PARAM"."IDERROR" IS 'ID Log Error';
  COMMENT ON COLUMN "IA"."LOG_ERROR_PARAM"."IDPARAM" IS 'PK Log Error Param';
  COMMENT ON COLUMN "IA"."LOG_ERROR_PARAM"."PARAMNAME" IS 'Nombre del parametro';
  COMMENT ON COLUMN "IA"."LOG_ERROR_PARAM"."PARAMVALUE" IS 'Valor del parametro';