-- Entorno de ejecucion: QA
-- Objetivo: confirmar que QA coincide exactamente con la captura recibida.
-- Este script es solo lectura.
-- En Toad, colocar el cursor dentro del WITH y ejecutar con F9.

SET PAGESIZE 500
SET LINESIZE 320

WITH ESPERADO AS
(
    SELECT 1 ORDEN, 1 CODIGO_EMPRESA, 164 TIPO_CREDITO, 'A' ESTADO,
           'RSALGADO' ADICIONADO_POR,
           TO_DATE('2024-01-11 08:47:43', 'YYYY-MM-DD HH24:MI:SS') FECHA_ADICION,
           CAST(NULL AS VARCHAR2(30)) MODIFICADO_POR,
           TO_DATE('2025-09-30 22:48:31', 'YYYY-MM-DD HH24:MI:SS') FECHA_MODIFICACION,
           0 OBSOLETO, 'N' CARGA, 'N' CREDITO_CAMPANA_ESPECIAL, 'N' CREDITO_FMO
      FROM DUAL
    UNION ALL
    SELECT 2, 1, 857, 'A', 'NOLIVO',
           TO_DATE('2025-08-27 10:24:09', 'YYYY-MM-DD HH24:MI:SS'), NULL,
           TO_DATE('2025-10-17 16:08:05', 'YYYY-MM-DD HH24:MI:SS'),
           0, 'N', 'S', 'S' FROM DUAL
    UNION ALL
    SELECT 3, 1, 752, 'A', 'NOLIVO',
           TO_DATE('2025-08-27 15:23:54', 'YYYY-MM-DD HH24:MI:SS'), NULL,
           TO_DATE('2025-10-16 14:45:31', 'YYYY-MM-DD HH24:MI:SS'),
           0, 'N', 'S', 'N' FROM DUAL
    UNION ALL
    SELECT 4, 1, 753, 'A', 'NOLIVO',
           TO_DATE('2025-08-27 15:24:57', 'YYYY-MM-DD HH24:MI:SS'), NULL,
           TO_DATE('2025-11-18 15:06:20', 'YYYY-MM-DD HH24:MI:SS'),
           0, 'N', 'N', 'S' FROM DUAL
    UNION ALL
    SELECT 5, 1, 883, 'A', 'NOLIVO',
           TO_DATE('2025-06-27 15:31:07', 'YYYY-MM-DD HH24:MI:SS'), NULL,
           TO_DATE('2025-07-17 11:19:19', 'YYYY-MM-DD HH24:MI:SS'),
           0, 'N', 'N', 'S' FROM DUAL
    UNION ALL
    SELECT 6, 1, 972, 'A', 'NOLIVO',
           TO_DATE('2025-07-02 15:19:59', 'YYYY-MM-DD HH24:MI:SS'), NULL,
           TO_DATE('2025-10-15 12:51:25', 'YYYY-MM-DD HH24:MI:SS'),
           0, 'N', 'S', 'S' FROM DUAL
    UNION ALL
    SELECT 7, 1, 854, 'A', 'NOLIVO',
           TO_DATE('2025-08-27 10:14:02', 'YYYY-MM-DD HH24:MI:SS'), NULL,
           TO_DATE('2025-10-17 10:33:43', 'YYYY-MM-DD HH24:MI:SS'),
           0, 'N', 'S', 'N' FROM DUAL
    UNION ALL
    SELECT 8, 1, 855, 'A', 'NOLIVO',
           TO_DATE('2025-08-27 10:23:15', 'YYYY-MM-DD HH24:MI:SS'), NULL,
           TO_DATE('2025-10-17 10:33:57', 'YYYY-MM-DD HH24:MI:SS'),
           0, 'N', 'S', 'N' FROM DUAL
    UNION ALL
    SELECT 9, 1, 751, 'A', 'NOLIVO',
           TO_DATE('2025-08-27 10:40:28', 'YYYY-MM-DD HH24:MI:SS'), NULL,
           TO_DATE('2025-11-18 15:05:49', 'YYYY-MM-DD HH24:MI:SS'),
           0, 'N', 'N', 'S' FROM DUAL
)
SELECT E.TIPO_CREDITO,
       CASE
           WHEN Q.TIPO_CREDITO IS NULL THEN 'FALTA_EN_QA'
           WHEN DECODE(Q.ESTADO, E.ESTADO, 1, 0) = 1
            AND DECODE(Q.ADICIONADO_POR, E.ADICIONADO_POR, 1, 0) = 1
            AND DECODE(Q.FECHA_ADICION, E.FECHA_ADICION, 1, 0) = 1
            AND DECODE(Q.MODIFICADO_POR, E.MODIFICADO_POR, 1, 0) = 1
            AND DECODE(Q.FECHA_MODIFICACION, E.FECHA_MODIFICACION, 1, 0) = 1
            AND DECODE(Q.OBSOLETO, E.OBSOLETO, 1, 0) = 1
            AND DECODE(Q.CARGA, E.CARGA, 1, 0) = 1
            AND DECODE(Q.CREDITO_CAMPANA_ESPECIAL, E.CREDITO_CAMPANA_ESPECIAL, 1, 0) = 1
            AND DECODE(Q.CREDITO_FMO, E.CREDITO_FMO, 1, 0) = 1
           THEN 'OK_IGUAL_CAPTURA'
           ELSE 'ERROR_DIFERENTE_CAPTURA'
       END AS RESULTADO,
       Q.CODIGO_EMPRESA,
       Q.ESTADO,
       Q.ADICIONADO_POR,
       TO_CHAR(Q.FECHA_ADICION, 'YYYY-MM-DD HH24:MI:SS') AS FECHA_ADICION,
       Q.MODIFICADO_POR,
       TO_CHAR(Q.FECHA_MODIFICACION, 'YYYY-MM-DD HH24:MI:SS') AS FECHA_MODIFICACION,
       Q.OBSOLETO,
       Q.CARGA,
       Q.CREDITO_CAMPANA_ESPECIAL,
       Q.CREDITO_FMO
  FROM ESPERADO E
  LEFT JOIN PR.PR_TIPO_CREDITO_REPRESTAMO Q
    ON Q.CODIGO_EMPRESA = E.CODIGO_EMPRESA
   AND Q.TIPO_CREDITO = E.TIPO_CREDITO
 ORDER BY E.ORDEN;

PROMPT Resultado esperado: 9 filas con RESULTADO = OK_IGUAL_CAPTURA
