
  CREATE TABLE "PA"."AGENCIA" 
   (	"COD_EMPRESA" VARCHAR2(5 BYTE), 
	"COD_AGENCIA" VARCHAR2(5 BYTE), 
	"DESCRIPCION" VARCHAR2(80 BYTE) CONSTRAINT "NN_AGENCIAS_DESCRIPCION" NOT NULL ENABLE, 
	"ES_CENTRAL" VARCHAR2(1 BYTE), 
	"EST_AGENCIA" VARCHAR2(5 BYTE), 
	"APARTADO_POSTAL" VARCHAR2(15 BYTE), 
	"COD_POSTAL" VARCHAR2(10 BYTE), 
	"DETALLE_DIR" VARCHAR2(160 BYTE), 
	"TRABAJA_DOM" VARCHAR2(1 BYTE), 
	"TRABAJA_SAB" VARCHAR2(1 BYTE), 
	"COD_PAIS" VARCHAR2(5 BYTE), 
	"COD_CAMARA" VARCHAR2(5 BYTE), 
	"COD_PROVINCIA" VARCHAR2(5 BYTE), 
	"COD_CANTON" VARCHAR2(5 BYTE), 
	"COD_DISTRITO" VARCHAR2(5 BYTE), 
	"COD_PUEBLO" VARCHAR2(5 BYTE), 
	"RECIBE_COMISION" VARCHAR2(1 BYTE), 
	"COD_ZONA" VARCHAR2(5 BYTE), 
	"GERENTE" VARCHAR2(10 BYTE), 
	"ES_SUB_AGENCIA" VARCHAR2(1 BYTE), 
	"EMAIL_GERENCIA" VARCHAR2(80 BYTE), 
	"ATIENDE_CLIENTE" VARCHAR2(1 BYTE), 
	"OFICIAL_BACKUP" VARCHAR2(10 BYTE), 
	"OFICIAL_MASIVO" VARCHAR2(1 BYTE), 
	"EMAIL_SUCURSAL" VARCHAR2(80 BYTE), 
	"NUEVO_MODELO_IMPRESION" VARCHAR2(1 BYTE) DEFAULT null, 
	"VICEPRESIDENTE" VARCHAR2(10 BYTE), 
	"COD_CENTROC" VARCHAR2(5 BYTE), 
	"COD_EMISOR_TJT" VARCHAR2(4 BYTE), 
	"LONGITUD" VARCHAR2(100 BYTE), 
	"LATITUD" VARCHAR2(100 BYTE), 
	"TIP_OFICINA" NUMBER(1,0), 
	"DESC_ENSAN_SECTOR" VARCHAR2(30 BYTE), 
	"FEC_APERTURA_OFIC" DATE, 
	"FEC_AUTORIZACION" DATE, 
	"NUM_APROBACION" VARCHAR2(25 BYTE), 
	"COD_AGENCIA_SB" VARCHAR2(5 BYTE), 
	"GESTION_CAJA_LIQUIDA" CHAR(1 BYTE), 
	"COD_AGENCIA_EIKON" VARCHAR2(5 BYTE) DEFAULT NULL, 
	"ENCARGADO" VARCHAR2(10 BYTE), 
	 CONSTRAINT "CK_AGENCIAS_TRABAJASAB" CHECK ( TRABAJA_SAB in ('S','N')             ) ENABLE, 
	 CONSTRAINT "CK_AGENCIA_ESTAGENCIA" CHECK ( EST_AGENCIA IN ('A','I','C')             ) ENABLE, 
	 CONSTRAINT "CK_AGENCIAS_ESCENTRAL" CHECK ( ES_CENTRAL in ('S','N')             ) ENABLE, 
	 CONSTRAINT "CK_AGENCIAS_TRABAJADOM" CHECK ( TRABAJA_DOM in ('S','N')             ) ENABLE, 
	 CONSTRAINT "FK_AGENCIA_DISTRITOS" FOREIGN KEY ("COD_PAIS", "COD_PROVINCIA", "COD_CANTON", "COD_DISTRITO")
	  REFERENCES "PA"."DISTRITOS" ("COD_PAIS", "COD_PROVINCIA", "COD_CANTON", "COD_DISTRITO") ENABLE, 
	 CONSTRAINT "FK_AGENCIA_PROVINCIAS" FOREIGN KEY ("COD_PAIS", "COD_PROVINCIA")
	  REFERENCES "PA"."PROVINCIAS" ("COD_PAIS", "COD_PROVINCIA") ENABLE, 
	 CONSTRAINT "FK_AGENCIA_PUEBLOS" FOREIGN KEY ("COD_PAIS", "COD_PROVINCIA", "COD_CANTON", "COD_DISTRITO", "COD_PUEBLO")
	  REFERENCES "PA"."PUEBLOS" ("COD_PAIS", "COD_PROVINCIA", "COD_CANTON", "COD_DISTRITO", "COD_PUEBLO") ENABLE, 
	 CONSTRAINT "FK_AGENCIAS_PAISES" FOREIGN KEY ("COD_PAIS")
	  REFERENCES "PA"."PAIS" ("COD_PAIS") ENABLE, 
	 CONSTRAINT "FK_AGENCIA_CANTONES" FOREIGN KEY ("COD_PAIS", "COD_PROVINCIA", "COD_CANTON")
	  REFERENCES "PA"."CANTONES" ("COD_PAIS", "COD_PROVINCIA", "COD_CANTON") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 80 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL KEEP FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA_EFD" ;
  CREATE UNIQUE INDEX "PA"."PK_AGENCIAS" ON "PA"."AGENCIA" ("COD_EMPRESA", "COD_AGENCIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IND_EFD" ;
ALTER TABLE "PA"."AGENCIA" ADD CONSTRAINT "PK_AGENCIAS" PRIMARY KEY ("COD_EMPRESA", "COD_AGENCIA")
  USING INDEX "PA"."PK_AGENCIAS"  ENABLE;

   COMMENT ON COLUMN "PA"."AGENCIA"."COD_EMPRESA" IS 'Codigo de la empresa a la que pertenece la informacion. Esta relacionada a la tabla PA.EMPRESA';
   COMMENT ON COLUMN "PA"."AGENCIA"."COD_AGENCIA" IS 'Codigo agencia';
   COMMENT ON COLUMN "PA"."AGENCIA"."DESCRIPCION" IS 'Descripcion';
   COMMENT ON COLUMN "PA"."AGENCIA"."ES_CENTRAL" IS 'Indicador de central';
   COMMENT ON COLUMN "PA"."AGENCIA"."EST_AGENCIA" IS 'Indicador de agencia';
   COMMENT ON COLUMN "PA"."AGENCIA"."APARTADO_POSTAL" IS 'Apartado postal';
   COMMENT ON COLUMN "PA"."AGENCIA"."COD_POSTAL" IS 'Codigo postal';
   COMMENT ON COLUMN "PA"."AGENCIA"."DETALLE_DIR" IS 'Detalle de direccion de agencia';
   COMMENT ON COLUMN "PA"."AGENCIA"."TRABAJA_DOM" IS 'Indicador de trabaja domingo';
   COMMENT ON COLUMN "PA"."AGENCIA"."TRABAJA_SAB" IS 'Indicador de trabajo';
   COMMENT ON COLUMN "PA"."AGENCIA"."COD_PAIS" IS 'Codigo de pais';
   COMMENT ON COLUMN "PA"."AGENCIA"."COD_CAMARA" IS 'codigo de camara';
   COMMENT ON COLUMN "PA"."AGENCIA"."COD_PROVINCIA" IS 'Codigo provincia';
   COMMENT ON COLUMN "PA"."AGENCIA"."COD_CANTON" IS 'Codigo canton';
   COMMENT ON COLUMN "PA"."AGENCIA"."COD_DISTRITO" IS 'Codigo distrito';
   COMMENT ON COLUMN "PA"."AGENCIA"."COD_PUEBLO" IS 'Codigo pueblo';
   COMMENT ON COLUMN "PA"."AGENCIA"."RECIBE_COMISION" IS 'Indicador de recibe comision';
   COMMENT ON COLUMN "PA"."AGENCIA"."COD_ZONA" IS 'Codigo de zona';
   COMMENT ON COLUMN "PA"."AGENCIA"."GERENTE" IS 'Gerente de la sucursal';
   COMMENT ON COLUMN "PA"."AGENCIA"."ES_SUB_AGENCIA" IS 'Indicador de subsucursal';
   COMMENT ON COLUMN "PA"."AGENCIA"."EMAIL_GERENCIA" IS 'Correo de la gerencia';
   COMMENT ON COLUMN "PA"."AGENCIA"."ATIENDE_CLIENTE" IS 'Indicador de atiende cliente';
   COMMENT ON COLUMN "PA"."AGENCIA"."OFICIAL_BACKUP" IS 'Oficial de backup';
   COMMENT ON COLUMN "PA"."AGENCIA"."OFICIAL_MASIVO" IS 'Oficial masivo';
   COMMENT ON COLUMN "PA"."AGENCIA"."EMAIL_SUCURSAL" IS 'Email donde se enviaran los correos de seguimiento de la transferencia';
   COMMENT ON COLUMN "PA"."AGENCIA"."NUEVO_MODELO_IMPRESION" IS 'Indicador de nuevo modelo de impresion';
   COMMENT ON COLUMN "PA"."AGENCIA"."VICEPRESIDENTE" IS 'Indica el VicePresidente que firma en la Sucursal';
   COMMENT ON COLUMN "PA"."AGENCIA"."COD_CENTROC" IS 'Codigo Centro de Costos';
   COMMENT ON COLUMN "PA"."AGENCIA"."COD_EMISOR_TJT" IS 'Codigo Emisor Tarjeta';
   COMMENT ON COLUMN "PA"."AGENCIA"."LONGITUD" IS 'La longitud corresponde a la coordenada geografica (Norte y Sur) de la oficina';
   COMMENT ON COLUMN "PA"."AGENCIA"."LATITUD" IS 'La latitud corresponde a la coordenada geografica (Norte y Sur) de la oficina';
   COMMENT ON COLUMN "PA"."AGENCIA"."COD_AGENCIA_SB" IS 'Código de Agencia de la Superintendencia de Bancos, es utilizado para reportes regulatorios';
   COMMENT ON TABLE "PA"."AGENCIA"  IS ' Tabla de las agencias del banco';

  CREATE INDEX "PA"."AGENCIA_FK3" ON "PA"."AGENCIA" ("COD_PAIS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PA_IND" ;

  CREATE INDEX "PA"."AGENCIA_FK4" ON "PA"."AGENCIA" ("COD_PAIS", "COD_PROVINCIA", "COD_CANTON") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PA_IND" ;

  CREATE INDEX "PA"."AGENCIA_FK5" ON "PA"."AGENCIA" ("COD_PAIS", "COD_PROVINCIA", "COD_CANTON", "COD_DISTRITO", "COD_PUEBLO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PA_IND" ;

  CREATE INDEX "PA"."AGENCIA_FK6" ON "PA"."AGENCIA" ("COD_PAIS", "COD_PROVINCIA", "COD_CANTON", "COD_DISTRITO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PA_IND" ;

  CREATE INDEX "PA"."AGENCIA_FK7" ON "PA"."AGENCIA" ("COD_PAIS", "COD_PROVINCIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PA_IND" ;


  GRANT QUERY REWRITE ON "PA"."AGENCIA" TO "ICUEVAS";
  GRANT REFERENCES ON "PA"."AGENCIA" TO "ICUEVAS";
  GRANT SELECT ON "PA"."AGENCIA" TO "ICUEVAS";
  GRANT UPDATE ON "PA"."AGENCIA" TO "ICUEVAS";
  GRANT ALTER ON "PA"."AGENCIA" TO "TCVERIFFIN";
  GRANT DELETE ON "PA"."AGENCIA" TO "TCVERIFFIN";
  GRANT INDEX ON "PA"."AGENCIA" TO "TCVERIFFIN";
  GRANT INSERT ON "PA"."AGENCIA" TO "TCVERIFFIN";
  GRANT SELECT ON "PA"."AGENCIA" TO "TCVERIFFIN";
  GRANT UPDATE ON "PA"."AGENCIA" TO "TCVERIFFIN";
  GRANT REFERENCES ON "PA"."AGENCIA" TO "TCVERIFFIN";
  GRANT ON COMMIT REFRESH ON "PA"."AGENCIA" TO "TCVERIFFIN";
  GRANT QUERY REWRITE ON "PA"."AGENCIA" TO "TCVERIFFIN";
  GRANT DEBUG ON "PA"."AGENCIA" TO "TCVERIFFIN";
  GRANT FLASHBACK ON "PA"."AGENCIA" TO "TCVERIFFIN";
  GRANT ALTER ON "PA"."AGENCIA" TO "TCVERIFINI";
  GRANT DELETE ON "PA"."AGENCIA" TO "TCVERIFINI";
  GRANT INDEX ON "PA"."AGENCIA" TO "TCVERIFINI";
  GRANT INSERT ON "PA"."AGENCIA" TO "TCVERIFINI";
  GRANT SELECT ON "PA"."AGENCIA" TO "TCVERIFINI";
  GRANT UPDATE ON "PA"."AGENCIA" TO "TCVERIFINI";
  GRANT REFERENCES ON "PA"."AGENCIA" TO "TCVERIFINI";
  GRANT ON COMMIT REFRESH ON "PA"."AGENCIA" TO "TCVERIFINI";
  GRANT QUERY REWRITE ON "PA"."AGENCIA" TO "TCVERIFINI";
  GRANT DEBUG ON "PA"."AGENCIA" TO "TCVERIFINI";
  GRANT FLASHBACK ON "PA"."AGENCIA" TO "TCVERIFINI";
  GRANT ALTER ON "PA"."AGENCIA" TO "BFERNANDEZ";
  GRANT DEBUG ON "PA"."AGENCIA" TO "BFERNANDEZ";
  GRANT DELETE ON "PA"."AGENCIA" TO "BFERNANDEZ";
  GRANT FLASHBACK ON "PA"."AGENCIA" TO "BFERNANDEZ";
  GRANT INDEX ON "PA"."AGENCIA" TO "BFERNANDEZ";
  GRANT INSERT ON "PA"."AGENCIA" TO "BFERNANDEZ";
  GRANT ON COMMIT REFRESH ON "PA"."AGENCIA" TO "BFERNANDEZ";
  GRANT QUERY REWRITE ON "PA"."AGENCIA" TO "BFERNANDEZ";
  GRANT REFERENCES ON "PA"."AGENCIA" TO "BFERNANDEZ";
  GRANT SELECT ON "PA"."AGENCIA" TO "BFERNANDEZ";
  GRANT UPDATE ON "PA"."AGENCIA" TO "BFERNANDEZ";
  GRANT ALTER ON "PA"."AGENCIA" TO "JSANCHEZ";
  GRANT DELETE ON "PA"."AGENCIA" TO "JSANCHEZ";
  GRANT INDEX ON "PA"."AGENCIA" TO "JSANCHEZ";
  GRANT INSERT ON "PA"."AGENCIA" TO "JSANCHEZ";
  GRANT SELECT ON "PA"."AGENCIA" TO "JSANCHEZ";
  GRANT UPDATE ON "PA"."AGENCIA" TO "JSANCHEZ";
  GRANT REFERENCES ON "PA"."AGENCIA" TO "JSANCHEZ";
  GRANT ON COMMIT REFRESH ON "PA"."AGENCIA" TO "JSANCHEZ";
  GRANT QUERY REWRITE ON "PA"."AGENCIA" TO "JSANCHEZ";
  GRANT DEBUG ON "PA"."AGENCIA" TO "JSANCHEZ";
  GRANT FLASHBACK ON "PA"."AGENCIA" TO "JSANCHEZ";
  GRANT ALTER ON "PA"."AGENCIA" TO "B2000";
  GRANT DELETE ON "PA"."AGENCIA" TO "B2000";
  GRANT INDEX ON "PA"."AGENCIA" TO "B2000";
  GRANT INSERT ON "PA"."AGENCIA" TO "B2000";
  GRANT SELECT ON "PA"."AGENCIA" TO "B2000";
  GRANT UPDATE ON "PA"."AGENCIA" TO "B2000";
  GRANT REFERENCES ON "PA"."AGENCIA" TO "B2000";
  GRANT ON COMMIT REFRESH ON "PA"."AGENCIA" TO "B2000";
  GRANT QUERY REWRITE ON "PA"."AGENCIA" TO "B2000";
  GRANT DEBUG ON "PA"."AGENCIA" TO "B2000";
  GRANT FLASHBACK ON "PA"."AGENCIA" TO "B2000";
  GRANT REFERENCES ON "PA"."AGENCIA" TO PUBLIC;
  GRANT SELECT ON "PA"."AGENCIA" TO "REF";
  GRANT SELECT ON "PA"."AGENCIA" TO "B2000TX";
  GRANT SELECT ON "PA"."AGENCIA" TO "IVR";
  GRANT SELECT ON "PA"."AGENCIA" TO "CONGEN";
  GRANT SELECT ON "PA"."AGENCIA" TO "CJ";
  GRANT SELECT ON "PA"."AGENCIA" TO "MK";
  GRANT SELECT ON "PA"."AGENCIA" TO "CC";
  GRANT ALTER ON "PA"."AGENCIA" TO "PR";
  GRANT DELETE ON "PA"."AGENCIA" TO "PR";
  GRANT INDEX ON "PA"."AGENCIA" TO "PR";
  GRANT INSERT ON "PA"."AGENCIA" TO "PR";
  GRANT SELECT ON "PA"."AGENCIA" TO "PR";
  GRANT UPDATE ON "PA"."AGENCIA" TO "PR";
  GRANT REFERENCES ON "PA"."AGENCIA" TO "PR";
  GRANT ON COMMIT REFRESH ON "PA"."AGENCIA" TO "PR";
  GRANT QUERY REWRITE ON "PA"."AGENCIA" TO "PR";
  GRANT DEBUG ON "PA"."AGENCIA" TO "PR";
  GRANT FLASHBACK ON "PA"."AGENCIA" TO "PR";
  GRANT SELECT ON "PA"."AGENCIA" TO "CD";
  GRANT SELECT ON "PA"."AGENCIA" TO "CG";
  GRANT SELECT ON "PA"."AGENCIA" TO "TF";
  GRANT SELECT ON "PA"."AGENCIA" TO "RH";
  GRANT DELETE ON "PA"."AGENCIA" TO "BPA";
  GRANT INSERT ON "PA"."AGENCIA" TO "BPA";
  GRANT SELECT ON "PA"."AGENCIA" TO "BPA";
  GRANT UPDATE ON "PA"."AGENCIA" TO "BPA";
  GRANT ALTER ON "PA"."AGENCIA" TO "BPA";
  GRANT ALTER ON "PA"."AGENCIA" TO PUBLIC;
  GRANT DELETE ON "PA"."AGENCIA" TO PUBLIC;
  GRANT INSERT ON "PA"."AGENCIA" TO PUBLIC;
  GRANT SELECT ON "PA"."AGENCIA" TO PUBLIC;
  GRANT UPDATE ON "PA"."AGENCIA" TO PUBLIC;
  GRANT ALTER ON "PA"."AGENCIA" TO "CONGEN";
  GRANT DELETE ON "PA"."AGENCIA" TO "CONGEN";
  GRANT INSERT ON "PA"."AGENCIA" TO "CONGEN";
  GRANT UPDATE ON "PA"."AGENCIA" TO "CONGEN";
  GRANT REFERENCES ON "PA"."AGENCIA" TO "CC";
  GRANT ALTER ON "PA"."AGENCIA" TO "CC";
  GRANT DELETE ON "PA"."AGENCIA" TO "CC";
  GRANT INDEX ON "PA"."AGENCIA" TO "CC";
  GRANT INSERT ON "PA"."AGENCIA" TO "CC";
  GRANT UPDATE ON "PA"."AGENCIA" TO "CC";
  GRANT ON COMMIT REFRESH ON "PA"."AGENCIA" TO "CC";
  GRANT QUERY REWRITE ON "PA"."AGENCIA" TO "CC";
  GRANT DEBUG ON "PA"."AGENCIA" TO "CC";
  GRANT FLASHBACK ON "PA"."AGENCIA" TO "CC";
  GRANT ALTER ON "PA"."AGENCIA" TO "PS";
  GRANT DELETE ON "PA"."AGENCIA" TO "PS";
  GRANT INDEX ON "PA"."AGENCIA" TO "PS";
  GRANT INSERT ON "PA"."AGENCIA" TO "PS";
  GRANT SELECT ON "PA"."AGENCIA" TO "PS";
  GRANT UPDATE ON "PA"."AGENCIA" TO "PS";
  GRANT REFERENCES ON "PA"."AGENCIA" TO "PS";
  GRANT ON COMMIT REFRESH ON "PA"."AGENCIA" TO "PS";
  GRANT QUERY REWRITE ON "PA"."AGENCIA" TO "PS";
  GRANT DEBUG ON "PA"."AGENCIA" TO "PS";
  GRANT FLASHBACK ON "PA"."AGENCIA" TO "PS";
  GRANT ALTER ON "PA"."AGENCIA" TO "TCAPROBAD1";
  GRANT DELETE ON "PA"."AGENCIA" TO "TCAPROBAD1";
  GRANT INDEX ON "PA"."AGENCIA" TO "TCAPROBAD1";
  GRANT INSERT ON "PA"."AGENCIA" TO "TCAPROBAD1";
  GRANT SELECT ON "PA"."AGENCIA" TO "TCAPROBAD1";
  GRANT UPDATE ON "PA"."AGENCIA" TO "TCAPROBAD1";
  GRANT REFERENCES ON "PA"."AGENCIA" TO "TCAPROBAD1";
  GRANT ON COMMIT REFRESH ON "PA"."AGENCIA" TO "TCAPROBAD1";
  GRANT QUERY REWRITE ON "PA"."AGENCIA" TO "TCAPROBAD1";
  GRANT DEBUG ON "PA"."AGENCIA" TO "TCAPROBAD1";
  GRANT FLASHBACK ON "PA"."AGENCIA" TO "TCAPROBAD1";
  GRANT ALTER ON "PA"."AGENCIA" TO "ICUEVA";
  GRANT DELETE ON "PA"."AGENCIA" TO "ICUEVA";
  GRANT INDEX ON "PA"."AGENCIA" TO "ICUEVA";
  GRANT INSERT ON "PA"."AGENCIA" TO "ICUEVA";
  GRANT SELECT ON "PA"."AGENCIA" TO "ICUEVA";
  GRANT UPDATE ON "PA"."AGENCIA" TO "ICUEVA";
  GRANT REFERENCES ON "PA"."AGENCIA" TO "ICUEVA";
  GRANT ON COMMIT REFRESH ON "PA"."AGENCIA" TO "ICUEVA";
  GRANT QUERY REWRITE ON "PA"."AGENCIA" TO "ICUEVA";
  GRANT DEBUG ON "PA"."AGENCIA" TO "ICUEVA";
  GRANT FLASHBACK ON "PA"."AGENCIA" TO "ICUEVA";
  GRANT ALTER ON "PA"."AGENCIA" TO "JEGARCIA";
  GRANT DELETE ON "PA"."AGENCIA" TO "JEGARCIA";
  GRANT INDEX ON "PA"."AGENCIA" TO "JEGARCIA";
  GRANT INSERT ON "PA"."AGENCIA" TO "JEGARCIA";
  GRANT SELECT ON "PA"."AGENCIA" TO "JEGARCIA";
  GRANT UPDATE ON "PA"."AGENCIA" TO "JEGARCIA";
  GRANT REFERENCES ON "PA"."AGENCIA" TO "JEGARCIA";
  GRANT ON COMMIT REFRESH ON "PA"."AGENCIA" TO "JEGARCIA";
  GRANT QUERY REWRITE ON "PA"."AGENCIA" TO "JEGARCIA";
  GRANT DEBUG ON "PA"."AGENCIA" TO "JEGARCIA";
  GRANT FLASHBACK ON "PA"."AGENCIA" TO "JEGARCIA";
  GRANT ALTER ON "PA"."AGENCIA" TO "TCAPROBAD2";
  GRANT DELETE ON "PA"."AGENCIA" TO "TCAPROBAD2";
  GRANT INDEX ON "PA"."AGENCIA" TO "TCAPROBAD2";
  GRANT INSERT ON "PA"."AGENCIA" TO "TCAPROBAD2";
  GRANT SELECT ON "PA"."AGENCIA" TO "TCAPROBAD2";
  GRANT UPDATE ON "PA"."AGENCIA" TO "TCAPROBAD2";
  GRANT REFERENCES ON "PA"."AGENCIA" TO "TCAPROBAD2";
  GRANT ON COMMIT REFRESH ON "PA"."AGENCIA" TO "TCAPROBAD2";
  GRANT QUERY REWRITE ON "PA"."AGENCIA" TO "TCAPROBAD2";
  GRANT DEBUG ON "PA"."AGENCIA" TO "TCAPROBAD2";
  GRANT FLASHBACK ON "PA"."AGENCIA" TO "TCAPROBAD2";
  GRANT ALTER ON "PA"."AGENCIA" TO "TCDIGITADO";
  GRANT DELETE ON "PA"."AGENCIA" TO "TCDIGITADO";
  GRANT INDEX ON "PA"."AGENCIA" TO "TCDIGITADO";
  GRANT INSERT ON "PA"."AGENCIA" TO "TCDIGITADO";
  GRANT SELECT ON "PA"."AGENCIA" TO "TCDIGITADO";
  GRANT UPDATE ON "PA"."AGENCIA" TO "TCDIGITADO";
  GRANT REFERENCES ON "PA"."AGENCIA" TO "TCDIGITADO";
  GRANT ON COMMIT REFRESH ON "PA"."AGENCIA" TO "TCDIGITADO";
  GRANT QUERY REWRITE ON "PA"."AGENCIA" TO "TCDIGITADO";
  GRANT DEBUG ON "PA"."AGENCIA" TO "TCDIGITADO";
  GRANT FLASHBACK ON "PA"."AGENCIA" TO "TCDIGITADO";
  GRANT ALTER ON "PA"."AGENCIA" TO "ICUEVAS";
  GRANT DEBUG ON "PA"."AGENCIA" TO "ICUEVAS";
  GRANT DELETE ON "PA"."AGENCIA" TO "ICUEVAS";
  GRANT FLASHBACK ON "PA"."AGENCIA" TO "ICUEVAS";
  GRANT INDEX ON "PA"."AGENCIA" TO "ICUEVAS";
  GRANT INSERT ON "PA"."AGENCIA" TO "ICUEVAS";
  GRANT ON COMMIT REFRESH ON "PA"."AGENCIA" TO "ICUEVAS";
  GRANT SELECT ON "PA"."AGENCIA" TO "SII";
  GRANT ALTER ON "PA"."AGENCIA" TO "FERMINR";
  GRANT DELETE ON "PA"."AGENCIA" TO "FERMINR";
  GRANT INDEX ON "PA"."AGENCIA" TO "FERMINR";
  GRANT INSERT ON "PA"."AGENCIA" TO "FERMINR";
  GRANT SELECT ON "PA"."AGENCIA" TO "FERMINR";
  GRANT UPDATE ON "PA"."AGENCIA" TO "FERMINR";
  GRANT REFERENCES ON "PA"."AGENCIA" TO "FERMINR";
  GRANT ON COMMIT REFRESH ON "PA"."AGENCIA" TO "FERMINR";
  GRANT QUERY REWRITE ON "PA"."AGENCIA" TO "FERMINR";
  GRANT DEBUG ON "PA"."AGENCIA" TO "FERMINR";
  GRANT FLASHBACK ON "PA"."AGENCIA" TO "FERMINR";
  GRANT ALTER ON "PA"."AGENCIA" TO "GASANCHEZ";
  GRANT DEBUG ON "PA"."AGENCIA" TO "GASANCHEZ";
  GRANT DELETE ON "PA"."AGENCIA" TO "GASANCHEZ";
  GRANT FLASHBACK ON "PA"."AGENCIA" TO "GASANCHEZ";
  GRANT INDEX ON "PA"."AGENCIA" TO "GASANCHEZ";
  GRANT INSERT ON "PA"."AGENCIA" TO "GASANCHEZ";
  GRANT ON COMMIT REFRESH ON "PA"."AGENCIA" TO "GASANCHEZ";
  GRANT QUERY REWRITE ON "PA"."AGENCIA" TO "GASANCHEZ";
  GRANT REFERENCES ON "PA"."AGENCIA" TO "GASANCHEZ";
  GRANT SELECT ON "PA"."AGENCIA" TO "GASANCHEZ";
  GRANT UPDATE ON "PA"."AGENCIA" TO "GASANCHEZ";
  GRANT SELECT ON "PA"."AGENCIA" TO "IA" WITH GRANT OPTION;
  GRANT SELECT ON "PA"."AGENCIA" TO "USR_APPS" WITH GRANT OPTION;
  GRANT SELECT ON "PA"."AGENCIA" TO "USR_BGP" WITH GRANT OPTION;
