
  CREATE TABLE "PA"."CUENTA_CLIENTE_RELACION" 
   (	"NUM_CUENTA" VARCHAR2(15 BYTE), 
	"CODIGO_CLIENTE" VARCHAR2(15 BYTE), 
	"TIPO_RELACION" VARCHAR2(1 BYTE), 
	"PRINCIPAL" VARCHAR2(1 BYTE), 
	"COD_SISTEMA" VARCHAR2(2 BYTE), 
	"ESTADO" VARCHAR2(1 BYTE), 
	"NUMERO_LINEA" NUMBER(2,0), 
	 CONSTRAINT "CK_CUECLIREL_PRINCIPAL" CHECK (PRINCIPAL IN ('S', 'N')) ENABLE, 
	 CONSTRAINT "CK_CUECLIREL_TIPREL" CHECK (TIPO_RELACION IN ('A', 'O', 'Y','F')) ENABLE, 
	 CONSTRAINT "FK_CUENCLIREL_SISTEMA" FOREIGN KEY ("COD_SISTEMA")
	  REFERENCES "PA"."SISTEMAS" ("COD_SISTEMA") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA_EFD" ;
  CREATE UNIQUE INDEX "PA"."PK_CUENTA_CLIENTE_RELACION" ON "PA"."CUENTA_CLIENTE_RELACION" ("NUM_CUENTA", "CODIGO_CLIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IND_EFD" ;
ALTER TABLE "PA"."CUENTA_CLIENTE_RELACION" ADD CONSTRAINT "PK_CUENTA_CLIENTE_RELACION" PRIMARY KEY ("NUM_CUENTA", "CODIGO_CLIENTE")
  USING INDEX "PA"."PK_CUENTA_CLIENTE_RELACION"  ENABLE;

   COMMENT ON COLUMN "PA"."CUENTA_CLIENTE_RELACION"."NUM_CUENTA" IS 'Numero de cuenta';
   COMMENT ON COLUMN "PA"."CUENTA_CLIENTE_RELACION"."CODIGO_CLIENTE" IS 'Codigo de cliente';
   COMMENT ON COLUMN "PA"."CUENTA_CLIENTE_RELACION"."TIPO_RELACION" IS 'Tipo de relacion';
   COMMENT ON COLUMN "PA"."CUENTA_CLIENTE_RELACION"."PRINCIPAL" IS 'Principal';
   COMMENT ON COLUMN "PA"."CUENTA_CLIENTE_RELACION"."COD_SISTEMA" IS 'Codigo sistema';
   COMMENT ON COLUMN "PA"."CUENTA_CLIENTE_RELACION"."ESTADO" IS 'Estado';
   COMMENT ON COLUMN "PA"."CUENTA_CLIENTE_RELACION"."NUMERO_LINEA" IS 'Numero de linea';
   COMMENT ON TABLE "PA"."CUENTA_CLIENTE_RELACION"  IS ' Cuenta cliente relacion';

  CREATE INDEX "PA"."CUENTA_CLIENTE_RELACION_FK4" ON "PA"."CUENTA_CLIENTE_RELACION" ("COD_SISTEMA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PA_IND" ;

  CREATE INDEX "PA"."CUENTA_CLIENTE_RELACION_IDX" ON "PA"."CUENTA_CLIENTE_RELACION" ("NUM_CUENTA", "CODIGO_CLIENTE", "COD_SISTEMA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PA_DAT" ;

  CREATE INDEX "PA"."IDX_CUENTA_CLIENTE_REL_CLI" ON "PA"."CUENTA_CLIENTE_RELACION" ("CODIGO_CLIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 MAXSIZE UNLIMITED
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PA_IDX" ;

  CREATE INDEX "PA"."IDX_CUENTA_RELACION" ON "PA"."CUENTA_CLIENTE_RELACION" ("NUM_CUENTA", "PRINCIPAL", "TIPO_RELACION", "CODIGO_CLIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 196608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IND_EFD" ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "PA"."TRG_REP_FIADOR_CODEUDOR" 
   BEFORE INSERT 
   ON PA.CUENTA_CLIENTE_RELACION
   REFERENCING NEW AS New OLD AS Old
   FOR EACH ROW
DECLARE
      vError   VARCHAR2(4000);
BEGIN
    IF :NEW.COD_SISTEMA = 'PR' AND :NEW.PRINCIPAL = 'N' AND :NEW.TIPO_RELACION IN ('F','O') THEN
        PR.Generar_Rep_FiadorCodeudor( pCodigoEmpresa      => '1',
                                       pCodigoPersona      => :NEW.CODIGO_CLIENTE,
                                       pTipo               => :NEW.TIPO_RELACION,      --'O' = Codeudor
                                       pCreditoNuevo       => :NEW.NUM_CUENTA,
                                       pCreditoAnterior    => NULL,
                                       pValidaReprestamo   => FALSE,
                                       pError              => vError);
   END IF;
END TRG_PR_GENERA_DEPONENTE;
/
ALTER TRIGGER "PA"."TRG_REP_FIADOR_CODEUDOR" DISABLE;


  GRANT DELETE ON "PA"."CUENTA_CLIENTE_RELACION" TO PUBLIC;
  GRANT INSERT ON "PA"."CUENTA_CLIENTE_RELACION" TO PUBLIC;
  GRANT SELECT ON "PA"."CUENTA_CLIENTE_RELACION" TO PUBLIC;
  GRANT UPDATE ON "PA"."CUENTA_CLIENTE_RELACION" TO PUBLIC;
  GRANT SELECT ON "PA"."CUENTA_CLIENTE_RELACION" TO "B2000";
  GRANT ALTER ON "PA"."CUENTA_CLIENTE_RELACION" TO "CD";
  GRANT DELETE ON "PA"."CUENTA_CLIENTE_RELACION" TO "CD";
  GRANT INDEX ON "PA"."CUENTA_CLIENTE_RELACION" TO "CD";
  GRANT INSERT ON "PA"."CUENTA_CLIENTE_RELACION" TO "CD";
  GRANT SELECT ON "PA"."CUENTA_CLIENTE_RELACION" TO "CD";
  GRANT UPDATE ON "PA"."CUENTA_CLIENTE_RELACION" TO "CD";
  GRANT REFERENCES ON "PA"."CUENTA_CLIENTE_RELACION" TO "CD";
  GRANT ON COMMIT REFRESH ON "PA"."CUENTA_CLIENTE_RELACION" TO "CD";
  GRANT QUERY REWRITE ON "PA"."CUENTA_CLIENTE_RELACION" TO "CD";
  GRANT DEBUG ON "PA"."CUENTA_CLIENTE_RELACION" TO "CD";
  GRANT FLASHBACK ON "PA"."CUENTA_CLIENTE_RELACION" TO "CD";
  GRANT SELECT ON "PA"."CUENTA_CLIENTE_RELACION" TO "SB";
  GRANT SELECT ON "PA"."CUENTA_CLIENTE_RELACION" TO "SW";
  GRANT SELECT ON "PA"."CUENTA_CLIENTE_RELACION" TO "TF";
  GRANT DELETE ON "PA"."CUENTA_CLIENTE_RELACION" TO "BPA";
  GRANT INSERT ON "PA"."CUENTA_CLIENTE_RELACION" TO "BPA";
  GRANT SELECT ON "PA"."CUENTA_CLIENTE_RELACION" TO "BPA";
  GRANT UPDATE ON "PA"."CUENTA_CLIENTE_RELACION" TO "BPA";
  GRANT ALTER ON "PA"."CUENTA_CLIENTE_RELACION" TO "BCC";
  GRANT DELETE ON "PA"."CUENTA_CLIENTE_RELACION" TO "BCC";
  GRANT INSERT ON "PA"."CUENTA_CLIENTE_RELACION" TO "BCC";
  GRANT UPDATE ON "PA"."CUENTA_CLIENTE_RELACION" TO "BCC";
  GRANT ON COMMIT REFRESH ON "PA"."CUENTA_CLIENTE_RELACION" TO "BCC";
  GRANT QUERY REWRITE ON "PA"."CUENTA_CLIENTE_RELACION" TO "BCC";
  GRANT DEBUG ON "PA"."CUENTA_CLIENTE_RELACION" TO "BCC";
  GRANT FLASHBACK ON "PA"."CUENTA_CLIENTE_RELACION" TO "BCC";
  GRANT ALTER ON "PA"."CUENTA_CLIENTE_RELACION" TO "BPA";
  GRANT ON COMMIT REFRESH ON "PA"."CUENTA_CLIENTE_RELACION" TO "BPA";
  GRANT QUERY REWRITE ON "PA"."CUENTA_CLIENTE_RELACION" TO "BPA";
  GRANT DEBUG ON "PA"."CUENTA_CLIENTE_RELACION" TO "BPA";
  GRANT FLASHBACK ON "PA"."CUENTA_CLIENTE_RELACION" TO "BPA";
  GRANT ALTER ON "PA"."CUENTA_CLIENTE_RELACION" TO "CONGEN";
  GRANT DELETE ON "PA"."CUENTA_CLIENTE_RELACION" TO "CONGEN";
  GRANT INSERT ON "PA"."CUENTA_CLIENTE_RELACION" TO "CONGEN";
  GRANT UPDATE ON "PA"."CUENTA_CLIENTE_RELACION" TO "CONGEN";
  GRANT ON COMMIT REFRESH ON "PA"."CUENTA_CLIENTE_RELACION" TO "CONGEN";
  GRANT QUERY REWRITE ON "PA"."CUENTA_CLIENTE_RELACION" TO "CONGEN";
  GRANT DEBUG ON "PA"."CUENTA_CLIENTE_RELACION" TO "CONGEN";
  GRANT FLASHBACK ON "PA"."CUENTA_CLIENTE_RELACION" TO "CONGEN";
  GRANT ALTER ON "PA"."CUENTA_CLIENTE_RELACION" TO "BCD";
  GRANT DELETE ON "PA"."CUENTA_CLIENTE_RELACION" TO "BCD";
  GRANT INSERT ON "PA"."CUENTA_CLIENTE_RELACION" TO "BCD";
  GRANT UPDATE ON "PA"."CUENTA_CLIENTE_RELACION" TO "BCD";
  GRANT ON COMMIT REFRESH ON "PA"."CUENTA_CLIENTE_RELACION" TO "BCD";
  GRANT QUERY REWRITE ON "PA"."CUENTA_CLIENTE_RELACION" TO "BCD";
  GRANT DEBUG ON "PA"."CUENTA_CLIENTE_RELACION" TO "BCD";
  GRANT FLASHBACK ON "PA"."CUENTA_CLIENTE_RELACION" TO "BCD";
  GRANT SELECT ON "PA"."CUENTA_CLIENTE_RELACION" TO "ASEGURA";
  GRANT ALTER ON "PA"."CUENTA_CLIENTE_RELACION" TO "PS";
  GRANT DELETE ON "PA"."CUENTA_CLIENTE_RELACION" TO "PS";
  GRANT INDEX ON "PA"."CUENTA_CLIENTE_RELACION" TO "PS";
  GRANT INSERT ON "PA"."CUENTA_CLIENTE_RELACION" TO "PS";
  GRANT SELECT ON "PA"."CUENTA_CLIENTE_RELACION" TO "PS";
  GRANT UPDATE ON "PA"."CUENTA_CLIENTE_RELACION" TO "PS";
  GRANT REFERENCES ON "PA"."CUENTA_CLIENTE_RELACION" TO "PS";
  GRANT ON COMMIT REFRESH ON "PA"."CUENTA_CLIENTE_RELACION" TO "PS";
  GRANT QUERY REWRITE ON "PA"."CUENTA_CLIENTE_RELACION" TO "PS";
  GRANT DEBUG ON "PA"."CUENTA_CLIENTE_RELACION" TO "PS";
  GRANT FLASHBACK ON "PA"."CUENTA_CLIENTE_RELACION" TO "PS";
  GRANT SELECT ON "PA"."CUENTA_CLIENTE_RELACION" TO "CONGEN";
  GRANT SELECT ON "PA"."CUENTA_CLIENTE_RELACION" TO "BCD";
  GRANT SELECT ON "PA"."CUENTA_CLIENTE_RELACION" TO "BCC";
  GRANT SELECT ON "PA"."CUENTA_CLIENTE_RELACION" TO "CC";
  GRANT SELECT ON "PA"."CUENTA_CLIENTE_RELACION" TO "TCAPROBAD1";
  GRANT SELECT ON "PA"."CUENTA_CLIENTE_RELACION" TO "ICUEVA";
  GRANT SELECT ON "PA"."CUENTA_CLIENTE_RELACION" TO "JEGARCIA";
  GRANT SELECT ON "PA"."CUENTA_CLIENTE_RELACION" TO "TCAPROBAD2";
  GRANT SELECT ON "PA"."CUENTA_CLIENTE_RELACION" TO "TCDIGITADO";
  GRANT SELECT ON "PA"."CUENTA_CLIENTE_RELACION" TO "ICUEVAS";
  GRANT SELECT ON "PA"."CUENTA_CLIENTE_RELACION" TO "TCVERIFFIN";
  GRANT SELECT ON "PA"."CUENTA_CLIENTE_RELACION" TO "TCVERIFINI";
  GRANT DELETE ON "PA"."CUENTA_CLIENTE_RELACION" TO "BPR";
  GRANT INSERT ON "PA"."CUENTA_CLIENTE_RELACION" TO "BPR";
  GRANT SELECT ON "PA"."CUENTA_CLIENTE_RELACION" TO "BPR";
  GRANT UPDATE ON "PA"."CUENTA_CLIENTE_RELACION" TO "BPR";
  GRANT SELECT ON "PA"."CUENTA_CLIENTE_RELACION" TO "BFERNANDEZ";
  GRANT DELETE ON "PA"."CUENTA_CLIENTE_RELACION" TO "PR";
  GRANT INSERT ON "PA"."CUENTA_CLIENTE_RELACION" TO "PR";
  GRANT SELECT ON "PA"."CUENTA_CLIENTE_RELACION" TO "PR" WITH GRANT OPTION;
  GRANT UPDATE ON "PA"."CUENTA_CLIENTE_RELACION" TO "PR";
  GRANT REFERENCES ON "PA"."CUENTA_CLIENTE_RELACION" TO "PR";
  GRANT SELECT ON "PA"."CUENTA_CLIENTE_RELACION" TO "JSANCHEZ";
  GRANT ALTER ON "PA"."CUENTA_CLIENTE_RELACION" TO "MG";
  GRANT DELETE ON "PA"."CUENTA_CLIENTE_RELACION" TO "MG";
  GRANT INDEX ON "PA"."CUENTA_CLIENTE_RELACION" TO "MG";
  GRANT INSERT ON "PA"."CUENTA_CLIENTE_RELACION" TO "MG";
  GRANT SELECT ON "PA"."CUENTA_CLIENTE_RELACION" TO "MG";
  GRANT UPDATE ON "PA"."CUENTA_CLIENTE_RELACION" TO "MG";
  GRANT REFERENCES ON "PA"."CUENTA_CLIENTE_RELACION" TO "MG";
  GRANT SELECT ON "PA"."CUENTA_CLIENTE_RELACION" TO "SII";
  GRANT SELECT ON "PA"."CUENTA_CLIENTE_RELACION" TO "FERMINR";
  GRANT SELECT ON "PA"."CUENTA_CLIENTE_RELACION" TO "GASANCHEZ";
