
  CREATE TABLE "PA"."LISTA_PEP" 
   (	"COD_PERSONA" VARCHAR2(15 BYTE), 
	"CONSECUTIVO" NUMBER(6,0), 
	"CARGO" VARCHAR2(80 BYTE), 
	"FEC_INGRESO" DATE, 
	"FEC_VENCIMIENTO" DATE, 
	"APODO" VARCHAR2(80 BYTE), 
	"ADICIONADO_POR" VARCHAR2(10 BYTE), 
	"FECHA_ADICION" DATE, 
	"MODIFICADO_POR" VARCHAR2(10 BYTE), 
	"FECHA_MODIFICACION" DATE, 
	"CODIGO_PARENTESCO" NUMBER(2,0), 
	"INSTITUCION_POLITICA" VARCHAR2(60 BYTE), 
	"CODIGO_OPERACION" VARCHAR2(4 BYTE), 
	"COD_MONEDA" VARCHAR2(4 BYTE), 
	"COD_PAIS" VARCHAR2(5 BYTE), 
	"NOMBRE_REL_PEP" VARCHAR2(60 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PA_DAT" ;
  CREATE UNIQUE INDEX "PA"."PK_LISTA_PEP" ON "PA"."LISTA_PEP" ("CONSECUTIVO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PA_IDX" ;
ALTER TABLE "PA"."LISTA_PEP" ADD CONSTRAINT "PK_LISTA_PEP" PRIMARY KEY ("CONSECUTIVO")
  USING INDEX "PA"."PK_LISTA_PEP"  ENABLE;

   COMMENT ON COLUMN "PA"."LISTA_PEP"."COD_PERSONA" IS 'codigo de persona.';
   COMMENT ON COLUMN "PA"."LISTA_PEP"."CONSECUTIVO" IS 'Consecutivo';
   COMMENT ON COLUMN "PA"."LISTA_PEP"."CARGO" IS 'Cargo';
   COMMENT ON COLUMN "PA"."LISTA_PEP"."FEC_INGRESO" IS 'Fecha de ingreso';
   COMMENT ON COLUMN "PA"."LISTA_PEP"."FEC_VENCIMIENTO" IS 'Fecha de vencimiento';
   COMMENT ON COLUMN "PA"."LISTA_PEP"."APODO" IS 'Apodo';
   COMMENT ON COLUMN "PA"."LISTA_PEP"."ADICIONADO_POR" IS 'Usuario agrego';
   COMMENT ON COLUMN "PA"."LISTA_PEP"."FECHA_ADICION" IS 'Fecha de adicion';
   COMMENT ON COLUMN "PA"."LISTA_PEP"."MODIFICADO_POR" IS 'Usuario modifico';
   COMMENT ON COLUMN "PA"."LISTA_PEP"."FECHA_MODIFICACION" IS 'Fecha de modificacion';
   COMMENT ON COLUMN "PA"."LISTA_PEP"."CODIGO_PARENTESCO" IS 'Codigo de parentesco';
   COMMENT ON COLUMN "PA"."LISTA_PEP"."INSTITUCION_POLITICA" IS 'Institucion politica';
   COMMENT ON COLUMN "PA"."LISTA_PEP"."CODIGO_OPERACION" IS 'Codigo de operacion';
   COMMENT ON COLUMN "PA"."LISTA_PEP"."COD_MONEDA" IS 'Codigo moneda';
   COMMENT ON COLUMN "PA"."LISTA_PEP"."COD_PAIS" IS 'Codigo del pais';
   COMMENT ON COLUMN "PA"."LISTA_PEP"."NOMBRE_REL_PEP" IS 'Nombre relacion personas politicamente expuestas';
   COMMENT ON TABLE "PA"."LISTA_PEP"  IS ' Lista de personas politicament expuestas';

  CREATE INDEX "PA"."IDX_PEP_PERS_VENC" ON "PA"."LISTA_PEP" ("COD_PERSONA", "FEC_VENCIMIENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PA_IDX" ;


  GRANT SELECT ON "PA"."LISTA_PEP" TO "CONGEN";
  GRANT DELETE ON "PA"."LISTA_PEP" TO "BPA";
  GRANT INSERT ON "PA"."LISTA_PEP" TO "BPA";
  GRANT SELECT ON "PA"."LISTA_PEP" TO "BPA";
  GRANT UPDATE ON "PA"."LISTA_PEP" TO "BPA";
  GRANT ALTER ON "PA"."LISTA_PEP" TO "BPA";
  GRANT ON COMMIT REFRESH ON "PA"."LISTA_PEP" TO "BPA";
  GRANT QUERY REWRITE ON "PA"."LISTA_PEP" TO "BPA";
  GRANT DEBUG ON "PA"."LISTA_PEP" TO "BPA";
  GRANT FLASHBACK ON "PA"."LISTA_PEP" TO "BPA";
  GRANT ALTER ON "PA"."LISTA_PEP" TO "CONGEN";
  GRANT DELETE ON "PA"."LISTA_PEP" TO "CONGEN";
  GRANT INSERT ON "PA"."LISTA_PEP" TO "CONGEN";
  GRANT UPDATE ON "PA"."LISTA_PEP" TO "CONGEN";
  GRANT ON COMMIT REFRESH ON "PA"."LISTA_PEP" TO "CONGEN";
  GRANT QUERY REWRITE ON "PA"."LISTA_PEP" TO "CONGEN";
  GRANT DEBUG ON "PA"."LISTA_PEP" TO "CONGEN";
  GRANT FLASHBACK ON "PA"."LISTA_PEP" TO "CONGEN";
  GRANT SELECT ON "PA"."LISTA_PEP" TO "SII";
