
  CREATE TABLE "PA"."PRODUCTOS" 
   (	"COD_CAT_PRODUCTO" VARCHAR2(2 BYTE) CONSTRAINT "NN_PRODUCTOS_CODCATPRODUCTO" NOT NULL ENABLE, 
	"COD_PRODUCTO" VARCHAR2(4 BYTE), 
	"COD_MONEDA" VARCHAR2(4 BYTE) CONSTRAINT "NN_PRODUCTOS_CODMONEDA" NOT NULL ENABLE, 
	"DESCRIPCION" VARCHAR2(80 BYTE) CONSTRAINT "NN_PRODUCTOS_DESCRIPCION" NOT NULL ENABLE, 
	"COD_EMPRESA" VARCHAR2(5 BYTE), 
	"DETALLE" VARCHAR2(1000 BYTE), 
	"CLTE_PROSPECTO" VARCHAR2(500 BYTE), 
	"NOM_FILTRO" VARCHAR2(10 BYTE), 
	"NOM_IMAGEN" VARCHAR2(12 BYTE), 
	"ABREVIATURA" VARCHAR2(5 BYTE), 
	"REQUERIMIENTOS" VARCHAR2(500 BYTE), 
	"COD_PRODUCTO_SB" VARCHAR2(5 BYTE), 
	"TIPO_PERSONA" VARCHAR2(1 BYTE), 
	"TIPO_INSTRUMENTO_SB" VARCHAR2(3 BYTE), 
	 CONSTRAINT "FK_PRODUCTOS_CAT_IMAGENES" FOREIGN KEY ("NOM_IMAGEN")
	  REFERENCES "PA"."CAT_IMAGENES" ("NOM_IMAGEN") ENABLE, 
	 CONSTRAINT "FK_PRODUCTOS_MONEDAS" FOREIGN KEY ("COD_MONEDA")
	  REFERENCES "PA"."MONEDA" ("COD_MONEDA") ENABLE, 
	 CONSTRAINT "FK_PRODUCTOS_SUBCATPROD" FOREIGN KEY ("COD_CAT_PRODUCTO", "ABREVIATURA")
	  REFERENCES "PA"."SUBCAT_PRODUCTOS" ("COD_CAT_PRODUCTO", "COD_SUBCAT_PRODUCTO") ENABLE, 
	 CONSTRAINT "FK_PRODUCTOS_CATPRODXEMPRESA" FOREIGN KEY ("COD_EMPRESA", "COD_CAT_PRODUCTO")
	  REFERENCES "PA"."CAT_PROD_X_EMPRESA" ("COD_EMPRESA", "COD_CAT_PRODUCTO") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 80 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA_EFD" ;
  CREATE UNIQUE INDEX "PA"."PK_PRODUCTOS" ON "PA"."PRODUCTOS" ("COD_EMPRESA", "COD_PRODUCTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IND_EFD" ;
ALTER TABLE "PA"."PRODUCTOS" ADD CONSTRAINT "PK_PRODUCTOS" PRIMARY KEY ("COD_EMPRESA", "COD_PRODUCTO")
  USING INDEX "PA"."PK_PRODUCTOS"  ENABLE;

   COMMENT ON COLUMN "PA"."PRODUCTOS"."COD_CAT_PRODUCTO" IS 'Codigo Categoria';
   COMMENT ON COLUMN "PA"."PRODUCTOS"."COD_PRODUCTO" IS 'Codigo de producto';
   COMMENT ON COLUMN "PA"."PRODUCTOS"."COD_MONEDA" IS 'Codigo moneda';
   COMMENT ON COLUMN "PA"."PRODUCTOS"."DESCRIPCION" IS 'Descripcion';
   COMMENT ON COLUMN "PA"."PRODUCTOS"."COD_EMPRESA" IS 'Codigo de la empresa a la que pertenece la informacion. Esta relacionada a la tabla PA.EMPRESA';
   COMMENT ON COLUMN "PA"."PRODUCTOS"."DETALLE" IS 'Detalle producto';
   COMMENT ON COLUMN "PA"."PRODUCTOS"."CLTE_PROSPECTO" IS 'Cliente Prospecto';
   COMMENT ON COLUMN "PA"."PRODUCTOS"."NOM_FILTRO" IS 'Nombre Filtro';
   COMMENT ON COLUMN "PA"."PRODUCTOS"."NOM_IMAGEN" IS 'Nombre Imagen';
   COMMENT ON COLUMN "PA"."PRODUCTOS"."ABREVIATURA" IS 'Abreviatura';
   COMMENT ON COLUMN "PA"."PRODUCTOS"."REQUERIMIENTOS" IS 'Abreviatura';
   COMMENT ON COLUMN "PA"."PRODUCTOS"."COD_PRODUCTO_SB" IS 'Codigo producto SuperIntendencia';
   COMMENT ON COLUMN "PA"."PRODUCTOS"."TIPO_PERSONA" IS 'Tipo de persona';
   COMMENT ON COLUMN "PA"."PRODUCTOS"."TIPO_INSTRUMENTO_SB" IS 'Tipo de instrumento SuperIntendencia';
   COMMENT ON TABLE "PA"."PRODUCTOS"  IS ' Productos';

  CREATE INDEX "PA"."PRODUCTOS_FK5" ON "PA"."PRODUCTOS" ("COD_EMPRESA", "COD_CAT_PRODUCTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PA_IND" ;

  CREATE INDEX "PA"."PRODUCTOS_FK6" ON "PA"."PRODUCTOS" ("NOM_IMAGEN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PA_IND" ;

  CREATE INDEX "PA"."PRODUCTOS_FK7" ON "PA"."PRODUCTOS" ("COD_MONEDA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PA_IND" ;

  CREATE INDEX "PA"."PRODUCTOS_FK8" ON "PA"."PRODUCTOS" ("COD_CAT_PRODUCTO", "ABREVIATURA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PA_IND" ;


  GRANT SELECT ON "PA"."PRODUCTOS" TO "B2000";
  GRANT UPDATE ON "PA"."PRODUCTOS" TO "BGE";
  GRANT SELECT ON "PA"."PRODUCTOS" TO "ASEGURA";
  GRANT SELECT ON "PA"."PRODUCTOS" TO "PS";
  GRANT REFERENCES ON "PA"."PRODUCTOS" TO PUBLIC;
  GRANT SELECT ON "PA"."PRODUCTOS" TO "B2000TX";
  GRANT SELECT ON "PA"."PRODUCTOS" TO "IVR";
  GRANT SELECT ON "PA"."PRODUCTOS" TO "DY";
  GRANT SELECT ON "PA"."PRODUCTOS" TO "CONGEN";
  GRANT ALTER ON "PA"."PRODUCTOS" TO "BDI";
  GRANT DELETE ON "PA"."PRODUCTOS" TO "BDI";
  GRANT INSERT ON "PA"."PRODUCTOS" TO "BDI";
  GRANT SELECT ON "PA"."PRODUCTOS" TO "BDI";
  GRANT UPDATE ON "PA"."PRODUCTOS" TO "BDI";
  GRANT ON COMMIT REFRESH ON "PA"."PRODUCTOS" TO "BDI";
  GRANT QUERY REWRITE ON "PA"."PRODUCTOS" TO "BDI";
  GRANT DEBUG ON "PA"."PRODUCTOS" TO "BDI";
  GRANT FLASHBACK ON "PA"."PRODUCTOS" TO "BDI";
  GRANT SELECT ON "PA"."PRODUCTOS" TO "BI2000";
  GRANT ALTER ON "PA"."PRODUCTOS" TO "BCC";
  GRANT DELETE ON "PA"."PRODUCTOS" TO "BCC";
  GRANT INSERT ON "PA"."PRODUCTOS" TO "BCC";
  GRANT SELECT ON "PA"."PRODUCTOS" TO "BCC";
  GRANT UPDATE ON "PA"."PRODUCTOS" TO "BCC";
  GRANT ON COMMIT REFRESH ON "PA"."PRODUCTOS" TO "BCC";
  GRANT QUERY REWRITE ON "PA"."PRODUCTOS" TO "BCC";
  GRANT DEBUG ON "PA"."PRODUCTOS" TO "BCC";
  GRANT FLASHBACK ON "PA"."PRODUCTOS" TO "BCC";
  GRANT SELECT ON "PA"."PRODUCTOS" TO "BCJ";
  GRANT ALTER ON "PA"."PRODUCTOS" TO "BCG";
  GRANT DELETE ON "PA"."PRODUCTOS" TO "BCG";
  GRANT INSERT ON "PA"."PRODUCTOS" TO "BCG";
  GRANT SELECT ON "PA"."PRODUCTOS" TO "BCG";
  GRANT UPDATE ON "PA"."PRODUCTOS" TO "BCG";
  GRANT ON COMMIT REFRESH ON "PA"."PRODUCTOS" TO "BCG";
  GRANT QUERY REWRITE ON "PA"."PRODUCTOS" TO "BCG";
  GRANT DEBUG ON "PA"."PRODUCTOS" TO "BCG";
  GRANT FLASHBACK ON "PA"."PRODUCTOS" TO "BCG";
  GRANT SELECT ON "PA"."PRODUCTOS" TO "DI";
  GRANT SELECT ON "PA"."PRODUCTOS" TO "CJ";
  GRANT SELECT ON "PA"."PRODUCTOS" TO "MK";
  GRANT SELECT ON "PA"."PRODUCTOS" TO "I2000";
  GRANT SELECT ON "PA"."PRODUCTOS" TO "CC";
  GRANT SELECT ON "PA"."PRODUCTOS" TO "PR";
  GRANT SELECT ON "PA"."PRODUCTOS" TO "CD";
  GRANT ALTER ON "PA"."PRODUCTOS" TO "SB";
  GRANT DELETE ON "PA"."PRODUCTOS" TO "SB";
  GRANT INDEX ON "PA"."PRODUCTOS" TO "SB";
  GRANT INSERT ON "PA"."PRODUCTOS" TO "SB";
  GRANT SELECT ON "PA"."PRODUCTOS" TO "SB";
  GRANT UPDATE ON "PA"."PRODUCTOS" TO "SB";
  GRANT REFERENCES ON "PA"."PRODUCTOS" TO "SB";
  GRANT ON COMMIT REFRESH ON "PA"."PRODUCTOS" TO "SB";
  GRANT QUERY REWRITE ON "PA"."PRODUCTOS" TO "SB";
  GRANT DEBUG ON "PA"."PRODUCTOS" TO "SB";
  GRANT FLASHBACK ON "PA"."PRODUCTOS" TO "SB";
  GRANT SELECT ON "PA"."PRODUCTOS" TO "TF";
  GRANT SELECT ON "PA"."PRODUCTOS" TO "FC";
  GRANT SELECT ON "PA"."PRODUCTOS" TO "RH";
  GRANT SELECT ON "PA"."PRODUCTOS" TO "CG";
  GRANT DELETE ON "PA"."PRODUCTOS" TO "BPA";
  GRANT INSERT ON "PA"."PRODUCTOS" TO "BPA";
  GRANT SELECT ON "PA"."PRODUCTOS" TO "BPA";
  GRANT UPDATE ON "PA"."PRODUCTOS" TO "BPA";
  GRANT ALTER ON "PA"."PRODUCTOS" TO PUBLIC;
  GRANT DELETE ON "PA"."PRODUCTOS" TO PUBLIC;
  GRANT INSERT ON "PA"."PRODUCTOS" TO PUBLIC;
  GRANT SELECT ON "PA"."PRODUCTOS" TO PUBLIC;
  GRANT UPDATE ON "PA"."PRODUCTOS" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "PA"."PRODUCTOS" TO PUBLIC;
  GRANT QUERY REWRITE ON "PA"."PRODUCTOS" TO PUBLIC;
  GRANT DEBUG ON "PA"."PRODUCTOS" TO PUBLIC;
  GRANT FLASHBACK ON "PA"."PRODUCTOS" TO PUBLIC;
  GRANT ALTER ON "PA"."PRODUCTOS" TO "BPA";
  GRANT ON COMMIT REFRESH ON "PA"."PRODUCTOS" TO "BPA";
  GRANT QUERY REWRITE ON "PA"."PRODUCTOS" TO "BPA";
  GRANT DEBUG ON "PA"."PRODUCTOS" TO "BPA";
  GRANT FLASHBACK ON "PA"."PRODUCTOS" TO "BPA";
  GRANT ALTER ON "PA"."PRODUCTOS" TO "CONGEN";
  GRANT DELETE ON "PA"."PRODUCTOS" TO "CONGEN";
  GRANT INSERT ON "PA"."PRODUCTOS" TO "CONGEN";
  GRANT UPDATE ON "PA"."PRODUCTOS" TO "CONGEN";
  GRANT ON COMMIT REFRESH ON "PA"."PRODUCTOS" TO "CONGEN";
  GRANT QUERY REWRITE ON "PA"."PRODUCTOS" TO "CONGEN";
  GRANT DEBUG ON "PA"."PRODUCTOS" TO "CONGEN";
  GRANT FLASHBACK ON "PA"."PRODUCTOS" TO "CONGEN";
  GRANT ALTER ON "PA"."PRODUCTOS" TO "BCJ";
  GRANT DELETE ON "PA"."PRODUCTOS" TO "BCJ";
  GRANT INSERT ON "PA"."PRODUCTOS" TO "BCJ";
  GRANT UPDATE ON "PA"."PRODUCTOS" TO "BCJ";
  GRANT ON COMMIT REFRESH ON "PA"."PRODUCTOS" TO "BCJ";
  GRANT QUERY REWRITE ON "PA"."PRODUCTOS" TO "BCJ";
  GRANT DEBUG ON "PA"."PRODUCTOS" TO "BCJ";
  GRANT FLASHBACK ON "PA"."PRODUCTOS" TO "BCJ";
  GRANT ALTER ON "PA"."PRODUCTOS" TO "BI2000";
  GRANT DELETE ON "PA"."PRODUCTOS" TO "BI2000";
  GRANT INSERT ON "PA"."PRODUCTOS" TO "BI2000";
  GRANT UPDATE ON "PA"."PRODUCTOS" TO "BI2000";
  GRANT ON COMMIT REFRESH ON "PA"."PRODUCTOS" TO "BI2000";
  GRANT QUERY REWRITE ON "PA"."PRODUCTOS" TO "BI2000";
  GRANT DEBUG ON "PA"."PRODUCTOS" TO "BI2000";
  GRANT FLASHBACK ON "PA"."PRODUCTOS" TO "BI2000";
  GRANT DELETE ON "PA"."PRODUCTOS" TO "BGE";
  GRANT INSERT ON "PA"."PRODUCTOS" TO "BGE";
  GRANT SELECT ON "PA"."PRODUCTOS" TO "BGE";
  GRANT SELECT ON "PA"."PRODUCTOS" TO "TCAPROBAD1";
  GRANT SELECT ON "PA"."PRODUCTOS" TO "ICUEVA";
  GRANT SELECT ON "PA"."PRODUCTOS" TO "JEGARCIA";
  GRANT SELECT ON "PA"."PRODUCTOS" TO "OCASTRO";
  GRANT SELECT ON "PA"."PRODUCTOS" TO "TCAPROBAD2";
  GRANT SELECT ON "PA"."PRODUCTOS" TO "TCDIGITADO";
  GRANT SELECT ON "PA"."PRODUCTOS" TO "ICUEVAS";
  GRANT SELECT ON "PA"."PRODUCTOS" TO "TCVERIFFIN";
  GRANT SELECT ON "PA"."PRODUCTOS" TO "TCVERIFINI";
  GRANT SELECT ON "PA"."PRODUCTOS" TO "BFERNANDEZ";
  GRANT SELECT ON "PA"."PRODUCTOS" TO "JSANCHEZ";
  GRANT SELECT ON "PA"."PRODUCTOS" TO "SII";
  GRANT SELECT ON "PA"."PRODUCTOS" TO "FERMINR";
  GRANT SELECT ON "PA"."PRODUCTOS" TO "GASANCHEZ";
  GRANT SELECT ON "PA"."PRODUCTOS" TO "BTC";
