
  CREATE TABLE "PA"."ROLES" 
   (	"COD_ROL" VARCHAR2(6 BYTE), 
	"DESCRIPCION" VARCHAR2(30 BYTE) CONSTRAINT "NN_ROLES_DESCRIPCION" NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 80 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA_EFD" ;
  CREATE UNIQUE INDEX "PA"."PK_ROLES" ON "PA"."ROLES" ("COD_ROL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IND_EFD" ;
ALTER TABLE "PA"."ROLES" ADD CONSTRAINT "PK_ROLES" PRIMARY KEY ("COD_ROL")
  USING INDEX "PA"."PK_ROLES"  ENABLE;

   COMMENT ON COLUMN "PA"."ROLES"."COD_ROL" IS 'Codigo del rol';
   COMMENT ON COLUMN "PA"."ROLES"."DESCRIPCION" IS 'Descripcion';
   COMMENT ON TABLE "PA"."ROLES"  IS ' Roles';


  GRANT REFERENCES ON "PA"."ROLES" TO PUBLIC;
  GRANT SELECT ON "PA"."ROLES" TO "CONGEN";
  GRANT DELETE ON "PA"."ROLES" TO "BPA";
  GRANT INSERT ON "PA"."ROLES" TO "BPA";
  GRANT SELECT ON "PA"."ROLES" TO "BPA";
  GRANT UPDATE ON "PA"."ROLES" TO "BPA";
  GRANT ALTER ON "PA"."ROLES" TO PUBLIC;
  GRANT DELETE ON "PA"."ROLES" TO PUBLIC;
  GRANT INSERT ON "PA"."ROLES" TO PUBLIC;
  GRANT SELECT ON "PA"."ROLES" TO PUBLIC;
  GRANT UPDATE ON "PA"."ROLES" TO PUBLIC;
  GRANT ALTER ON "PA"."ROLES" TO "CONGEN";
  GRANT DELETE ON "PA"."ROLES" TO "CONGEN";
  GRANT INSERT ON "PA"."ROLES" TO "CONGEN";
  GRANT UPDATE ON "PA"."ROLES" TO "CONGEN";
  GRANT ALTER ON "PA"."ROLES" TO "BPA";
  GRANT SELECT ON "PA"."ROLES" TO "SII";
