-- Script para crear la tabla PR.PR_SOLICITUD_REPRESTAMO (Completo)

CREATE TABLE PR.PR_SOLICITUD_REPRESTAMO (
    CODIGO_EMPRESA          NUMBER(4) NOT NULL,
    ID_REPRESTAMO           NUMBER(14) NOT NULL,
    NOMBRES                 VARCHAR2(65 BYTE),
    APELLIDOS               VARCHAR2(65 BYTE),
    IDENTIFICACION          VARCHAR2(30 BYTE),
    FEC_NACIMIENTO          DATE,
    SEXO                    VARCHAR2(1 BYTE),
    NACIONALIDAD            VARCHAR2(20 BYTE),
    ESTADO_CIVIL            VARCHAR2(4 BYTE),
    TELEFONO_CELULAR        VARCHAR2(30 BYTE),
    TELEFONO_RESIDENCIA     VARCHAR2(30 BYTE),
    TELEFONO_TRABAJO        VARCHAR2(30 BYTE),
    EMAIL                   VARCHAR2(200 BYTE),
    COD_DIRECCION           VARCHAR2(15 BYTE),
    TIP_DIRECCION           VARCHAR2(1 BYTE),
    DIRECCION               VARCHAR2(160 BYTE),
    PLAZO                   NUMBER(5),
    OPCION_RECHAZO          VARCHAR2(1 BYTE),
    NO_CREDITO              NUMBER(7),
    ESTADO                  VARCHAR2(5 BYTE),
    ADICIONADO_POR          VARCHAR2(30 BYTE) NOT NULL,
    FECHA_ADICION           DATE DEFAULT SYSDATE NOT NULL,
    MODIFICADO_POR          VARCHAR2(30 BYTE),
    FECHA_MODIFICACION      DATE,
    CODIGO_ACTIVIDAD        VARCHAR2(15 BYTE),
    MARGEN_BRUTO_STD        NUMBER(6,4),
    GASTO_OPERATIVO_STD     NUMBER(14,2),
    VENTAS_MENSUAL          NUMBER(14,2),
    COSTO_VENTAS            NUMBER(14,2),
    GASTO_OPERATIVO         NUMBER(14,2),
    OTROS_INGRESOS          NUMBER(14,2),
    GASTOS_FAMILIARES       NUMBER(14,2),
    EXCEDENTE_FAMILIARES    NUMBER(14,2),
    REL_CUOTA_EXCED_FAM     NUMBER(14,2),
    CODIGO_AGENCIA          VARCHAR2(5 BYTE),
    CODIGO_OFICIAL          VARCHAR2(5 BYTE),
    ID_TEMPFUD              NUMBER(15),
    NOMARCHIVO              VARCHAR2(50 BYTE),
    ID_TEMPFEC              NUMBER(15),
    COD_PAIS                VARCHAR2(5 BYTE),
    COD_PROVINCIA           VARCHAR2(5 BYTE),
    COD_CANTON              VARCHAR2(5 BYTE),
    COD_DISTRITO            VARCHAR2(5 BYTE),
    COD_CIUDAD              VARCHAR2(5 BYTE),
    TIPO_CREDITO            NUMBER,
    WORLD_COMPLIANCE        NUMBER,
    IDENTIFICADOR_FIADOR    VARCHAR2(30 BYTE),
    TELEFONO_FIADOR         VARCHAR2(30 BYTE),
    EMAIL_FIADOR            VARCHAR2(200 BYTE),
    DIRECCION_FIADOR        VARCHAR2(160 BYTE),
    NOMBRE_FIADOR           VARCHAR2(65 BYTE),
    APELLIDO_FIADOR         VARCHAR2(65 BYTE),
    -- Constraint de Llave Primaria
    CONSTRAINT PK_SOLICITUD_REPRESTAMO PRIMARY KEY (CODIGO_EMPRESA, ID_REPRESTAMO)
);

-- Comentarios Opcionales
COMMENT ON TABLE PR.PR_SOLICITUD_REPRESTAMO IS 'Tabla que almacena los datos de la solicitud de représtamo iniciada por un cliente.';
COMMENT ON COLUMN PR.PR_SOLICITUD_REPRESTAMO.CODIGO_EMPRESA IS 'Código de la empresa.';
COMMENT ON COLUMN PR.PR_SOLICITUD_REPRESTAMO.ID_REPRESTAMO IS 'Identificador único del registro de représtamo (enlaza con PR_REPRESTAMOS).';
COMMENT ON COLUMN PR.PR_SOLICITUD_REPRESTAMO.IDENTIFICACION IS 'Número de identificación del cliente solicitante.';
COMMENT ON COLUMN PR.PR_SOLICITUD_REPRESTAMO.NO_CREDITO IS 'Número del nuevo crédito generado tras el desembolso.';
COMMENT ON COLUMN PR.PR_SOLICITUD_REPRESTAMO.ESTADO IS 'Estado actual de la solicitud dentro del flujo del représtamo.';
COMMENT ON COLUMN PR.PR_SOLICITUD_REPRESTAMO.CODIGO_AGENCIA IS 'Código de la agencia asociada a la solicitud.';
COMMENT ON COLUMN PR.PR_SOLICITUD_REPRESTAMO.CODIGO_OFICIAL IS 'Código del oficial de negocio asociado (posiblemente).';
COMMENT ON COLUMN PR.PR_SOLICITUD_REPRESTAMO.ID_TEMPFUD IS 'ID de la tabla temporal FUD asociada (si aplica).';
COMMENT ON COLUMN PR.PR_SOLICITUD_REPRESTAMO.NOMARCHIVO IS 'Nombre del archivo FUD generado (si aplica).';
COMMENT ON COLUMN PR.PR_SOLICITUD_REPRESTAMO.ID_TEMPFEC IS 'ID de la tabla temporal FEC asociada (si aplica).';
COMMENT ON COLUMN PR.PR_SOLICITUD_REPRESTAMO.TIPO_CREDITO IS 'Tipo de crédito finalmente asignado o seleccionado.';
COMMENT ON COLUMN PR.PR_SOLICITUD_REPRESTAMO.WORLD_COMPLIANCE IS 'Resultado numérico de la validación en listas World Compliance (si aplica).';
COMMENT ON COLUMN PR.PR_SOLICITUD_REPRESTAMO.IDENTIFICADOR_FIADOR IS 'Número de identificación del fiador (si aplica).';
COMMENT ON COLUMN PR.PR_SOLICITUD_REPRESTAMO.ADICIONADO_POR IS 'Usuario que creó o registró la solicitud.';
COMMENT ON COLUMN PR.PR_SOLICITUD_REPRESTAMO.FECHA_ADICION IS 'Fecha en que se creó o registró la solicitud.';

-- Índices opcionales (ejemplos)
-- CREATE INDEX IDX_SOLREPRE_IDENTIFICACION ON PR.PR_SOLICITUD_REPRESTAMO (IDENTIFICACION);
-- CREATE INDEX IDX_SOLREPRE_AGENCIA ON PR.PR_SOLICITUD_REPRESTAMO (CODIGO_AGENCIA);
-- CREATE INDEX IDX_SOLREPRE_ESTADO ON PR.PR_SOLICITUD_REPRESTAMO (ESTADO);
-- CREATE INDEX IDX_SOLREPRE_NOCREDITO ON PR.PR_SOLICITUD_REPRESTAMO (NO_CREDITO);
-- CREATE INDEX IDX_SOLREPRE_IDTEMPFUD ON PR.PR_SOLICITUD_REPRESTAMO (ID_TEMPFUD);