-- Entorno: QA02
-- Schema: CC
-- Fecha: 2026-04-24
-- Origen: DDL pegado por el usuario desde QA ADEMI 02 / QA02.
-- Motivo: Caso de borrado del cliente/persona 1202121 con ORA-02292.
-- Observacion: DDL normalizado para consulta del repo. Conserva estructura, PK,
-- indices, checks, FKs y triggers/sinonimo relevantes del DDL recibido.

DROP TABLE CC.CUENTA_EFECTIVO CASCADE CONSTRAINTS;

CREATE TABLE CC.CUENTA_EFECTIVO
(
  COD_EMPRESA               VARCHAR2(5 BYTE),
  NUM_CUENTA                NUMBER(14),
  COD_PRODUCTO              VARCHAR2(4 BYTE) CONSTRAINT NN_CUENTA_EFEC_COD_PRODUCTO NOT NULL,
  COD_AGENCIA               VARCHAR2(5 BYTE) CONSTRAINT NN_CUENTA_EFEC_COD_AGENCIA NOT NULL,
  COD_CLIENTE               VARCHAR2(15 BYTE) CONSTRAINT NN_CUENTA_EFEC_COD_CLIENTE NOT NULL,
  COD_DIRECCION             VARCHAR2(8 BYTE) CONSTRAINT NN_CUENTA_EFEC_COD_DIRECCION NOT NULL,
  COD_GRUPO                 VARCHAR2(6 BYTE),
  COD_GRUPO_CIERR           VARCHAR2(6 BYTE) CONSTRAINT NN_CUENTA_EFEC_COD_GRUPO_CIERR NOT NULL,
  COD_EJECUTIVO             VARCHAR2(10 BYTE) CONSTRAINT NN_CUENTA_EFEC_COD_EJECUTIVO NOT NULL,
  COD_BLOQUEO               VARCHAR2(5 BYTE),
  COD_CANCELACION           VARCHAR2(5 BYTE),
  COD_EMBARGO               VARCHAR2(5 BYTE),
  FEC_BLOQUEO               DATE,
  FEC_CANCELAC              DATE,
  FEC_ING_GRUPO             DATE,
  FEC_APERTURA              DATE,
  FEC_INI_SOBGRO            DATE,
  FEC_ULT_ACT_INT           DATE,
  FEC_ULT_CAP_INT           DATE,
  FEC_ULT_MOVIMTO           DATE,
  COD_CONGELACION           VARCHAR2(5 BYTE),
  NOMBRE_CHEQUERA           VARCHAR2(80 BYTE),
  TITULARES                 VARCHAR2(200 BYTE),
  CLASE_CUENTA              VARCHAR2(1 BYTE) CONSTRAINT NN_CUENTA_EFEC_CLASE_CUENTA NOT NULL,
  CATEG_CUENTA              VARCHAR2(5 BYTE) CONSTRAINT NN_CUENTA_EFEC_CATEG_CUENTA NOT NULL,
  FREC_CALC_INT             VARCHAR2(1 BYTE) CONSTRAINT NN_CUENTA_EFEC_FREC_CALC_INT NOT NULL,
  TIP_ASIGNA_TASA           VARCHAR2(1 BYTE) CONSTRAINT NN_CUENTA_EFEC_TIP_ASIGNA_TASA NOT NULL,
  TIP_ASIGNA_CARG           VARCHAR2(1 BYTE) CONSTRAINT NN_CUENTA_EFEC_TIP_ASIGNA_CARG NOT NULL,
  TIP_CAR_ADMINIS           VARCHAR2(1 BYTE) CONSTRAINT NN_CUENTA_EFEC_TIP_CAR_ADMINIS NOT NULL,
  TIP_CAPITALIZAC           VARCHAR2(1 BYTE) CONSTRAINT NN_CUENTA_EFEC_TIP_CAPITALIZAC NOT NULL,
  TIP_CORRESPOND            VARCHAR2(5 BYTE) CONSTRAINT NN_CUENTA_EFEC_TIP_CORRESPOND NOT NULL,
  IND_IDIOMA                VARCHAR2(1 BYTE) CONSTRAINT NN_CUENTA_EFEC_IND_IDIOMA NOT NULL,
  IND_SOLICITUD             VARCHAR2(1 BYTE) CONSTRAINT NN_CUENTA_EFEC_IND_SOLICITUD NOT NULL,
  IND_ESTADO                VARCHAR2(1 BYTE) CONSTRAINT NN_CUENTA_EFEC_IND_ESTADO NOT NULL,
  IND_CTA_ALTERNA           VARCHAR2(1 BYTE) CONSTRAINT NN_CUENTA_EFEC_IND_CTA_ALTERNA NOT NULL,
  IND_TRANS_AUTOM           VARCHAR2(1 BYTE) CONSTRAINT NN_CUENTA_EFEC_IND_TRANS_AUTOM NOT NULL,
  IND_MANCOMUNADA           VARCHAR2(1 BYTE) CONSTRAINT NN_CUENTA_EFEC_IND_MANCOMUNADA NOT NULL,
  IND_IMPUESTO              VARCHAR2(1 BYTE) CONSTRAINT NN_CUENTA_EFEC_IND_IMPUESTO NOT NULL,
  IND_PAG_INTERES           VARCHAR2(1 BYTE) CONSTRAINT NN_CUENTA_EFEC_IND_PAG_INTERES NOT NULL,
  IND_RESERVA_ESP           VARCHAR2(1 BYTE) CONSTRAINT NN_CUENTA_EFEC_IND_RESERVA_ESP NOT NULL,
  CANTIDAD_CHEQUES          NUMBER(8) CONSTRAINT NN_CUENTA_EFEC_CANTIDAD_CHEQU NOT NULL,
  CANT_CKS_MES              NUMBER(8) CONSTRAINT NN_CUENTA_EFEC_CANT_CKS_MES NOT NULL,
  CANT_DEP_MES              NUMBER(8) CONSTRAINT NN_CUENTA_EFEC_CANT_DEP_MES NOT NULL,
  DIAS_ACUM_SALDO           NUMBER(5),
  SAL_TOTAL_CTA             NUMBER(18,2) CONSTRAINT NN_CUENTA_EFEC_SAL_TOTAL_CTA NOT NULL,
  SAL_TOT_DIA_ANT           NUMBER(18,2) CONSTRAINT NN_CUENTA_EFEC_SAL_TOT_DIA_ANT NOT NULL,
  SAL_RESERVA               NUMBER(18,2) CONSTRAINT NN_CUENTA_EFEC_SAL_RESERVA NOT NULL,
  SAL_MINIMO                NUMBER(18,2) CONSTRAINT NN_CUENTA_EFEC_SAL_MINIMO NOT NULL,
  SAL_CONSULTADO            NUMBER(18,2) CONSTRAINT NN_CUENTA_EFEC_SAL_CONSULTADO NOT NULL,
  SAL_CONGELADO             NUMBER(18,2) CONSTRAINT NN_CUENTA_EFEC_SAL_CONGELADO NOT NULL,
  SAL_EMBARGADO             NUMBER(18,2) CONSTRAINT NN_CUENTA_EFEC_SAL_EMBARGADO NOT NULL,
  SAL_MENOR                 NUMBER(18,2) CONSTRAINT NN_CUENTA_EFEC_SAL_MENOR NOT NULL,
  SAL_PROMEDIO              NUMBER(18,2) CONSTRAINT NN_CUENTA_EFEC_SAL_PROMEDIO NOT NULL,
  SAL_MAXIMO                NUMBER(18,2) CONSTRAINT NN_CUENTA_EFEC_SAL_MAXIMO NOT NULL,
  SAL_AL_CIERRE             NUMBER(18,2) CONSTRAINT NN_CUENTA_EFEC_SAL_AL_CIERRE NOT NULL,
  SAL_MENOR_MES             NUMBER(18,2) CONSTRAINT NN_CUENTA_EFEC_SAL_MENOR_MES NOT NULL,
  SAL_PROMED_MES            NUMBER(18,2) CONSTRAINT NN_CUENTA_EFEC_SAL_PROMED_MES NOT NULL,
  SAL_MAXIMO_MES            NUMBER(18,2) CONSTRAINT NN_CUENTA_EFEC_SAL_MAXIMO_MES NOT NULL,
  ACUMULAD_IMPTOS           NUMBER(18,2) CONSTRAINT NN_CUENTA_EFEC_ACUMULAD_IMPTOS NOT NULL,
  MON_RESERVA_UTL           NUMBER(18,2) CONSTRAINT NN_CUENTA_EFEC_MON_RESERVA_UTL NOT NULL,
  MON_SOBGRO_AUT            NUMBER(18,2) CONSTRAINT NN_CUENTA_EFEC_MON_SOBGRO_AUT NOT NULL,
  MON_SOB_NO_AUT            NUMBER(18,2) CONSTRAINT NN_CUENTA_EFEC_MON_SOB_NO_AUT NOT NULL,
  MON_SOBGRO_DISP           NUMBER(18,2) CONSTRAINT NN_CUENTA_EFEC_MON_SOBGRO_DISP NOT NULL,
  MON_TOTAL_CARGO           NUMBER(18,2) CONSTRAINT NN_CUENTA_EFEC_MON_TOTAL_CARGO NOT NULL,
  MONTO_IMPTOS              NUMBER(18,2) CONSTRAINT NN_CUENTA_EFEC_MONTO_IMPTOS NOT NULL,
  INT_SOBRE_SALDO           NUMBER(18,2) CONSTRAINT NN_CUENTA_EFEC_INT_SOBRE_SALDO NOT NULL,
  INT_CAP_EMBARGO           NUMBER(18,2) CONSTRAINT NN_CUENTA_EFEC_INT_CAP_EMBARGO NOT NULL,
  INT_CAP_CONGELA           NUMBER(18,2) CONSTRAINT NN_CUENTA_EFEC_INT_CAP_CONGELA NOT NULL,
  INT_CAP_RESERVA           NUMBER(18,2) CONSTRAINT NN_CUENTA_EFEC_INT_CAP_RESERVA NOT NULL,
  INT_POR_PAGAR             NUMBER(18,2) CONSTRAINT NN_CUENTA_EFEC_INT_POR_PAGAR NOT NULL,
  INT_SOBGRO_AUT            NUMBER(18,2) CONSTRAINT NN_CUENTA_EFEC_INT_SOBGRO_AUT NOT NULL,
  INT_USO_SOBGRO            NUMBER(18,2) CONSTRAINT NN_CUENTA_EFEC_INT_USO_SOBGRO NOT NULL,
  NUM_CTA_RELACIO           NUMBER(14),
  SAL_TRANSITO              NUMBER(18,2) CONSTRAINT NN_CUENTA_EFEC_SAL_TRANSITO NOT NULL,
  IND_SOBGRO                VARCHAR2(1 BYTE),
  MON_REVALOR_MES           NUMBER(16,2),
  INT_RESERVA_UTL           NUMBER(18,2),
  SAL_ULT_CORTE             NUMBER(18,2),
  IND_RESERVA_UTL           VARCHAR2(1 BYTE) CONSTRAINT NN_CUENTA_EFEC_IND_RESERVA_UTL NOT NULL,
  SAL_ACU_DIA_ANT           NUMBER(18,2),
  MON_MAX_SOB               NUMBER(18,2),
  SAL_TOT_MES_ANT           NUMBER(18,2),
  FEC_VENC_SOBREG           DATE,
  FEC_VENC_RESERV           DATE,
  FEC_ACT_SOB_RES           DATE,
  USU_ACT_SOB_RES           VARCHAR2(10 BYTE),
  INT_MES_ANT               NUMBER(18,2),
  MON_MAX_RES               NUMBER(18,2),
  SAL_ULT_HISTORI           NUMBER(18,2),
  INT_SOB_NO_AUT            NUMBER(18,2) CONSTRAINT NN_CUENTA_EFEC_INT_SOB_NO_AUT NOT NULL,
  ULT_CKE_ENTREG            NUMBER(12) CONSTRAINT NN_CUENTA_EFEC_ULT_CKE_ENTREG NOT NULL,
  INT_MES_ACTUAL            NUMBER(18,2) CONSTRAINT NN_CUENTA_EFEC_INT_MES_ACTUAL NOT NULL,
  CAN_TDEBITO_DIA           NUMBER(4),
  MON_TDEBITO_DIA           NUMBER(18,2),
  IND_SOB_NO_AUT            VARCHAR2(1 BYTE) CONSTRAINT NN_CTA_EFECTIVO_IND_SOB_NO_AUT NOT NULL,
  TAS_INTERES               NUMBER(7,3),
  DIAS_ACUM_TASA            NUMBER(6),
  OBSERVACION_CORTA         VARCHAR2(30 BYTE),
  PERIOD_REVISI             NUMBER(4),
  FEC_REVISION              DATE,
  COD_TAS_INT               VARCHAR2(5 BYTE),
  NUM_CUENTA_ASOC           NUMBER(14),
  IND_EXP_SYNCOUT           VARCHAR2(1 BYTE),
  SUBTIP_DEBTRANS           VARCHAR2(5 BYTE),
  MON_TRANSITO_UTL          NUMBER(18,2),
  IND_RESTRINGIDA           VARCHAR2(1 BYTE) CONSTRAINT NN_CUENTA_EFEC_IND_RESTRING NOT NULL,
  COBRA_CARGO_INACT         VARCHAR2(1 BYTE) CONSTRAINT NN_CUENTA_EFEC_COB_CARG_INA NOT NULL,
  COBRA_CARGO_SOBGRO        VARCHAR2(1 BYTE) CONSTRAINT NN_CUENTA_EFEC_COB_CARG_SOB NOT NULL,
  COBRA_CARGO_CHK_PLAZA     VARCHAR2(1 BYTE) CONSTRAINT NN_CUENTA_EFEC_COB_CARG_CHK NOT NULL,
  PORC_DISP_LINEA_SOB       NUMBER(8,4),
  PORC_DISP_LINEA_RES       NUMBER(8,4),
  INT_DISP_LINEA_SOB        NUMBER(18,2),
  INT_DISP_LINEA_RES        NUMBER(18,2),
  MON_AUT_RES               NUMBER(18,2),
  SAL_EMBARGO_PEND          NUMBER(18,2),
  SAL_RESERVA_EMB           NUMBER(18,2),
  SAL_TRANSITO_EMB          NUMBER(18,2),
  IND_PAG_INT_RESERVA       VARCHAR2(1 BYTE),
  IND_TAS_INT_RESERVA       VARCHAR2(1 BYTE),
  TIP_TAS_RESERV            VARCHAR2(5 BYTE),
  OPE_MAT_RESERV            VARCHAR2(1 BYTE),
  SPREAD_RESERV             NUMBER(8,4),
  DIA_BASE_RESERV           NUMBER(3),
  ULT_MOVTO_IMPRESO         NUMBER(10),
  FEC_ULT_IMPRESION         DATE,
  CLAVE_IVR                 VARCHAR2(4 BYTE),
  DEP_NOCTURNO_SEGURO       VARCHAR2(1 BYTE),
  IND_CONTROL_SECUENCIA     VARCHAR2(1 BYTE),
  IND_CTA_SUBTITULADA       VARCHAR2(1 BYTE) DEFAULT 'N',
  NOMBRE_SUBTITULO          VARCHAR2(60 BYTE),
  REPRESENTANTE_LEGAL       VARCHAR2(15 BYTE),
  IND_PAG_IMP_TRANSF        VARCHAR2(1 BYTE) DEFAULT 'S',
  CUENTA_CHEQUERA           VARCHAR2(11 BYTE),
  NUM_CUENTA_NACIONAL       VARCHAR2(28 BYTE),
  TIPO_CHEQUERA             VARCHAR2(5 BYTE),
  IND_DEPOSITO_IDENT        VARCHAR2(1 BYTE),
  FEC_VIGENCIA_DEP_IDENT    DATE,
  FEC_PUBLICA_ABANDONA      DATE,
  FEC_TRANSF_ABANDONADA_BC  DATE,
  IND_CTA_FACTORING         VARCHAR2(1 BYTE),
  IND_CTA_LEASING           VARCHAR2(1 BYTE),
  FEC_PRI_CR                DATE,
  CANCELAR_CTA              VARCHAR2(1 BYTE),
  FEC_CONTRATO              DATE,
  ADICIONADO_POR            VARCHAR2(10 BYTE),
  FECHA_ADICION             DATE,
  MODIFICADO_POR            VARCHAR2(10 BYTE),
  FECHA_MODIFICACION        DATE,
  MOT_INACTIVIDAD           VARCHAR2(2 BYTE) DEFAULT 'NA',
  FEC_ULT_MOVIMTO_ACT       DATE,
  CODIGO_PROMOTOR           VARCHAR2(10 BYTE)
)
TABLESPACE DATA_EFD
LOGGING
NOCOMPRESS
NOCACHE;

COMMENT ON TABLE CC.CUENTA_EFECTIVO IS 'En esta tabla se almacenan las cuentas de efectivo administradas por el sistema';

CREATE UNIQUE INDEX CC.PK_CUENTA_EFECTIVO ON CC.CUENTA_EFECTIVO (COD_EMPRESA, NUM_CUENTA) TABLESPACE IND_EFD;

ALTER TABLE CC.CUENTA_EFECTIVO ADD (
  CONSTRAINT CK_CTAEFEC_DEPNOCTURNOSEG CHECK (DEP_NOCTURNO_SEGURO IN ('S', 'N')) ENABLE VALIDATE,
  CONSTRAINT CK_CTAEFEC_INDCTASUBTIT CHECK (IND_CTA_SUBTITULADA IN ('S', 'N')) ENABLE VALIDATE,
  CONSTRAINT CK_CTAEFEC_INDCTLSEQ CHECK (IND_CONTROL_SECUENCIA IN ('S', 'N')) ENABLE VALIDATE,
  CONSTRAINT CK_CTAEFEC_INDDEPOIDENT CHECK (IND_DEPOSITO_IDENT IN ('S', 'N')) ENABLE VALIDATE,
  CONSTRAINT CK_CTAEFEC_INDPAGIMPTRANSF CHECK (IND_PAG_IMP_TRANSF IN ('S', 'N')) ENABLE VALIDATE,
  CONSTRAINT CK_CTAEFEC_INDPAGINTRESERV CHECK (IND_PAG_INT_RESERVA IN ('S', 'N')) ENABLE VALIDATE,
  CONSTRAINT CK_CTAEFEC_INDTASINTRESERV CHECK (IND_TAS_INT_RESERVA IN ('P', 'C')) ENABLE VALIDATE,
  CONSTRAINT CK_CTA_EFECTIVO_IND_SOB_NO_AUT CHECK (IND_SOB_NO_AUT IN ('S','N')) ENABLE VALIDATE,
  CONSTRAINT CK_CUENTAEFEC_MOTINAC CHECK (MOT_INACTIVIDAD IN ('NA', 'FA', 'AB')) ENABLE VALIDATE,
  CONSTRAINT CK_CUENTA_EFECTIVO_CTA_SUB01 CHECK (IND_CTA_SUBTITULADA IN ('S','N')) ENABLE VALIDATE,
  CONSTRAINT CK_CUENTA_EFEC_CLASE_CUENTA CHECK (CLASE_CUENTA IN ('E','P')) ENABLE VALIDATE,
  CONSTRAINT CK_CUENTA_EFEC_COB_CARG_CHK CHECK (COBRA_CARGO_CHK_PLAZA IN ('S','N')) ENABLE VALIDATE,
  CONSTRAINT CK_CUENTA_EFEC_COB_CARG_INA CHECK (COBRA_CARGO_INACT IN ('S','N')) ENABLE VALIDATE,
  CONSTRAINT CK_CUENTA_EFEC_COB_CARG_SOB CHECK (COBRA_CARGO_SOBGRO IN ('S','N')) ENABLE VALIDATE,
  CONSTRAINT CK_CUENTA_EFEC_FREC_CALC_INT CHECK (FREC_CALC_INT IN ('D','S','Q','M','N')) ENABLE VALIDATE,
  CONSTRAINT CK_CUENTA_EFEC_IND_CTA_ALTERNA CHECK (IND_CTA_ALTERNA IN ('S','N')) ENABLE VALIDATE,
  CONSTRAINT CK_CUENTA_EFEC_IND_ESTADO CHECK (IND_ESTADO IN ('0','1','2','3','4','5','6','7','8','9')) ENABLE VALIDATE,
  CONSTRAINT CK_CUENTA_EFEC_IND_IDIOMA CHECK (IND_IDIOMA IN ('E','I')) ENABLE VALIDATE,
  CONSTRAINT CK_CUENTA_EFEC_IND_IMPUESTO CHECK (IND_IMPUESTO IN ('S','N')) ENABLE VALIDATE,
  CONSTRAINT CK_CUENTA_EFEC_IND_MANCOMUNADA CHECK (IND_MANCOMUNADA IN ('S','N')) ENABLE VALIDATE,
  CONSTRAINT CK_CUENTA_EFEC_IND_PAG_INTERES CHECK (IND_PAG_INTERES IN ('S','N')) ENABLE VALIDATE,
  CONSTRAINT CK_CUENTA_EFEC_IND_RESERVA_ESP CHECK (IND_RESERVA_ESP IN ('S','N')) ENABLE VALIDATE,
  CONSTRAINT CK_CUENTA_EFEC_IND_RESERVA_UTL CHECK (IND_RESERVA_UTL IN ('S','N')) ENABLE VALIDATE,
  CONSTRAINT CK_CUENTA_EFEC_IND_RESTRING CHECK (IND_RESTRINGIDA IN ('S','N')) ENABLE VALIDATE,
  CONSTRAINT CK_CUENTA_EFEC_IND_SOBGRO CHECK (IND_SOBGRO IN ('S','N')) ENABLE VALIDATE,
  CONSTRAINT CK_CUENTA_EFEC_IND_SOLICITUD CHECK (IND_SOLICITUD IN ('S','N')) ENABLE VALIDATE,
  CONSTRAINT CK_CUENTA_EFEC_IND_TRANS_AUTOM CHECK (IND_TRANS_AUTOM IN ('S','N')) ENABLE VALIDATE,
  CONSTRAINT CK_CUENTA_EFEC_TIP_ASIGNA_CARG CHECK (TIP_ASIGNA_CARG IN ('E','G','R','I','N')) ENABLE VALIDATE,
  CONSTRAINT CK_CUENTA_EFEC_TIP_ASIGNA_TASA CHECK (TIP_ASIGNA_TASA IN ('G','R','I','N')) ENABLE VALIDATE,
  CONSTRAINT CK_CUENTA_EFEC_TIP_CAPITALIZAC CHECK (TIP_CAPITALIZAC IN ('D','S','Q','M','B','T','E','A','N','C')) ENABLE VALIDATE,
  CONSTRAINT CK_CUENTA_EFEC_TIP_CAR_ADMINIS CHECK (TIP_CAR_ADMINIS IN ('G','R','I','N')) ENABLE VALIDATE,
  CONSTRAINT CK_IND_CTA_SUBTITULADA CHECK (IND_CTA_SUBTITULADA IN ('S', 'N')) ENABLE VALIDATE,
  CONSTRAINT CUENTA_EFECTIVO_C01 CHECK (NVL(SAL_TOTAL_CTA,0) >= 0) ENABLE NOVALIDATE,
  CONSTRAINT CUENTA_EFECTIVO_C02 CHECK (NVL(SAL_CONGELADO,0) >= 0) ENABLE NOVALIDATE,
  CONSTRAINT CUENTA_EFECTIVO_C03 CHECK (NVL(SAL_EMBARGADO,0) >= 0) ENABLE NOVALIDATE,
  CONSTRAINT PK_CUENTA_EFECTIVO PRIMARY KEY (COD_EMPRESA, NUM_CUENTA) USING INDEX CC.PK_CUENTA_EFECTIVO ENABLE VALIDATE
);

CREATE INDEX CC.CUENTA_EFECTIVO_01 ON CC.CUENTA_EFECTIVO (TO_NUMBER("COD_EMPRESA")) TABLESPACE CC_IDX;
CREATE INDEX CC.CUENTA_EFECTIVO_FK1 ON CC.CUENTA_EFECTIVO (COD_EMPRESA, CATEG_CUENTA) TABLESPACE CC_IDX;
CREATE INDEX CC.CUENTA_EFECTIVO_FK10 ON CC.CUENTA_EFECTIVO (COD_EMPRESA, TIP_CORRESPOND) TABLESPACE CC_IDX;
CREATE INDEX CC.CUENTA_EFECTIVO_FK2 ON CC.CUENTA_EFECTIVO (COD_EMPRESA, COD_GRUPO) TABLESPACE CC_IDX;
CREATE INDEX CC.CUENTA_EFECTIVO_FK3 ON CC.CUENTA_EFECTIVO (COD_EMPRESA, COD_GRUPO_CIERR) TABLESPACE CC_IDX;
CREATE INDEX CC.CUENTA_EFECTIVO_FK4 ON CC.CUENTA_EFECTIVO (COD_EMPRESA, TIPO_CHEQUERA) TABLESPACE CC_IDX;
CREATE INDEX CC.CUENTA_EFECTIVO_FK5 ON CC.CUENTA_EFECTIVO (COD_EMPRESA, COD_PRODUCTO) TABLESPACE CC_IDX;
CREATE INDEX CC.CUENTA_EFECTIVO_FK6 ON CC.CUENTA_EFECTIVO (COD_EMPRESA, TIP_TAS_RESERV) TABLESPACE CC_IDX;
CREATE INDEX CC.CUENTA_EFECTIVO_FK7 ON CC.CUENTA_EFECTIVO (COD_EMPRESA, COD_TAS_INT) TABLESPACE CC_IDX;
CREATE INDEX CC.CUENTA_EFECTIVO_FK8 ON CC.CUENTA_EFECTIVO (REPRESENTANTE_LEGAL) TABLESPACE CC_IDX;
CREATE INDEX CC.CUENTA_EFECTIVO_FK9 ON CC.CUENTA_EFECTIVO (COD_CLIENTE, COD_DIRECCION) TABLESPACE CC_IDX;
CREATE INDEX CC.IDX_CE_EMP_CLI_CTA ON CC.CUENTA_EFECTIVO (COD_EMPRESA, COD_CLIENTE, NUM_CUENTA) TABLESPACE CC_IDX;
CREATE INDEX CC.IDX_CUENTA_AGENCIA ON CC.CUENTA_EFECTIVO (COD_EMPRESA, COD_AGENCIA, IND_ESTADO) TABLESPACE IND_EFD;
CREATE INDEX CC.IDX_CUENTA_EFECTIVO ON CC.CUENTA_EFECTIVO (COD_EMPRESA, COD_CLIENTE) TABLESPACE IND_EFD;
CREATE INDEX CC.IDX_CUENTA_EFECTIVO_EAFP ON CC.CUENTA_EFECTIVO (COD_EMPRESA, COD_AGENCIA, COD_PRODUCTO, FEC_APERTURA) TABLESPACE CC_IDX;
CREATE INDEX CC.IDX01_CUENTA_EFECTIVO ON CC.CUENTA_EFECTIVO (NUM_CUENTA) TABLESPACE CC_IDX;

CREATE OR REPLACE TRIGGER CC.CC_BITACORA_MAESTRO
AFTER UPDATE OF IND_ESTADO ON CC.CUENTA_EFECTIVO
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
DECLARE
  vUser VARCHAR2(30);
  vOSUser VARCHAR2(30);
  vMachine VARCHAR2(64);
  vProgram VARCHAR2(64);
BEGIN
  BEGIN
    SELECT UPPER(USER), UPPER(osuser), UPPER(machine), SUBSTR(program,1,150)
      INTO vUser, vOSUser, vMachine, vProgram
      FROM v$session
     WHERE sid = (SELECT sid FROM v$mystat WHERE ROWNUM = 1);
  EXCEPTION
    WHEN OTHERS THEN
      vUser := '';
      vOSUser := '';
      vMachine := '';
      vProgram := '';
  END;

  IF :old.ind_estado <> :new.ind_estado THEN
    BEGIN
      INSERT INTO bitacora_maestros
        (fecha, cuenta, usuario_oracle, usuario_os, terminal, sistema, tabla, campo, valor_anterior, valor_nuevo, programa)
      VALUES
        (SYSDATE, :old.num_cuenta, vUser, vOSUser, vMachine, 'CC', 'CUENTA_EFECTIVO', 'IND_ESTADO',
         :old.ind_estado, :new.ind_estado, vProgram);
    EXCEPTION
      WHEN OTHERS THEN
        NULL;
    END;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER CC.ESTADO_CUENTA
AFTER UPDATE OF IND_ESTADO ON CC.CUENTA_EFECTIVO
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
DECLARE
  vEstado VARCHAR2(1);
BEGIN
  IF UPDATING THEN
    IF :NEW.IND_ESTADO IN ('1','6') THEN
      vEstado := 'S';
    ELSE
      vEstado := 'N';
    END IF;

    BEGIN
      UPDATE TARJETAS_CTAS
         SET CUENTA_VALIDA = vEstado
       WHERE COD_EMPRESA = :NEW.COD_EMPRESA
         AND NUM_CUENTA = :NEW.NUM_CUENTA;
    EXCEPTION
      WHEN OTHERS THEN
        NULL;
    END;
  END IF;
EXCEPTION
  WHEN OTHERS THEN
    NULL;
END;
/

CREATE OR REPLACE TRIGGER CC.TRG_CC_CUENTA_EFECTIVO
BEFORE INSERT OR UPDATE ON CC.CUENTA_EFECTIVO
FOR EACH ROW
BEGIN
  IF :new.fec_apertura IS NULL THEN
    :new.fec_apertura := TRUNC(SYSDATE);
  END IF;

  IF INSERTING THEN
    :New.Adicionado_Por := USER;
    :New.Fecha_adicion := SYSDATE;
  ELSIF UPDATING THEN
    :New.Modificado_Por := USER;
    :New.Fecha_Modificacion := SYSDATE;
    IF :New.Adicionado_Por != :Old.Adicionado_Por THEN
      :New.Adicionado_Por := :Old.Adicionado_Por;
    END IF;
    IF :New.Fecha_adicion != :Old.Fecha_adicion THEN
      :New.Fecha_adicion := :Old.Fecha_adicion;
    END IF;
  END IF;
END TRG_CJ_CajaSaldosExist;
/

CREATE OR REPLACE PUBLIC SYNONYM CUENTA_EFECTIVO FOR CC.CUENTA_EFECTIVO;

ALTER TABLE CC.CUENTA_EFECTIVO ADD (
  CONSTRAINT FK10_CUENTA_EFECTIVO FOREIGN KEY (COD_EMPRESA, TIP_CORRESPOND) REFERENCES CC.TIPOS_CORRESPON (COD_EMPRESA, TIP_CORRESPON) ENABLE VALIDATE,
  CONSTRAINT FK6_CUENTA_EFECTIVO FOREIGN KEY (COD_EMPRESA, COD_GRUPO) REFERENCES CC.GRUPO_CUENTA (COD_EMPRESA, COD_GRUPO) ENABLE VALIDATE,
  CONSTRAINT FK9_CUENTA_EFECTIVO FOREIGN KEY (COD_EMPRESA, CATEG_CUENTA) REFERENCES CC.CATEG_CUENTA (COD_EMPRESA, COD_CATEGORIA) ENABLE VALIDATE,
  CONSTRAINT FK_CTAEFEC_DIRECCION FOREIGN KEY (COD_CLIENTE, COD_DIRECCION) REFERENCES PA.DIR_PERSONAS (COD_PERSONA, COD_DIRECCION) ENABLE VALIDATE,
  CONSTRAINT FK_CTAEFEC_EMPRESA FOREIGN KEY (COD_EMPRESA) REFERENCES PA.EMPRESA (COD_EMPRESA) ENABLE VALIDATE,
  CONSTRAINT FK_CTAEFEC_GRPCIERRE FOREIGN KEY (COD_EMPRESA, COD_GRUPO_CIERR) REFERENCES CC.GRUPOS_CIERRE (COD_EMPRESA, COD_GRUPO) ENABLE VALIDATE,
  CONSTRAINT FK_CTAEFEC_REPRELEGAL FOREIGN KEY (REPRESENTANTE_LEGAL) REFERENCES PA.PERSONAS (COD_PERSONA) ENABLE VALIDATE,
  CONSTRAINT FK_CTAEFEC_TASAINTERES FOREIGN KEY (COD_EMPRESA, COD_TAS_INT) REFERENCES PA.TASAS_INTERES (COD_EMPRESA, COD_TASA) ENABLE VALIDATE,
  CONSTRAINT FK_CTAEFEC_TIPTASRESERV FOREIGN KEY (COD_EMPRESA, TIP_TAS_RESERV) REFERENCES PA.TASAS_INTERES (COD_EMPRESA, COD_TASA) ENABLE VALIDATE,
  CONSTRAINT FK_CTA_EFE_CLIENTES FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES PA.CLIENTE (COD_EMPRESA, COD_CLIENTE) ENABLE VALIDATE,
  CONSTRAINT FK_CUENTAEFEC_PRODUCTOS FOREIGN KEY (COD_EMPRESA, COD_PRODUCTO) REFERENCES PA.PRODUCTOS (COD_EMPRESA, COD_PRODUCTO) ENABLE VALIDATE,
  CONSTRAINT FK_CUENTAEFEC_TIPOSCHEQU FOREIGN KEY (COD_EMPRESA, TIPO_CHEQUERA) REFERENCES CC.TIPOS_CHEQUERAS (COD_EMPRESA, TIPO_CHEQUERA) ENABLE VALIDATE
);

