-- Entorno: QA02
-- Schema: CC
-- Fecha: 2026-04-24
-- Origen: DDL pegado por el usuario desde QA ADEMI 02 / QA02.
-- Motivo: Caso de borrado del cliente/persona 1202121 con ORA-02292.
-- Observacion: DDL normalizado completo de estructura y relaciones relevantes.

DROP TABLE CC.INT_CUENTA_DIARIO CASCADE CONSTRAINTS;

CREATE TABLE CC.INT_CUENTA_DIARIO
(
  COD_EMPRESA            VARCHAR2(5 BYTE) NOT NULL,
  NUM_CUENTA             NUMBER(14) NOT NULL,
  FEC_INTERES            DATE NOT NULL,
  COD_PRODUCTO           VARCHAR2(4 BYTE),
  COD_AGENCIA            VARCHAR2(5 BYTE),
  COD_CLIENTE            VARCHAR2(15 BYTE),
  MON_CALCULO            NUMBER(18,2),
  TAS_INTERES            NUMBER(10,6),
  MON_INTERES            NUMBER(18,2) NOT NULL,
  DIAS_BASE              NUMBER(3) NOT NULL,
  DIAS_CALCULO           NUMBER(3) NOT NULL,
  IND_ESTADO             VARCHAR2(1 BYTE) NOT NULL,
  ADICIONADO_POR         VARCHAR2(10 BYTE) NOT NULL,
  FECHA_ADICION          DATE NOT NULL,
  MODIFICADO_POR         VARCHAR2(10 BYTE),
  FECHA_MODIFICACION     DATE,
  NUM_ASIENTO            NUMBER(10),
  CUENTA_CONTABLE_DEBE   VARCHAR2(30 BYTE),
  CUENTA_CONTABLE_HABER  VARCHAR2(30 BYTE)
)
TABLESPACE CC_DAT
LOGGING
NOCOMPRESS
NOCACHE;

CREATE UNIQUE INDEX CC.INT_CUENTA_DIARIO_PK ON CC.INT_CUENTA_DIARIO (COD_EMPRESA, NUM_CUENTA, FEC_INTERES) TABLESPACE CC_DAT;

ALTER TABLE CC.INT_CUENTA_DIARIO ADD (
  CONSTRAINT INT_CUENTA_DIARIO_PK PRIMARY KEY (COD_EMPRESA, NUM_CUENTA, FEC_INTERES) USING INDEX CC.INT_CUENTA_DIARIO_PK ENABLE VALIDATE
);

CREATE INDEX CC.IDX_INTCTADIA_CUENTAEFEC ON CC.INT_CUENTA_DIARIO (COD_EMPRESA, NUM_CUENTA) TABLESPACE IND_EFD;
CREATE INDEX CC.IDX_INTCTADIA_PRODAGEFEC ON CC.INT_CUENTA_DIARIO (COD_EMPRESA, FEC_INTERES, COD_PRODUCTO, COD_AGENCIA) TABLESPACE IND_EFD;
CREATE INDEX CC.INT_CUENTA_DIARIO_FEC_IDX ON CC.INT_CUENTA_DIARIO (COD_EMPRESA, FEC_INTERES) TABLESPACE CC_DAT;

CREATE OR REPLACE TRIGGER CC.TRG_INT_CUENTA_DIARIO
BEFORE INSERT OR UPDATE ON CC.INT_CUENTA_DIARIO
FOR EACH ROW
BEGIN
  IF INSERTING THEN
    :New.Adicionado_Por := USER;
    :New.Fecha_adicion := SYSDATE;
  ELSIF UPDATING THEN
    :New.Modificado_Por := USER;
    :New.Fecha_Modificacion := SYSDATE;
    IF :New.Adicionado_Por != :Old.Adicionado_Por THEN
      :New.Adicionado_Por := :Old.Adicionado_Por;
    END IF;
    IF :New.Fecha_adicion != :Old.Fecha_adicion THEN
      :New.Fecha_adicion := :Old.Fecha_adicion;
    END IF;
  END IF;
END TRG_INT_CUENTA_DIARIO;
/

CREATE OR REPLACE PUBLIC SYNONYM INT_CUENTA_DIARIO FOR CC.INT_CUENTA_DIARIO;

ALTER TABLE CC.INT_CUENTA_DIARIO ADD (
  CONSTRAINT INT_CUENTA_DIARIO_R01
  FOREIGN KEY (COD_EMPRESA, NUM_CUENTA)
  REFERENCES CC.CUENTA_EFECTIVO (COD_EMPRESA, NUM_CUENTA)
  ENABLE VALIDATE
);

