
  CREATE TABLE "PR"."PR_ESTADOS_REPRESTAMO" 
   (	"CODIGO_EMPRESA" NUMBER(4,0) NOT NULL ENABLE, 
	"CODIGO_ESTADO" VARCHAR2(5 BYTE) NOT NULL ENABLE, 
	"DES_ESTADO" VARCHAR2(500 BYTE) NOT NULL ENABLE, 
	"ORDEN" NUMBER(5,0), 
	"IND_NOTIFICA_CLIENTE" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	"ESTADO" VARCHAR2(5 BYTE) NOT NULL ENABLE, 
	"ICONO" VARCHAR2(100 BYTE), 
	"ADICIONADO_POR" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"FECHA_ADICION" DATE NOT NULL ENABLE, 
	"MODIFICADO_POR" VARCHAR2(30 BYTE), 
	"FECHA_MODIFICACION" DATE, 
	"IND_CAMBIA_ESTADO_REPRE" VARCHAR2(1 BYTE), 
	"GRUPO" VARCHAR2(100 BYTE), 
	"COLOR" VARCHAR2(50 BYTE), 
	"IND_CAMBIA_ESTADO_ORIGINAL" VARCHAR2(1 BYTE), 
	"COMENTARIO" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 MAXSIZE UNLIMITED
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PR_DAT" ;
  CREATE UNIQUE INDEX "PR"."PK_PR_ESTADOS_REPRESTAMOS" ON "PR"."PR_ESTADOS_REPRESTAMO" ("CODIGO_EMPRESA", "CODIGO_ESTADO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 MAXSIZE UNLIMITED
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PR_DAT" ;
ALTER TABLE "PR"."PR_ESTADOS_REPRESTAMO" ADD CONSTRAINT "PK_PR_ESTADOS_REPRESTAMOS" PRIMARY KEY ("CODIGO_EMPRESA", "CODIGO_ESTADO")
  USING INDEX "PR"."PK_PR_ESTADOS_REPRESTAMOS"  ENABLE;

   COMMENT ON COLUMN "PR"."PR_ESTADOS_REPRESTAMO"."GRUPO" IS 'Agrupación de los estados según su criterio de procesamiento.';

  CREATE OR REPLACE EDITIONABLE TRIGGER "PR"."TRG_BUI_PR_ESTADOS_REPRESTAMO" 
BEFORE INSERT OR UPDATE
ON PR.PR_ESTADOS_REPRESTAMO REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
  IF INSERTING THEN
     :new.fecha_adicion := sysdate;  
     if :new.adicionado_por is null THEN
        :new.adicionado_por := user;
     end if;
  ELSE 
     :new.fecha_modificacion := sysdate;
     if :new.modificado_por is null THEN
        :new.modificado_por := user;
     end if;
  END IF;
END;
/
ALTER TRIGGER "PR"."TRG_BUI_PR_ESTADOS_REPRESTAMO" ENABLE;


  GRANT SELECT ON "PR"."PR_ESTADOS_REPRESTAMO" TO "BPR";
