
  CREATE TABLE "PR"."PR_SOLICITUD_REPRESTAMO" 
   (	"CODIGO_EMPRESA" NUMBER(4,0) NOT NULL ENABLE, 
	"ID_REPRESTAMO" NUMBER(14,0) NOT NULL ENABLE, 
	"NOMBRES" VARCHAR2(65 BYTE), 
	"APELLIDOS" VARCHAR2(65 BYTE), 
	"IDENTIFICACION" VARCHAR2(30 BYTE), 
	"FEC_NACIMIENTO" DATE, 
	"SEXO" VARCHAR2(3 BYTE), 
	"NACIONALIDAD" VARCHAR2(20 BYTE), 
	"ESTADO_CIVIL" VARCHAR2(3 BYTE), 
	"TELEFONO_CELULAR" VARCHAR2(20 BYTE), 
	"TELEFONO_RESIDENCIA" VARCHAR2(20 BYTE), 
	"TELEFONO_TRABAJO" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(200 BYTE), 
	"COD_DIRECCION" VARCHAR2(15 BYTE), 
	"TIP_DIRECCION" VARCHAR2(1 BYTE), 
	"DIRECCION" VARCHAR2(160 BYTE), 
	"PLAZO" NUMBER(5,0), 
	"OPCION_RECHAZO" VARCHAR2(1 BYTE), 
	"NO_CREDITO" NUMBER(7,0), 
	"ESTADO" VARCHAR2(5 BYTE) NOT NULL ENABLE, 
	"ADICIONADO_POR" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"FECHA_ADICION" DATE NOT NULL ENABLE, 
	"MODIFICADO_POR" VARCHAR2(30 BYTE), 
	"FECHA_MODIFICACION" DATE, 
	"CODIGO_ACTIVIDAD" VARCHAR2(15 BYTE), 
	"MARGEN_BRUTO_STD" NUMBER(6,4), 
	"GASTO_OPERATIVO_STD" NUMBER(14,2), 
	"VENTAS_MENSUAL" NUMBER(14,2), 
	"COSTO_VENTAS" NUMBER(14,2), 
	"GASTO_OPERATIVO" NUMBER(14,2), 
	"OTROS_INGRESOS" NUMBER(14,2), 
	"GASTOS_FAMILIARES" NUMBER(14,2), 
	"EXCEDENTE_FAMILIARES" NUMBER(14,2), 
	"REL_CUOTA_EXCED_FAM" NUMBER(14,2), 
	"CODIGO_AGENCIA" VARCHAR2(5 BYTE), 
	"CODIGO_OFICIAL" VARCHAR2(5 BYTE), 
	"ID_TEMPFUD" NUMBER(15,0), 
	"NOMARCHIVO" VARCHAR2(50 BYTE), 
	"ID_TEMPFEC" NUMBER(15,0), 
	"COD_PAIS" VARCHAR2(5 BYTE), 
	"COD_PROVINCIA" VARCHAR2(5 BYTE), 
	"COD_CANTON" VARCHAR2(5 BYTE), 
	"COD_DISTRITO" VARCHAR2(5 BYTE), 
	"COD_CIUDAD" VARCHAR2(5 BYTE), 
	"TIPO_CREDITO" NUMBER DEFAULT NULL, 
	"WORLD_COMPLIANCE" NUMBER, 
	"IDENTIFICADOR_FIADOR" VARCHAR2(30 BYTE), 
	"TELEFONO_FIADOR" VARCHAR2(30 BYTE), 
	"EMAIL_FIADOR" VARCHAR2(200 BYTE), 
	"DIRECCION_FIADOR" VARCHAR2(160 BYTE), 
	"NOMBRE_FIADOR" VARCHAR2(65 BYTE), 
	"APELLIDO_FIADOR" VARCHAR2(65 BYTE), 
	"APP_ADEMI" VARCHAR2(2 BYTE), 
	 CONSTRAINT "PK_SOLICITUD_REPRESTAMO" PRIMARY KEY ("CODIGO_EMPRESA", "ID_REPRESTAMO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PR_DAT"  ENABLE, 
	 CONSTRAINT "FK_SOLICITUD_REPRESTAMO" FOREIGN KEY ("CODIGO_EMPRESA", "ID_REPRESTAMO")
	  REFERENCES "PR"."PR_REPRESTAMOS" ("CODIGO_EMPRESA", "ID_REPRESTAMO") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PR_DAT" ;

  CREATE INDEX "PR"."IDX_SOLICITUD_REPRESTAMO" ON "PR"."PR_SOLICITUD_REPRESTAMO" ("CODIGO_EMPRESA", "NO_CREDITO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 MAXSIZE UNLIMITED
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PR_DAT" ;

  CREATE INDEX "PR"."IDX_SOLREPRE_EMP_NOCRED" ON "PR"."PR_SOLICITUD_REPRESTAMO" ("NO_CREDITO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PR_DAT" ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "PR"."TRG_BUI_SOLICITUD_REPRESTAMO" 
BEFORE INSERT OR UPDATE
ON PR.PR_SOLICITUD_REPRESTAMO REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
  IF INSERTING THEN
     :new.fecha_adicion := sysdate;
     --PR_PKG_REPRESTAMOS.p_generar_bitacora(:new.ID_REPRESTAMO,NULL,'RE',NULL,'Carga inicial');
  ELSE 
     :new.fecha_modificacion := sysdate;
  END IF;
END;
/
ALTER TRIGGER "PR"."TRG_BUI_SOLICITUD_REPRESTAMO" ENABLE;


  GRANT INSERT ON "PR"."PR_SOLICITUD_REPRESTAMO" TO "BPR";
  GRANT SELECT ON "PR"."PR_SOLICITUD_REPRESTAMO" TO "BPR";
  GRANT UPDATE ON "PR"."PR_SOLICITUD_REPRESTAMO" TO "BPR";
  GRANT SELECT ON "PR"."PR_SOLICITUD_REPRESTAMO" TO "PA" WITH GRANT OPTION;
