create or replace PACKAGE    pkg_solicitud_credito is
    procedure pcrearfud(pid_tempfud    in out number,
                        pnomarchivo    in out varchar2,
                        pprocesado     in out varchar2,
                        pidaperturacliente in out varchar2,
                        ptipodocumentoidentidad in out varchar2,
                        pnumdocumentoidentidad in out varchar2,
                        pidoficial     in out varchar2,
                        pidagencia     in out varchar2,
                        --                        pPIN OUTrimer_Apellido                 VARCHAR2 , ---Buscar en Padrón
                        --                        pSIN OUTegundo_Apellido                VARCHAR2 ,
                        --                        pPIN OUTrimer_Nombre.                   VARCHAR2 ,
                        --                        pSIN OUTegundo_Nombre                  VARCHAR2 ,
                        pprimernombre  in out varchar2,
                        pprimerapellido in out varchar2,
                        psexo          in out varchar2,
                        pfechanacimiento in out varchar2,
                        papodo         in out varchar2,
                        pidempleado    in out varchar2,
                        pidpais        in out varchar2,
                        pidprovincia   in out varchar2,
                        pidmunicipio   in out varchar2,
                        piddistrito    in out varchar2,
                        pidestadocivil in out varchar2,
                        pnohijos       in out varchar2,
                        pdependientes  in out varchar2,
                        pgradoint      in out varchar2,
                        pidocupacion   in out varchar2,
                        pidvinculado   in out varchar2,
                        pnombrevinculado in out varchar2,
                        pidtipovinculado in out varchar2,
                        pidcomosuponosotros in out varchar2,
                        pdireccion     in out varchar2,
                        pdireccion_idsector in out varchar2,
                        pdireccion_idprovincia in out varchar2,
                        pdireccion_idmunicipio in out varchar2,
                        pdireccion_distrito in out varchar2,
                        pdireccion_idtipovivienda in out varchar2,
                        pref_domicilio in out varchar2,
                        ptelefono_casa in out varchar2,
                        ptelefono_celular in out varchar2,
                        pnombrenegocio in out varchar2,
                        pnoempleados   in out varchar2,
                        prnc           in out varchar2,
                        pfax           in out varchar2,
                        pemail         in out varchar2,
                        psectoreconomico in out varchar2,
                        pactividad_ciiu in out varchar2,
                        pidrama_ciiu   in out varchar2,
                        pinicio_mes    in out varchar2,
                        pinicio_ano    in out varchar2,
                        pubicacion_neg in out varchar2,
                        plugartrabajo  in out varchar2,
                        pfechaingreso  in out varchar2,
                        pcargo         in out varchar2,
                        ptrabajo_direccion in out varchar2,
                        ptrabajo_idsector in out varchar2,
                        ptrabajo_idprovincia in out varchar2,
                        ptrabajo_idmunicipio in out varchar2,
                        ptrabajo_iddistrito in out varchar2,
                        ppuntoreferencia in out varchar2,
                        ptelefono      in out varchar2,
                        pextension     in out varchar2,
                        prefpersonales_apellidos in out varchar2,
                        prefpersonales_nombres in out varchar2,
                        prefpersonales_telefono in out varchar2,
                        prefpersonales_relfamiliar in out varchar2,
                        prefpersonales_nombres2 in out varchar2,
                        prefpersonales_apellidos2 in out varchar2,
                        prefpersonales_telefono2 in out varchar2,
                        prefpersonales_relfam2 in out varchar2,
                        pactualmenteenmora in out varchar2,
                        pcumpliorequisitos in out varchar2,
                        ppresento_doc_fraudulenta in out varchar2,
                        pdijolaverdad  in out varchar2,
                        pclienteesfiador in out varchar2,
                        pclientemoroso in out varchar2,
                        psobreendeudamiento_sf in out varchar2,
                        pactividadcliente in out varchar2,
                        ptipopersona   in out varchar2,
                        ptipodocumentoidentidadco in out varchar2,
                        pnumdocumentoidentidadco in out varchar2,
                        pprimernombreco in out varchar2,
                        pprimerapellidoco in out varchar2,
                        psexoco        in out varchar2,
                        pfechanacimientoco in out varchar2,
                        papodoco       in out varchar2,
                        pidempleadoco  in out varchar2,
                        pidpaisco      in out varchar2,
                        pidprovinciaco in out varchar2,
                        pidmunicipioco in out varchar2,
                        piddistritoco  in out varchar2,
                        pidestadocivilco in out varchar2,
                        pnohijosco     in out varchar2,
                        pdependientesco in out varchar2,
                        pgradointco    in out varchar2,
                        pidocupacionco in out varchar2,
                        pidvinculadoco in out varchar2,
                        pnombrevinculadoco in out varchar2,
                        pidtipovinculadoco in out varchar2,
                        pidcomosuponosotrosco in out varchar2,
                        pnombrenegocioco in out varchar2,
                        pnoempleadosco in out varchar2,
                        prncco         in out varchar2,
                        pfaxco         in out varchar2,
                        pemailco       in out varchar2,
                        psectoreconomicoco in out varchar2,
                        pactividad_ciiuco in out varchar2,
                        pidrama_ciiuco in out varchar2,
                        pinicio_mesco  in out varchar2,
                        pinicio_anoco  in out varchar2,
                        pubicacion_negco in out varchar2,
                        plugartrabajoco in out varchar2,
                        pfechaingresoco in out varchar2,
                        ptrabajo_direccionco in out varchar2,
                        ptrabajo_idsectorco in out varchar2,
                        ptrabajo_idprovinciaco in out varchar2,
                        ptrabajo_idmunicipioco in out varchar2,
                        ptrabajo_iddistritoco in out varchar2,
                        ppuntoreferenciaco in out varchar2,
                        ptelefonoco    in out varchar2,
                        pextensionco   in out varchar2,
                        pcargoco       in out varchar2,
                        preside_mes    in out varchar2,
                        preside_ano    in out varchar2,
                        pactividadco   in out varchar2,
                        ptipopersonaco in out varchar2,
                        ptiposolicitud in out varchar2,
                        pcodigoproyecto in out varchar2,
                        pdestinocredito in out varchar2,
                        pespecifiquedestino in out varchar2,
                        ptipopersonacal in out varchar2,
                        pedadcal       in out varchar2,
                        pmontocal      in out varchar2,
                        pplazocal      in out varchar2,
                        pmonedacal     in out varchar2,
                        pdiapagocal    in out varchar2,
                        pfrecuenciacal in out varchar2,
                        pgraciacal     in out varchar2,
                        pgarantiacal   in out varchar2,
                        pseguro_vehiculocal in out varchar2,
                        pseguro_vidacal in out varchar2,
                        pseguro_incendiocal in out varchar2,
                        pgastoscal     in out varchar2,
                        ptipoprestamocal in out varchar2,
                        pgarantiasolidariacal in out varchar2,
                        phipotecariacal in out varchar2,
                        pprendariacal  in out varchar2,
                        pliquidacal    in out varchar2,
                        pcuotasegurocal in out varchar2,
                        pcuotaprestamocal in out varchar2,
                        ptotalfinanciarcal in out varchar2,
                        ptasacal       in out varchar2,
                        pgastoslegalescal in out varchar2,
                        psegurovidacal in out varchar2,
                        pseguroaliadacal in out varchar2,
                        psegurovehcal  in out varchar2,
                        pclasificacion in out varchar2,
                        pfirmacliente  in out varchar2,
                        pfirmaco       in out varchar2,
                        pclientepertenece in out varchar2,
                        pfecha_registro in out varchar2, ---malmanzar 10-03-2022
                        ptipocal       in out number,
                        ptipoparentesco in out varchar2,
                        ptipoparentescoco in out varchar2,
                        ptipopersona2  in out varchar2,
                        ptipocliente   in out varchar2,
                        ptipoproductos in out varchar2,
                        pactividadciiu_sol in out varchar2,
                        pidramaciiu_sol in out varchar2,
                        errorcode      in out varchar2,
                        errordescription in out varchar2,
                        pnocredito     in out number,
                        psegundonombre in out varchar2,
                        psegundoapellido in out varchar2,
                        psegundonombreco in out varchar2,
                        psegundoapellidoco in out varchar2,
                        pcodpaisiso    in out varchar2,
                        papellidocasadacliente in out varchar2,
                        pcedulaextranjera in out varchar2);

    procedure pcrearfec(pidtempfec     in out number,
                        pnomarchivo    in out varchar2,
                        pidevaluacioncrediticia in out varchar2,
                        ptipodocumentoidentidad in out varchar2,
                        pdocumentoidentidad in out varchar2,
                        pnombrecliente in out varchar2,
                        pnumerosolicitud in out number,
                        pmontorecomendado in out number,
                        pfrecuencia    in out varchar2, --malmanzar 14-07-222
                        pplazo         in out number,
                        ppro1ventasmensuales in out number,
                        ppro2ventasmensuales in out number,
                        ppro3ventasmensuales in out number,
                        pprootroventasmensuales in out number,
                        pventasmensuales1 in out number,
                        pventasmensuales2 in out number,
                        pventasmensuales3 in out number,
                        pventasmensuales4 in out number,
                        pventasmensuales5 in out number,
                        pventasmensuales6 in out number,
                        pventasmensuales7 in out number,
                        pventasmensuales8 in out number,
                        pventasmensualesot in out number,
                        pventas_ingresos in out number,
                        ppro1costosventasmensuales in out number,
                        ppro2costosventasmensuales in out number,
                        ppro3costosventasmensuales in out number,
                        pprootrocostosventasmensuales in out number,
                        pcostoventas1  in out number,
                        pcostoventas2  in out number,
                        pcostoventas3  in out number,
                        pcostoventas4  in out number,
                        pcostoventas5  in out number,
                        pcostoventas6  in out number,
                        pcostoventas7  in out number,
                        pcostoventas8  in out number,
                        pcostoventasot in out number,
                        pcostoventas   in out number,
                        psueldo        in out number,
                        pservicio      in out number,
                        palquiler      in out number,
                        ptransporte_combs in out number,
                        ppagointereses in out number,
                        potrosingresos_operacionales in out number,
                        palimentacion  in out number,
                        pvivienda      in out number,
                        pvestido       in out number,
                        ptransporte    in out number,
                        pservicios     in out number,
                        pmedicinas     in out number,
                        peducacion     in out number,
                        pdeudasfamiliares in out number,
                        potros_gastos  in out number,
                        ptotalgastos_familiares in out number,
                        pexcedentefamiliar in out number,
                        potros         in out number,
                        pmaquinaria_mueblesequipos in out number,
                        pefectivo_cajabanco in out number,
                        pcuentaxcobrar in out number,
                        pinventario_prod_tem in out number,
                        pinventario_prod_proc in out number,
                        pinventario_materiaprima in out number,
                        pmercancia     in out number,
                        panticipo_proveedores in out number,
                        plocalnegocio  in out number,
                        pobligacionesfinancieras in out number,
                        ptotal_pasivo_lp in out number,
                        pmueble_vehiculo in out number,
                        pdeudacomercial in out number,
                        ptasa          in out number,
                        pcuota         in out number,
                        pcuentapagarprovedor in out number,
                        pcuentapagarvarias in out number,
                        pinmuebles     in out number,
                        ptotal_activofamiliar in out number,
                        pdeudabancaria in out number,
                        ptotal_pasivofamiliar in out number,
                        ppatrio_fam_balgen in out number, ---
                        ptotal_activocorriente in out number,
                        ptotal_activofijo in out number,
                        ptotal_activos1 in out number,
                        ptotal_pasivocorrientes in out number,
                        ptotal_pasivo  in out number,
                        ptotal_pasivopatrimonio in out number,
                        ppasivo_patrimonio in out number,
                        ppatrimonio    in out number,
                        pactivocorte_pascte in out number,
                        potrosingresos_excedente in out number,
                        pcuotarecomendada_excedfam in out number,
                        ptotalpasivo_patrimonio in out number,
                        putilidadneta_patrimonio in out number,
                        putilidadneta_totalactivos1 in out number,
                        putilidadneta_ventas in out number,
                        pcuentasxcobrar_ventas in out number,
                        pcostoventa_inventario in out number,
                        pgastoslegales in out number, --
                        pmoneda        in out varchar2,
                        pcapital_trabajo in out number,
                        pfechabalancegeneral in out varchar2,
                        pdesde         in out varchar2,
                        phasta         in out varchar2,
                        ptotalcostooperacional in out number,
                        putilidadneta  in out number,
                        pventasdiarias_promedio in out number,
                        pdiastrabajados in out number,
                        pcomprassemanalesdeclaradas in out number,
                        pventasmensualesdeclaradas in out number,
                        pmargendeclarado in out number,
                        pmontomesalto  in out number,
                        pmontomesmedio in out number,
                        pcomprasmensualesdeclaradas in out number,
                        pmontomesbajo  in out number,
                        pventasmensuales in out number,
                        pcostoventamensual in out number,
                        putilidadbruta in out number,
                        pmargenganancia in out number,
                        pprimera_ref_vecinos in out varchar2,
                        psegunda_ref_vecinos in out varchar2,
                        pambientefamiliar in out varchar2,
                        pdependientes  in out number,
                        pedad          in out varchar2, --Number  27-07-2022
                        pestadosaludfamilia in out varchar2, --Number  27-07-2022
                        pingresos      in out varchar2, --Number  27-07-2022
                        potrosingresos in out varchar2, --Number  27-07-2022
                        pexperiencia_neg in out number, --malmanzar 27-07-2022
                        phoras_neg     in out number,
                        plocalpropio   in out varchar2, --malmanzar 14-07-2022
                        ptiempoempleo  in out number,
                        pubicacionnegocio in out varchar2,
                        pllevaregistro in out varchar2,
                        pmejorasnegocio in out varchar2,
                        pclientesfrecuentes in out number,
                        pnivelcompetencia in out varchar2, --malmanzar 14-07-2022
                        pfecha_balancegeneral_al in out varchar2,
                        --                             IN OUT
                        pdestinocredito in out varchar2,
                        pespecifiquedestino in out varchar2,
                        pestadosolicitud in out number,
                        pactividadeconomica in out varchar2,
                        pactividadeconomicadinrap in out varchar2,
                        pmargenbrutoestandar in out number,
                        pgastosoperacionalesestandar in out number,
                        palto_indicadores in out number,
                        pbajo_indicadores in out number,
                        plunes         in out varchar2,
                        pmartes        in out varchar2,
                        pmiercoles     in out varchar2,
                        pjueves        in out varchar2,
                        pviernes       in out varchar2,
                        psabado        in out varchar2,
                        pdomingo       in out varchar2,
                        ptotal_ventasaltas in out number,
                        ptotal_ventasbajas in out number,
                        ptotal_ventassemanales in out number,
                        ptotal_ventasmensuales in out number,
                        pmargenbrutodeclarado in out number,
                        palimentacion_gastos in out number,
                        pvivienda_gastos in out number,
                        peducacion_gastos in out number,
                        psalud_gastos  in out number,
                        ptransporte_gastos in out number,
                        pvestido_gastos in out number,
                        ppagodeudas_gastos in out number,
                        potros_gastos_familiares in out number,
                        ptotal_gastos  in out number,
                        pventas_gastos in out number,
                        pcostosventas_gastos in out number,
                        pgastosoperativos in out number,
                        potros_ingresos_gastos in out number,
                        ptotal_gastos_familiares in out number,
                        pexcedentefamiliar_gastos in out number,
                        pcuotasolicitada in out number,
                        prelcuotasolicitada_excfam in out number,
                        pmonto_recomendacion in out number,
                        pmoneda_recomendacion in out varchar2,
                        pplazo_recomendacion in out number,
                        ptasa_recomendacion in out number,
                        pfrecuencia_recomendacion in out varchar2,
                        pcuota_recomendacion in out number,
                        pestadosolicitud_recomendacion in out number,
                        pcuotarecomendada_excfamiliar in out number,
                        pventasevalanterior in out number,
                        pactual_ventas in out number,
                        pvariacionventas in out number,
                        pcomentario1   in out varchar2,
                        pcomentario2   in out varchar2,
                        ppro1nombre    in out varchar2,
                        ppro1materiaprima1 in out number,
                        ppro1materiaprima2 in out number,
                        ppro1materiaprima3 in out number,
                        ppro1totalmp   in out number,
                        ppro1sueldo1   in out number,
                        ppro1sueldo2   in out number,
                        ppro1totalsueldo in out number,
                        ppro1otroscostos in out number,
                        ppro1totalcostos in out number,
                        ppro1costounitario in out number,
                        ppro1preciounitario in out number,
                        ppro1unidadesvendidas in out number,
                        ppro1margenganancia in out number,
                        ppro2nombre    in out varchar2,
                        ppro2materiaprima1 in out number,
                        ppro2materiaprima2 in out number,
                        ppro2materiaprima3 in out number,
                        ppro2totalmp   in out number,
                        ppro2sueldo1   in out number,
                        ppro2sueldo2   in out number,
                        ppro2totalsueldo in out number,
                        ppro2otroscostos in out number,
                        ppro2totalcostos in out number,
                        ppro2costounitario in out number,
                        ppro2preciounitario in out number,
                        ppro2unidadesvendidas in out number,
                        ppro2margenganancia in out number,
                        ppro3nombre    in out varchar2,
                        ppro3materiaprima1 in out number,
                        ppro3materiaprima2 in out number,
                        ppro3materiaprima3 in out number,
                        ppro3totalmp   in out number,
                        ppro3sueldo1   in out number,
                        ppro3sueldo2   in out number,
                        ppro3totalsueldo in out number,
                        ppro3otroscostos in out number,
                        ppro3totalcostos in out number,
                        ppro3costounitario in out number,
                        ppro3preciounitario in out number,
                        ppro3unidadesvendidas in out number,
                        ppro3margenganancia in out number,
                        pprootromateriaprima1 in out number,
                        pprootromateriaprima2 in out number,
                        pprootromateriaprima3 in out number,
                        pprootrototalmp in out number,
                        pprootrosueldo1 in out number,
                        pprootrosueldo2 in out number,
                        pprootrototalsueldo in out number,
                        pprootrootroscostos in out number,
                        pprootrototalcostos in out number,
                        pprootrocostounitario in out number,
                        pprootropreciounitario in out number,
                        pprootrounidadesvendidas in out number,
                        pprootromargenganancia in out number,
                        plinea1        in out varchar2,
                        ppreciounitario1 in out number,
                        pcostounitario1 in out number,
                        pmargendeganancia1 in out number,
                        punidadesvendidas1 in out number,
                        plinea2        in out varchar2,
                        ppreciounitario2 in out number,
                        pcostounitario2 in out number,
                        pmargendeganancia2 in out number,
                        punidadesvendidas2 in out number,
                        plinea3        in out varchar2,
                        ppreciounitario3 in out number,
                        pcostounitario3 in out number,
                        pmargendeganancia3 in out number,
                        punidadesvendidas3 in out number,
                        plineaot       in out varchar2,
                        ppreciounitarioot in out number,
                        pcostounitarioot in out number,
                        pmargendegananciaot in out number,
                        punidadesvendidasot in out number,
                        ptipocredito   in out varchar2,
                        pgarantias     in out varchar2,
                        pvalorgarantia in out varchar2,
                        pdescripciongarantia in out varchar2,
                        pprestamodescontar in out varchar2,
                        plinea4        in out varchar2,
                        ppreciounitario4 in out number,
                        pcostounitario4 in out number,
                        pmargendeganancia4 in out number,
                        punidadesvendidas4 in out number,
                        plinea5        in out varchar2,
                        ppreciounitario5 in out number,
                        pcostounitario5 in out number,
                        pmargendeganancia5 in out number,
                        punidadesvendidas5 in out number,
                        plinea6        in out varchar2,
                        ppreciounitario6 in out number,
                        pcostounitario6 in out number,
                        pmargendeganancia6 in out number,
                        punidadesvendidas6 in out number,
                        plinea7        in out varchar2,
                        ppreciounitario7 in out number,
                        pcostounitario7 in out number,
                        pmargendeganancia7 in out number,
                        punidadesvendidas7 in out number,
                        plinea8        in out varchar2,
                        ppreciounitario8 in out number,
                        pcostounitario8 in out number,
                        pmargendeganancia8 in out number,
                        punidadesvendidas8 in out number,
                        pcomentario    in out varchar2,
                        pidoficial     in out varchar2,
                        pfecharegistro in out date,
                        pfechafija     in out varchar2,
                        pidestado      in out varchar2,
                        pmensaje       in out varchar2,
                        pnosubida      in out varchar2,
                        pidgrupo       in out varchar2,
                        pimpreso       in out varchar2,
                        /*Valores a retornar para eliminar uso Función fnupdatefud que ejecuta via WS
                           proceso debe implementarse en el llamado de SQL/Server
                          */
                        pestadofec     in out varchar2,
                        pmensajefec    in out varchar2,
                        pnosolicitud   in out number);

    function f_periodicidad_pda_core(pfrecuenciacal_pda varchar2)
        return varchar2;

    function fninsertfud(pid_tempfud    number,
                         pnomarchivo    varchar2,
                         pprocesado     varchar2,
                         pidaperturacliente varchar2,
                         ptipodocumentoidentidad varchar2,
                         pnumdocumentoidentidad varchar2,
                         pidoficial     varchar2,
                         pidagencia     varchar2,
                         pprimernombre  varchar2,
                         pprimerapellido varchar2,
                         psexo          varchar2,
                         pfechanacimiento varchar2,
                         papodo         varchar2,
                         pidempleado    varchar2,
                         pidpais        varchar2,
                         pidprovincia   varchar2,
                         pidmunicipio   varchar2,
                         piddistrito    varchar2,
                         pidestadocivil varchar2,
                         pnohijos       varchar2,
                         pdependientes  varchar2,
                         pgradoint      varchar2,
                         pidocupacion   varchar2,
                         pidvinculado   varchar2,
                         pnombrevinculado varchar2,
                         pidtipovinculado varchar2,
                         pidcomosuponosotros varchar2,
                         pdireccion     varchar2,
                         pdireccion_idsector varchar2,
                         pdireccion_idprovincia varchar2,
                         pdireccion_idmunicipio varchar2,
                         pdireccion_distrito varchar2,
                         pdireccion_idtipovivienda varchar2,
                         pref_domicilio varchar2,
                         ptelefono_casa varchar2,
                         ptelefono_celular varchar2,
                         pnombrenegocio varchar2,
                         pnoempleados   varchar2,
                         prnc           varchar2,
                         pfax           varchar2,
                         pemail         varchar2,
                         psectoreconomico varchar2,
                         pactividad_ciiu varchar2,
                         pidrama_ciiu   varchar2,
                         pinicio_mes    varchar2,
                         pinicio_ano    varchar2,
                         pubicacion_neg varchar2,
                         plugartrabajo  varchar2,
                         pfechaingreso  varchar2,
                         pcargo         varchar2,
                         ptrabajo_direccion varchar2,
                         ptrabajo_idsector varchar2,
                         ptrabajo_idprovincia varchar2,
                         ptrabajo_idmunicipio varchar2,
                         ptrabajo_iddistrito varchar2,
                         ppuntoreferencia varchar2,
                         ptelefono      varchar2,
                         pextension     varchar2,
                         prefpersonales_apellidos varchar2,
                         prefpersonales_nombres varchar2,
                         prefpersonales_telefono varchar2,
                         prefpersonales_relfamiliar varchar2,
                         prefpersonales_nombres2 varchar2,
                         prefpersonales_apellidos2 varchar2,
                         prefpersonales_telefono2 varchar2,
                         prefpersonales_relfam2 varchar2,
                         pactualmenteenmora varchar2,
                         pcumpliorequisitos varchar2,
                         ppresento_doc_fraudulenta varchar2,
                         pdijolaverdad  varchar2,
                         pclienteesfiador varchar2,
                         pclientemoroso varchar2,
                         psobreendeudamiento_sf varchar2,
                         pactividadcliente varchar2,
                         ptipopersona   varchar2,
                         ptipodocumentoidentidadco varchar2,
                         pnumdocumentoidentidadco varchar2,
                         pprimernombreco varchar2,
                         pprimerapellidoco varchar2,
                         psexoco        varchar2,
                         pfechanacimientoco varchar2,
                         papodoco       varchar2,
                         pidempleadoco  varchar2,
                         pidpaisco      varchar2,
                         pidprovinciaco varchar2,
                         pidmunicipioco varchar2,
                         piddistritoco  varchar2,
                         pidestadocivilco varchar2,
                         pnohijosco     varchar2,
                         pdependientesco varchar2,
                         pgradointco    varchar2,
                         pidocupacionco varchar2,
                         pidvinculadoco varchar2,
                         pnombrevinculadoco varchar2,
                         pidtipovinculadoco varchar2,
                         pidcomosuponosotrosco varchar2,
                         pnombrenegocioco varchar2,
                         pnoempleadosco varchar2,
                         prncco         varchar2,
                         pfaxco         varchar2,
                         pemailco       varchar2,
                         psectoreconomicoco varchar2,
                         pactividad_ciiuco varchar2,
                         pidrama_ciiuco varchar2,
                         pinicio_mesco  varchar2,
                         pinicio_anoco  varchar2,
                         pubicacion_negco varchar2,
                         plugartrabajoco varchar2,
                         pfechaingresoco varchar2,
                         ptrabajo_direccionco varchar2,
                         ptrabajo_idsectorco varchar2,
                         ptrabajo_idprovinciaco varchar2,
                         ptrabajo_idmunicipioco varchar2,
                         ptrabajo_iddistritoco varchar2,
                         ppuntoreferenciaco varchar2,
                         ptelefonoco    varchar2,
                         pextensionco   varchar2,
                         pcargoco       varchar2,
                         preside_mes    varchar2,
                         preside_ano    varchar2,
                         pactividadco   varchar2,
                         ptipopersonaco varchar2,
                         ptiposolicitud varchar2,
                         pcodigoproyecto varchar2,
                         pdestinocredito varchar2,
                         pespecifiquedestino varchar2,
                         ptipopersonacal varchar2,
                         pedadcal       varchar2,
                         pmontocal      varchar2,
                         pplazocal      varchar2,
                         pmonedacal     varchar2,
                         pdiapagocal    varchar2,
                         pfrecuenciacal varchar2,
                         pgraciacal     varchar2,
                         pgarantiacal   varchar2,
                         pseguro_vehiculocal varchar2,
                         pseguro_vidacal varchar2,
                         pseguro_incendiocal varchar2,
                         pgastoscal     varchar2,
                         ptipoprestamocal varchar2,
                         pgarantiasolidariacal varchar2,
                         phipotecariacal varchar2,
                         pprendariacal  varchar2,
                         pliquidacal    varchar2,
                         pcuotasegurocal varchar2,
                         pcuotaprestamocal varchar2,
                         ptotalfinanciarcal varchar2,
                         ptasacal       varchar2,
                         pgastoslegalescal varchar2,
                         psegurovidacal varchar2,
                         pseguroaliadacal varchar2,
                         psegurovehcal  varchar2,
                         pclasificacion varchar2,
                         pfirmacliente  varchar2,
                         pfirmaco       varchar2,
                         pclientepertenece varchar2,
                         pfecha_registro varchar2,
                         ptipocal       number,
                         ptipoparentesco varchar2,
                         ptipoparentescoco varchar2,
                         ptipopersona2  varchar2,
                         ptipocliente   varchar2,
                         ptipoproductos varchar2,
                         pactividadciiu_sol varchar2,
                         pidramaciiu_sol varchar2,
                         pnocredito     varchar2,
                         psegundonombre varchar2,
                         psegundoapellido varchar2,
                         psegundonombreco varchar2,
                         psegundoapellidoco varchar2,
                         pcodpaisiso    varchar2,
                         papellidocasadacliente varchar2,
                         pcedulaextranjera varchar2)
        return varchar2;

    function fninsertfec(pid_tempfec    number,
                         pnomarchivo    varchar2,
                         pprocesado     varchar2,
                         pidevaluacioncrediticia varchar2,
                         ptipodocumentoidentidad varchar2,
                         pdocumentoidentidad varchar2,
                         pnombrecliente varchar2,
                         pnumerosolicitud number,
                         pprimera_ref_vecinos varchar2,
                         psegunda_ref_vecinos varchar2,
                         pambientefamiliar varchar2,
                         pdependientes  number,
                         pedad          varchar2,
                         pestadosaludfamilia varchar2,
                         pingresos      varchar2,
                         potrosingresos varchar2,
                         pexperiencia_neg number,
                         phoras_neg     number,
                         plocalpropio   varchar2,
                         ptiempoempleo  number,
                         pubicacionnegocio varchar2,
                         pllevaregistro varchar2,
                         pmejorasnegocio varchar2,
                         pclientesfrecuentes number,
                         pnivelcompetencia varchar2,
                         pventasdiarias_promedio number,
                         pdiastrabajados number,
                         pventasmensualesdeclaradas number,
                         pcomprassemanalesdeclaradas number,
                         pcomprasmensualesdeclaradas number,
                         pmargendeclarado number,
                         pmontomesalto  number,
                         pmontomesmedio number,
                         pmontomesbajo  number,
                         pventasmensuales number,
                         pcostoventamensual number,
                         pmargenganancia number,
                         pdesde         varchar2,
                         phasta         varchar2,
                         pventas_ingresos number,
                         pcostoventas   number,
                         putilidadbruta number,
                         psueldo        number,
                         pservicio      number,
                         palquiler      number,
                         ptransporte_combs number,
                         ppagointereses number,
                         potros         number,
                         ptotalcostooperacional number,
                         putilidadneta  number,
                         potrosingresos_operacionales number,
                         palimentacion  number,
                         pvivienda      number,
                         pvestido       number,
                         ptransporte    number,
                         pservicios     number,
                         pmedicinas     number,
                         peducacion     number,
                         pdeudasfamiliares number,
                         potros_gastos  number,
                         ptotalgastos_familiares number,
                         pexcedentefamiliar number,
                         pfechabalancegeneral varchar2,
                         pefectivo_cajabanco number,
                         pcuentaxcobrar number,
                         pinventario_prod_tem number,
                         pinventario_prod_proc number,
                         pinventario_materiaprima number,
                         pmercancia     number,
                         panticipo_proveedores number,
                         pfecha_balancegeneral_al varchar2,
                         pmueble_vehiculo number,
                         pinmuebles     number,
                         ptotal_activofamiliar number,
                         pdeudacomercial number,
                         pdeudabancaria number,
                         ptotal_pasivofamiliar number,
                         ppatrio_fam_balgen number,
                         pmaquinaria_mueblesequipos number,
                         plocalnegocio  number,
                         pobligacionesfinancieras number,
                         pcuentapagarprovedor number,
                         pcuentapagarvarias number,
                         ptotal_activocorriente number,
                         ptotal_activofijo number,
                         ptotal_activos1 number,
                         ptotal_pasivocorrientes number,
                         ptotal_pasivo_lp number,
                         ptotal_pasivo  number,
                         ppatrimonio    number,
                         ptotal_pasivopatrimonio number,
                         pcapital_trabajo number,
                         ppasivo_patrimonio number,
                         pactivocorte_pascte number,
                         potrosingresos_excedente number,
                         pcuotarecomendada_excedfam number,
                         ptotalpasivo_patrimonio number,
                         putilidadneta_patrimonio number,
                         putilidadneta_totalactivos1 number,
                         putilidadneta_ventas number,
                         pcuentasxcobrar_ventas number,
                         pcostoventa_inventario number,
                         pmontorecomendado number,
                         pgastoslegales number,
                         pmoneda        varchar2,
                         pplazo         number,
                         ptasa          number,
                         pfrecuencia    varchar2,
                         pcuota         number,
                         pdestinocredito varchar2,
                         pespecifiquedestino varchar2,
                         pestadosolicitud number,
                         pactividadeconomica varchar2,
                         pactividadeconomicadinrap varchar2,
                         pmargenbrutoestandar number,
                         pgastosoperacionalesestandar number,
                         palto_indicadores number,
                         pbajo_indicadores number,
                         plunes         varchar2,
                         pmartes        varchar2,
                         pmiercoles     varchar2,
                         pjueves        varchar2,
                         pviernes       varchar2,
                         psabado        varchar2,
                         pdomingo       varchar2,
                         ptotal_ventasaltas number,
                         ptotal_ventasbajas number,
                         ptotal_ventassemanales number,
                         ptotal_ventasmensuales number,
                         pmargenbrutodeclarado number,
                         palimentacion_gastos number,
                         pvivienda_gastos number,
                         peducacion_gastos number,
                         psalud_gastos  number,
                         ptransporte_gastos number,
                         pvestido_gastos number,
                         ppagodeudas_gastos number,
                         potros_gastos_familiares number,
                         ptotal_gastos  number,
                         pventas_gastos number,
                         pcostosventas_gastos number,
                         pgastosoperativos number,
                         potros_ingresos_gastos number,
                         ptotal_gastos_familiares number,
                         pexcedentefamiliar_gastos number,
                         pcuotasolicitada number,
                         prelcuotasolicitada_excfam number,
                         pmonto_recomendacion number,
                         pmoneda_recomendacion varchar2,
                         pplazo_recomendacion number,
                         ptasa_recomendacion number,
                         pfrecuencia_recomendacion varchar2,
                         pcuota_recomendacion number,
                         pestadosolicitud_recomendacion number,
                         pcuotarecomendada_excfamiliar number,
                         pventasevalanterior number,
                         pactual_ventas number,
                         pvariacionventas number,
                         pcomentario1   varchar2,
                         pcomentario2   varchar2,
                         ppro1nombre    varchar2,
                         ppro1materiaprima1 number,
                         ppro1materiaprima2 number,
                         ppro1materiaprima3 number,
                         ppro1totalmp   number,
                         ppro1sueldo1   number,
                         ppro1sueldo2   number,
                         ppro1totalsueldo number,
                         ppro1otroscostos number,
                         ppro1totalcostos number,
                         ppro1costounitario number,
                         ppro1preciounitario number,
                         ppro1unidadesvendidas number,
                         ppro1ventasmensuales number,
                         ppro1costosventasmensuales number,
                         ppro1margenganancia number,
                         ppro2nombre    varchar2,
                         ppro2materiaprima1 number,
                         ppro2materiaprima2 number,
                         ppro2materiaprima3 number,
                         ppro2totalmp   number,
                         ppro2sueldo1   number,
                         ppro2sueldo2   number,
                         ppro2totalsueldo number,
                         ppro2otroscostos number,
                         ppro2totalcostos number,
                         ppro2costounitario number,
                         ppro2preciounitario number,
                         ppro2unidadesvendidas number,
                         ppro2ventasmensuales number,
                         ppro2costosventasmensuales number,
                         ppro2margenganancia number,
                         ppro3nombre    varchar2,
                         ppro3materiaprima1 number,
                         ppro3materiaprima2 number,
                         ppro3materiaprima3 number,
                         ppro3totalmp   number,
                         ppro3sueldo1   number,
                         ppro3sueldo2   number,
                         ppro3totalsueldo number,
                         ppro3otroscostos number,
                         ppro3totalcostos number,
                         ppro3costounitario number,
                         ppro3preciounitario number,
                         ppro3unidadesvendidas number,
                         ppro3ventasmensuales number,
                         ppro3costosventasmensuales number,
                         ppro3margenganancia number,
                         pprootromateriaprima1 number,
                         pprootromateriaprima2 number,
                         pprootromateriaprima3 number,
                         pprootrototalmp number,
                         pprootrosueldo1 number,
                         pprootrosueldo2 number,
                         pprootrototalsueldo number,
                         pprootrootroscostos number,
                         pprootrototalcostos number,
                         pprootrocostounitario number,
                         pprootropreciounitario number,
                         pprootrounidadesvendidas number,
                         pprootroventasmensuales number,
                         pprootrocostosventasmensuales number,
                         pprootromargenganancia number,
                         plinea1        varchar2,
                         ppreciounitario1 number,
                         pcostounitario1 number,
                         pmargendeganancia1 number,
                         punidadesvendidas1 number,
                         pventasmensuales1 number,
                         pcostoventas1  number,
                         plinea2        varchar2,
                         ppreciounitario2 number,
                         pcostounitario2 number,
                         pmargendeganancia2 number,
                         punidadesvendidas2 number,
                         pventasmensuales2 number,
                         pcostoventas2  number,
                         plinea3        varchar2,
                         ppreciounitario3 number,
                         pcostounitario3 number,
                         pmargendeganancia3 number,
                         punidadesvendidas3 number,
                         pventasmensuales3 number,
                         pcostoventas3  number,
                         plineaot       varchar2,
                         ppreciounitarioot number,
                         pcostounitarioot number,
                         pmargendegananciaot number,
                         punidadesvendidasot number,
                         pventasmensualesot number,
                         pcostoventasot number,
                         ptipocredito   varchar2,
                         pgarantias     varchar2,
                         pvalorgarantia varchar2,
                         pdescripciongarantia varchar2,
                         pprestamodescontar varchar2,
                         plinea4        varchar2,
                         ppreciounitario4 number,
                         pcostounitario4 number,
                         pmargendeganancia4 number,
                         punidadesvendidas4 number,
                         pventasmensuales4 number,
                         pcostoventas4  number,
                         plinea5        varchar2,
                         ppreciounitario5 number,
                         pcostounitario5 number,
                         pmargendeganancia5 number,
                         punidadesvendidas5 number,
                         pventasmensuales5 number,
                         pcostoventas5  number,
                         plinea6        varchar2,
                         ppreciounitario6 number,
                         pcostounitario6 number,
                         pmargendeganancia6 number,
                         punidadesvendidas6 number,
                         pventasmensuales6 number,
                         pcostoventas6  number,
                         plinea7        varchar2,
                         ppreciounitario7 number,
                         pcostounitario7 number,
                         pmargendeganancia7 number,
                         punidadesvendidas7 number,
                         pventasmensuales7 number,
                         pcostoventas7  number,
                         plinea8        varchar2,
                         ppreciounitario8 number,
                         pcostounitario8 number,
                         pmargendeganancia8 number,
                         punidadesvendidas8 number,
                         pventasmensuales8 number,
                         pcostoventas8  number,
                         pcomentario    varchar2,
                         pidoficial     varchar2,
                         pfecharegistro date,
                         pfechafija     varchar2,
                         pidestado      varchar2,
                         pmensaje       varchar2,
                         pnosubida      varchar2,
                         pidgrupo       varchar2,
                         pimpreso       varchar2)
        return boolean;

    procedure crea_fec_solicitud(pcodigo_empresa in number, pid_represtamo in number, pmensaje out varchar2, perror out varchar2);

    procedure p_crear_fudextendida(pid                number,
                                   pid_tempfud        number,
                                   pnomarchivo        varchar2,
                                   --Nacionalidad USA
                                   presidenteusa      number, --VARCHAR2,
                                   pnropasaporteusa   varchar2,
                                   pnroitin           varchar2,
                                   pnrossn            varchar2,
                                   pnroresidencia     varchar2,
                                   ---
                                   pzona              number,
                                   pcondicionvivienda number,
                                   pnegociodomicilio  number, --VARCHAR2,
                                   ptiposervicio      number,
                                   pmontoinicial      number,
                                   porigenrecursos    varchar2, --NUMBER,
                                   pformaoperacion    number,
                                   pingresosmensual   number,
                                   --PEPS
                                   pfuncionariogob    number, --VARCHAR2, --PEPS
                                   pespeficiquefunci  varchar2,
                                   pparentescofunci   number, --VARCHAR2, --PARENTESCO PEPS
                                   pexpecifiqueparen  varchar2,
                                   preferenciacomernom1 varchar2,
                                   preferenciacomertel1 varchar2,
                                   preferenciacomernom2 varchar2,
                                   preferenciacomertel2 varchar2,
                                   preferenciabancanom1 varchar2,
                                   preferenciabancatip1 varchar2,
                                   preferenciabancanum1 varchar2,
                                   preferenciabancanom2 varchar2,
                                   preferenciabancatip2 varchar2,
                                   preferenciabancanum2 varchar2,
                                   preferenciaperapodo1 varchar2,
                                   preferenciaperapodo2 varchar2,
                                   preferenciafamnom  varchar2,
                                   preferenciafamape  varchar2,
                                   preferenciafamapodo varchar2,
                                   preferenciafamtelefono varchar2,
                                   --pSEGUROCONTRATADO            NUMBER,
                                   --pSEGUROOTROESPEFICIQUE       VARCHAR2,
                                   pseguroincendiopyme /*pSEGUROINCENDIOLINEA*/ number, --malmanzar 16-03-2023
                                   psegurodesempleodis number,
                                   psegurootroespeficique varchar2,
                                   pfecha_carga       date,
                                   --malmanzar 23-01-2023 Begin
                                   ptipomoneda        number,
                                   pformasdeposito    number,
                                   pactivostotal      number,
                                   pvolumenventa      number,
                                   ppatrimonioneto    number,
                                   prangovolumenmensual number,
                                   pcantidadtransacciones number,
                                   ptieneebankingnumber number,
                                   pposeedobleciudadania varchar2,
                                   pposeedobleciudadaniapais varchar2,
                                   --malmanzar 23-01-2023 end
                                   pmensaje       out varchar2,
                                   perrorcode     out varchar2,
                                   perrordescription out varchar2);


    procedure p_insert_fudextendida(pid                number,
                                    pid_tempfud        number,
                                    pnomarchivo        varchar2,
                                    presidenteusa      number, ---VARCHAR2,
                                    pnropasaporteusa   varchar2,
                                    pnroitin           varchar2,
                                    pnrossn            varchar2,
                                    pnroresidencia     varchar2,
                                    pzona              number,
                                    pcondicionvivienda number,
                                    pnegociodomicilio  number, --VARCHAR2,
                                    ptiposervicio      number,
                                    pmontoinicial      number,
                                    porigenrecursos    varchar2, -- NUMBER,
                                    pformaoperacion    number,
                                    pingresosmensual   number,
                                    pfuncionariogob    number, --VARCHAR2,
                                    pespeficiquefunci  varchar2,
                                    pparentescofunci   number, --VARCHAR2,
                                    pexpecifiqueparen  varchar2,
                                    preferenciacomernom1 varchar2,
                                    preferenciacomertel1 varchar2,
                                    preferenciacomernom2 varchar2,
                                    preferenciacomertel2 varchar2,
                                    preferenciabancanom1 varchar2,
                                    preferenciabancatip1 varchar2,
                                    preferenciabancanum1 varchar2,
                                    preferenciabancanom2 varchar2,
                                    preferenciabancatip2 varchar2,
                                    preferenciabancanum2 varchar2,
                                    preferenciaperapodo1 varchar2,
                                    preferenciaperapodo2 varchar2,
                                    preferenciafamnom  varchar2,
                                    preferenciafamape  varchar2,
                                    preferenciafamapodo varchar2,
                                    preferenciafamtelefono varchar2,
                                    --pSEGUROCONTRATADO            NUMBER,
                                    -- pSEGUROOTROESPEFICIQUE       VARCHAR2,
                                    pseguroincendiopyme /*pSEGUROINCENDIOLINEA*/ number, --malmanzar 16-03-2023
                                    psegurodesempleodis number,
                                    psegurootroespeficique varchar2,
                                    pfecha_carga       date,
                                    --malmanzar 23-01-2023 Begin
                                    ptipomoneda        number,
                                    pformasdeposito    number,
                                    pactivostotal      number,
                                    pvolumenventa      number,
                                    ppatrimonioneto    number,
                                    prangovolumenmensual number,
                                    pcantidadtransacciones number,
                                    ptieneebankingnumber number,
                                    pposeedobleciudadania varchar2,
                                    pposeedobleciudadaniapais varchar2,
                                    --malmanzar 23-01-2023 end
                                    pmensaje       out varchar2,
                                    perrorcode     out varchar2,
                                    perrordescription out varchar2);

    function f_tipoid_pda_core(ptipo_id_pda varchar2)
        return varchar2;

    procedure p_direccion(pidpais        in     varchar2,
                          pidcanton      in     varchar2,
                          pidmunicipio   in     varchar2,
                          piddistrito    in     varchar2,
                          ---Out
                          pidpais_core      out varchar2,
                          pidregion_core    out varchar2, --Region, identificada en el core como provincia
                          pidcanton_core    out varchar2, --Provincia, identificada en el core como Cantón
                          pidmunicipio_core   out varchar2,
                          piddistrito_core   out varchar2);

    procedure agregar_indicador_marcarpoliza(incodempresa   in     varchar2,
                                             innocredito    in     number,
                                             incodagencia   in     varchar2,
                                             intipopoliza   in     varchar2,
                                             inindicador    in     varchar2,
                                             mensaje           out varchar2);

    procedure p_refcom_portacredit(pcod_persona varchar2, ptelefono varchar2, pnombre_referencia varchar2);

    procedure p_refbanc_portacredit(pcod_persona varchar2, ptipo_cuenta varchar2, pnum_cuenta varchar2, pnombre_referencia varchar2);

    procedure p_ref_personales(pcod_persona   varchar2,
                               pcod_empresa   varchar2,
                               pcod_tipo_id   varchar2,
                               pnombre_ref    varchar2,
                               pnum_id        varchar2,
                               pcod_area      varchar2,
                               pnum_telefono  varchar2,
                               ppuesto        varchar2,
                               plugar_trabajo varchar2,
                               prelacion_persona varchar2,
                               pobservaciones varchar2,
                               pextension_tel varchar2);

    procedure p_datos_reg_fatca(pn_cod_cliente in     datos_regulacion_fatca.cod_cliente%type,
                                pc_numero_pasaporte in datos_regulacion_fatca.numero_pasaporte%type,
                                pc_cod_pais    in     datos_regulacion_fatca.cod_pais%type,
                                pc_numero_ss   in     datos_regulacion_fatca.numero_ss%type,
                                pc_numero_tin  in     datos_regulacion_fatca.numero_tin%type,
                                pc_numero_greencard in datos_regulacion_fatca.num_green_card%type,
                                pc_direccion   in     datos_regulacion_fatca.direccion%type,
                                pc_ciudad      in     datos_regulacion_fatca.ciudad%type,
                                pc_num_telefono in    datos_regulacion_fatca.num_telefono%type,
                                pc_num_telefono2 in   datos_regulacion_fatca.num_telefono2%type,
                                pc_es_residente in    datos_regulacion_fatca.es_residente%type,
                                pc_form_impresion in  datos_regulacion_fatca.form_impresion%type,
                                pc_form_cambio in     boolean,
                                pn_opcion      in     number,
                                pc_mensaje     in out varchar2);

    procedure p_lista_p(pcod_persona varchar2, pcargo varchar2, pparentescofunci varchar2);

    procedure p_operaciones_realizar(pcod_persona   varchar2,
                                     ptipo_producto varchar2,
                                     pcod_moneda    varchar2,
                                     pproposito     varchar2,
                                     pmonto_inicial number,
                                     pinstrumento_bancario varchar2,
                                     porigen_fondos varchar2,
                                     pno_credito    number);

    procedure pcrearsolicitud_old(vsolicitud in pr.solicitud_credito_obj,  pn_nocredito out number, pc_task out pa.tarea_list, errorcode in out varchar2, errordescription in out varchar2);

    procedure p_busca_id_persona(pcod_tipo_id varchar2, pnum_id varchar2, pcod_persona out varchar2);

    --
    --PROCEDURE p_id_persona ( IDENTIFICACIONES   PA.ID_PERSONAS_LIST , pCod_Persona Out varchar2 );


    procedure p_procesar_persona(ppersona       in     pr.persona_cr_obj,
                                 psolicitud     in     varchar2,
                                 pcod_oficial   in     number,
                                 pcodigo_agencia in    number,
                                 --Out
                                 -- pTipo_Solicitante     OUT VARCHAR2,
                                 psalario       in     number, --malmanzar 02-05-2024
                                 pcod_persona      out varchar2,
                                 errorcode         out varchar2,
                                 errordescription   out varchar2);

    function get_regionprovincia(pcod_pais in varchar2, pcod_canton in varchar2)
        return number;


    function get_ciuu(pcod_persona varchar2)
        return varchar2;

    function id_existe(ptipo_id varchar2, pnum_id varchar2)
        return boolean;

    procedure pcreafecpersona(p_solicitud    in     number,
                              p_codcliente   in     varchar2,
                              p_codagencia   in     number,
                              ptipo_solicitante in  varchar2,
                              --P_cuotasegurocal,
                              ----              monedacal,
                              p_destinocredito in   varchar2,
                              p_especifiquedestino in varchar2,
                              pidtempfec     in     number,
                              pnomarchivo    in     varchar2,
                              pidevaluacioncrediticia in varchar2,
                              ptipodocumentoidentidad in varchar2,
                              pdocumentoidentidad in varchar2,
                              pnombrecliente in     varchar2,
                              pnumerosolicitud in   number,
                              pmontorecomendado in  number,
                              pfrecuencia    in     varchar2, --malmanzar 14-07-222
                              pplazo         in     number,
                              ppro1ventasmensuales in number,
                              ppro2ventasmensuales in number,
                              ppro3ventasmensuales in number,
                              pprootroventasmensuales in number,
                              pventasmensuales1 in  number,
                              pventasmensuales2 in  number,
                              pventasmensuales3 in  number,
                              pventasmensuales4 in  number,
                              pventasmensuales5 in  number,
                              pventasmensuales6 in  number,
                              pventasmensuales7 in  number,
                              pventasmensuales8 in  number,
                              pventasmensualesot in number,
                              pventas_ingresos in   number,
                              ppro1costosventasmensuales in number,
                              ppro2costosventasmensuales in number,
                              ppro3costosventasmensuales in number,
                              pprootrocostosventasmensuales in number,
                              pcostoventas1  in     number,
                              pcostoventas2  in     number,
                              pcostoventas3  in     number,
                              pcostoventas4  in     number,
                              pcostoventas5  in     number,
                              pcostoventas6  in     number,
                              pcostoventas7  in     number,
                              pcostoventas8  in     number,
                              pcostoventasot in     number,
                              pcostoventas   in     number,
                              psueldo        in     number,
                              pservicio      in     number,
                              palquiler      in     number,
                              ptransporte_combs in  number,
                              ppagointereses in     number,
                              potrosingresos_operacionales in number,
                              palimentacion  in     number,
                              pvivienda      in     number,
                              pvestido       in     number,
                              ptransporte    in     number,
                              pservicios     in     number,
                              pmedicinas     in     number,
                              peducacion     in     number,
                              pdeudasfamiliares in  number,
                              potros_gastos  in     number,
                              ptotalgastos_familiares in number,
                              pexcedentefamiliar in number,
                              potros         in     number,
                              pmaquinaria_mueblesequipos in number,
                              pefectivo_cajabanco in number,
                              pcuentaxcobrar in     number,
                              pinventario_prod_tem in number,
                              pinventario_prod_proc in number,
                              pinventario_materiaprima in number,
                              pmercancia     in     number,
                              panticipo_proveedores in number,
                              plocalnegocio  in     number,
                              pobligacionesfinancieras in number,
                              ptotal_pasivo_lp in   number,
                              pmueble_vehiculo in   number,
                              pdeudacomercial in    number,
                              ptasa          in     number,
                              pcuota         in     number,
                              pcuentapagarprovedor in number,
                              pcuentapagarvarias in number,
                              pinmuebles     in     number,
                              ptotal_activofamiliar in number,
                              pdeudabancaria in     number,
                              ptotal_pasivofamiliar in number,
                              ppatrio_fam_balgen in number, ---
                              ptotal_activocorriente in number,
                              ptotal_activofijo in  number,
                              ptotal_activos1 in    number,
                              ptotal_pasivocorrientes in number,
                              ptotal_pasivo  in     number,
                              ptotal_pasivopatrimonio in number,
                              ppasivo_patrimonio in number,
                              ppatrimonio    in     number,
                              pactivocorte_pascte in number,
                              potrosingresos_excedente in number,
                              pcuotarecomendada_excedfam in number,
                              ptotalpasivo_patrimonio in number,
                              putilidadneta_patrimonio in number,
                              putilidadneta_totalactivos1 in number,
                              putilidadneta_ventas in number,
                              pcuentasxcobrar_ventas in number,
                              pcostoventa_inventario in number,
                              pgastoslegales in     number, --
                              pmoneda        in     varchar2,
                              pcapital_trabajo in   number,
                              pfechabalancegeneral in varchar2,
                              pdesde         in     varchar2,
                              phasta         in     varchar2,
                              ptotalcostooperacional in number,
                              putilidadneta  in     number,
                              pventasdiarias_promedio in number,
                              pdiastrabajados in    number,
                              pcomprassemanalesdeclaradas in number,
                              pventasmensualesdeclaradas in number,
                              pmargendeclarado in   number,
                              pmontomesalto  in     number,
                              pmontomesmedio in     number,
                              pcomprasmensualesdeclaradas in number,
                              pmontomesbajo  in     number,
                              pventasmensuales in   number,
                              pcostoventamensual in number,
                              putilidadbruta in     number,
                              pmargenganancia in    number,
                              pprimera_ref_vecinos in varchar2,
                              psegunda_ref_vecinos in varchar2,
                              pambientefamiliar in  varchar2,
                              pdependientes  in     number,
                              pedad          in     varchar2, --Number  27-07-2022
                              pestadosaludfamilia in varchar2, --Number  27-07-2022
                              pingresos      in     varchar2, --Number  27-07-2022
                              potrosingresos in     varchar2, --Number  27-07-2022
                              pexperiencia_neg in   number, --malmanzar 27-07-2022
                              phoras_neg     in     number,
                              plocalpropio   in     varchar2, --malmanzar 14-07-2022
                              ptiempoempleo  in     number,
                              pubicacionnegocio in  varchar2,
                              pllevaregistro in     varchar2,
                              pmejorasnegocio in    varchar2,
                              pclientesfrecuentes in number,
                              pnivelcompetencia in  varchar2, --malmanzar 14-07-2022
                              pfecha_balancegeneral_al in varchar2,
                              --                             IN OU
                              pdestinocredito in    varchar2,
                              pespecifiquedestino in varchar2,
                              pestadosolicitud in   number,
                              pactividadeconomica in varchar2,
                              pactividadeconomicadinrap in varchar2,
                              pmargenbrutoestandar in number,
                              pgastosoperacionalesestandar in number,
                              palto_indicadores in  number,
                              pbajo_indicadores in  number,
                              plunes         in     varchar2,
                              pmartes        in     varchar2,
                              pmiercoles     in     varchar2,
                              pjueves        in     varchar2,
                              pviernes       in     varchar2,
                              psabado        in     varchar2,
                              pdomingo       in     varchar2,
                              ptotal_ventasaltas in number,
                              ptotal_ventasbajas in number,
                              ptotal_ventassemanales in number,
                              ptotal_ventasmensuales in number,
                              pmargenbrutodeclarado in number,
                              palimentacion_gastos in number,
                              pvivienda_gastos in   number,
                              peducacion_gastos in  number,
                              psalud_gastos  in     number,
                              ptransporte_gastos in number,
                              pvestido_gastos in    number,
                              ppagodeudas_gastos in number,
                              potros_gastos_familiares in number,
                              ptotal_gastos  in     number,
                              pventas_gastos in     number,
                              pcostosventas_gastos in number,
                              pgastosoperativos in  number,
                              potros_ingresos_gastos in number,
                              ptotal_gastos_familiares in number,
                              pexcedentefamiliar_gastos in number,
                              pcuotasolicitada in   number,
                              prelcuotasolicitada_excfam in number,
                              pmonto_recomendacion in number,
                              pmoneda_recomendacion in varchar2,
                              pplazo_recomendacion in number,
                              ptasa_recomendacion in number,
                              pfrecuencia_recomendacion in varchar2,
                              pcuota_recomendacion in number,
                              pestadosolicitud_recomendacion in number,
                              pcuotarecomendada_excfamiliar in number,
                              pventasevalanterior in number,
                              pactual_ventas in     number,
                              pvariacionventas in   number,
                              pcomentario1   in     varchar2,
                              pcomentario2   in     varchar2,
                              ppro1nombre    in     varchar2,
                              ppro1materiaprima1 in number,
                              ppro1materiaprima2 in number,
                              ppro1materiaprima3 in number,
                              ppro1totalmp   in     number,
                              ppro1sueldo1   in     number,
                              ppro1sueldo2   in     number,
                              ppro1totalsueldo in   number,
                              ppro1otroscostos in   number,
                              ppro1totalcostos in   number,
                              ppro1costounitario in number,
                              ppro1preciounitario in number,
                              ppro1unidadesvendidas in number,
                              ppro1margenganancia in number,
                              ppro2nombre    in     varchar2,
                              ppro2materiaprima1 in number,
                              ppro2materiaprima2 in number,
                              ppro2materiaprima3 in number,
                              ppro2totalmp   in     number,
                              ppro2sueldo1   in     number,
                              ppro2sueldo2   in     number,
                              ppro2totalsueldo in   number,
                              ppro2otroscostos in   number,
                              ppro2totalcostos in   number,
                              ppro2costounitario in number,
                              ppro2preciounitario in number,
                              ppro2unidadesvendidas in number,
                              ppro2margenganancia in number,
                              ppro3nombre    in     varchar2,
                              ppro3materiaprima1 in number,
                              ppro3materiaprima2 in number,
                              ppro3materiaprima3 in number,
                              ppro3totalmp   in     number,
                              ppro3sueldo1   in     number,
                              ppro3sueldo2   in     number,
                              ppro3totalsueldo in   number,
                              ppro3otroscostos in   number,
                              ppro3totalcostos in   number,
                              ppro3costounitario in number,
                              ppro3preciounitario in number,
                              ppro3unidadesvendidas in number,
                              ppro3margenganancia in number,
                              pprootromateriaprima1 in number,
                              pprootromateriaprima2 in number,
                              pprootromateriaprima3 in number,
                              pprootrototalmp in    number,
                              pprootrosueldo1 in    number,
                              pprootrosueldo2 in    number,
                              pprootrototalsueldo in number,
                              pprootrootroscostos in number,
                              pprootrototalcostos in number,
                              pprootrocostounitario in number,
                              pprootropreciounitario in number,
                              pprootrounidadesvendidas in number,
                              pprootromargenganancia in number,
                              plinea1        in     varchar2,
                              ppreciounitario1 in   number,
                              pcostounitario1 in    number,
                              pmargendeganancia1 in number,
                              punidadesvendidas1 in number,
                              plinea2        in     varchar2,
                              ppreciounitario2 in   number,
                              pcostounitario2 in    number,
                              pmargendeganancia2 in number,
                              punidadesvendidas2 in number,
                              plinea3        in     varchar2,
                              ppreciounitario3 in   number,
                              pcostounitario3 in    number,
                              pmargendeganancia3 in number,
                              punidadesvendidas3 in number,
                              plineaot       in     varchar2,
                              ppreciounitarioot in  number,
                              pcostounitarioot in   number,
                              pmargendegananciaot in number,
                              punidadesvendidasot in number,
                              ptipocredito   in     varchar2,
                              pgarantias     in     varchar2,
                              pvalorgarantia in     varchar2,
                              pdescripciongarantia in varchar2,
                              pprestamodescontar in varchar2,
                              plinea4        in     varchar2,
                              ppreciounitario4 in   number,
                              pcostounitario4 in    number,
                              pmargendeganancia4 in number,
                              punidadesvendidas4 in number,
                              plinea5        in     varchar2,
                              ppreciounitario5 in   number,
                              pcostounitario5 in    number,
                              pmargendeganancia5 in number,
                              punidadesvendidas5 in number,
                              plinea6        in     varchar2,
                              ppreciounitario6 in   number,
                              pcostounitario6 in    number,
                              pmargendeganancia6 in number,
                              punidadesvendidas6 in number,
                              plinea7        in     varchar2,
                              ppreciounitario7 in   number,
                              pcostounitario7 in    number,
                              pmargendeganancia7 in number,
                              punidadesvendidas7 in number,
                              plinea8        in     varchar2,
                              ppreciounitario8 in   number,
                              pcostounitario8 in    number,
                              pmargendeganancia8 in number,
                              punidadesvendidas8 in number,
                              pcomentario    in     varchar2,
                              pidoficial     in     varchar2,
                              pfecharegistro in     date,
                              pfechafija     in     varchar2,
                              pidestado      in     varchar2,
                              pmensaje       in     varchar2,
                              pnosubida      in     varchar2,
                              pidgrupo       in     varchar2,
                              pimpreso       in     varchar2,
                              /*Valores a retornar para eliminar uso Funci¿n fnupdatefud que ejecuta via WS
                                 proceso debe implementarse en el llamado de SQL/Server
                                */
                              pestadofec        out varchar2,
                              pmensajefec       out varchar2 ---pNoSolicitud                        OUT NUMBER
                                                            );

    procedure pvalida_solicitud(psolicitud in pr.solicitud_credito_obj, perrores out number);

    --FUNCTION Valida_tipcredito_clienteNuevo(pTipo_credito in number, pno_cliente in number)RETURN BOOLEAN;

    procedure p_info_laboral(p_persona      in     varchar2,
                             p_fec_ing      in     date,
                             p_lugar_lab    in     varchar2,
                             p_sueldo       in     number,
                             p_puesto       in     varchar2,
                             p_direccion    in     varchar2,
                             p_telefono     in     varchar2,
                             p_extension    in     varchar2,
                             --Excello:JPH:2020-03-18:REQ_ 108967:Begin >>
                             --P_Archivo_FUD  In  Varchar2,
                             ---P_TIdper_FUD   In  Varchar2,
                             ---P_NumIdoer_FUD In  Varchar2,
                             --Excello:JPH:2020-03-18:REQ_ 108967:End <<
                             p_procesado       out varchar2,
                             p_msgerr          out varchar2);

    function f_direccion_completa(pcod_pais_iso  varchar2,
                                  pcod_canton    varchar2,
                                  pcod_provincia varchar2,
                                  pcod_distrito  varchar2,
                                  pcalle         varchar2,
                                  pincluyedespais varchar2,
                                  pincluyedesprovincia varchar2)
        return varchar2;
procedure pcrearsolicitud(vsolicitud in pr.solicitud_credito_obj, pn_nocredito out number, pc_task out pa.tarea_list, errorcode in out varchar2, errordescription in out varchar2);        
end;