DROP TABLE PR.PR_CREDITOS_HI CASCADE CONSTRAINTS;

CREATE TABLE PR.PR_CREDITOS_HI
(
  CODIGO_EMPRESA                  NUMBER(4),
  NO_CREDITO                      NUMBER(7),
  CODIGO_AGENCIA                  NUMBER(5),
  CODIGO_MONEDA                   NUMBER(2),
  CODIGO_CLIENTE                  NUMBER(7),
  CODIGO_DIRECCION                NUMBER(8),
  TIPO_CREDITO                    NUMBER(3),
  ESTADO                          VARCHAR2(2 BYTE),
  MONTO_CREDITO                   NUMBER(16,2),
  ES_LINEA_CREDITO                VARCHAR2(1 BYTE),
  TIPO_LINEA                      VARCHAR2(1 BYTE),
  MANEJO                          NUMBER(1),
  MODALIDAD_COBRO                 VARCHAR2(1 BYTE),
  TIPO_INTERESES                  VARCHAR2(1 BYTE),
  TIPO_CALENDARIO                 NUMBER(1),
  TIPO_CUOTA                      VARCHAR2(1 BYTE),
  CODIGO_PERIODO_CUOTA            VARCHAR2(2 BYTE),
  CODIGO_PERIODO_INTERESES        VARCHAR2(2 BYTE),
  PERIODO_COMISION_NORMAL         VARCHAR2(2 BYTE),
  COMISION_NORMAL                 NUMBER(10,4),
  CUOTA                           NUMBER(16,2),
  MONTO_DESEMBOLSADO              NUMBER(16,2),
  MONTO_PAGADO_PRINCIPAL          NUMBER(16,2),
  MONTO_PAGADO_INTERESES          NUMBER(16,2),
  INTERESES_ACUMULADOS            NUMBER(16,2),
  MONTO_REVALORIZACION            NUMBER(16,2),
  INTERESES_EN_SUSPENSO           NUMBER(16,2),
  CUOTA_ANTERIOR                  NUMBER(16,2),
  PLAZO                           NUMBER(5),
  ID_SISTEMA_EXTERNO              VARCHAR2(15 BYTE),
  NO_SOLICITUD                    NUMBER(7),
  NO_CREDITO_ORIGEN               NUMBER(7),
  TIPO_TASA                       VARCHAR2(1 BYTE),
  CODIGO_TIPO_DE_TASA             VARCHAR2(5 BYTE),
  VARIACION_BASE                  NUMBER(10,4),
  TASA_INTERES                    NUMBER(10,4),
  TASA_ORIGINAL                   NUMBER(10,4),
  CODIGO_TASA_MORATORIOS          VARCHAR2(5 BYTE),
  VARIACION_MORA                  NUMBER(10,4),
  TASA_MORATORIOS                 NUMBER(10,4),
  PERIODO_REVISION_TASA           VARCHAR2(2 BYTE),
  VARIACION_MAX_REVISION          NUMBER(10,4),
  VARIACION_MAX_TOTAL             NUMBER(10,4),
  GRACIA_PRINCIPAL                NUMBER(5),
  GRACIA_MORA                     NUMBER(3),
  CODIGO_ORIGEN                   NUMBER(2),
  NO_PROGRAMA_ASOCIADO            VARCHAR2(20 BYTE),
  CODIGO_EJECUTIVO                VARCHAR2(10 BYTE),
  COBRADOR                        NUMBER(2),
  CODIGO_REFERENTE                NUMBER(3),
  CODIGO_ANALISTA                 NUMBER(5),
  CODIGO_NIVEL_APROBACION         NUMBER(2)     DEFAULT 0,
  F_APERTURA                      DATE,
  F_VENCIMIENTO                   DATE,
  F_CANCELACION                   DATE,
  F_ADJUDICACION                  DATE,
  F_ULTIMA_REVISION               DATE,
  F_ULTIMO_PAGO_PRINCIPAL         DATE,
  F_ULTIMO_PAGO_INTERESES         DATE,
  F_PRIMER_DESEMBOLSO             DATE,
  F_ULTIMO_DESEMBOLSO             DATE,
  F_PROXIMA_COMISION              DATE,
  F_APROBACION                    DATE,
  F_ULTIMO_PAGO_MORA              DATE,
  F_RECONOCIM_INTERESES           DATE,
  F_PRINCIPAL_ANTERIOR            DATE,
  F_INTERESES_ANTERIOR            DATE,
  F_MORA_ANTERIOR                 DATE,
  F_ULTIMA_REVALORIZACION         DATE,
  TIPO_ABONO                      VARCHAR2(1 BYTE),
  CUENTA_ABONO                    NUMBER(25),
  TIPO_DESEMBOLSO                 VARCHAR2(1 BYTE),
  CUENTA_DESEM                    NUMBER(25),
  CONTINUA_COBRO_INTERESES        VARCHAR2(1 BYTE),
  DIA_PAGO                        VARCHAR2(2 BYTE),
  MARCA_REV_TASA                  VARCHAR2(1 BYTE),
  REVALORIZA                      VARCHAR2(1 BYTE),
  OBSERVACIONES1                  VARCHAR2(255 BYTE),
  OBSERVACIONES2                  VARCHAR2(255 BYTE),
  ADICIONADO_POR                  VARCHAR2(10 BYTE),
  FECHA_ADICION                   DATE,
  MODIFICADO_POR                  VARCHAR2(10 BYTE),
  FECHA_MODIFICACION              DATE,
  CODIGO_SUB_APLICACION           NUMBER(3),
  MONTO_VARIACION                 NUMBER(16,2),
  CODIGO_ACTIVIDAD                NUMBER(5),
  CODIGO_SUBACTIVIDAD             NUMBER(5),
  CODIGO_CALIFICACION_SISTEMA     VARCHAR2(5 BYTE),
  CODIGO_CALIFICACION_MANUAL      VARCHAR2(5 BYTE),
  OBSERVACIONES_CALIFICACION      VARCHAR2(255 BYTE),
  ATRASO_PROMEDIO                 NUMBER(5),
  TIPO_COMISION                   VARCHAR2(1 BYTE),
  PLAN_INVERSION                  NUMBER(3),
  PAIS_DESTINO                    NUMBER(6),
  DEPARTAMENTO_DESTINO            NUMBER(6),
  MUNICIPIO_DESTINO               NUMBER(6),
  DISTRITO_DESTINO                NUMBER(6),
  CODIGO_SUB_CLASE                NUMBER(6),
  TIPO_MORA                       VARCHAR2(1 BYTE),
  PORCENTAJE_TASA_MORA            NUMBER(7,4),
  APROBADO_POR                    VARCHAR2(10 BYTE),
  CODIGO_PLAZO                    NUMBER(2),
  TASA_ORIGINAL_MORA              NUMBER(10,4),
  MONTO_X_DESEMBOLSAR             NUMBER(16,2),
  CALIFICADO_POR                  VARCHAR2(10 BYTE),
  F_ULTIMA_CALIFICACION           DATE,
  PLAZO_OPERACIONES               NUMBER(5),
  PERMITE_SOBREGIRO               VARCHAR2(1 BYTE),
  PORCENTAJE_SOBREGIRO            NUMBER(10,4),
  F_PRORROGA                      DATE,
  F_ULTIMO_PAGO_COMISION          DATE,
  F_PROXIMA_REVISION              DATE,
  F_ULTIMA_REV_MORA               DATE,
  OBSERVACIONES3                  VARCHAR2(255 BYTE),
  OBSERVACIONES4                  VARCHAR2(255 BYTE),
  BLOQUEO_DESEMBOLSO              VARCHAR2(1 BYTE),
  DESC_CARGOS                     VARCHAR2(1 BYTE),
  DESC_POLIZA                     VARCHAR2(1 BYTE),
  DESC_CUOTA                      VARCHAR2(1 BYTE),
  DESC_COMISION                   VARCHAR2(1 BYTE),
  ACUMULA_INTERESES               VARCHAR2(1 BYTE),
  VARIACION_MINIMA                NUMBER(10,4),
  VARIACION_MAXIMA                NUMBER(10,4),
  TIPO_REVISION                   VARCHAR2(1 BYTE),
  PERIODOS_GRACIA_PRINCIPAL       NUMBER(2),
  F_PAGO_COMISION_ATRASADA        DATE,
  TIPO_REGRESO_COBRO              VARCHAR2(2 BYTE),
  F_PAGO_COBRO_ADMINISTRATIVO     DATE,
  BASE_CALCULO_MORATORIOS         NUMBER(3),
  INTERESES_ANTICIPADOS           NUMBER(16,2),
  INTERESES_ANTES_COBRO_JUDICIAL  NUMBER(16,2),
  MARCA_COBRO_ADMINISTRATIVO      VARCHAR2(1 BYTE),
  PORC_SALDO_NO_UTILIZADO         NUMBER(10,4),
  F_ULTIMO_PAGO_INTERESES_VENC    DATE,
  F_PROXIMA_MORA_FLAT             DATE,
  RENOVACION                      NUMBER(2),
  COD_NOTARIO                     VARCHAR2(15 BYTE),
  CLIENTE_PROSPECTO               VARCHAR2(1 BYTE),
  NUMERO_CF                       VARCHAR2(19 BYTE),
  DESCUENTA_INTERESES_DESEMBOLSO  VARCHAR2(1 BYTE),
  CANTIDAD_CUOTAS_DESCONTAR       NUMBER(5),
  NO_POLIZA_BCO                   VARCHAR2(25 BYTE),
  IND_PR_VEHICULO                 VARCHAR2(1 BYTE),
  CANTIDAD_COBRO_CARGO            NUMBER(5),
  DESTINO_DE_FONDOS               VARCHAR2(200 BYTE),
  COD_PROMOTOR                    VARCHAR2(10 BYTE),
  F_RESTRUCTURACION               DATE,
  F_RESTRUC_A_VIGENTE             DATE,
  RES_APR_INMED                   VARCHAR2(5 BYTE),
  DIR_SUCURSAL                    VARCHAR2(200 BYTE),
  MTO_INICIAL_COTIZACION          NUMBER(18,2),
  MTO_FINANCIADO                  NUMBER(18,2),
  VENDEDOR                        VARCHAR2(120 BYTE),
  PORCIENTO_RETENCION             NUMBER(18,4),
  NETO_PAGAR                      NUMBER(18,2),
  NO_COTIZACION                   VARCHAR2(120 BYTE),
  GASTOS_CIERRE                   NUMBER(18,2),
  COMISIONPTO15                   NUMBER(18,2),
  INT_COMPLETIVO_ACUM             NUMBER(18,2)  DEFAULT 0,
  NUM_GRUPO_MICROCREDITO          NUMBER(15),
  SEGREGACION_RD                  VARCHAR2(6 BYTE),
  ESTADO_APROBACION               VARCHAR2(3 BYTE) DEFAULT 'P',
  ESVIDA                          VARCHAR2(1 BYTE) DEFAULT 'N',
  ESVEHICULO                      VARCHAR2(1 BYTE) DEFAULT 'N',
  ESINCENDIO                      VARCHAR2(1 BYTE) DEFAULT 'N',
  UNIDAD_PLAZO                    VARCHAR2(1 BYTE),
  PLAZO_SEGUN_UNIDAD              NUMBER(6),
  TIPO_TASA_VEHICULOS             VARCHAR2(3 BYTE),
  MORA_SUSPENSO_ACUMUL            NUMBER(16,2),
  MORA_INTERES_ACUMUL             NUMBER(16,2),
  MON_MORA_PAGADO                 NUMBER(16,2),
  COD_ENTE_UNIVERSIDAD            VARCHAR2(5 BYTE),
  IDCARRERA_UNIVERSIDAD           VARCHAR2(4 BYTE),
  MORA_INTERES_ACUMUL_RESP        NUMBER(16,2),
  FECHA_ULT_CONTA_POLIZA          DATE,
  MONTO_PAGOS_INTERESES_SUSPENSO  NUMBER(18,2),
  MONTO_PAGOS_MORA_SUSPENSO       NUMBER(16,2),
  ESINCENDIO_PYME                 VARCHAR2(1 BYTE),
  TIPO_REESTRUCTURACION           VARCHAR2(5 BYTE),
  FRE_REV_TASA                    VARCHAR2(3 BYTE)
)
TABLESPACE PR_DAT
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          3M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;

COMMENT ON TABLE PR.PR_CREDITOS_HI IS ' (Historico) Esta tabla es usada para almacenar la informacion de los creditos, ya sea cuando se generan a partir de una solicitud, o bien, aquellas operaciones registradas directamente, sin necesidad de solicitud. En esta tabla se almacenan los creditos independientes, lineas de credito y las operaciones (desembolsos) pertenecientes a alguna linea';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.CODIGO_EMPRESA IS 'Codigo de la Empresa.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.NO_CREDITO IS 'Numero de Credito.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.CODIGO_AGENCIA IS 'Codigo de la Agencia.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.CODIGO_MONEDA IS 'Codigo de Moneda.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.CODIGO_CLIENTE IS 'Codigo de Cliente.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.CODIGO_DIRECCION IS 'Codigo de Direccion del Cliente.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.TIPO_CREDITO IS 'Tipo de Credito.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.ESTADO IS 'Estado del Credito.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.MONTO_CREDITO IS 'Monto del Credito.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.ES_LINEA_CREDITO IS 'Es Linea de Credito     (S/N).';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.TIPO_LINEA IS 'Tipo de Linea de Credito:    (E)nvolvente. 
                                           (R)evolvente.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.MANEJO IS 'Manejo:  (1) Operaciones 
               (2) Movimientos';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.MODALIDAD_COBRO IS 'Tipo de Modalidad de Cobro:     (H)orizontal. 
                                                  (V)ertical.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.TIPO_INTERESES IS 'Tipo de Intereses:      (A)nticipados. 
                                 (V)encidos.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.TIPO_CALENDARIO IS 'Tipo de Calendario:      (1)  Natural/Natural. 
                                    (2)  Natural/Financiero. 
                                    (3)  Financiero/Financiero. 
                                    (4)  Financiero/Natural.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.TIPO_CUOTA IS 'Tipo de Cuota:    (N) - Nivelada. 
                           (L) - Libre. 
                           (M) - Multiperiodica. 
                           (P) - Principal Nivelado. 
                           (V) - Al Vencimiento. 
                           (U) - Un Solo Pago.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.CODIGO_PERIODO_CUOTA IS 'Codigo del Periodo de Cobro de la Cuota.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.CODIGO_PERIODO_INTERESES IS 'Codigo del Periodo de Cobro de los Intereses si el tipo de cuota es Multiperiodica.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.PERIODO_COMISION_NORMAL IS 'Codigo del Periodo de Cobro de la Comision.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.COMISION_NORMAL IS 'Porcentaje de Comision a Cobrar.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.CUOTA IS 'Monto de la Cuota.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.MONTO_DESEMBOLSADO IS 'Monto Total Desembolsado.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.MONTO_PAGADO_PRINCIPAL IS 'Monto Pagado en Principal.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.MONTO_PAGADO_INTERESES IS 'Monto Pagado en Intereses.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.INTERESES_ACUMULADOS IS 'Total en Intereses Acumulados.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.MONTO_REVALORIZACION IS 'Monto de Revalorizacion del Credito.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.INTERESES_EN_SUSPENSO IS 'Total en Intereses en Suspenso.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.CUOTA_ANTERIOR IS 'Monto de la Cuota Anterior.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.PLAZO IS 'Cantidad de Dias Plazo';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.ID_SISTEMA_EXTERNO IS 'Numero de Credito del Sistema Anterior';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.NO_SOLICITUD IS 'Numero de Solicitud de Credito.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.NO_CREDITO_ORIGEN IS 'Numero de Credito Origen (Linea de Credito).';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.TIPO_TASA IS 'Tipo de Tasa de Interes:         (F)ija. 
                                              (V)ariable.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.CODIGO_TIPO_DE_TASA IS 'Codigo del Tipo de Tasa de Interes.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.VARIACION_BASE IS 'Variacion de la Tasa de Interes.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.TASA_INTERES IS 'Tasa de Interes.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.TASA_ORIGINAL IS 'Tasa Original de Interes.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.CODIGO_TASA_MORATORIOS IS 'Codigo del Tipo de Tasa de Moratorios.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.VARIACION_MORA IS 'Variacion  de la Tasa de Moratorios.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.TASA_MORATORIOS IS 'Tasa de Moratorios.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.PERIODO_REVISION_TASA IS 'Periodo de Revision de la Tasa de Interes.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.VARIACION_MAX_REVISION IS 'Variacion Maxima en la Revision de Tasas de Interes.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.VARIACION_MAX_TOTAL IS 'Variacion Minima en la Revision de Tasas de Interes.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.GRACIA_PRINCIPAL IS 'Dias de Gracia en Principal.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.GRACIA_MORA IS 'Dias de Gracia en Moratorios.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.CODIGO_ORIGEN IS 'Codigo del Origen de los Fondos.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.NO_PROGRAMA_ASOCIADO IS 'Numero de Programa Asociado.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.CODIGO_EJECUTIVO IS 'Codigo del Ejecutivo de Credito.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.COBRADOR IS 'Codigo del Cobrador.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.CODIGO_REFERENTE IS 'Codigo del Referente del Credito.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.CODIGO_ANALISTA IS 'Codigo del Analista de Credito.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.CODIGO_NIVEL_APROBACION IS 'Codigo del Nivel de Aprobacion del Credito.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.F_APERTURA IS 'Fecha de Apertura del Credito.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.F_VENCIMIENTO IS 'Fecha de Vencimiento del Credito.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.F_CANCELACION IS 'Fecha de Cancelacion del Credito.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.F_ADJUDICACION IS 'Fecha de Adjudicacion del Credito.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.F_ULTIMA_REVISION IS 'Fecha de Ultima Revision de Tasas de Interes.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.F_ULTIMO_PAGO_PRINCIPAL IS 'Fecha de Ultimo Pago de Principal.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.F_ULTIMO_PAGO_INTERESES IS 'Fecha de Ultimo Pago de Intereses.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.F_PRIMER_DESEMBOLSO IS 'Fecha del Primer Desembolso del Credito.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.F_ULTIMO_DESEMBOLSO IS 'Fecha del Ultimo Desembolso del Credito.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.F_PROXIMA_COMISION IS 'Fecha de la Proxima Comision del Credito.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.F_APROBACION IS 'Fecha de Aprobacion del Credito.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.F_ULTIMO_PAGO_MORA IS 'Fecha de Ultimo Pago de Moratorios.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.F_RECONOCIM_INTERESES IS 'Fecha de Reconocimiento de Intereses.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.F_PRINCIPAL_ANTERIOR IS 'Fecha del Ultimo Pago de Principal Anterior.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.F_INTERESES_ANTERIOR IS 'Fecha del Ultimo Pago de Interes Anterior.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.F_MORA_ANTERIOR IS 'Fecha del Ultimo Pago de Mora Anterior.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.F_ULTIMA_REVALORIZACION IS 'Fecha de Ultima Revalorizacion.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.TIPO_ABONO IS 'Tipo de Abono:      (I) - Ingreso desde Cajas. 
                              (A) - Cuenta Contable. 
                              (C) - Cuenta Relacionada.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.CUENTA_ABONO IS 'Cuenta desde donde se Efectuaran los Abonos.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.TIPO_DESEMBOLSO IS 'Tipo de Desembolso:     (K) - Cheque. 
                                     (A) - Cuenta Contable. 
                                     (C) - Cuenta Relacionada.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.CUENTA_DESEM IS 'Cuenta a donde se Efectuaran los Desembolsos.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.CONTINUA_COBRO_INTERESES IS 'Continua el Cobro de Intereses  (S/N).';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.DIA_PAGO IS 'Dia de Pago del Credito.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.MARCA_REV_TASA IS 'Marca al Credito para Revision de Tasas de Interes.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.REVALORIZA IS 'Revaloriza  (S/N).';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.OBSERVACIONES1 IS 'Observaciones #1.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.OBSERVACIONES2 IS 'Observaciones #2.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.ADICIONADO_POR IS 'Codigo del Usuario que Creo el Registro.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.FECHA_ADICION IS 'Fecha de Creacion del Registro.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.MODIFICADO_POR IS 'Codigo del Usuario que Modifico el Registro.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.FECHA_MODIFICACION IS 'Fecha de Modificacion del Registro.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.CODIGO_SUB_APLICACION IS 'Codigo de la Sub Aplicacion.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.MONTO_VARIACION IS 'Monto de Variaciones al Principal.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.CODIGO_ACTIVIDAD IS 'Codigo de Actividad Economica.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.CODIGO_SUBACTIVIDAD IS 'Codigo de SubActividad Economica.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.CODIGO_CALIFICACION_SISTEMA IS 'Codigo de Calificacion dada por el Sistema.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.CODIGO_CALIFICACION_MANUAL IS 'Codigo de Calificacion dada Manualmente.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.OBSERVACIONES_CALIFICACION IS 'Observaciones Referentes a la Calificacion.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.ATRASO_PROMEDIO IS 'Atraso Promedio.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.TIPO_COMISION IS 'Tipo de Comision.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.PLAN_INVERSION IS 'Codigo del Plan de Inversion.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.PAIS_DESTINO IS 'Codigo del Pais Destino.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.DEPARTAMENTO_DESTINO IS 'Codigo del Departamento Destino.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.MUNICIPIO_DESTINO IS 'Codigo del Municipio Destino.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.DISTRITO_DESTINO IS 'Codigo del Distrito Destino.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.CODIGO_SUB_CLASE IS 'Codigo de la SubClase (SubSubActividad).';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.TIPO_MORA IS 'Tipo de Mora.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.PORCENTAJE_TASA_MORA IS 'Porcentaje de Tasa de Mora.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.APROBADO_POR IS 'Codigo del Usuario que Aprueba el Credito.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.CODIGO_PLAZO IS 'Codigo del Tipo de Plazo.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.TASA_ORIGINAL_MORA IS 'Tasa Original de Mora.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.MONTO_X_DESEMBOLSAR IS 'Monto por Desembolsar.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.CALIFICADO_POR IS 'Codigo del Usuario que Califico al Credito.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.F_ULTIMA_CALIFICACION IS 'Fecha de la Ultima Calificacion Efectuada.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.PLAZO_OPERACIONES IS 'Plazo de las Operaciones Hijas.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.PERMITE_SOBREGIRO IS 'Permite Sobregiro  (S/N).';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.PORCENTAJE_SOBREGIRO IS 'Porcentaje de Sobregiro.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.F_PRORROGA IS 'Fecha de la Prorroga al Vencimiento.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.F_ULTIMO_PAGO_COMISION IS 'Fecha del Ultimo Pago de la Comision.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.F_PROXIMA_REVISION IS 'Fecha de la Proxima Revision de Tasas.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.F_ULTIMA_REV_MORA IS 'Fecha de Ultima Revision de Moratorios.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.OBSERVACIONES3 IS 'Observaciones #3.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.OBSERVACIONES4 IS 'Observaciones #4.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.BLOQUEO_DESEMBOLSO IS 'Bloqueo sobre el Desembolso.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.DESC_CARGOS IS 'Descuenta los Cargos en el Desembolso (S/N).';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.DESC_POLIZA IS 'Descuenta la Poliza en el Desembolso (S/N).';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.DESC_CUOTA IS 'Descuenta la Cuota en el Desembolso (S/N).';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.DESC_COMISION IS 'Descuenta la Comision en el Desembolso (S/N).';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.ACUMULA_INTERESES IS 'Acumula Intereses  (S/N).';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.VARIACION_MINIMA IS 'Variacion Minima.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.VARIACION_MAXIMA IS 'Variacion Maxima.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.TIPO_REVISION IS 'Tipo de Revision:      (A)utomatica. 
                                 (M)anual.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.PERIODOS_GRACIA_PRINCIPAL IS 'Periodos de Gracia en Principal.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.F_PAGO_COMISION_ATRASADA IS 'Fecha de Pago de Comision Atrasada.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.TIPO_REGRESO_COBRO IS 'Tipo de Regreso de Cobro.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.F_PAGO_COBRO_ADMINISTRATIVO IS 'Fecha de Pago de Cobro Administrativo.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.BASE_CALCULO_MORATORIOS IS 'Base de Calculo de Moratorios  (360 o 365)';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.INTERESES_ANTICIPADOS IS 'Intereses Anticipados.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.INTERESES_ANTES_COBRO_JUDICIAL IS 'Intereses Acumulados antes de Envio a Cobro Judicial.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.MARCA_COBRO_ADMINISTRATIVO IS 'Cobro Administrativo sin importar atraso (S/N)';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.PORC_SALDO_NO_UTILIZADO IS 'Porcentaje a cobrarse sobre Desembolsos Parciales de Lineas de Credito.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.F_ULTIMO_PAGO_INTERESES_VENC IS 'Fecha de ultimo pago de intereses despues del vencimiento del credito';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.F_PROXIMA_MORA_FLAT IS 'Fecha de proxima generacion de mora flat';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.COD_NOTARIO IS 'Codigo del abogado notario';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.DESCUENTA_INTERESES_DESEMBOLSO IS 'Indicador para prestamos que se descuenta los intereses en el desembolso';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.CANTIDAD_CUOTAS_DESCONTAR IS 'Cantidad de cuotas descontadas en el desembolso';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.NO_POLIZA_BCO IS 'Numero de polizas para vehiculo';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.IND_PR_VEHICULO IS 'Indica si el prestamo fue emitido para financiar la compra de vehiculo';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.COD_PROMOTOR IS 'Codigo de promotor de venta';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.F_RESTRUCTURACION IS 'Fecha en que se el credito paso de Restructurado a Vigente.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.F_RESTRUC_A_VIGENTE IS 'Fecha en que el prestamo para se restructurado a vigente';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.DIR_SUCURSAL IS 'Direccion de la Sucursal de la Tienda.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.MTO_INICIAL_COTIZACION IS 'Monto con que se inicio la cotizacion.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.MTO_FINANCIADO IS 'Monto financiado por el BSC.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.VENDEDOR IS 'Nombre del Vendedor.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.PORCIENTO_RETENCION IS 'Porcentaje de Retencion establecido.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.NETO_PAGAR IS 'Monto Neto a Pagar.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.NO_COTIZACION IS 'Numero de la Cotizacion.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.GASTOS_CIERRE IS 'Monto de gastos para el cierre.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.COMISIONPTO15 IS 'Monto de la comision del 0.15%.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.NUM_GRUPO_MICROCREDITO IS 'Identificador del grupo de microcredito asociado al prestamo.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.SEGREGACION_RD IS 'Campo relacionado a la tabla ACTIVIDADES_ECONOMICAS_BC_CIIU.';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.ESTADO_APROBACION IS 'Estado del proceso de aprobacion, ligado a PA_CATALOGO_CODIGOS con el codigo_gen = 003';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.ESVIDA IS 'Poliza de Vida S-Si, N-No';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.ESVEHICULO IS 'Poliza de Vehiculo S-Si, N-No';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.ESINCENDIO IS 'Poliza de Incendio S-Si, N-No';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.MONTO_PAGOS_INTERESES_SUSPENSO IS 'monto pagado intereses en suspenso';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.MONTO_PAGOS_MORA_SUSPENSO IS 'monto pagado a interses moratorios en suspenso';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.ESINCENDIO_PYME IS 'Indica que el crédito posee una poliza por Insendio para PYMES, posibles valores S o NULL ';

COMMENT ON COLUMN PR.PR_CREDITOS_HI.TIPO_REESTRUCTURACION IS 'RN = Reestructurado conformfe a la definicion dada por el REA,
 RP = Représtamo o Refinancimiento,
 RV = Renovación,
 RT = Reestructurado Temporal de acuerdo a las normativas vigentes en el período,
 RL = Crédito Reestructurado y acogido al proceso de la Ley No.141 -15, Reestructuración
      y Liquidación de Empresas y Personas Físicas Comerciantes del 7 de agosto del 2015,
 NR = No ha sido reestructurado';


CREATE UNIQUE INDEX PR.PK_PRH_CREDITOS ON PR.PR_CREDITOS_HI
(CODIGO_EMPRESA, NO_CREDITO)
LOGGING
TABLESPACE PR_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          192K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE PR.PR_CREDITOS_HI ADD (
  CONSTRAINT CK_CREDITOSHI_CLIENTEPROSPECTO
  CHECK (CLIENTE_PROSPECTO IN ('P','C'))
  ENABLE VALIDATE
,  CONSTRAINT CK_CREDITOSHI_DESCINTDESEM
  CHECK (DESCUENTA_INTERESES_DESEMBOLSO IN ('S','N'))
  ENABLE VALIDATE
,  CONSTRAINT CK_CREDITOSHI_INDPRVEHICULO
  CHECK (IND_PR_VEHICULO IN ('S','N'))
  ENABLE VALIDATE
,  CONSTRAINT FK_CREDITOSHI_ACUMULAINTERESES
  CHECK (ACUMULA_INTERESES IN ('S','N'))
  ENABLE VALIDATE
,  CONSTRAINT FK_CREDITOSHI_DESCCARGOS
  CHECK (DESC_CARGOS IN ('S','N'))
  ENABLE VALIDATE
,  CONSTRAINT FK_CREDITOSHI_DESCCOMISION
  CHECK (DESC_COMISION IN ('S','N'))
  ENABLE VALIDATE
,  CONSTRAINT FK_CREDITOSHI_DESCCUOTA
  CHECK (DESC_CUOTA IN ('S','N'))
  ENABLE VALIDATE
,  CONSTRAINT FK_CREDITOSHI_DESCPOLIZA
  CHECK (DESC_POLIZA IN ('S','N'))
  ENABLE VALIDATE
,  CONSTRAINT FK_CREDITOSHI_ESTADO
  CHECK (ESTADO IN ('A','C','F','N','P', 'R', 'U','X', 'T'))
  ENABLE VALIDATE
,  CONSTRAINT FK_CREDITOSHI_MARCACOBROADM
  CHECK (MARCA_COBRO_ADMINISTRATIVO IN ('S','N'))
  ENABLE VALIDATE
,  CONSTRAINT FK_CREDITOSHI_TIPOCOMISION
  CHECK (TIPO_COMISION IN ('A','V'))
  ENABLE VALIDATE
,  CONSTRAINT FK_CREDITOSHI_TIPOMORA
  CHECK (TIPO_MORA IN ('1','2'))
  ENABLE VALIDATE
,  CONSTRAINT FK_CREDITOSHI_TIPOREVISION
  CHECK (TIPO_REVISION IN ('A','M'))
  ENABLE VALIDATE
,  CONSTRAINT PR_CREDITOHI_INCENDIO_PYMES
  CHECK ( Esincendio_Pyme = 'S' Or Esincendio_Pyme Is Null  )
  ENABLE VALIDATE
,  CONSTRAINT PK_PRH_CREDITOS
  PRIMARY KEY
  (CODIGO_EMPRESA, NO_CREDITO)
  USING INDEX PR.PK_PRH_CREDITOS
  ENABLE VALIDATE);


CREATE INDEX PR.IDX02_PR_CREDITOS_HI ON PR.PR_CREDITOS_HI
(CODIGO_EMPRESA, CODIGO_CLIENTE)
LOGGING
TABLESPACE PR_DAT
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX PR.PR_CREDITOS_HI_FK1 ON PR.PR_CREDITOS_HI
(SEGREGACION_RD)
LOGGING
TABLESPACE PR_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX PR.PR_CREDITOS_HI_FK10 ON PR.PR_CREDITOS_HI
(CODIGO_EMPRESA, PLAN_INVERSION)
LOGGING
TABLESPACE PR_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX PR.PR_CREDITOS_HI_FK11 ON PR.PR_CREDITOS_HI
(CODIGO_ORIGEN)
LOGGING
TABLESPACE PR_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX PR.PR_CREDITOS_HI_FK2 ON PR.PR_CREDITOS_HI
(CODIGO_EMPRESA, NUM_GRUPO_MICROCREDITO)
LOGGING
TABLESPACE PR_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX PR.PR_CREDITOS_HI_FK3 ON PR.PR_CREDITOS_HI
(CODIGO_PERIODO_CUOTA)
LOGGING
TABLESPACE PR_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX PR.PR_CREDITOS_HI_FK4 ON PR.PR_CREDITOS_HI
(CODIGO_PLAZO)
LOGGING
TABLESPACE PR_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX PR.PR_CREDITOS_HI_FK5 ON PR.PR_CREDITOS_HI
(COD_NOTARIO)
LOGGING
TABLESPACE PR_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX PR.PR_CREDITOS_HI_FK6 ON PR.PR_CREDITOS_HI
(PERIODO_REVISION_TASA)
LOGGING
TABLESPACE PR_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX PR.PR_CREDITOS_HI_FK7 ON PR.PR_CREDITOS_HI
(CODIGO_REFERENTE)
LOGGING
TABLESPACE PR_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX PR.PR_CREDITOS_HI_FK8 ON PR.PR_CREDITOS_HI
(CODIGO_PERIODO_INTERESES)
LOGGING
TABLESPACE PR_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX PR.PR_CREDITOS_HI_FK9 ON PR.PR_CREDITOS_HI
(PERIODO_COMISION_NORMAL)
LOGGING
TABLESPACE PR_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE OR REPLACE TRIGGER PR.TRG_AI_PR_CREDITOS_HI 
AFTER INSERT
ON PR.PR_CREDITOS_HI REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DISABLE
BEGIN
  IF nvl(:new.estado,'x') = 'N' THEN
     -- Solo entra acá si se borra y el creditos está ANULADO (N)    
      PR.PINSERTAFILEFLOW(:old.no_credito, 'AN', USER, '0');
  END IF;
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/


CREATE OR REPLACE PUBLIC SYNONYM PR_CREDITOS_HI FOR PR.PR_CREDITOS_HI;


ALTER TABLE PR.PR_CREDITOS_HI ADD (
  CONSTRAINT FK_CREDITOSHI_NOTARIO 
  FOREIGN KEY (COD_NOTARIO) 
  REFERENCES PA.PERSONAS (COD_PERSONA)
  ENABLE VALIDATE
,  CONSTRAINT FK_CREDITOSHI_PERIODICIDAD 
  FOREIGN KEY (CODIGO_PERIODO_CUOTA) 
  REFERENCES PR.PR_PERIODICIDAD (CODIGO_PERIODO)
  ENABLE VALIDATE
,  CONSTRAINT FK_CREDITOSHI_PERIODINT 
  FOREIGN KEY (CODIGO_PERIODO_INTERESES) 
  REFERENCES PR.PR_PERIODICIDAD (CODIGO_PERIODO)
  ENABLE VALIDATE
,  CONSTRAINT FK_CREDITOSHI_PERIODNORMAL 
  FOREIGN KEY (PERIODO_COMISION_NORMAL) 
  REFERENCES PR.PR_PERIODICIDAD (CODIGO_PERIODO)
  ENABLE VALIDATE
,  CONSTRAINT FK_CREDITOSHI_PERIODREVTASA 
  FOREIGN KEY (PERIODO_REVISION_TASA) 
  REFERENCES PR.PR_PERIODICIDAD (CODIGO_PERIODO)
  ENABLE VALIDATE
,  CONSTRAINT FK_CREDITOSHI_PLANINVERSION 
  FOREIGN KEY (CODIGO_EMPRESA, PLAN_INVERSION) 
  REFERENCES PR.PR_PLAN_INVERSION (CODIGO_EMPRESA, PLAN_INVERSION)
  ENABLE VALIDATE
,  CONSTRAINT FK_CREDITOSHI_PRORIGENFONDOS 
  FOREIGN KEY (CODIGO_ORIGEN) 
  REFERENCES PR.PR_ORIGEN_FONDOS (CODIGO_ORIGEN)
  ENABLE VALIDATE
,  CONSTRAINT FK_CREDITOSHI_REFERENTES 
  FOREIGN KEY (CODIGO_REFERENTE) 
  REFERENCES PR.PR_REFERENTES (CODIGO_REFERENTE)
  ENABLE VALIDATE
,  CONSTRAINT FK_CREDITOSHI_TIPOSPLAZOS 
  FOREIGN KEY (CODIGO_PLAZO) 
  REFERENCES PR.PR_TIPOS_PLAZOS (CODIGO_PLAZO)
  ENABLE VALIDATE
,  CONSTRAINT FK_PRCREDITOSHI_PAACTECONCIIU 
  FOREIGN KEY (SEGREGACION_RD) 
  REFERENCES PA.ACTIVIDADES_ECONOMICAS_BC_CIIU (SEGREGACION_RD)
  ENABLE VALIDATE
,  CONSTRAINT FK_PR_CREDITOSHIS_PRGRPMC 
  FOREIGN KEY (CODIGO_EMPRESA, NUM_GRUPO_MICROCREDITO) 
  REFERENCES PR.PR_GRUPO_MICROCREDITO (CODIGO_EMPRESA, NUM_GRUPO)
  ENABLE VALIDATE);

GRANT ALTER, DELETE, INSERT, SELECT, UPDATE ON PR.PR_CREDITOS_HI TO BPR;

GRANT SELECT ON PR.PR_CREDITOS_HI TO CDG;

GRANT ALTER, DELETE, INSERT, SELECT, UPDATE ON PR.PR_CREDITOS_HI TO CONGEN;

GRANT SELECT ON PR.PR_CREDITOS_HI TO DY;

GRANT SELECT ON PR.PR_CREDITOS_HI TO FC;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE ON PR.PR_CREDITOS_HI TO PUBLIC;

GRANT SELECT ON PR.PR_CREDITOS_HI TO SII;
