DROP TABLE PR.PR_CARGA_DIRECCIONADA CASCADE CONSTRAINTS;

CREATE TABLE PR.PR_CARGA_DIRECCIONADA
(
  CODIGO_EMPRESA         NUMBER(4)              DEFAULT 1,
  CODIGO_CLIENTE         NUMBER(7)              NOT NULL,
  NOMBRES                VARCHAR2(65 BYTE),
  CELULAR                VARCHAR2(11 BYTE)      NOT NULL,
  NO_CREDITO             NUMBER(7)              NOT NULL,
  MTO_PREAPROBADO        NUMBER(18,2)           NOT NULL,
  AGENCIA                VARCHAR2(65 BYTE),
  OFICIAL                VARCHAR2(65 BYTE),
  ZONA                   VARCHAR2(65 BYTE),
  ESTADO                 VARCHAR2(5 BYTE)       DEFAULT 'P',
  OBSERVACIONES          VARCHAR2(500 BYTE),
  ADICIONADO_POR         VARCHAR2(30 BYTE)      DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'),USER),
  FECHA_ADICION          DATE                   DEFAULT SYSDATE,
  MODIFICADO_POR         VARCHAR2(30 BYTE),
  FECHA_MODIFICACION     DATE,
  ID_CARGA_DIRECCIONADA  NUMBER
)
TABLESPACE PR_DAT
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING
NOCOMPRESS
NOCACHE;


CREATE OR REPLACE TRIGGER PR.PR_CARGA_MANUAL
BEFORE INSERT ON PR.PR_CARGA_DIRECCIONADA
FOR EACH ROW
BEGIN
    SELECT PR.PR_PKG_REPRESTAMOS.F_GENERA_SECUENCIA_CARGA_DIRIGIDA  INTO :NEW.ID_CARGA_DIRECCIONADA FROM DUAL;
END;
/
