DROP TABLE PR.PR_ESTADOS_REPRESTAMO CASCADE CONSTRAINTS;

CREATE TABLE PR.PR_ESTADOS_REPRESTAMO
(
  CODIGO_EMPRESA              NUMBER(4)         NOT NULL,
  CODIGO_ESTADO               VARCHAR2(5 BYTE)  NOT NULL,
  DES_ESTADO                  VARCHAR2(500 BYTE) NOT NULL,
  ORDEN                       NUMBER(5),
  IND_NOTIFICA_CLIENTE        VARCHAR2(1 BYTE)  NOT NULL,
  ESTADO                      VARCHAR2(5 BYTE)  NOT NULL,
  ICONO                       VARCHAR2(100 BYTE),
  ADICIONADO_POR              VARCHAR2(30 BYTE) NOT NULL,
  FECHA_ADICION               DATE              NOT NULL,
  MODIFICADO_POR              VARCHAR2(30 BYTE),
  FECHA_MODIFICACION          DATE,
  IND_CAMBIA_ESTADO_REPRE     VARCHAR2(1 BYTE),
  GRUPO                       VARCHAR2(100 BYTE),
  COLOR                       VARCHAR2(50 BYTE),
  IND_CAMBIA_ESTADO_ORIGINAL  VARCHAR2(1 BYTE),
  COMENTARIO                  VARCHAR2(4000 BYTE)
)
TABLESPACE PR_DAT
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;

COMMENT ON COLUMN PR.PR_ESTADOS_REPRESTAMO.GRUPO IS 'Agrupación de los estados según su criterio de procesamiento.';


CREATE UNIQUE INDEX PR.PK_PR_ESTADOS_REPRESTAMOS ON PR.PR_ESTADOS_REPRESTAMO
(CODIGO_EMPRESA, CODIGO_ESTADO)
LOGGING
TABLESPACE PR_DAT
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE PR.PR_ESTADOS_REPRESTAMO ADD (
  CONSTRAINT PK_PR_ESTADOS_REPRESTAMOS
  PRIMARY KEY
  (CODIGO_EMPRESA, CODIGO_ESTADO)
  USING INDEX PR.PK_PR_ESTADOS_REPRESTAMOS
  ENABLE VALIDATE);


CREATE OR REPLACE TRIGGER PR.TRG_BUI_PR_ESTADOS_REPRESTAMO
BEFORE INSERT OR UPDATE
ON PR.PR_ESTADOS_REPRESTAMO REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
  IF INSERTING THEN
     :new.fecha_adicion := sysdate;  
     if :new.adicionado_por is null THEN
        :new.adicionado_por := user;
     end if;
  ELSE 
     :new.fecha_modificacion := sysdate;
     if :new.modificado_por is null THEN
        :new.modificado_por := user;
     end if;
  END IF;
END;
/


CREATE OR REPLACE PUBLIC SYNONYM PR_ESTADOS_REPRESTAMO FOR PR.PR_ESTADOS_REPRESTAMO;


GRANT SELECT ON PR.PR_ESTADOS_REPRESTAMO TO BPR;
