DROP TABLE PR.PR_OPCIONES_REPRESTAMO CASCADE CONSTRAINTS;

CREATE TABLE PR.PR_OPCIONES_REPRESTAMO
(
  CODIGO_EMPRESA        NUMBER(4)               NOT NULL,
  ID_REPRESTAMO         NUMBER(14)              NOT NULL,
  PLAZO                 NUMBER(5)               NOT NULL,
  MTO_PRESTAMO          NUMBER(18,2)            NOT NULL,
  MTO_DESCONTAR         NUMBER(18,2)            NOT NULL,
  MTO_DEPOSITAR         NUMBER(18,2)            NOT NULL,
  MTO_CUOTA             NUMBER(18,2)            NOT NULL,
  MTO_CARGOS            NUMBER(18,2)            NOT NULL,
  MTO_SEGURO_VIDA       NUMBER(18,2)            NOT NULL,
  MTO_SEGURO_DESEMPLEO  NUMBER(18,2)            NOT NULL,
  TASA                  NUMBER(5,2)             NOT NULL,
  ORDEN                 NUMBER(5),
  ESTADO                VARCHAR2(5 BYTE)        NOT NULL,
  ADICIONADO_POR        VARCHAR2(30 BYTE)       NOT NULL,
  FECHA_ADICION         DATE                    NOT NULL,
  MODIFICADO_POR        VARCHAR2(30 BYTE),
  FECHA_MODIFICACION    DATE,
  MTO_CUOTA_TOTAL       NUMBER(18,2),
  MTO_SEGURO_MIPYME     NUMBER(18,2)
)
TABLESPACE PR_DAT
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;

COMMENT ON COLUMN PR.PR_OPCIONES_REPRESTAMO.ID_REPRESTAMO IS 'Identificacion del Represtamo';

COMMENT ON COLUMN PR.PR_OPCIONES_REPRESTAMO.PLAZO IS 'Numero de plazo de la opción.';

COMMENT ON COLUMN PR.PR_OPCIONES_REPRESTAMO.MTO_PRESTAMO IS 'Monto del Represtamo.';

COMMENT ON COLUMN PR.PR_OPCIONES_REPRESTAMO.MTO_DESCONTAR IS 'Monto pendiente a descontar del préstamo anterior.';

COMMENT ON COLUMN PR.PR_OPCIONES_REPRESTAMO.MTO_DEPOSITAR IS 'Monto a desembolsar del représtamo.';

COMMENT ON COLUMN PR.PR_OPCIONES_REPRESTAMO.MTO_CUOTA IS 'Monto la cuota del représtamo.';

COMMENT ON COLUMN PR.PR_OPCIONES_REPRESTAMO.MTO_CARGOS IS 'Monto de cargos y gastos de cierre.';

COMMENT ON COLUMN PR.PR_OPCIONES_REPRESTAMO.MTO_SEGURO_VIDA IS 'Monto del seguro de vida.';

COMMENT ON COLUMN PR.PR_OPCIONES_REPRESTAMO.MTO_SEGURO_DESEMPLEO IS 'Monto del seguro de desempleo.';

COMMENT ON COLUMN PR.PR_OPCIONES_REPRESTAMO.TASA IS 'Tasa del représtamo de acuerdo al tipo de crédito.';

COMMENT ON COLUMN PR.PR_OPCIONES_REPRESTAMO.ORDEN IS 'Orden en que se va a mostrar la opción.';

COMMENT ON COLUMN PR.PR_OPCIONES_REPRESTAMO.ESTADO IS 'Estado de la opción.';


CREATE UNIQUE INDEX PR.PK_PR_OPCIONES_REPRESTAMOS ON PR.PR_OPCIONES_REPRESTAMO
(CODIGO_EMPRESA, ID_REPRESTAMO, PLAZO)
LOGGING
TABLESPACE PR_DAT
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE PR.PR_OPCIONES_REPRESTAMO ADD (
  CONSTRAINT PK_PR_OPCIONES_REPRESTAMOS
  PRIMARY KEY
  (CODIGO_EMPRESA, ID_REPRESTAMO, PLAZO)
  USING INDEX PR.PK_PR_OPCIONES_REPRESTAMOS
  ENABLE VALIDATE);


CREATE OR REPLACE TRIGGER "PR"."TRG_BUI_PR_OPCIONES_REPRESTAMO" 
BEFORE INSERT OR UPDATE
ON PR.PR_OPCIONES_REPRESTAMO REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
  IF INSERTING THEN
     :new.fecha_adicion := sysdate;  
     if :new.adicionado_por is null THEN
        :new.adicionado_por := user;
     end if;
  ELSE 
     :new.fecha_modificacion := sysdate;
     if :new.modificado_por is null THEN
        :new.modificado_por := user;
     end if;
  END IF;
END;
/


CREATE OR REPLACE PUBLIC SYNONYM PR_OPCIONES_REPRESTAMO FOR PR.PR_OPCIONES_REPRESTAMO;


ALTER TABLE PR.PR_OPCIONES_REPRESTAMO ADD (
  CONSTRAINT FK_OPCIONES_REPRESTAMO 
  FOREIGN KEY (CODIGO_EMPRESA, ID_REPRESTAMO) 
  REFERENCES PR.PR_REPRESTAMOS (CODIGO_EMPRESA, ID_REPRESTAMO)
  ENABLE VALIDATE);

GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON PR.PR_OPCIONES_REPRESTAMO TO BPR;

GRANT SELECT ON PR.PR_OPCIONES_REPRESTAMO TO PA WITH GRANT OPTION;
