DROP TABLE PR.PR_PLAZO_CREDITO_REPRESTAMO CASCADE CONSTRAINTS;

CREATE TABLE PR.PR_PLAZO_CREDITO_REPRESTAMO
(
  CODIGO_EMPRESA      NUMBER(4)                 NOT NULL,
  TIPO_CREDITO        NUMBER(3)                 NOT NULL,
  PLAZO               NUMBER(5)                 NOT NULL,
  MONTO_MIN           NUMBER(18,2)              NOT NULL,
  MONTO_MAX           NUMBER(18,2)              NOT NULL,
  ADICIONADO_POR      VARCHAR2(30 BYTE)         NOT NULL,
  FECHA_ADICION       DATE                      DEFAULT SYSDATE               NOT NULL,
  MODIFICADO_POR      VARCHAR2(30 BYTE),
  FECHA_MODIFICACION  DATE
)
TABLESPACE PR_DAT
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE UNIQUE INDEX PR.PK_PR_PLAZO_REPRESTAMO ON PR.PR_PLAZO_CREDITO_REPRESTAMO
(CODIGO_EMPRESA, TIPO_CREDITO, PLAZO)
LOGGING
TABLESPACE PR_DAT
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE PR.PR_PLAZO_CREDITO_REPRESTAMO ADD (
  CONSTRAINT PK_PR_PLAZO_REPRESTAMO
  PRIMARY KEY
  (CODIGO_EMPRESA, TIPO_CREDITO, PLAZO)
  USING INDEX PR.PK_PR_PLAZO_REPRESTAMO
  ENABLE VALIDATE);


CREATE INDEX PR.PK_PR_PLAZO_REPRE_MONTO ON PR.PR_PLAZO_CREDITO_REPRESTAMO
(CODIGO_EMPRESA, TIPO_CREDITO, MONTO_MIN, MONTO_MAX)
LOGGING
TABLESPACE PR_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE OR REPLACE PUBLIC SYNONYM PR_PLAZO_CREDITO_REPRESTAMO FOR PR.PR_PLAZO_CREDITO_REPRESTAMO;


ALTER TABLE PR.PR_PLAZO_CREDITO_REPRESTAMO ADD (
  CONSTRAINT FK01_PR_PLAZO_REPRESTAMO 
  FOREIGN KEY (CODIGO_EMPRESA, TIPO_CREDITO) 
  REFERENCES PR.PR_TIPO_CREDITO_REPRESTAMO (CODIGO_EMPRESA, TIPO_CREDITO)
  ENABLE VALIDATE);

GRANT SELECT ON PR.PR_PLAZO_CREDITO_REPRESTAMO TO BPR;
