DROP TABLE PR.PR_REPRESTAMOS CASCADE CONSTRAINTS;

CREATE TABLE PR.PR_REPRESTAMOS
(
  CODIGO_EMPRESA               NUMBER(4) CONSTRAINT NN_PR_REPRESTAMOS01 NOT NULL,
  ID_REPRESTAMO                NUMBER(14) CONSTRAINT NN_PR_REPRESTAMOS02 NOT NULL,
  CODIGO_CLIENTE               NUMBER(7) CONSTRAINT NN_PR_REPRESTAMOS03 NOT NULL,
  FECHA_CORTE                  DATE CONSTRAINT NN_PR_REPRESTAMOS04 NOT NULL,
  NO_CREDITO                   NUMBER(7) CONSTRAINT NN_PR_REPRESTAMOS05 NOT NULL,
  ESTADO                       VARCHAR2(3 BYTE) CONSTRAINT NN_PR_REPRESTAMOS06 NOT NULL,
  CODIGO_PRECALIFICACION       VARCHAR2(2 BYTE),
  DIAS_ATRASO                  NUMBER(10) CONSTRAINT NN_PR_REPRESTAMOS08 NOT NULL,
  FECHA_PROCESO                DATE CONSTRAINT NN_PR_REPRESTAMOS09 NOT NULL,
  PIN                          NUMBER(6)        NOT NULL,
  INTENTOS_PIN                 NUMBER(1)        DEFAULT 0                     NOT NULL,
  INTENTOS_IDENTIFICACION      NUMBER(1)        DEFAULT 0                     NOT NULL,
  IND_SOLICITA_AYUDA           VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL,
  MTO_CREDITO_ACTUAL           NUMBER(18,2)     NOT NULL,
  MTO_PREAPROBADO              NUMBER(18,2)     NOT NULL,
  OBSERVACIONES                VARCHAR2(4000 BYTE),
  ADICIONADO_POR               VARCHAR2(30 BYTE) CONSTRAINT NN_PR_REPRESTAMOS10 NOT NULL,
  FECHA_ADICION                DATE CONSTRAINT NN_PR_REPRESTAMOS11 NOT NULL,
  MODIFICADO_POR               VARCHAR2(30 BYTE),
  FECHA_MODIFICACION           DATE,
  ESTADO_ORIGINAL              VARCHAR2(3 BYTE),
  XCORE_GLOBAL                 NUMBER(7,2),
  XCORE_CUSTOM                 NUMBER(7,2),
  ID_CARGA_DIRIGIDA            NUMBER,
  ID_REPRE_CAMPANA_ESPECIALES  NUMBER,
  ES_FIADOR                    VARCHAR2(30 BYTE)
)
TABLESPACE PR_DAT
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE UNIQUE INDEX PR.PK_REPRESTAMOS ON PR.PR_REPRESTAMOS
(CODIGO_EMPRESA, ID_REPRESTAMO)
LOGGING
TABLESPACE PR_DAT
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE PR.PR_REPRESTAMOS ADD (
  CONSTRAINT PK_REPRESTAMOS
  PRIMARY KEY
  (CODIGO_EMPRESA, ID_REPRESTAMO)
  USING INDEX PR.PK_REPRESTAMOS
  ENABLE VALIDATE);


CREATE INDEX PR.IND01_PR_REPRESTAMOS ON PR.PR_REPRESTAMOS
(CODIGO_EMPRESA, NO_CREDITO)
LOGGING
TABLESPACE PR_DAT
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX PR.IND02_PR_REPRESTAMOS ON PR.PR_REPRESTAMOS
(CODIGO_EMPRESA, ESTADO)
LOGGING
TABLESPACE PR_DAT
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX PR.IND3_PR_REPRESTAMO ON PR.PR_REPRESTAMOS
(CODIGO_CLIENTE, ESTADO)
LOGGING
TABLESPACE PR_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE OR REPLACE TRIGGER "PR"."TRG_BUI_PR_REPRESTAMOS" 
BEFORE INSERT OR UPDATE
ON PR.PR_REPRESTAMOS REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
  IF INSERTING THEN
     :new.fecha_adicion := sysdate;
     --PR_PKG_REPRESTAMOS.p_generar_bitacora(:new.ID_REPRESTAMO,NULL,'RE',NULL,'Carga inicial');
  ELSE 
     :new.fecha_modificacion := sysdate;
     UPDATE PR.PR_SOLICITUD_REPRESTAMO S
       SET S.ESTADO = NVL(:NEW.ESTADO, :OLD.ESTADO)
     WHERE S.CODIGO_EMPRESA = :NEW.CODIGO_EMPRESA
       AND S.ID_REPRESTAMO = NVL(:NEW.ID_REPRESTAMO, :OLD.ID_REPRESTAMO);
  END IF;
END;
/


CREATE OR REPLACE PUBLIC SYNONYM PR_REPRESTAMOS FOR PR.PR_REPRESTAMOS;


GRANT SELECT ON PR.PR_REPRESTAMOS TO BPR;

GRANT SELECT ON PR.PR_REPRESTAMOS TO CDG;

GRANT SELECT ON PR.PR_REPRESTAMOS TO PA WITH GRANT OPTION;
