DROP TABLE PR.PR_TIPO_CREDITO CASCADE CONSTRAINTS;

CREATE TABLE PR.PR_TIPO_CREDITO
(
  CODIGO_EMPRESA                  NUMBER(3),
  TIPO_CREDITO                    NUMBER(3),
  DESCRIPCION                     VARCHAR2(60 BYTE) CONSTRAINT NN_PR_TIPCREDITO_DESCRIPCION NOT NULL,
  CODIGO_SUB_APLICACION           NUMBER(3) CONSTRAINT NN_PR_TIPCREDITO_CODSUBAPLI NOT NULL,
  ES_LINEA_CREDITO                VARCHAR2(1 BYTE) CONSTRAINT NN_PR_TIPCREDITO_ESLINEACRED NOT NULL,
  CODIGO_MONEDA                   NUMBER(2) CONSTRAINT NN_PR_TIPCREDITO_CODMONEDA NOT NULL,
  CODIGO_PLAZO                    NUMBER(2) CONSTRAINT NN_PR_TIPCREDITO_CODPLAZO NOT NULL,
  CODIGO_ORIGEN                   NUMBER(2) CONSTRAINT NN_PR_TIPCREDITO_CODORIGEN NOT NULL,
  MODALIDAD_COBRO                 VARCHAR2(1 BYTE) CONSTRAINT NN_PR_TIPCREDITO_MODALICOBRO NOT NULL,
  TIENE_VENCIMIENTO               VARCHAR2(1 BYTE) CONSTRAINT NN_PR_TIPCREDITO_TIENEVENCIMI NOT NULL,
  TIPO_INTERESES                  VARCHAR2(1 BYTE) CONSTRAINT NN_PR_TIPCREDITO_TIPINTERES NOT NULL,
  TIPO_CALENDARIO                 NUMBER(1) CONSTRAINT NN_PR_TIPCREDITO_TIPCALENDARIO NOT NULL,
  TIPO_LINEA                      VARCHAR2(1 BYTE),
  MANEJO                          NUMBER(1),
  PLAZO_MINIMO                    NUMBER(5),
  PLAZO_MAXIMO                    NUMBER(5),
  MONTO_MINIMO                    NUMBER(16,2),
  MONTO_MAXIMO                    NUMBER(16,2),
  TIPO_TASA                       VARCHAR2(1 BYTE) CONSTRAINT NN_PR_TIPCREDITO_TIPTASA NOT NULL,
  CODIGO_TIPO_DE_TASA             NUMBER(2),
  VARIACION_BASE                  NUMBER(10,4),
  TASA_INTERES                    NUMBER(10,4),
  CODIGO_TASA_MORATORIOS          NUMBER(2),
  VARIACION_MORA                  NUMBER(10,4),
  TASA_MORATORIOS                 NUMBER(10,4),
  GRACIA_PRINCIPAL                NUMBER(5),
  GRACIA_MORA                     NUMBER(2),
  DIAS_ATRASO_COBRO_JUD           NUMBER(5),
  CONTINUA_COBRO_INTERESES        VARCHAR2(1 BYTE) CONSTRAINT NN_PR_TIPCREDITO_CONTCOBROINT NOT NULL,
  COMISION_NORMAL                 NUMBER(10,4),
  COMISION_NORMAL_MINIMA          NUMBER(10,4),
  COMISION_NORMAL_MAXIMA          NUMBER(10,4),
  PERIODO_COMISION_NORMAL         VARCHAR2(2 BYTE),
  REVALORIZA                      VARCHAR2(1 BYTE) CONSTRAINT NN_PR_TIPCREDITO_REVALORIZA NOT NULL,
  APROBACION_CON_GARANTIA         VARCHAR2(1 BYTE) CONSTRAINT NN_PR_TIPCREDITO_APROBCONGARAN NOT NULL,
  ADICIONADO_POR                  VARCHAR2(10 BYTE) CONSTRAINT NN_PR_TIPCREDITO_ADIPOR NOT NULL,
  FECHA_ADICION                   DATE CONSTRAINT NN_PR_TIPCREDITO_FECADI NOT NULL,
  MODIFICADO_POR                  VARCHAR2(10 BYTE),
  FECHA_MODIFICACION              DATE,
  TIPO_COMISION                   VARCHAR2(1 BYTE),
  TIPO_MORA                       VARCHAR2(1 BYTE),
  PORCENTAJE_TASA_MORA            NUMBER(7,4),
  MAX_DIAS_VENCIDO_COBRO          NUMBER(5),
  PERMITE_SOBREGIRO               VARCHAR2(1 BYTE),
  PORCENTAJE_SOBREGIRO            NUMBER(10,4),
  CARGO_COMISION                  NUMBER(3) CONSTRAINT NN_PR_TIPCREDITO_CARGOCOMISION NOT NULL,
  CARGO_POLIZA                    NUMBER(3) CONSTRAINT NN_PR_TIPCREDITO_CARGOPOLIZA NOT NULL,
  CODIGO_CORTE                    VARCHAR2(5 BYTE) CONSTRAINT NN_PR_TIPCREDITO_CODIGOCORTE NOT NULL,
  VARIACION_MINIMA                NUMBER(10,4),
  VARIACION_MAXIMA                NUMBER(10,4),
  PERIODOS_GRACIA_PRINCIPAL       NUMBER(2),
  CARGO_COMISION_ATRASADA         NUMBER(3),
  MNEMONICO                       VARCHAR2(5 BYTE),
  CARGO_COBRO_ADMINISTRATIVO      NUMBER(3),
  COBRA_COMISION_ATRASADA         VARCHAR2(1 BYTE),
  COBRA_COBRO_ADMINISTRATIVO      VARCHAR2(1 BYTE),
  DIAS_ATRASO_COBRO_ADMIN         NUMBER(3),
  BASE_CALCULO_MORATORIOS         NUMBER(3),
  COMISION_SOBRE_SALDOS           VARCHAR2(1 BYTE),
  SALDOS_TEORICOS                 VARCHAR2(1 BYTE),
  CARGO_IVA                       NUMBER(3),
  COBRA_SALDO_NO_UTILIZADO        VARCHAR2(1 BYTE),
  CARGO_SALDO_NO_UTILIZADO        NUMBER(3),
  COMISION_GENERA_IVA             VARCHAR2(1 BYTE),
  COBRA_INTERESES_DIA_PAGO        VARCHAR2(1 BYTE),
  CARGO_INTERES_PRORROGADO        NUMBER(3),
  CARGO_MORATORIO_PRORROGADO      NUMBER(3),
  CARGO_COMISION_PRORROGADA       NUMBER(3),
  TIPO_CALCULO_MORA               VARCHAR2(1 BYTE),
  CARGO_MORA_FLAT                 NUMBER(3),
  DIA_PAGO                        VARCHAR2(2 BYTE),
  TIPO_CARTERA                    NUMBER(1),
  DIAS_ATRASO_EN_VIGENTE          NUMBER(5),
  ES_PRE_APROBADO                 VARCHAR2(1 BYTE) DEFAULT 'N',
  VIGENCIA_SOLICITUD              NUMBER(3)     DEFAULT 0,
  COBRO_AUT_POLIZA                VARCHAR2(1 BYTE) DEFAULT 'N',
  ES_CUOTA_MULTIPLE               VARCHAR2(1 BYTE),
  TIPO_CREDITO_HIJOS              NUMBER(3),
  DESCUENTA_INTERESES_DESEMBOLSO  VARCHAR2(1 BYTE),
  CANTIDAD_CUOTAS_DESCONTAR       NUMBER(5),
  IND_POLIZA_BCO                  VARCHAR2(1 BYTE),
  IND_PR_VEHICULO                 VARCHAR2(1 BYTE),
  MAX_PORC_EXTRAORDINARIO         NUMBER(10,2),
  CON_GARANTIA_CERTIFICADO        VARCHAR2(1 BYTE),
  PORCENTAJE_PIGNORACION_CD       NUMBER(7,4),
  OFICIAL_AUTORIZADO              VARCHAR2(1 BYTE),
  GRUPO_TIPO_CREDITO              VARCHAR2(2 BYTE),
  TIPO_DE_PERSONA                 VARCHAR2(1 BYTE),
  LLAMADA_ATRASO                  VARCHAR2(1 BYTE) DEFAULT 'N',
  IND_ES_RESERVA                  VARCHAR2(1 BYTE) DEFAULT 'N',
  IND_CREDITO_UNIVERSITARIO       VARCHAR2(1 BYTE) DEFAULT 'N',
  IND_MICRO_CREDITO               VARCHAR2(1 BYTE) DEFAULT 'N',
  LIMITE_TOLERABLE_EA             NUMBER(5,2),
  LIMITE_TOLERABLE_LC             NUMBER(5,2),
  LIMITE_TOLERABLE_GF             NUMBER(5,2),
  LIMITE_TOLERABLE_CP             NUMBER(5,2),
  FACILIDAD_CREDITIC              NUMBER(3)     DEFAULT 112,
  IND_COBRA_MORA                  VARCHAR2(1 BYTE) DEFAULT 'S',
  ESTADO                          VARCHAR2(1 BYTE),
  TIPO_CUOTA                      VARCHAR2(1 BYTE),
  MULTIPLES_DESEMBOLSOS           VARCHAR2(1 BYTE) DEFAULT 'N',
  DESEMBOLSO_PACTADO              VARCHAR2(1 BYTE) DEFAULT 'N',
  CANCELA_RECREDITO               VARCHAR2(1 BYTE) DEFAULT 'S',
  ES_MODELO                       VARCHAR2(1 BYTE) DEFAULT 'N',
  COD_FLEXIBILIZACION             VARCHAR2(5 BYTE),
  FEC_VEN_FLEXIBILIZACION         DATE
)
TABLESPACE DATA_EFD
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          256K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;

COMMENT ON TABLE PR.PR_TIPO_CREDITO IS ' Esta tabla es usada para almacenar las caracteristicas que perfilan diferentes tipos de operaciones, con el fin de que dicha informacion sea trasladada y usada como default en el registro de solicitudes o creditos';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.CODIGO_EMPRESA IS 'Codigo de la Empresa';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.TIPO_CREDITO IS 'Tipo de Credito.';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.DESCRIPCION IS 'Descripcion.';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.CODIGO_SUB_APLICACION IS 'Codigo de la Sub-Aplicacion.';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.ES_LINEA_CREDITO IS 'Es Linea de Credito  (S/N).';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.CODIGO_MONEDA IS 'Codigo de Moneda.';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.CODIGO_PLAZO IS 'Codigo del Tipo de Plazo.';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.CODIGO_ORIGEN IS 'Codigo del Origen de los Recursos.';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.MODALIDAD_COBRO IS 'Modalidad de Cobro:     (H)orizontal  
                                     (V)ertical.';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.TIENE_VENCIMIENTO IS 'Tiene Vencimiento (S/N).';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.TIPO_INTERESES IS 'Tipo de Interes:    (A)nticipado 
                            (V)encido.';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.TIPO_CALENDARIO IS 'Tipo de Calendario:      (1)  Natural/Natural. 
                                    (2)  Natural/Financiero. 
                                    (3)  Financiero/Financiero. 
                                    (4)  Financiero/Natural.';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.TIPO_LINEA IS 'Tipo de Linea:   (E)nvolvente 
                         (R)evolvente.';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.MANEJO IS 'Manejo: (1) Operaciones. 
             (2) Movimientos.';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.PLAZO_MINIMO IS 'Plazo Minimo Aceptado para Otorgar Creditos.';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.PLAZO_MAXIMO IS 'Plazo Maximo Aceptado para Otorgar Creditos.';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.MONTO_MINIMO IS 'Monto Minimo Aceptado para Otorgar Creditos.';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.MONTO_MAXIMO IS 'Monto Maximo Aceptado para Otorgar Creditos.';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.TIPO_TASA IS 'Tipo de Tasa de Interes:    (F)ija 
                                        (V)ariable.';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.CODIGO_TIPO_DE_TASA IS 'Codigo del Tipo de Tasa de Interes.';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.VARIACION_BASE IS 'Variacion Base de la Tasa de Interes.';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.TASA_INTERES IS 'Tasa de Interes a Otorgar.';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.CODIGO_TASA_MORATORIOS IS 'Codigo de la Tasa de Moratorios.';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.VARIACION_MORA IS 'Variacion de la Tasa de Moratorios.';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.TASA_MORATORIOS IS 'Tasa de Moratorios a Otorgar.';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.GRACIA_PRINCIPAL IS 'Cantidad de Dias de Gracia en Principal.';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.GRACIA_MORA IS 'Cantidad de Dias de Gracia en Moratorios.';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.DIAS_ATRASO_COBRO_JUD IS 'Cantidad de Dias de Atraso para Candidato a Cobro Judicial.';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.CONTINUA_COBRO_INTERESES IS 'Continua Cobro de Intereses en Cobro Judicial (S/N).';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.COMISION_NORMAL IS 'Porcentaje de Comision a Otorgar.';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.COMISION_NORMAL_MINIMA IS 'Porcentaje de Comision Minima Aceptada.';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.COMISION_NORMAL_MAXIMA IS 'Porcentaje de Comision Maxima Aceptada.';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.PERIODO_COMISION_NORMAL IS 'Codigo del Periodo de Comision.';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.REVALORIZA IS 'Revaloriza   (S/N).';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.APROBACION_CON_GARANTIA IS 'Aprobacion de Creditos con Garantia  (S/N).';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.ADICIONADO_POR IS 'Codigo del Usuario que Creo el Registro.';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.FECHA_ADICION IS 'Fecha de Creacion del Registro.';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.MODIFICADO_POR IS 'Codigo del Usuario que Modifico el Registro.';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.FECHA_MODIFICACION IS 'Fecha de Modificacion del Registro.';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.TIPO_COMISION IS 'Tipo de Comision:     (A)nticipada 
                                 (V)encida.';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.TIPO_MORA IS 'Tipo de Mora.';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.PORCENTAJE_TASA_MORA IS 'Porcentaje de Tasa de Moratorios.';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.MAX_DIAS_VENCIDO_COBRO IS 'Maximo de Dias antes de Devengar Intereses en Suspenso.';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.PERMITE_SOBREGIRO IS 'Permite Sobregiro  (S/N).';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.PORCENTAJE_SOBREGIRO IS 'Porcentaje de Sobregiro.';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.CARGO_COMISION IS 'Codigo del Cargo por Concepto de Comision';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.CARGO_POLIZA IS 'Codigo del Cargo por Concepto de Poliza.';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.CODIGO_CORTE IS 'Codigo de Corte.';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.VARIACION_MINIMA IS 'Variacion Minima.';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.VARIACION_MAXIMA IS 'Variacion Maxima.';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.PERIODOS_GRACIA_PRINCIPAL IS 'Periodos de Gracia en Principal.';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.CARGO_COMISION_ATRASADA IS 'Codigo Cargo por Concepto de Comision Atrasada.';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.MNEMONICO IS 'Abreviatura o Mnemonico del Tipo de Credito.';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.CARGO_COBRO_ADMINISTRATIVO IS 'Codigo Cargo por Concepto de Cobro Administrativo.';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.COBRA_COMISION_ATRASADA IS 'Cobra Comision Atrasada  (S/N).';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.COBRA_COBRO_ADMINISTRATIVO IS 'Cobra Cobro Administrativo  (S/N).';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.DIAS_ATRASO_COBRO_ADMIN IS 'Cantidad de Dias de Atraso a Cobro Administrativo.';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.BASE_CALCULO_MORATORIOS IS 'Base de Calculo de los Moratorios  (360 o 365)';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.COMISION_SOBRE_SALDOS IS 'Comision: (S) Calculada sobre Saldo del prestamo. 
                 (N) Calculada sobre Monto del prestamo.';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.SALDOS_TEORICOS IS 'Calculo del Interes:  (S) Sobre saldos Teoricos y    
                                       hasta  el vencimiento. 
                                (N) Sobre saldos Reales y  
                                       calcula despues del  
                                       vencimiento.';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.CARGO_IVA IS 'Codigo Cargo por Concepto de IVA.';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.COBRA_SALDO_NO_UTILIZADO IS 'Cobra cargo por saldos en Lineas de Credito (S/N).';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.CARGO_SALDO_NO_UTILIZADO IS 'Codigo Cargo por saldos en Lineas de Credito.';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.COMISION_GENERA_IVA IS 'Comision genera IVA (S/N).';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.COBRA_INTERESES_DIA_PAGO IS 'Cobra intereses hasta dia de pago o hasta fecha de cuota.';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.CARGO_INTERES_PRORROGADO IS 'Cargo aplicado por el monto de intereses adeudado en una prorroga.';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.CARGO_MORATORIO_PRORROGADO IS 'Cargo aplicado por el monto de mora adeudado en una prorroga';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.CARGO_COMISION_PRORROGADA IS 'Cargo aplicado por el monto de comision adeudado en una prorroga.';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.TIPO_CALCULO_MORA IS 'Indicador de forma de calculo de mora (P/I/F)';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.CARGO_MORA_FLAT IS 'Codigo Cargo a generarse por mora flat.';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.DIA_PAGO IS 'Dia de pago default para creditos desembolsados.';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.TIPO_CARTERA IS 'Tipo de Cartera de Negocios:  Comercial, Consumo, Hipotecario, Microempresa y Otros.';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.ES_PRE_APROBADO IS 'Aplica solo para tipo credito Pre-Aprobado.';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.VIGENCIA_SOLICITUD IS 'Cant. Dias para desembolsar un CR. (Aplica solo para tipo credito Pre-Aprobado).';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.COBRO_AUT_POLIZA IS 'Cobro Automatico Poliza.';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.ES_CUOTA_MULTIPLE IS 'Indica si es tipo de Credito de Cuota Flexible (Multiple).';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.TIPO_CREDITO_HIJOS IS 'Este es el tipo de credito para las operaciones que contienen los planes de pago.';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.DESCUENTA_INTERESES_DESEMBOLSO IS 'Indique si descuenta los intereses en el desembolso.';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.CANTIDAD_CUOTAS_DESCONTAR IS 'Cantidad de cuotas a descontar al momento del desembolso';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.IND_POLIZA_BCO IS 'Indique si manejara poliza automatica con el banco.';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.IND_PR_VEHICULO IS 'Indica si el credito es de vehiculo';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.MAX_PORC_EXTRAORDINARIO IS '% maximo del monto del credito que se puede pagar en cuotas extraordinarias.';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.CON_GARANTIA_CERTIFICADO IS 'Especifica si pone como garantia un CD.';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.PORCENTAJE_PIGNORACION_CD IS 'Porcentaje permitido a Pignorar.';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.OFICIAL_AUTORIZADO IS 'Especifica si los oficiales pueden autorizar este tipo de credito.';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.GRUPO_TIPO_CREDITO IS '(C)=Comercial, (P)=Consumo, (H)= Hipotecario, (T)=Tienda';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.TIPO_DE_PERSONA IS 'F-Fisico; J-Juridico; A-Ambos';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.LLAMADA_ATRASO IS 'Indica si el porducto debe incluirse en las llamadas por atrasos (VOCOM)';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.IND_ES_RESERVA IS 'Indica que es para Lineas de Credito de Reservas.';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.IND_CREDITO_UNIVERSITARIO IS 'Indica si es un credito universitario o no.';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.LIMITE_TOLERABLE_EA IS 'Cargo de ahorro obligatorio para los casos que aplica en los grupos';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.LIMITE_TOLERABLE_LC IS 'Límite tolerable del índice financiero de Endeudamiento Actual';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.LIMITE_TOLERABLE_GF IS 'Límite tolerable del índice financiero de Liquidez Corriente';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.LIMITE_TOLERABLE_CP IS 'Límite tolerable del índice financiero de Gastos Familiares';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.IND_COBRA_MORA IS 'Indicador si el tipo de credito se le cobra moratorios, Si (S), No (N)';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.MULTIPLES_DESEMBOLSOS IS 'Identifica si el tipo de crédito permitira varios desembolsos (S/N) ';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.ES_MODELO IS 'S = Utilizado como modelo base para crear nuevos codigos';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.COD_FLEXIBILIZACION IS 'Código de Flexibilización Normativa: e.g. E19';

COMMENT ON COLUMN PR.PR_TIPO_CREDITO.FEC_VEN_FLEXIBILIZACION IS 'Fecha de vencimiento de la Flexibilización: e.g. 20/01/2025';


CREATE UNIQUE INDEX PR.PK_PR_TIPO_CREDITO ON PR.PR_TIPO_CREDITO
(CODIGO_EMPRESA, TIPO_CREDITO)
LOGGING
TABLESPACE IND_EFD
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE PR.PR_TIPO_CREDITO ADD (
  CONSTRAINT CK_CUOTA_MULTIPLE
  CHECK (es_cuota_multiple in ('S','N'))
  ENABLE VALIDATE
,  CONSTRAINT CK_PRTIPOCRED_CANTCUOTADESC
  CHECK (cantidad_cuotas_descontar >= 0)
  ENABLE VALIDATE
,  CONSTRAINT CK_PRTIPOCRED_COBRAINTDIAPAGO
  CHECK (cobra_intereses_dia_pago In ('S'))
  ENABLE VALIDATE
,  CONSTRAINT CK_PRTIPOCRED_MAXPORCEXT
  CHECK (max_porc_extraordinario >= 0)
  ENABLE VALIDATE
,  CONSTRAINT CK_PR_TIPCREDITO_APROBCONGARAN
  CHECK ( APROBACION_CON_GARANTIA IN ('S','N')             )
  ENABLE VALIDATE
,  CONSTRAINT CK_PR_TIPCREDITO_CONCOBROINT
  CHECK ( CONTINUA_COBRO_INTERESES IN ('S','N')             )
  ENABLE VALIDATE
,  CONSTRAINT CK_PR_TIPCREDITO_ESLINEACRED
  CHECK ( ES_LINEA_CREDITO IN ('S','N')             )
  ENABLE VALIDATE
,  CONSTRAINT CK_PR_TIPCREDITO_MANEJO
  CHECK ( MANEJO IN ('1','2')             )
  ENABLE VALIDATE
,  CONSTRAINT CK_PR_TIPCREDITO_MODALICOBRO
  CHECK ( MODALIDAD_COBRO IN ('V','H')             )
  ENABLE VALIDATE
,  CONSTRAINT CK_PR_TIPCREDITO_REVALORIZA
  CHECK ( REVALORIZA IN ('S','N')             )
  ENABLE VALIDATE
,  CONSTRAINT CK_PR_TIPCREDITO_TIENEVENCIMI
  CHECK ( TIENE_VENCIMIENTO IN ('S','N')             )
  ENABLE VALIDATE
,  CONSTRAINT CK_PR_TIPCREDITO_TIPCALENDARIO
  CHECK ( TIPO_CALENDARIO IN ('1','2','3','4')             )
  ENABLE VALIDATE
,  CONSTRAINT CK_PR_TIPCREDITO_TIPINTERES
  CHECK ( TIPO_INTERESES IN ('V','A')             )
  ENABLE VALIDATE
,  CONSTRAINT CK_PR_TIPCREDITO_TIPLINEA
  CHECK ( TIPO_LINEA IN ('R','E')             )
  ENABLE VALIDATE
,  CONSTRAINT CK_PR_TIPCREDITO_TIPTASA
  CHECK ( TIPO_TASA IN ('F','V')             )
  ENABLE VALIDATE
,  CONSTRAINT CK_PR_TIPCRED_TIPCOMISION
  CHECK ( TIPO_COMISION IN ('A','V','D')             )
  ENABLE VALIDATE
,  CONSTRAINT CK_PR_TIPO_CREDITOGARANCD
  CHECK (Con_Garantia_Certificado IN ('S', 'N'))
  ENABLE VALIDATE
,  CONSTRAINT MM_PR_TIPCREDITO_COMINORMAL
  CHECK ( COMISION_NORMAL>=0             )
  ENABLE VALIDATE
,  CONSTRAINT MM_PR_TIPCREDITO_COMINORMALMAX
  CHECK ( COMISION_NORMAL_MAXIMA >=  0             )
  ENABLE VALIDATE
,  CONSTRAINT MM_PR_TIPCREDITO_COMINORMALMIN
  CHECK ( COMISION_NORMAL_MINIMA >=  0             )
  ENABLE VALIDATE
,  CONSTRAINT MM_PR_TIPCREDITO_GRACIAMORA
  CHECK ( GRACIA_MORA >=  0             )
  ENABLE VALIDATE
,  CONSTRAINT MM_PR_TIPCREDITO_GRACIAPRINCI
  CHECK ( GRACIA_PRINCIPAL >=  0             )
  ENABLE VALIDATE
,  CONSTRAINT MM_PR_TIPCREDITO_MONTOMAXIMO
  CHECK ( MONTO_MAXIMO >  0             )
  ENABLE VALIDATE
,  CONSTRAINT MM_PR_TIPCREDITO_MONTOMINIMO
  CHECK ( MONTO_MINIMO >  0             )
  ENABLE VALIDATE
,  CONSTRAINT MM_PR_TIPCREDITO_PLAZOMAXIMO
  CHECK ( PLAZO_MAXIMO >  0             )
  ENABLE VALIDATE
,  CONSTRAINT MM_PR_TIPCREDITO_PLAZOMINIMO
  CHECK ( PLAZO_MINIMO >  0             )
  ENABLE VALIDATE
,  CONSTRAINT NN_PR_TIPCREDITO_FACTCRE
  CHECK (FACILIDAD_CREDITIC IS NOT NULL)
  ENABLE VALIDATE
,  CHECK (TIPO_CUOTA IN ('N','P','V','U','L','M'))
  ENABLE VALIDATE
,  CHECK (ESTADO IN ('A','I'))
  ENABLE VALIDATE
,  CONSTRAINT PK_PR_TIPO_CREDITO
  PRIMARY KEY
  (CODIGO_EMPRESA, TIPO_CREDITO)
  USING INDEX PR.PK_PR_TIPO_CREDITO
  ENABLE VALIDATE);


CREATE INDEX PR.IDX$$_02010001 ON PR.PR_TIPO_CREDITO
(TIPO_CREDITO, CODIGO_EMPRESA, SALDOS_TEORICOS)
LOGGING
TABLESPACE PR_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX PR.IDX_PRTIPOCREDITO_GRUPTIPCRED ON PR.PR_TIPO_CREDITO
(GRUPO_TIPO_CREDITO)
LOGGING
TABLESPACE PR_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX PR.IDX01_02010002 ON PR.PR_TIPO_CREDITO
(TIPO_CREDITO, CODIGO_EMPRESA, GRUPO_TIPO_CREDITO)
LOGGING
TABLESPACE PR_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX PR.PR_TIPO_CREDITO_FK7 ON PR.PR_TIPO_CREDITO
(CODIGO_ORIGEN)
LOGGING
TABLESPACE PR_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX PR.PR_TIPO_CREDITO_FK8 ON PR.PR_TIPO_CREDITO
(CODIGO_PLAZO)
LOGGING
TABLESPACE PR_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX PR.PR_TIPOCREDITO_CIERRE_FK ON PR.PR_TIPO_CREDITO
(CODIGO_EMPRESA, TIPO_CREDITO, IND_COBRA_MORA)
LOGGING
TABLESPACE PR_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE OR REPLACE TRIGGER "PR"."PR_TIPO_CREDITO_CONCEP" 
BEFORE INSERT
ON PR.PR_TIPO_CREDITO
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN

FOR X IN ( SELECT CODIGO_EMPRESA, CODIGO_ESTADO, CONCEPTO, COD_SEC_CONTABLE, CUENTA_CONTABLE
              FROM PR_CUENTAS_X_CONCEPTO
            WHERE TIPO_CREDITO = (SELECT MIN(TIPO_CREDITO)
                                    FROM PR_TIPO_CREDITO
                                   WHERE  grupo_tipo_credito = :NEW.grupo_tipo_credito
                                     AND CODIGO_MONEDA = :NEW.CODIGO_MONEDA)
                                     ) LOOP
   INSERT INTO PR_CUENTAS_X_CONCEPTO(CODIGO_EMPRESA,TIPO_CREDITO, CODIGO_ESTADO, CONCEPTO, COD_SEC_CONTABLE, CUENTA_CONTABLE, ADICIONADO_POR, FECHA_ADICION, MODIFICADO_POR, FECHA_MODIFICACION)
                              VALUES(X.CODIGO_EMPRESA,:NEW.TIPO_CREDITO, X.CODIGO_ESTADO, X.CONCEPTO, X.COD_SEC_CONTABLE, X.CUENTA_CONTABLE, USER, SYSDATE, NULL, NULL);
END LOOP;
Exception
When others then 
Null;
             
END;
/


CREATE OR REPLACE PUBLIC SYNONYM PR_TIPO_CREDITO FOR PR.PR_TIPO_CREDITO;


ALTER TABLE PR.PR_TIPO_CREDITO ADD (
  CONSTRAINT FK_INTERESGEN_TIPOCREDITO 
  FOREIGN KEY (CODIGO_EMPRESA, TIPO_CREDITO) 
  REFERENCES PR.PR_TIPO_CREDITO (CODIGO_EMPRESA, TIPO_CREDITO)
  ENABLE VALIDATE
,  CONSTRAINT FK_PR_TIPCREDITO_ORIGEN 
  FOREIGN KEY (CODIGO_ORIGEN) 
  REFERENCES PR.PR_ORIGEN_FONDOS (CODIGO_ORIGEN)
  ENABLE VALIDATE
,  CONSTRAINT FK_PR_TIPCREDITO_TIPPLAZOS 
  FOREIGN KEY (CODIGO_PLAZO) 
  REFERENCES PR.PR_TIPOS_PLAZOS (CODIGO_PLAZO)
  ENABLE VALIDATE);

GRANT ALTER, DELETE, INSERT, SELECT, UPDATE ON PR.PR_TIPO_CREDITO TO BDI;

GRANT SELECT ON PR.PR_TIPO_CREDITO TO BPA;

GRANT ALTER, DELETE, INSERT, SELECT, UPDATE ON PR.PR_TIPO_CREDITO TO BPR;

GRANT SELECT ON PR.PR_TIPO_CREDITO TO BTC;

GRANT SELECT ON PR.PR_TIPO_CREDITO TO CDG;

GRANT ALTER, DELETE, INSERT, SELECT, UPDATE ON PR.PR_TIPO_CREDITO TO CONGEN;

GRANT SELECT ON PR.PR_TIPO_CREDITO TO DI;

GRANT ALTER, DELETE, INSERT, SELECT, UPDATE ON PR.PR_TIPO_CREDITO TO MPASCUAL;

GRANT SELECT ON PR.PR_TIPO_CREDITO TO PA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE ON PR.PR_TIPO_CREDITO TO PUBLIC;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON PR.PR_TIPO_CREDITO TO RH;

GRANT SELECT ON PR.PR_TIPO_CREDITO TO SII;

GRANT SELECT ON PR.PR_TIPO_CREDITO TO TF;
