DROP TABLE PR.PR_TIPO_CREDITO_REPRESTAMO CASCADE CONSTRAINTS;

CREATE TABLE PR.PR_TIPO_CREDITO_REPRESTAMO
(
  CODIGO_EMPRESA            NUMBER(4)           NOT NULL,
  TIPO_CREDITO              NUMBER(3)           NOT NULL,
  ESTADO                    VARCHAR2(1 BYTE)    NOT NULL,
  ADICIONADO_POR            VARCHAR2(30 BYTE)   DEFAULT USER                  NOT NULL,
  FECHA_ADICION             DATE                DEFAULT SYSDATE               NOT NULL,
  MODIFICADO_POR            VARCHAR2(30 BYTE),
  FECHA_MODIFICACION        DATE,
  OBSOLETO                  NUMBER              DEFAULT 0,
  CARGA                     CHAR(1 BYTE)        DEFAULT 'S',
  CREDITO_CAMPANA_ESPECIAL  CHAR(1 BYTE)        DEFAULT NULL,
  CREDITO_FMO               CHAR(1 BYTE)
)
TABLESPACE PR_DAT
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE UNIQUE INDEX PR.PK01_TIPO_CRED_REPRESTAMO ON PR.PR_TIPO_CREDITO_REPRESTAMO
(CODIGO_EMPRESA, TIPO_CREDITO)
LOGGING
TABLESPACE PR_DAT
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE PR.PR_TIPO_CREDITO_REPRESTAMO ADD (
  CONSTRAINT CK01_TIPO_CREDITO_REPRESTAMO
  CHECK (ESTADO in ('A','I'))
  ENABLE VALIDATE
,  CONSTRAINT PK01_TIPO_CRED_REPRESTAMO
  PRIMARY KEY
  (CODIGO_EMPRESA, TIPO_CREDITO)
  USING INDEX PR.PK01_TIPO_CRED_REPRESTAMO
  ENABLE VALIDATE);


CREATE OR REPLACE TRIGGER "PR"."TRG_BUI_TIPO_CRED_REPRESTAMO" 
BEFORE INSERT OR UPDATE
ON PR.PR_tipo_credito_REPRESTAMO REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
  IF INSERTING THEN
     :new.fecha_adicion := sysdate;
     :new.estado := 'A';
  ELSE 
     :new.fecha_modificacion := sysdate;
  END IF;
END;
/


CREATE OR REPLACE PUBLIC SYNONYM PR_TIPO_CREDITO_REPRESTAMO FOR PR.PR_TIPO_CREDITO_REPRESTAMO;


ALTER TABLE PR.PR_TIPO_CREDITO_REPRESTAMO ADD (
  CONSTRAINT FK01_TIPO_CREDITO_REPRESTAMO 
  FOREIGN KEY (CODIGO_EMPRESA, TIPO_CREDITO) 
  REFERENCES PR.PR_TIPO_CREDITO (CODIGO_EMPRESA, TIPO_CREDITO)
  ENABLE VALIDATE);

GRANT SELECT ON PR.PR_TIPO_CREDITO_REPRESTAMO TO BPR;
