-- =============================================================
-- ACUMULADO - Comparacion rigurosa ANTES vs DESPUES
-- Compara por llave de negocio:
--   CODIGO_EMPRESA, CODIGO_CLIENTE, NO_CREDITO, FECHA_CORTE
-- No compara ID_REPRESTAMO entre runs porque la secuencia cambia.
-- =============================================================

DEFINE RUN_LABEL_BASE = ANTES
DEFINE RUN_LABEL_TEST = DESPUES

PROMPT
PROMPT === 1. Resumen de runs ===
SELECT RUN_LABEL,
       TEST_USER,
       STARTED_AT,
       FINISHED_AT,
       LOTE_ORIGINAL,
       LOTE_PRUEBA,
       RE_INSERTADOS,
       SOLICITUDES,
       CANALES,
       OPCIONES,
       BITACORA,
       NOTAS
  FROM OPTACUM_RUN_CONTROL 
 WHERE RUN_LABEL IN (UPPER('&RUN_LABEL_BASE'), UPPER('&RUN_LABEL_TEST'))
 ORDER BY RUN_LABEL;

PROMPT
PROMPT === 2. Filas exclusivas en PR_REPRESTAMOS (esperado: 0) ===
WITH A AS (
    SELECT CODIGO_EMPRESA, CODIGO_CLIENTE, NO_CREDITO, FECHA_CORTE, ESTADO
      FROM OPTACUM_SNAP_REPRESTAMOS
     WHERE RUN_LABEL = UPPER('&RUN_LABEL_BASE')
),
D AS (
    SELECT CODIGO_EMPRESA, CODIGO_CLIENTE, NO_CREDITO, FECHA_CORTE, ESTADO
      FROM OPTACUM_SNAP_REPRESTAMOS
     WHERE RUN_LABEL = UPPER('&RUN_LABEL_TEST')
)
SELECT 'SOLO_EN_' || UPPER('&RUN_LABEL_TEST') AS ORIGEN,
       D.CODIGO_EMPRESA,
       D.CODIGO_CLIENTE,
       D.NO_CREDITO,
       D.FECHA_CORTE,
       D.ESTADO
  FROM D
 WHERE NOT EXISTS (
           SELECT 1
             FROM A
            WHERE A.CODIGO_EMPRESA = D.CODIGO_EMPRESA
              AND A.CODIGO_CLIENTE = D.CODIGO_CLIENTE
              AND A.NO_CREDITO = D.NO_CREDITO
              AND A.FECHA_CORTE = D.FECHA_CORTE
       )
UNION ALL
SELECT 'SOLO_EN_' || UPPER('&RUN_LABEL_BASE'),
       A.CODIGO_EMPRESA,
       A.CODIGO_CLIENTE,
       A.NO_CREDITO,
       A.FECHA_CORTE,
       A.ESTADO
  FROM A
 WHERE NOT EXISTS (
           SELECT 1
             FROM D
            WHERE D.CODIGO_EMPRESA = A.CODIGO_EMPRESA
              AND D.CODIGO_CLIENTE = A.CODIGO_CLIENTE
              AND D.NO_CREDITO = A.NO_CREDITO
              AND D.FECHA_CORTE = A.FECHA_CORTE
       );

PROMPT
PROMPT === 3. Diferencias de campos clave en PR_REPRESTAMOS (esperado: 0) ===
WITH A AS (
    SELECT *
      FROM OPTACUM_SNAP_REPRESTAMOS
     WHERE RUN_LABEL = UPPER('&RUN_LABEL_BASE')
),
D AS (
    SELECT *
      FROM OPTACUM_SNAP_REPRESTAMOS
     WHERE RUN_LABEL = UPPER('&RUN_LABEL_TEST')
)
SELECT A.CODIGO_EMPRESA,
       A.CODIGO_CLIENTE,
       A.NO_CREDITO,
       A.FECHA_CORTE,
       A.ESTADO AS ESTADO_BASE,
       D.ESTADO AS ESTADO_TEST,
       A.DIAS_ATRASO AS DIAS_BASE,
       D.DIAS_ATRASO AS DIAS_TEST,
       A.MTO_CREDITO_ACTUAL AS MTO_BASE,
       D.MTO_CREDITO_ACTUAL AS MTO_TEST,
       A.CODIGO_PRECALIFICACION AS PRECAL_BASE,
       D.CODIGO_PRECALIFICACION AS PRECAL_TEST,
       NVL(A.OBSERVACIONES, '#') AS OBS_BASE,
       NVL(D.OBSERVACIONES, '#') AS OBS_TEST
  FROM A
  JOIN D
    ON D.CODIGO_EMPRESA = A.CODIGO_EMPRESA
   AND D.CODIGO_CLIENTE = A.CODIGO_CLIENTE
   AND D.NO_CREDITO = A.NO_CREDITO
   AND D.FECHA_CORTE = A.FECHA_CORTE
 WHERE A.ESTADO != D.ESTADO
    OR NVL(A.DIAS_ATRASO, -1) != NVL(D.DIAS_ATRASO, -1)
    OR NVL(A.MTO_CREDITO_ACTUAL, -1) != NVL(D.MTO_CREDITO_ACTUAL, -1)
    OR NVL(A.CODIGO_PRECALIFICACION, '#') != NVL(D.CODIGO_PRECALIFICACION, '#')
    OR NVL(A.OBSERVACIONES, '#') != NVL(D.OBSERVACIONES, '#');

PROMPT
PROMPT === 4A. Filas exclusivas en PR_SOLICITUD_REPRESTAMO (esperado: 0) ===
WITH MAP_IDS AS (
    SELECT A.ID_REPRESTAMO AS ID_BASE,
           D.ID_REPRESTAMO AS ID_TEST,
           A.CODIGO_EMPRESA,
           A.CODIGO_CLIENTE,
           A.NO_CREDITO,
           A.FECHA_CORTE
      FROM OPTACUM_SNAP_REPRESTAMOS A
      JOIN OPTACUM_SNAP_REPRESTAMOS D
        ON D.RUN_LABEL = UPPER('&RUN_LABEL_TEST')
       AND A.RUN_LABEL = UPPER('&RUN_LABEL_BASE')
       AND D.CODIGO_EMPRESA = A.CODIGO_EMPRESA
       AND D.CODIGO_CLIENTE = A.CODIGO_CLIENTE
       AND D.NO_CREDITO = A.NO_CREDITO
       AND D.FECHA_CORTE = A.FECHA_CORTE
)
SELECT 'FALTA_EN_' || UPPER('&RUN_LABEL_TEST') AS ORIGEN,
       M.CODIGO_EMPRESA,
       M.CODIGO_CLIENTE,
       M.NO_CREDITO,
       M.FECHA_CORTE
  FROM MAP_IDS M
 WHERE EXISTS (
           SELECT 1
             FROM OPTACUM_SNAP_SOLICITUD S
            WHERE S.RUN_LABEL = UPPER('&RUN_LABEL_BASE')
              AND S.CODIGO_EMPRESA = M.CODIGO_EMPRESA
              AND S.ID_REPRESTAMO = M.ID_BASE
       )
   AND NOT EXISTS (
           SELECT 1
             FROM OPTACUM_SNAP_SOLICITUD S
            WHERE S.RUN_LABEL = UPPER('&RUN_LABEL_TEST')
              AND S.CODIGO_EMPRESA = M.CODIGO_EMPRESA
              AND S.ID_REPRESTAMO = M.ID_TEST
       )
UNION ALL
SELECT 'FALTA_EN_' || UPPER('&RUN_LABEL_BASE'),
       M.CODIGO_EMPRESA,
       M.CODIGO_CLIENTE,
       M.NO_CREDITO,
       M.FECHA_CORTE
  FROM MAP_IDS M
 WHERE EXISTS (
           SELECT 1
             FROM OPTACUM_SNAP_SOLICITUD S
            WHERE S.RUN_LABEL = UPPER('&RUN_LABEL_TEST')
              AND S.CODIGO_EMPRESA = M.CODIGO_EMPRESA
              AND S.ID_REPRESTAMO = M.ID_TEST
       )
   AND NOT EXISTS (
           SELECT 1
             FROM OPTACUM_SNAP_SOLICITUD S
            WHERE S.RUN_LABEL = UPPER('&RUN_LABEL_BASE')
              AND S.CODIGO_EMPRESA = M.CODIGO_EMPRESA
              AND S.ID_REPRESTAMO = M.ID_BASE
       );

PROMPT
PROMPT === 4B. Diferencias en PR_SOLICITUD_REPRESTAMO (esperado: 0) ===
WITH MAP_IDS AS (
    SELECT A.ID_REPRESTAMO AS ID_BASE,
           D.ID_REPRESTAMO AS ID_TEST,
           A.CODIGO_EMPRESA,
           A.CODIGO_CLIENTE,
           A.NO_CREDITO,
           A.FECHA_CORTE
      FROM OPTACUM_SNAP_REPRESTAMOS A
      JOIN OPTACUM_SNAP_REPRESTAMOS D
        ON D.RUN_LABEL = UPPER('&RUN_LABEL_TEST')
       AND A.RUN_LABEL = UPPER('&RUN_LABEL_BASE')
       AND D.CODIGO_EMPRESA = A.CODIGO_EMPRESA
       AND D.CODIGO_CLIENTE = A.CODIGO_CLIENTE
       AND D.NO_CREDITO = A.NO_CREDITO
       AND D.FECHA_CORTE = A.FECHA_CORTE
),
SB AS (
    SELECT S.CODIGO_EMPRESA,
           M.CODIGO_CLIENTE AS CODIGO_CLIENTE_KEY,
           M.NO_CREDITO AS NO_CREDITO_KEY,
           M.FECHA_CORTE AS FECHA_CORTE_KEY,
           S.ESTADO,
           S.TELEFONO_CELULAR,
           S.EMAIL,
           S.DIRECCION,
           S.TIPO_CREDITO
      FROM OPTACUM_SNAP_SOLICITUD S
      JOIN MAP_IDS M
        ON M.ID_BASE = S.ID_REPRESTAMO
       AND M.CODIGO_EMPRESA = S.CODIGO_EMPRESA
     WHERE S.RUN_LABEL = UPPER('&RUN_LABEL_BASE')
),
ST AS (
    SELECT S.CODIGO_EMPRESA,
           M.CODIGO_CLIENTE AS CODIGO_CLIENTE_KEY,
           M.NO_CREDITO AS NO_CREDITO_KEY,
           M.FECHA_CORTE AS FECHA_CORTE_KEY,
           S.ESTADO,
           S.TELEFONO_CELULAR,
           S.EMAIL,
           S.DIRECCION,
           S.TIPO_CREDITO
      FROM OPTACUM_SNAP_SOLICITUD S
      JOIN MAP_IDS M
        ON M.ID_TEST = S.ID_REPRESTAMO
       AND M.CODIGO_EMPRESA = S.CODIGO_EMPRESA
     WHERE S.RUN_LABEL = UPPER('&RUN_LABEL_TEST')
)
SELECT SB.CODIGO_EMPRESA,
       SB.CODIGO_CLIENTE_KEY AS CODIGO_CLIENTE,
       SB.NO_CREDITO_KEY AS NO_CREDITO,
       SB.FECHA_CORTE_KEY AS FECHA_CORTE,
       NVL(SB.ESTADO, '#') AS ESTADO_BASE,
       NVL(ST.ESTADO, '#') AS ESTADO_TEST,
       NVL(SB.TELEFONO_CELULAR, '#') AS CEL_BASE,
       NVL(ST.TELEFONO_CELULAR, '#') AS CEL_TEST,
       NVL(SB.EMAIL, '#') AS EMAIL_BASE,
       NVL(ST.EMAIL, '#') AS EMAIL_TEST,
       NVL(SB.DIRECCION, '#') AS DIR_BASE,
       NVL(ST.DIRECCION, '#') AS DIR_TEST,
       NVL(TO_CHAR(SB.TIPO_CREDITO), '#') AS TIPO_BASE,
       NVL(TO_CHAR(ST.TIPO_CREDITO), '#') AS TIPO_TEST
  FROM SB
  JOIN ST
    ON ST.CODIGO_EMPRESA = SB.CODIGO_EMPRESA
   AND ST.CODIGO_CLIENTE_KEY = SB.CODIGO_CLIENTE_KEY
   AND ST.NO_CREDITO_KEY = SB.NO_CREDITO_KEY
   AND ST.FECHA_CORTE_KEY = SB.FECHA_CORTE_KEY
 WHERE NVL(SB.ESTADO, '#') != NVL(ST.ESTADO, '#')
    OR NVL(SB.TELEFONO_CELULAR, '#') != NVL(ST.TELEFONO_CELULAR, '#')
    OR NVL(SB.EMAIL, '#') != NVL(ST.EMAIL, '#')
    OR NVL(SB.DIRECCION, '#') != NVL(ST.DIRECCION, '#')
    OR NVL(TO_CHAR(SB.TIPO_CREDITO), '#') != NVL(TO_CHAR(ST.TIPO_CREDITO), '#');

PROMPT
PROMPT === 5. Diferencias en PR_CANALES_REPRESTAMO (esperado: 0) ===
WITH MAP_IDS AS (
    SELECT A.ID_REPRESTAMO AS ID_BASE,
           D.ID_REPRESTAMO AS ID_TEST,
           A.CODIGO_EMPRESA,
           A.CODIGO_CLIENTE,
           A.NO_CREDITO,
           A.FECHA_CORTE
      FROM OPTACUM_SNAP_REPRESTAMOS A
      JOIN OPTACUM_SNAP_REPRESTAMOS D
        ON D.RUN_LABEL = UPPER('&RUN_LABEL_TEST')
       AND A.RUN_LABEL = UPPER('&RUN_LABEL_BASE')
       AND D.CODIGO_EMPRESA = A.CODIGO_EMPRESA
       AND D.CODIGO_CLIENTE = A.CODIGO_CLIENTE
       AND D.NO_CREDITO = A.NO_CREDITO
       AND D.FECHA_CORTE = A.FECHA_CORTE
),
CB AS (
    SELECT M.CODIGO_EMPRESA,
           M.CODIGO_CLIENTE,
           M.NO_CREDITO,
           M.FECHA_CORTE,
           C.CANAL,
           C.VALOR
      FROM OPTACUM_SNAP_CANALES C
      JOIN MAP_IDS M
        ON M.ID_BASE = C.ID_REPRESTAMO
       AND M.CODIGO_EMPRESA = C.CODIGO_EMPRESA
     WHERE C.RUN_LABEL = UPPER('&RUN_LABEL_BASE')
),
CT AS (
    SELECT M.CODIGO_EMPRESA,
           M.CODIGO_CLIENTE,
           M.NO_CREDITO,
           M.FECHA_CORTE,
           C.CANAL,
           C.VALOR
      FROM OPTACUM_SNAP_CANALES C
      JOIN MAP_IDS M
        ON M.ID_TEST = C.ID_REPRESTAMO
       AND M.CODIGO_EMPRESA = C.CODIGO_EMPRESA
     WHERE C.RUN_LABEL = UPPER('&RUN_LABEL_TEST')
)
SELECT 'SOLO_EN_' || UPPER('&RUN_LABEL_TEST') AS ORIGEN,
       CT.CODIGO_EMPRESA,
       CT.CODIGO_CLIENTE,
       CT.NO_CREDITO,
       CT.FECHA_CORTE,
       CT.CANAL,
       CT.VALOR
  FROM CT
 WHERE NOT EXISTS (
           SELECT 1
             FROM CB
            WHERE CB.CODIGO_EMPRESA = CT.CODIGO_EMPRESA
              AND CB.CODIGO_CLIENTE = CT.CODIGO_CLIENTE
              AND CB.NO_CREDITO = CT.NO_CREDITO
              AND CB.FECHA_CORTE = CT.FECHA_CORTE
              AND CB.CANAL = CT.CANAL
              AND NVL(CB.VALOR, '#') = NVL(CT.VALOR, '#')
       )
UNION ALL
SELECT 'SOLO_EN_' || UPPER('&RUN_LABEL_BASE'),
       CB.CODIGO_EMPRESA,
       CB.CODIGO_CLIENTE,
       CB.NO_CREDITO,
       CB.FECHA_CORTE,
       CB.CANAL,
       CB.VALOR
  FROM CB
 WHERE NOT EXISTS (
           SELECT 1
             FROM CT
            WHERE CT.CODIGO_EMPRESA = CB.CODIGO_EMPRESA
              AND CT.CODIGO_CLIENTE = CB.CODIGO_CLIENTE
              AND CT.NO_CREDITO = CB.NO_CREDITO
              AND CT.FECHA_CORTE = CB.FECHA_CORTE
              AND CT.CANAL = CB.CANAL
              AND NVL(CT.VALOR, '#') = NVL(CB.VALOR, '#')
       );

PROMPT
PROMPT === 6A. Filas exclusivas en PR_OPCIONES_REPRESTAMO (esperado: 0) ===
WITH MAP_IDS AS (
    SELECT A.ID_REPRESTAMO AS ID_BASE,
           D.ID_REPRESTAMO AS ID_TEST,
           A.CODIGO_EMPRESA,
           A.CODIGO_CLIENTE,
           A.NO_CREDITO,
           A.FECHA_CORTE
      FROM OPTACUM_SNAP_REPRESTAMOS A
      JOIN OPTACUM_SNAP_REPRESTAMOS D
        ON D.RUN_LABEL = UPPER('&RUN_LABEL_TEST')
       AND A.RUN_LABEL = UPPER('&RUN_LABEL_BASE')
       AND D.CODIGO_EMPRESA = A.CODIGO_EMPRESA
       AND D.CODIGO_CLIENTE = A.CODIGO_CLIENTE
       AND D.NO_CREDITO = A.NO_CREDITO
       AND D.FECHA_CORTE = A.FECHA_CORTE
),
OB AS (
    SELECT M.CODIGO_EMPRESA,
           M.CODIGO_CLIENTE,
           M.NO_CREDITO,
           M.FECHA_CORTE,
           O.PLAZO
      FROM OPTACUM_SNAP_OPCIONES O
      JOIN MAP_IDS M
        ON M.ID_BASE = O.ID_REPRESTAMO
       AND M.CODIGO_EMPRESA = O.CODIGO_EMPRESA
     WHERE O.RUN_LABEL = UPPER('&RUN_LABEL_BASE')
),
OT AS (
    SELECT M.CODIGO_EMPRESA,
           M.CODIGO_CLIENTE,
           M.NO_CREDITO,
           M.FECHA_CORTE,
           O.PLAZO
      FROM OPTACUM_SNAP_OPCIONES O
      JOIN MAP_IDS M
        ON M.ID_TEST = O.ID_REPRESTAMO
       AND M.CODIGO_EMPRESA = O.CODIGO_EMPRESA
     WHERE O.RUN_LABEL = UPPER('&RUN_LABEL_TEST')
)
SELECT 'SOLO_EN_' || UPPER('&RUN_LABEL_TEST') AS ORIGEN,
       OT.CODIGO_EMPRESA,
       OT.CODIGO_CLIENTE,
       OT.NO_CREDITO,
       OT.FECHA_CORTE,
       OT.PLAZO
  FROM OT
 WHERE NOT EXISTS (
           SELECT 1
             FROM OB
            WHERE OB.CODIGO_EMPRESA = OT.CODIGO_EMPRESA
              AND OB.CODIGO_CLIENTE = OT.CODIGO_CLIENTE
              AND OB.NO_CREDITO = OT.NO_CREDITO
              AND OB.FECHA_CORTE = OT.FECHA_CORTE
              AND OB.PLAZO = OT.PLAZO
       )
UNION ALL
SELECT 'SOLO_EN_' || UPPER('&RUN_LABEL_BASE'),
       OB.CODIGO_EMPRESA,
       OB.CODIGO_CLIENTE,
       OB.NO_CREDITO,
       OB.FECHA_CORTE,
       OB.PLAZO
  FROM OB
 WHERE NOT EXISTS (
           SELECT 1
             FROM OT
            WHERE OT.CODIGO_EMPRESA = OB.CODIGO_EMPRESA
              AND OT.CODIGO_CLIENTE = OB.CODIGO_CLIENTE
              AND OT.NO_CREDITO = OB.NO_CREDITO
              AND OT.FECHA_CORTE = OB.FECHA_CORTE
              AND OT.PLAZO = OB.PLAZO
       );

PROMPT
PROMPT === 6B. Diferencias en PR_OPCIONES_REPRESTAMO (esperado: 0) ===
WITH MAP_IDS AS (
    SELECT A.ID_REPRESTAMO AS ID_BASE,
           D.ID_REPRESTAMO AS ID_TEST,
           A.CODIGO_EMPRESA,
           A.CODIGO_CLIENTE,
           A.NO_CREDITO,
           A.FECHA_CORTE
      FROM OPTACUM_SNAP_REPRESTAMOS A
      JOIN OPTACUM_SNAP_REPRESTAMOS D
        ON D.RUN_LABEL = UPPER('&RUN_LABEL_TEST')
       AND A.RUN_LABEL = UPPER('&RUN_LABEL_BASE')
       AND D.CODIGO_EMPRESA = A.CODIGO_EMPRESA
       AND D.CODIGO_CLIENTE = A.CODIGO_CLIENTE
       AND D.NO_CREDITO = A.NO_CREDITO
       AND D.FECHA_CORTE = A.FECHA_CORTE
),
OB AS (
    SELECT M.CODIGO_EMPRESA,
           M.CODIGO_CLIENTE,
           M.NO_CREDITO,
           M.FECHA_CORTE,
           O.PLAZO,
           O.MTO_PRESTAMO,
           O.MTO_DESCONTAR,
           O.MTO_DEPOSITAR,
           O.MTO_CUOTA,
           O.MTO_CARGOS,
           O.TASA,
           O.ESTADO
      FROM OPTACUM_SNAP_OPCIONES O
      JOIN MAP_IDS M
        ON M.ID_BASE = O.ID_REPRESTAMO
       AND M.CODIGO_EMPRESA = O.CODIGO_EMPRESA
     WHERE O.RUN_LABEL = UPPER('&RUN_LABEL_BASE')
),
OT AS (
    SELECT M.CODIGO_EMPRESA,
           M.CODIGO_CLIENTE,
           M.NO_CREDITO,
           M.FECHA_CORTE,
           O.PLAZO,
           O.MTO_PRESTAMO,
           O.MTO_DESCONTAR,
           O.MTO_DEPOSITAR,
           O.MTO_CUOTA,
           O.MTO_CARGOS,
           O.TASA,
           O.ESTADO
      FROM OPTACUM_SNAP_OPCIONES O
      JOIN MAP_IDS M
        ON M.ID_TEST = O.ID_REPRESTAMO
       AND M.CODIGO_EMPRESA = O.CODIGO_EMPRESA
     WHERE O.RUN_LABEL = UPPER('&RUN_LABEL_TEST')
)
SELECT OB.CODIGO_EMPRESA,
       OB.CODIGO_CLIENTE,
       OB.NO_CREDITO,
       OB.FECHA_CORTE,
       OB.PLAZO,
       OB.ESTADO AS ESTADO_BASE,
       OT.ESTADO AS ESTADO_TEST,
       OB.MTO_PRESTAMO AS PREST_BASE,
       OT.MTO_PRESTAMO AS PREST_TEST,
       OB.MTO_DEPOSITAR AS DEP_BASE,
       OT.MTO_DEPOSITAR AS DEP_TEST,
       OB.TASA AS TASA_BASE,
       OT.TASA AS TASA_TEST
  FROM OB
  JOIN OT
    ON OT.CODIGO_EMPRESA = OB.CODIGO_EMPRESA
   AND OT.CODIGO_CLIENTE = OB.CODIGO_CLIENTE
   AND OT.NO_CREDITO = OB.NO_CREDITO
   AND OT.FECHA_CORTE = OB.FECHA_CORTE
   AND OT.PLAZO = OB.PLAZO
 WHERE NVL(OB.ESTADO, '#') != NVL(OT.ESTADO, '#')
    OR NVL(OB.MTO_PRESTAMO, -1) != NVL(OT.MTO_PRESTAMO, -1)
    OR NVL(OB.MTO_DESCONTAR, -1) != NVL(OT.MTO_DESCONTAR, -1)
    OR NVL(OB.MTO_DEPOSITAR, -1) != NVL(OT.MTO_DEPOSITAR, -1)
    OR NVL(OB.MTO_CUOTA, -1) != NVL(OT.MTO_CUOTA, -1)
    OR NVL(OB.MTO_CARGOS, -1) != NVL(OT.MTO_CARGOS, -1)
    OR NVL(OB.TASA, -1) != NVL(OT.TASA, -1);

PROMPT
PROMPT === 7. Diferencias en PR_BITACORA_REPRESTAMO normalizada (esperado: 0) ===
WITH MAP_IDS AS (
    SELECT A.ID_REPRESTAMO AS ID_BASE,
           D.ID_REPRESTAMO AS ID_TEST,
           A.CODIGO_EMPRESA,
           A.CODIGO_CLIENTE,
           A.NO_CREDITO,
           A.FECHA_CORTE
      FROM OPTACUM_SNAP_REPRESTAMOS A
      JOIN OPTACUM_SNAP_REPRESTAMOS D
        ON D.RUN_LABEL = UPPER('&RUN_LABEL_TEST')
       AND A.RUN_LABEL = UPPER('&RUN_LABEL_BASE')
       AND D.CODIGO_EMPRESA = A.CODIGO_EMPRESA
       AND D.CODIGO_CLIENTE = A.CODIGO_CLIENTE
       AND D.NO_CREDITO = A.NO_CREDITO
       AND D.FECHA_CORTE = A.FECHA_CORTE
),
BB AS (
    SELECT M.CODIGO_EMPRESA,
           M.CODIGO_CLIENTE,
           M.NO_CREDITO,
           M.FECHA_CORTE,
           B.CODIGO_ESTADO,
           NVL(B.STEP, '#') AS STEP_NORM,
           NVL(B.OBSERVACIONES, '#') AS OBS_NORM,
           NVL(B.CANAL, '#') AS CANAL_NORM,
           COUNT(*) AS CNT
      FROM OPTACUM_SNAP_BITACORA B
      JOIN MAP_IDS M
        ON M.ID_BASE = B.ID_REPRESTAMO
       AND M.CODIGO_EMPRESA = B.CODIGO_EMPRESA
     WHERE B.RUN_LABEL = UPPER('&RUN_LABEL_BASE')
     GROUP BY
           M.CODIGO_EMPRESA,
           M.CODIGO_CLIENTE,
           M.NO_CREDITO,
           M.FECHA_CORTE,
           B.CODIGO_ESTADO,
           NVL(B.STEP, '#'),
           NVL(B.OBSERVACIONES, '#'),
           NVL(B.CANAL, '#')
),
BT AS (
    SELECT M.CODIGO_EMPRESA,
           M.CODIGO_CLIENTE,
           M.NO_CREDITO,
           M.FECHA_CORTE,
           B.CODIGO_ESTADO,
           NVL(B.STEP, '#') AS STEP_NORM,
           NVL(B.OBSERVACIONES, '#') AS OBS_NORM,
           NVL(B.CANAL, '#') AS CANAL_NORM,
           COUNT(*) AS CNT
      FROM OPTACUM_SNAP_BITACORA B
      JOIN MAP_IDS M
        ON M.ID_TEST = B.ID_REPRESTAMO
       AND M.CODIGO_EMPRESA = B.CODIGO_EMPRESA
     WHERE B.RUN_LABEL = UPPER('&RUN_LABEL_TEST')
     GROUP BY
           M.CODIGO_EMPRESA,
           M.CODIGO_CLIENTE,
           M.NO_CREDITO,
           M.FECHA_CORTE,
           B.CODIGO_ESTADO,
           NVL(B.STEP, '#'),
           NVL(B.OBSERVACIONES, '#'),
           NVL(B.CANAL, '#')
)
SELECT 'SOLO_EN_' || UPPER('&RUN_LABEL_TEST') AS ORIGEN,
       BT.CODIGO_EMPRESA,
       BT.CODIGO_CLIENTE,
       BT.NO_CREDITO,
       BT.FECHA_CORTE,
       BT.CODIGO_ESTADO,
       BT.STEP_NORM,
       BT.OBS_NORM,
       BT.CANAL_NORM,
       BT.CNT
  FROM BT
 WHERE NOT EXISTS (
           SELECT 1
             FROM BB
            WHERE BB.CODIGO_EMPRESA = BT.CODIGO_EMPRESA
              AND BB.CODIGO_CLIENTE = BT.CODIGO_CLIENTE
              AND BB.NO_CREDITO = BT.NO_CREDITO
              AND BB.FECHA_CORTE = BT.FECHA_CORTE
              AND BB.CODIGO_ESTADO = BT.CODIGO_ESTADO
              AND BB.STEP_NORM = BT.STEP_NORM
              AND BB.OBS_NORM = BT.OBS_NORM
              AND BB.CANAL_NORM = BT.CANAL_NORM
              AND BB.CNT = BT.CNT
       )
UNION ALL
SELECT 'SOLO_EN_' || UPPER('&RUN_LABEL_BASE'),
       BB.CODIGO_EMPRESA,
       BB.CODIGO_CLIENTE,
       BB.NO_CREDITO,
       BB.FECHA_CORTE,
       BB.CODIGO_ESTADO,
       BB.STEP_NORM,
       BB.OBS_NORM,
       BB.CANAL_NORM,
       BB.CNT
  FROM BB
 WHERE NOT EXISTS (
           SELECT 1
             FROM BT
            WHERE BT.CODIGO_EMPRESA = BB.CODIGO_EMPRESA
              AND BT.CODIGO_CLIENTE = BB.CODIGO_CLIENTE
              AND BT.NO_CREDITO = BB.NO_CREDITO
              AND BT.FECHA_CORTE = BB.FECHA_CORTE
              AND BT.CODIGO_ESTADO = BB.CODIGO_ESTADO
              AND BT.STEP_NORM = BB.STEP_NORM
              AND BT.OBS_NORM = BB.OBS_NORM
              AND BT.CANAL_NORM = BB.CANAL_NORM
              AND BT.CNT = BB.CNT
       );
