WITH BASE AS (
    SELECT
        R.CODIGO_REPORTE,
        R.ORIGEN_PKM,
        CASE
            WHEN INSTR(R.CODIGO_REFERENCIA, ':') = 0 THEN R.CODIGO_REFERENCIA
            ELSE IA.PKG_API_PKM.ObtieneParteReferencia(R.CODIGO_REFERENCIA, ':', 3)
        END AS F_NUM_CUENTA,
        NVL(
            SUBSTR(R.NOMBRE_ARCHIVO, 1, INSTRB(R.NOMBRE_ARCHIVO, '_') - 1),
            'N/A'
        ) AS TIPO_ARCHIVO,
        R.ID_TIPO_DOCUMENTO AS F_DOCUMENT_TYPE,
        REPLACE(R.NOMBRE_ARCHIVO, '.pdf', '') AS NOMBRE_ARCHIVO_BASE,
        REGEXP_SUBSTR(REPLACE(R.NOMBRE_ARCHIVO, '.pdf', ''), '[^_]+', 1, 1) AS SEGMENTO_1,
        REGEXP_SUBSTR(REPLACE(R.NOMBRE_ARCHIVO, '.pdf', ''), '[^_]+', 1, 2) AS SEGMENTO_2,
        REGEXP_SUBSTR(REPLACE(R.NOMBRE_ARCHIVO, '.pdf', ''), '[^_]+', 1, 3) AS SEGMENTO_3,
        REGEXP_SUBSTR(REPLACE(R.NOMBRE_ARCHIVO, '.pdf', ''), '[^_]+', 1, 4) AS SEGMENTO_4,
        REGEXP_SUBSTR(REPLACE(R.NOMBRE_ARCHIVO, '.pdf', ''), '[^_]+', 1, 3) AS CODIGO_CLIENTE_EXTRAIDO,
        REPLACE(R.NOMBRE_ARCHIVO, ':', '_') AS NOMBRE_ARCHIVO,
        R.FECHA_REPORTE,
        R.ESTADO_REPORTE AS ESTADO_REPORTE_CODIGO,
        CASE R.ESTADO_REPORTE
            WHEN 'P' THEN 'PENDIENTE'
            WHEN 'R' THEN 'PENDIENTE ROBOTIZADO'
            WHEN 'D' THEN 'DESCARGADO'
            WHEN 'S' THEN 'ENVIADO A PKM'
            WHEN 'E' THEN 'ERROR'
            WHEN 'H' THEN 'RESERVADO PARA DESCARGA'
            WHEN 'SP' THEN 'RESERVADO PARA ENVIO'
            ELSE 'ESTADO NO MAPEADO: ' || R.ESTADO_REPORTE
        END AS ESTADO_REPORTE,
        R.CODIGO_REFERENCIA
    FROM PA.PA_REPORTES_AUTOMATICOS R
),
REPORTES AS (
    SELECT
        B.CODIGO_REPORTE,
        B.ORIGEN_PKM,
        B.F_NUM_CUENTA,
        B.TIPO_ARCHIVO,
        B.F_DOCUMENT_TYPE,
        B.NOMBRE_ARCHIVO_BASE,
        B.SEGMENTO_1,
        B.SEGMENTO_2,
        B.SEGMENTO_3,
        B.SEGMENTO_4,
        B.CODIGO_CLIENTE_EXTRAIDO,
        (
            SELECT C.NUMERO_IDENTIFICACION
            FROM PA.CLIENTES_B2000 C
            WHERE C.CODIGO_EMPRESA = '1'
              AND TRIM(TO_CHAR(C.CODIGO_CLIENTE)) = B.CODIGO_CLIENTE_EXTRAIDO
              AND ROWNUM = 1
        ) AS IDENTIFICACION,
        PA.OBT_NOMBRE_PERSONA(B.CODIGO_CLIENTE_EXTRAIDO) AS CLIENTE,
        CASE
            WHEN EXISTS (
                SELECT 1
                FROM PA.CLIENTES_B2000 C
                WHERE C.CODIGO_EMPRESA = '1'
                  AND TRIM(TO_CHAR(C.CODIGO_CLIENTE)) = B.SEGMENTO_1
            ) THEN 'S'
            ELSE 'N'
        END AS SEGMENTO_1_ES_CLIENTE,
        CASE
            WHEN EXISTS (
                SELECT 1
                FROM PA.CLIENTES_B2000 C
                WHERE C.CODIGO_EMPRESA = '1'
                  AND TRIM(TO_CHAR(C.CODIGO_CLIENTE)) = B.SEGMENTO_2
            ) THEN 'S'
            ELSE 'N'
        END AS SEGMENTO_2_ES_CLIENTE,
        CASE
            WHEN EXISTS (
                SELECT 1
                FROM PA.CLIENTES_B2000 C
                WHERE C.CODIGO_EMPRESA = '1'
                  AND TRIM(TO_CHAR(C.CODIGO_CLIENTE)) = B.SEGMENTO_3
            ) THEN 'S'
            ELSE 'N'
        END AS SEGMENTO_3_ES_CLIENTE,
        CASE
            WHEN EXISTS (
                SELECT 1
                FROM PA.CLIENTES_B2000 C
                WHERE C.CODIGO_EMPRESA = '1'
                  AND TRIM(TO_CHAR(C.CODIGO_CLIENTE)) = B.SEGMENTO_4
            ) THEN 'S'
            ELSE 'N'
        END AS SEGMENTO_4_ES_CLIENTE,
        B.NOMBRE_ARCHIVO,
        B.FECHA_REPORTE,
        B.ESTADO_REPORTE,
        B.ESTADO_REPORTE_CODIGO,
        B.CODIGO_REFERENCIA
    FROM BASE B
)
SELECT
    R.ORIGEN_PKM,
    R.F_NUM_CUENTA,
    R.TIPO_ARCHIVO,
    R.F_DOCUMENT_TYPE,
    R.CODIGO_CLIENTE_EXTRAIDO,
    R.SEGMENTO_1,
    R.SEGMENTO_2,
    R.SEGMENTO_3,
    R.SEGMENTO_4,
    CASE
        WHEN R.SEGMENTO_3_ES_CLIENTE = 'S' THEN R.SEGMENTO_3
        WHEN R.SEGMENTO_1_ES_CLIENTE = 'S' THEN R.SEGMENTO_1
        WHEN R.SEGMENTO_2_ES_CLIENTE = 'S' THEN R.SEGMENTO_2
        WHEN R.SEGMENTO_4_ES_CLIENTE = 'S' THEN R.SEGMENTO_4
        ELSE NULL
    END AS CODIGO_CLIENTE_DETECTADO,
    CASE
        WHEN R.SEGMENTO_3_ES_CLIENTE = 'S' THEN 'SEGMENTO_3_POSICION_ESPERADA'
        WHEN R.SEGMENTO_1_ES_CLIENTE = 'S' THEN 'SEGMENTO_1'
        WHEN R.SEGMENTO_2_ES_CLIENTE = 'S' THEN 'SEGMENTO_2'
        WHEN R.SEGMENTO_4_ES_CLIENTE = 'S' THEN 'SEGMENTO_4'
        ELSE NULL
    END AS POSICION_CODIGO_CLIENTE_DETECTADO,
    CASE
        WHEN R.CODIGO_CLIENTE_EXTRAIDO IS NULL THEN 'NO_HAY_TERCER_SEGMENTO_EN_NOMBRE_ARCHIVO'
        WHEN R.SEGMENTO_3_ES_CLIENTE = 'S' THEN 'CODIGO_CLIENTE_EN_POSICION_ESPERADA'
        WHEN R.SEGMENTO_1_ES_CLIENTE = 'S'
          OR R.SEGMENTO_2_ES_CLIENTE = 'S'
          OR R.SEGMENTO_4_ES_CLIENTE = 'S' THEN 'CODIGO_CLIENTE_EXISTE_EN_OTRA_POSICION'
        ELSE 'TERCER_SEGMENTO_NO_EXISTE_COMO_CLIENTE_EN_CLIENTES_B2000'
    END AS DIAGNOSTICO_CODIGO_CLIENTE,
    R.IDENTIFICACION,
    R.CLIENTE,
    R.NOMBRE_ARCHIVO,
    R.FECHA_REPORTE,
    R.ESTADO_REPORTE,
    R.ESTADO_REPORTE_CODIGO,
    R.CODIGO_REPORTE,
    R.CODIGO_REFERENCIA,
    CASE
        WHEN R.ORIGEN_PKM = 'Onboarding' THEN 'ENTRA_EN_PAGINA_136'
        ELSE 'NO_ENTRA_EN_PAGINA_136_POR_ORIGEN'
    END AS DIAGNOSTICO_ORIGEN
FROM REPORTES R
WHERE R.F_NUM_CUENTA = '21055516645617'
ORDER BY
    R.FECHA_REPORTE DESC,
    R.CODIGO_REPORTE DESC;
