-- =============================================================================
-- Historia: INV_REGISTROS_FALTANTES_ONBOARDING
-- Script: Validar cuenta de certificado digital contra reportes automaticos
--
-- Proposito:
--   Para certificados digitales, PA.PA_REPORTES_AUTOMATICOS se registra usando
--   el NUM_CERTIFICADO, no necesariamente el NUM_CUENTA de fondos. Este script
--   primero ubica el certificado por NUM_CUENTA en CD.CD_CERTIFICADO y luego
--   busca sus documentos en PA.PA_REPORTES_AUTOMATICOS.
--
-- Uso en Toad:
--   1. Ejecutar en el ambiente investigado.
--   2. Reemplazar la lista de CUENTAS por los numeros reportados.
--   3. No modifica datos.
-- =============================================================================

-- BLOQUE 0: Verificar nombres reales de columnas en el ambiente.
-- En QADEMI02_19C el package CD.PKG_CD_DIGITAL inserta en CLIENTE.
SELECT
    C.OWNER,
    C.TABLE_NAME,
    C.COLUMN_ID,
    C.COLUMN_NAME,
    C.DATA_TYPE,
    C.DATA_LENGTH
FROM ALL_TAB_COLUMNS C
WHERE C.OWNER = 'CD'
  AND C.TABLE_NAME = 'CD_CERTIFICADO'
  AND C.COLUMN_NAME IN ('NUM_CUENTA', 'NUM_CERTIFICADO', 'CLIENTE', 'COD_CLIENTE', 'TITULAR')
ORDER BY C.COLUMN_ID;

-- BLOQUE 1: Mapear NUM_CUENTA -> NUM_CERTIFICADO.
WITH CUENTAS AS (
    SELECT '190001000001893' AS NUM_CUENTA FROM DUAL
),
CERTIFICADOS AS (
    SELECT
        C.NUM_CUENTA AS NUM_CUENTA_BUSCADO,
        CD.COD_EMPRESA,
        CD.NUM_CERTIFICADO,
        CD.CLIENTE AS COD_CLIENTE,
        CD.COD_PRODUCTO,
        CD.COD_MONEDA,
        CD.MONTO,
        CD.ESTADO AS ESTADO_CERTIFICADO,
        CD.FEC_EMISION,
        CD.FEC_VENCIMIENTO
    FROM CUENTAS C
    LEFT JOIN CD.CD_CERTIFICADO CD
        ON TRIM(TO_CHAR(CD.NUM_CUENTA)) = C.NUM_CUENTA
)
SELECT
    C.NUM_CUENTA_BUSCADO,
    C.COD_EMPRESA,
    C.NUM_CERTIFICADO,
    C.COD_CLIENTE,
    C.COD_PRODUCTO,
    C.COD_MONEDA,
    C.MONTO,
    C.ESTADO_CERTIFICADO,
    C.FEC_EMISION,
    C.FEC_VENCIMIENTO,
    CASE
        WHEN C.NUM_CERTIFICADO IS NULL THEN 'NO_EXISTE_CERTIFICADO_PARA_ESTA_CUENTA'
        ELSE 'EXISTE_CERTIFICADO'
    END AS DIAGNOSTICO_CERTIFICADO
FROM CERTIFICADOS C
ORDER BY
    C.NUM_CUENTA_BUSCADO,
    C.FEC_EMISION DESC,
    C.NUM_CERTIFICADO DESC;

-- BLOQUE 2: Validar si los NUM_CERTIFICADO encontrados fueron registrados
-- en PA.PA_REPORTES_AUTOMATICOS.
WITH CUENTAS AS (
    SELECT '190001000001893' AS NUM_CUENTA FROM DUAL
),
CERTIFICADOS AS (
    SELECT
        C.NUM_CUENTA AS NUM_CUENTA_BUSCADO,
        CD.COD_EMPRESA,
        CD.NUM_CERTIFICADO,
        CD.CLIENTE AS COD_CLIENTE,
        CD.COD_PRODUCTO,
        CD.COD_MONEDA,
        CD.MONTO,
        CD.ESTADO AS ESTADO_CERTIFICADO,
        CD.FEC_EMISION,
        CD.FEC_VENCIMIENTO
    FROM CUENTAS C
    LEFT JOIN CD.CD_CERTIFICADO CD
        ON TRIM(TO_CHAR(CD.NUM_CUENTA)) = C.NUM_CUENTA
)
SELECT
    C.NUM_CUENTA_BUSCADO,
    C.NUM_CERTIFICADO,
    C.COD_CLIENTE,
    C.COD_PRODUCTO,
    C.ESTADO_CERTIFICADO,
    C.FEC_EMISION,
    R.CODIGO_REPORTE,
    R.ORIGEN_PKM,
    R.ID_TIPO_DOCUMENTO,
    CASE R.ESTADO_REPORTE
        WHEN 'P' THEN 'PENDIENTE'
        WHEN 'R' THEN 'PENDIENTE ROBOTIZADO'
        WHEN 'D' THEN 'DESCARGADO'
        WHEN 'S' THEN 'ENVIADO A PKM'
        WHEN 'E' THEN 'ERROR'
        WHEN 'H' THEN 'RESERVADO PARA DESCARGA'
        WHEN 'SP' THEN 'RESERVADO PARA ENVIO'
        ELSE R.ESTADO_REPORTE
    END AS ESTADO_REPORTE,
    R.ESTADO_REPORTE AS ESTADO_REPORTE_CODIGO,
    R.CODIGO_REFERENCIA,
    R.NOMBRE_ARCHIVO,
    R.FECHA_REPORTE,
    CASE
        WHEN C.NUM_CERTIFICADO IS NULL THEN 'NO_EXISTE_CERTIFICADO_PARA_ESTA_CUENTA'
        WHEN R.CODIGO_REPORTE IS NULL THEN 'CERTIFICADO_EXISTE_PERO_NO_ESTA_EN_PA_REPORTES_AUTOMATICOS'
        WHEN R.ORIGEN_PKM = 'Onboarding' THEN 'REGISTRADO_Y_ENTRA_EN_PAGINA_136'
        ELSE 'REGISTRADO_PERO_NO_ENTRA_EN_PAGINA_136_POR_ORIGEN'
    END AS DIAGNOSTICO
FROM CERTIFICADOS C
LEFT JOIN PA.PA_REPORTES_AUTOMATICOS R
    ON R.CODIGO_REFERENCIA LIKE '%' || C.NUM_CERTIFICADO || '%'
    OR R.NOMBRE_ARCHIVO LIKE '%' || C.NUM_CERTIFICADO || '%'
ORDER BY
    C.NUM_CUENTA_BUSCADO,
    C.FEC_EMISION DESC,
    C.NUM_CERTIFICADO DESC,
    R.FECHA_REPORTE DESC,
    R.CODIGO_REPORTE DESC;

-- BLOQUE 3: Buscar directo por NUM_CERTIFICADO si ya se conoce.
-- Reemplazar el valor por el certificado reportado.
SELECT
    R.CODIGO_REPORTE,
    R.ORIGEN_PKM,
    R.ID_TIPO_DOCUMENTO,
    CASE R.ESTADO_REPORTE
        WHEN 'P' THEN 'PENDIENTE'
        WHEN 'R' THEN 'PENDIENTE ROBOTIZADO'
        WHEN 'D' THEN 'DESCARGADO'
        WHEN 'S' THEN 'ENVIADO A PKM'
        WHEN 'E' THEN 'ERROR'
        WHEN 'H' THEN 'RESERVADO PARA DESCARGA'
        WHEN 'SP' THEN 'RESERVADO PARA ENVIO'
        ELSE R.ESTADO_REPORTE
    END AS ESTADO_REPORTE,
    R.ESTADO_REPORTE AS ESTADO_REPORTE_CODIGO,
    R.CODIGO_REFERENCIA,
    R.NOMBRE_ARCHIVO,
    R.FECHA_REPORTE,
    CASE
        WHEN R.ORIGEN_PKM = 'Onboarding' THEN 'ENTRA_EN_PAGINA_136'
        ELSE 'NO_ENTRA_EN_PAGINA_136_POR_ORIGEN'
    END AS DIAGNOSTICO_ORIGEN
FROM PA.PA_REPORTES_AUTOMATICOS R
WHERE R.CODIGO_REFERENCIA LIKE '%' || 'PONER_NUM_CERTIFICADO_AQUI' || '%'
   OR R.NOMBRE_ARCHIVO LIKE '%' || 'PONER_NUM_CERTIFICADO_AQUI' || '%'
ORDER BY
    R.FECHA_REPORTE DESC,
    R.CODIGO_REPORTE DESC;
