CREATE TABLE PA.PA_DE05_SIB
(
  CEDULA         VARCHAR2(30 BYTE),
  FECHA_CASTIGO  DATE,
  NOMBRE         VARCHAR2(100 BYTE),
  ENTIDAD        VARCHAR2(150 BYTE),
  FECHA_PROCESO  DATE                           DEFAULT TRUNC(SYSDATE)
)
TABLESPACE PA_DAT
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING
NOCOMPRESS
NOCACHE;


CREATE OR REPLACE PUBLIC SYNONYM PA_DE05_SIB FOR PA.PA_DE05_SIB;


GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON PA.PA_DE05_SIB TO BCC;
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON PA.PA_DE05_SIB TO BGC;
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON PA.PA_DE05_SIB TO BIA;
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON PA.PA_DE05_SIB TO BPA;
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON PA.PA_DE05_SIB TO BPR;
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON PA.PA_DE05_SIB TO BTC;
