CREATE TABLE CD_CERTIFICADO (
    COD_EMPRESA                VARCHAR2(5 BYTE) NOT NULL,
    NUM_CERTIFICADO            VARCHAR2(15 BYTE) NOT NULL,
    COD_AGENCIA                VARCHAR2(10 BYTE) NOT NULL,
    COD_PRODUCTO               VARCHAR2(4 BYTE),
    COD_CLIENTE                VARCHAR2(10 BYTE) NOT NULL,
    COD_SERIE                  VARCHAR2(10 BYTE),
    CONSECUTIVO                NUMBER(10) NOT NULL,
    CUENTA_CONTABLE            VARCHAR2(15 BYTE) NOT NULL,
    COD_TASA                   VARCHAR2(8 BYTE),
    ADICIONADO_POR             VARCHAR2(10 BYTE),
    CLASIFICACION              VARCHAR2(1 BYTE),
    CLASIFICADO                VARCHAR2(4 BYTE),
    CRE_COMISION               NUMBER(4) NOT NULL,
    CRE_INTERES                NUMBER(22, 7),
    DES_MES                    NUMBER(22, 7),
    DES_INTERES                NUMBER(22, 2),
    DIAS_CONGELAMIENTO         NUMBER(4),
    ESTADO                     VARCHAR2(1 BYTE) NOT NULL,
    EXC_IMPUESTO               VARCHAR2(1 BYTE),
    FEC_EMISION                DATE NOT NULL,
    IND_EMISION                DATE,
    IND_BENEFICIARIO_CD        VARCHAR2(1 BYTE),
    IND_BENEFICIARIO_CU        VARCHAR2(1 BYTE),
    LUG_CAPTACION              VARCHAR2(10 BYTE),
    MONTO                      NUMBER(17, 2),
    PLA_DIAS                   NUMBER(4),
    PLA_MESES                  NUMBER(4),
    CIUDAD_CD                  VARCHAR2(8 BYTE),
    TAS_BRUTA                  NUMBER(8, 4),
    TAS_NETA                   NUMBER(8, 4),
    TIP_PLAZO                  VARCHAR2(1 BYTE),
    TITULAR                    VARCHAR2(10 BYTE) NOT NULL,
    UTILIZADO                  VARCHAR2(1 BYTE) DEFAULT 'N',
    IND_RENO_AUTO              VARCHAR2(1 BYTE),
    NUM_MACROTITULO            NUMBER(15),
    FEC_ENTREGA                DATE,
    FEC_MODIFICACION           DATE,
    FEC_CALC_INTERES           DATE,
    FEC_PAGO                   DATE,
    FEC_ULT_ANTICI             DATE,
    FEC_ULT_CALCULO            DATE,
    FEC_ULT_REVISION           DATE,
    FEC_PROX_CAL               DATE,
    FEC_PROX_REVI              DATE,
    FEC_VENCIMIENTO            DATE,
    MODIFICADO_POR             VARCHAR2(10 BYTE),
    COMENTARIO                 VARCHAR2(1024 BYTE),
    MON_INTERES_PAGADO         NUMBER(17, 2),
    NUM_SERIE                  VARCHAR2(10 BYTE),
    PRE_REVISION               VARCHAR2(1 BYTE),
    PLA_REVISION               NUMBER(4),
    PRE_INTERES                VARCHAR2(1 BYTE),
    PLA_INTERES                NUMBER(4),
    PRE_CAPITALIZA             VARCHAR2(1 BYTE),
    PLA_CAPITALIZA             NUMBER(4),
    COD_AGENCIA_OP             VARCHAR2(10 BYTE),
    COD_AGENCIA_CP             VARCHAR2(5 BYTE),
    COD_PRODUCTO_CP            VARCHAR2(4 BYTE) NOT NULL,
    MON_INT_A_PAGAR            NUMBER(22, 7),
    MON_ACUM_INT_CAP           NUMBER(22, 7),
    MON_ACUM_INT_CAL           NUMBER(22, 7),
    MON_INT_RECONOCIDOS        NUMBER(17, 2),
    TIP_CERTIFICADO            VARCHAR2(1 BYTE),
    COD_MONEDA                 VARCHAR2(4 BYTE) NOT NULL,
    FEC_ULT_CAP                DATE,
    MON_ACUM_INT_CAP_BRUTO     NUMBER(17, 2),
    MON_ACUM_INT_CAL_BRUTO     NUMBER(17, 2),
    MON_RETENIDO               NUMBER(17, 2),
    MONTO_ORIGINAL             NUMBER(17, 2),
    MON_INT_PROYECTADO         NUMBER(17, 2),
    MON_INT_PROYECTADO_BRUTO   NUMBER(17, 2),
    TIENE_DOC_FISICO           VARCHAR2(1 BYTE),
    NUMERO_ASIENTO_CONTABLE    NUMBER(10),
    NUMERO_SOLICITUD_CAJAS     NUMBER(10),
    FORMA_PAGO_INTERESES       VARCHAR2(2 BYTE),
    MON_INT_GANADO             NUMBER(17, 2),
    MON_INT_RECONOCIDOS_BRUTO  NUMBER(17, 2),
    NUM_CUENTA                 NUMBER(14),
    PORCENTAJE_RENTA           NUMBER(8, 4),
    BASE_CALCULO               NUMBER(3),
    BASE_PLAZO                 NUMBER(3),
    OPERACION                  VARCHAR2(1 BYTE),
    NUEVO_CERTIFICADO          VARCHAR2(15 BYTE),
    DIA_PAGO_INT               NUMBER(2),
    FEC_ULT_RENOV              DATE,
    NUM_VECES_RENOVADO         NUMBER(3),
    UNIFICAR_CD                VARCHAR2(1 BYTE),
    MONTO_CHEQUES              NUMBER(18, 2),
    DIAS_EFECTIVO              NUMBER(3),
    DIAS_CHEQUES               NUMBER(3),
    DIAS_AJUSTE                NUMBER(3),
    MON_EFECTIVO               NUMBER(18, 2),
    COD_EJECUTIVO              VARCHAR2(10 BYTE),
    CODIGO_VERIFICACION        VARCHAR2(10 BYTE),
    FIRMA_AUT1                 VARCHAR2(10 BYTE),
    FIRMA_AUT2                 VARCHAR2(10 BYTE),
    NO_DOC_ORIGEN              NUMBER(10),
    INT_CAP_NO_SALDO           NUMBER(17, 2),
    AUTORIZA_ANUL              VARCHAR2(10 BYTE),
    AUTORIZA_ANUL2             VARCHAR2(10 BYTE),
    PROCESAR                   VARCHAR2(1 BYTE),
    NUMERO_ASIENTO             NUMBER(8),
    NUM_PREIMPRESO             VARCHAR2(10 BYTE),
    FEC_PROX_PAG               DATE,
    CODIGO_PROMOTOR            VARCHAR2(10 BYTE),
    CONSTRAINT PK_CD_CERTIFICADO PRIMARY KEY (COD_EMPRESA, NUM_CERTIFICADO)
);
