CREATE TABLE PERSONAS_FISICAS (
    COD_PER_FISICA             VARCHAR2(15 Byte) NOT NULL,
    EST_CIVIL                  VARCHAR2(5 Byte),
    SEXO                       VARCHAR2(1 Byte),
    FEC_NACIMIENTO             DATE,
    PRIMER_APELLIDO            VARCHAR2(25 Byte),
    SEGUNDO_APELLIDO           VARCHAR2(25 Byte),
    PRIMER_NOMBRE              VARCHAR2(25 Byte),
    SEGUNDO_NOMBRE             VARCHAR2(25 Byte),
    PROFESION                  VARCHAR2(18 Byte),
    IDIOMA_CORREO              VARCHAR2(4 Byte),
    ES_MAL_DEUDOR              VARCHAR2(1 Byte),
    CONYUGUE                   VARCHAR2(15 Byte),
    NACIONALIDAD               VARCHAR2(20 Byte),
    COD_ESTADO                 VARCHAR2(3 Byte),
    ESTATAL                    VARCHAR2(1 Byte),
    EMAIL_USUARIO              VARCHAR2(116 Byte),
    EMAIL_SERVIDOR             VARCHAR2(20 Byte),
    NIVEL_ESTUDIOS             VARCHAR2(5 Byte),
    TIPO_VIVIENDA              VARCHAR2(5 Byte),
    NUM_HIJOS                  NUMBER(3),
    NUM_DEPENDIENTES           NUMBER(3),
    ES_RESIDENTE               VARCHAR2(1 Byte),
    TIEMPO_VIVIEN_ACT          NUMBER(4),
    EVAL_REF_BANCARIA          VARCHAR2(1 Byte),
    EVAL_REF_TARJETAS          VARCHAR2(1 Byte),
    EVAL_REF_LABORAL           VARCHAR2(1 Byte),
    TOTAL_INGRESOS             NUMBER(18,2) NOT NULL,
    COD_PAIS                   VARCHAR2(5 Byte),
    INCLUIDO_POR               VARCHAR2(10 Byte),
    FEC_INCLUSION              DATE,
    MODIFICADO_POR             VARCHAR2(10 Byte),
    FEC_MODIFICACION           DATE,
    SCORING                    VARCHAR2(6 Byte),
    ACTIVIDAD                  VARCHAR2(200 Byte),
    RANGO_INGRESOS             NUMBER(2),
    CASADA_APELLIDO            VARCHAR2(15 Byte),
    ES_FUNCIONARIO             VARCHAR2(1 Byte),
    ES_PEPS                    VARCHAR2(1 Byte),
    COD_ACTIVIDAD              VARCHAR2(6 Byte),
    COD_SUBACTIVIDAD           NUMBER, -- No precision specified, assuming generic NUMBER
    TIPO_PERSONA               VARCHAR2(2 Byte),
    TIPO_CLIENTE               NUMBER(18), -- No precision specified, assuming generic NUMBER(18) based on context usually seen
    COD_PAIS_PADRE             VARCHAR2(5 Byte),
    COD_PAIS_MADRE             VARCHAR2(5 Byte),
    COD_PAIS_CONYUGUE          VARCHAR2(5 Byte),
    MAS_180_DIAS_EEUU          VARCHAR2(5 Byte),
    COD_FINALIDAD              VARCHAR2(3 Byte),
    PESO                       NUMBER(3),
    ESTATURA                   VARCHAR2(5 Byte),
    ACTIVIDAD_POLIZAH          VARCHAR2(1 Byte),
    DEPORTE_POLIZAH            VARCHAR2(5 Byte),
    PESO_POLIZAH               NUMBER(3),
    ESTATURA_POLIZAH           VARCHAR2(5 Byte),
    APELLIDO_CASADA            VARCHAR2(25 Byte),
    TERCER_NOMBRE              VARCHAR2(25 Byte),
    SOC_CONYUGAL               VARCHAR2(1 Byte) DEFAULT 'S',
    IND_FALLECIMIENTO          VARCHAR2(1 Byte),
    FEC_FALLECIMIENTO          DATE,
    GPO_RIESGO                 VARCHAR2(5 Byte),
    NUM_EMPLEADOS              NUMBER(10),
    VENTAS_INGRESOS            NUMBER(22,2),
    CP_TOTAL_ACTIVO            NUMBER(22,2),
    IND_CLTE_VIP               VARCHAR2(1 Byte),
    TIPO_GEN_DIVISAS           VARCHAR2(2 Byte),
    OCUPACION_CLASIF_NAC       VARCHAR2(5 Byte),
    CONSTRAINT PK_PER_FISICA PRIMARY KEY (COD_PER_FISICA)
);