CREATE TABLE PR_BITACORA_REPRESTAMO (
    CODIGO_EMPRESA        NUMBER(4) NOT NULL,
    ID_REPRESTAMO         NUMBER(14) NOT NULL,
    ID_BITACORA           NUMBER(10) NOT NULL,
    FECHA_BITACORA        DATE NOT NULL,
    CODIGO_ESTADO         VARCHAR2(5 Byte) NOT NULL,
    STEP                  VARCHAR2(2 Byte),
    OBSERVACIONES         VARCHAR2(500 Byte),
    CANAL                 VARCHAR2(2 Byte),
    ADICIONADO_POR        VARCHAR2(30 Byte) NOT NULL,
    FECHA_ADICION         DATE NOT NULL,
    MODIFICADO_POR        VARCHAR2(30 Byte),
    FECHA_MODIFICACION    DATE,
    CONSTRAINT PK_PR_BITACORA_REPRESTAMO PRIMARY KEY (CODIGO_EMPRESA, ID_REPRESTAMO, ID_BITACORA)
);