CREATE TABLE PR_CANALES_REPRESTAMO (
    CODIGO_EMPRESA      NUMBER(4) NOT NULL,
    ID_REPRESTAMO       NUMBER(14) NOT NULL,
    CANAL               VARCHAR2(2 BYTE) NOT NULL,
    VALOR               VARCHAR2(250 BYTE) NOT NULL,
    ADICIONADO_POR      VARCHAR2(30 BYTE) NOT NULL,
    FECHA_ADICION       DATE NOT NULL,
    MODIFICADO_POR      VARCHAR2(30 BYTE), -- Permite valores NULL
    FECHA_MODIFICACION  DATE,              -- Permite valores NULL
    CONSTRAINT PK_PR_CANALES_REPRESTAMO PRIMARY KEY (CODIGO_EMPRESA, ID_REPRESTAMO, CANAL)
);