-- Validacion auxiliar pagina 134 - productos digitales de cuentas.
-- Objetivo: confirmar existencia, cantidad y saldo por producto del universo 210/211.

SELECT
    ce.COD_PRODUCTO,
    NVL(prod.DESCRIPCION, 'PRODUCTO ' || ce.COD_PRODUCTO) AS NOMBRE_PRODUCTO,
    COUNT(*) AS CANTIDAD_CUENTAS,
    SUM(CASE WHEN ce.FEC_CANCELAC IS NULL THEN 1 ELSE 0 END) AS CANTIDAD_ACTIVAS,
    SUM(CASE WHEN ce.FEC_CANCELAC IS NOT NULL THEN 1 ELSE 0 END) AS CANTIDAD_CANCELADAS,
    NVL(SUM(ce.SAL_TOTAL_CTA), 0) AS SALDO_TOTAL
FROM CC.CUENTA_EFECTIVO ce
LEFT JOIN PA.PRODUCTOS prod
    ON prod.COD_PRODUCTO = ce.COD_PRODUCTO
   AND prod.COD_EMPRESA = ce.COD_EMPRESA
WHERE ce.COD_PRODUCTO IN ('210', '211')
GROUP BY
    ce.COD_PRODUCTO,
    NVL(prod.DESCRIPCION, 'PRODUCTO ' || ce.COD_PRODUCTO)
ORDER BY
    ce.COD_PRODUCTO;
