PROCEDURE PVALIDA_WORLD_COMPLIANCE IS CURSOR CARGAR_WORLD_COMPLIANCE IS
SELECT R.ID_REPRESTAMO,
    R.NO_CREDITO,
    PF.PRIMER_APELLIDO,
    PF.PRIMER_NOMBRE,
    b.NUMERO_IDENTIFICACION -- S.IDENTIFICACION
FROM PR_REPRESTAMOS R
    LEFT JOIN PERSONAS_FISICAS PF ON PF.COD_PER_FISICA = R.CODIGO_CLIENTE
    LEFT JOIN PR_SOLICITUD_REPRESTAMO S ON S.ID_REPRESTAMO = R.ID_REPRESTAMO
    LEFT JOIN CLIENTES_B2000 B ON B.CODIGO_CLIENTE = R.CODIGO_CLIENTE
WHERE R.ESTADO = 'RE'
    AND WORLD_COMPLIANCE IS NULL
    AND ROWNUM <= TO_NUMBER(
        PR_PKG_REPRESTAMOS.f_obt_parametro_Represtamo('LOTE_PROCESO_WORLD_COMPLIANCE')
    );
--AND NOT EXISTS( SELECT CODIGO_ESTADO FROM PR_BITACORA_REPRESTAMO WHERE CODIGO_ESTADO = 'CLS' AND ID_REPRESTAMO = R.ID_REPRESTAMO );
CURSOR CUR_UPDATE_CREADOS IS
SELECT A.ROWID ID,
    A.ID_REPRESTAMO,
    A.CODIGO_CLIENTE,
    A.ESTADO,
    S.WORLD_COMPLIANCE
FROM PR.PR_REPRESTAMOS A
    LEFT JOIN PR_SOLICITUD_REPRESTAMO S ON S.ID_REPRESTAMO = A.ID_REPRESTAMO
WHERE A.ESTADO = 'RE';
v_response CLOB;
vUrlAPI VARCHAR2 (256);
vKey RAW (2000);
vRutaWallet VARCHAR2 (1000);
vPassWallet VARCHAR2 (200);
vHigherPercent NUMBER;
Vlote_WORLD_COMPLIANCE NUMBER(10);
vTotal_Carga NUMBER(10);
vCantidad_Procesar NUMBER(10);
vRespuesta VARCHAR2(200);
vPrimerNombre VARCHAR2(200);
vSegundoNombre VARCHAR2(200);
vPrimerApellido VARCHAR2(200);
vSegundoApellido VARCHAR2(200);
VALOR NUMBER;
PMENSAJE VARCHAR2(500);
--Defino la variable para capturar si existe un detalle
--idCabeceraDet NUMBER;
BEGIN --VERIFICAR SI EXISTE EL REGISTRO
/*BEGIN
 SELECT ID_APLICACION_PASO_DET
 INTO idCabeceraDet
 FROM PR.PR_APLICACION_PASO_DET
 WHERE ID_APLICACION_PASO_DET = pIDAPLICACION;
 
 DBMS_OUTPUT.PUT_LINE ( 'qUE PASO AQUI = ' || idCabeceraDet );
 
 EXCEPTION
 WHEN NO_DATA_FOUND THEN
 --SI NO SE ENCUENTRA NINGUN REGISTRO CREARA UNO NUEVO
 PR.PR_PKG_TRAZABILIDAD.PR_CREAR_BITACORA_DET ( 'RD_CARGA_PRECALIFICACION', 'RD_CARGA.OBT_WORLD_COMPLIANCE', 'INICIADO', pMensaje ); 
 
 
 --OBTENER EL ID DEL NUEVO REGISTRO
 SELECT PR.SEQ_PR_APLICACION_PASO_DET.CURRVAL
 INTO idCabeceraDet
 FROM DUAL;  
 
 DBMS_OUTPUT.PUT_LINE ( 'idCabeceraDet = ' || idCabeceraDet );
 
 --ACTUALIZAR EL PARAMETRO DE ENTRADA CON EL NUEVO ID
 pIDAPLICACION := idCabeceraDet;
 
 DBMS_OUTPUT.PUT_LINE ( 'pIDAPLICACION PARA EL OTRO PASO = ' || pIDAPLICACION );
 DBMS_OUTPUT.PUT_LINE ('SE CREO EL REGISTRO CON ID: ' || idCabeceraDet);
 
 WHEN OTHERS THEN
 DBMS_OUTPUT.PUT_LINE('Error inesperado al verificar o crear el registro: ' || SQLERRM);
 RETURN;                     
 END;
 
 --ACTUALIZAR BITACORA SI YA EXISTE
 IF idCabeceraDet IS NOT NULL THEN
 PR.PR_PKG_TRAZABILIDAD.PR_ACTUALIZAR_BITACORA_DET (pIDAPLICACION, 'ENPROCESO', 30, 'EN PROCESO', pMensaje );
 END IF;*/
Vlote_WORLD_COMPLIANCE := TO_NUMBER(
    PR_PKG_REPRESTAMOS.f_obt_parametro_Represtamo('LOTE_PROCESO_WORLD_COMPLIANCE')
);
BEGIN
SELECT COUNT(*) INTO vTotal_Carga
FROM PR.PR_REPRESTAMOS A
WHERE A.ESTADO = 'RE';
EXCEPTION
WHEN NO_DATA_FOUND THEN vTotal_Carga := 0;
END;
--Cambio el estado del detalle de la bitacora
--PR.PR_PKG_TRAZABILIDAD.PR_ACTUALIZAR_BITACORA_DET (pIDAPLICACION, 'ENPROCESO', 60, 'EN PROCESO', pMensaje ); 
vCantidad_Procesar := round(vTotal_Carga / Vlote_WORLD_COMPLIANCE) + 1;
FOR i IN 1..vCantidad_Procesar LOOP FOR A IN CARGAR_WORLD_COMPLIANCE LOOP BEGIN PR.PR_PKG_REPRESTAMOS.OBT_WORLD_COMPLIANCE (
    REPLACE(A.NUMERO_IDENTIFICACION, '-'),
    UTL_URL.ESCAPE(a.PRIMER_NOMBRE),
    UTL_URL.ESCAPE(a.PRIMER_APELLIDO),
    VALOR,
    PMENSAJE
);
IF VALOR IS NULL THEN VALOR := 0;
END IF;
DBMS_OUTPUT.PUT_LINE (
    'WORLD_COMPLIANCE ' || VALOR || ' id ' || a.id_represtamo
);
UPDATE PR.PR_SOLICITUD_REPRESTAMO
SET WORLD_COMPLIANCE = VALOR
WHERE ID_REPRESTAMO = A.ID_REPRESTAMO;
COMMIT;
EXCEPTION
WHEN OTHERS THEN
DECLARE vIdError PLS_INTEGER := 0;
BEGIN setError(
    pProgramUnit => 'OBT_WORLD_COMPLIANCE',
    pPieceCodeName => NULL,
    pErrorDescription => SQLERRM,
    pErrorTrace => DBMS_UTILITY.FORMAT_ERROR_BACKTRACE,
    pEmailNotification => NULL,
    pParamList => IA.LOGGER.vPARAMLIST,
    pOutputLogger => FALSE,
    pExecutionTime => NULL,
    pIdError => vIdError
);
END;
END;
--DBMS_OUTPUT.PUT_LINE ( 'WORLD_COMPLIANCE ' || VALOR || ' id ' ||a.id_represtamo );
--DBMS_OUTPUT.PUT_LINE ( 'v_response = ' || v_response );
--DBMS_OUTPUT.PUT_LINE ('higherPercent = ' || VALOR);
END LOOP;
END LOOP;
--Cambio el estado del detalle de la bitacora
--PR.PR_PKG_TRAZABILIDAD.PR_ACTUALIZAR_BITACORA_DET (pIDAPLICACION, 'ENPROCESO', 90, 'EN PROCESO', pMensaje ); 
FOR A IN CUR_UPDATE_CREADOS LOOP --DBMS_OUTPUT.PUT_LINE ( 'a.WORLD_COMPLIANCE = ' || a.WORLD_COMPLIANCE );
--DBMS_OUTPUT.PUT_LINE ( 'a.ID = ' || a.ID_REPRESTAMO );
IF NVL(a.WORLD_COMPLIANCE, 0) > TO_NUMBER(
    PR_PKG_REPRESTAMOS.f_obt_parametro_Represtamo('WORLD_COMPLIANCE')
) THEN
UPDATE PR.PR_REPRESTAMOS
SET ESTADO = 'RXW'
WHERE ID_REPRESTAMO = A.ID_REPRESTAMO;
PR.PR_PKG_REPRESTAMOS.P_Generar_Bitacora(
    A.ID_REPRESTAMO,
    NULL,
    'RXW',
    NULL,
    'Credito cancelado por World Compliance',
    USER
);
COMMIT;
END IF;
END LOOP;
--ACTUALIZO LA BITACORA
--PR.PR_PKG_TRAZABILIDAD.PR_ACTUALIZAR_BITACORA_DET (pIDAPLICACION, 'ENPROCESO', 100, 'SE ACTUALIZO', pMensaje );
--FINALIZO EL DETALLE DE LA BITACORA
--PR.PR_PKG_TRAZABILIDAD.PR_FINALIZAR_BITACORA_DET (pIDAPLICACION, 'FINALIZADO', 'SE FINALIZO', pMensaje ); 
EXCEPTION
WHEN OTHERS THEN
DECLARE vIdError PLS_INTEGER := 0;
BEGIN pMensaje := 'ERROR CON EL STORE PROCEDURE PVALIDA_WORLD_COMPLIANCE';
setError(
    pProgramUnit => 'OBT_WORLD_COMPLIANCE',
    pPieceCodeName => NULL,
    pErrorDescription => SQLERRM,
    pErrorTrace => DBMS_UTILITY.FORMAT_ERROR_BACKTRACE,
    pEmailNotification => NULL,
    pParamList => IA.LOGGER.vPARAMLIST,
    pOutputLogger => FALSE,
    pExecutionTime => NULL,
    pIdError => vIdError
);
--Capturo el error del detalle
--PR.PR_PKG_TRAZABILIDAD.PR_ACTUALIZAR_BITACORA_DET (pIDAPLICACION, 'ERROR', 100, SQLERRM,pMensaje  );
END;
END PVALIDA_WORLD_COMPLIANCE;