SELECT R.FECHA_PROCESO,
       R.ID_REPRESTAMO,
       R.CODIGO_CLIENTE,
       S.IDENTIFICACION,
       PA.OBT_NOMBRE_PERSONA(R.CODIGO_CLIENTE) NOMBRES,
       A.VALOR,
       R.NO_CREDITO,
       NVL(C.ESTADO,H.ESTADO) AS ESTADO_CREDITO,
       R.DIAS_ATRASO,
       R.CODIGO_PRECALIFICACION,
       R.MTO_PREAPROBADO,
      (TC.TIPO_CREDITO || ' - ' || TC.DESCRIPCION) AS DESCRIPCON,
       PR.PR_PKG_REPRESTAMOS.F_OBT_DESCRIPCION_ESTADO(R.ESTADO) ESTADO,
       R.XCORE_GLOBAL XCORE_ADEMI,
       PR.PR_PKG_REPRESTAMOS.F_OBTIENE_DESC_BITACORA(PIDREPRESTAMO => R.ID_REPRESTAMO, PESTADO => 'CLS')||' '||
       PR.PR_PKG_REPRESTAMOS.F_OBTIENE_DESC_BITACORA(PIDREPRESTAMO => R.ID_REPRESTAMO, PESTADO => 'RSB')||' '||
       PR.PR_PKG_REPRESTAMOS.F_OBTIENE_DESC_BITACORA(PIDREPRESTAMO => R.ID_REPRESTAMO, PESTADO => 'RCS' )CLASIFICACION_SIB,
       NVL(C.CODIGO_AGENCIA,H.CODIGO_AGENCIA) AS CODIGO_AGENCIA,
       AG.DESCRIPCION NOMBRE_AGENCIA,
       PA.OBT_NOMBRE_EMPLEADO(NVL(C.codigo_empresa,H.codigo_empresa), NVL(C.CODIGO_EJECUTIVO,H.CODIGO_EJECUTIVO)) NOMBRE_OFICIAL,
       NVL(C.codigo_empresa,H.codigo_empresa) CODIGO_SUCURSAL,
       NVL(C.CODIGO_EJECUTIVO,H.CODIGO_EJECUTIVO) CODIGO_OFICIAL,
       AG.COD_ZONA,
       PA.OBT_DESC_ZONA(1,AG.COD_ZONA) ZONA,
       R.CODIGO_EMPRESA,
       R.FECHA_CORTE,
       R.PIN,
       R.INTENTOS_PIN,
       R.INTENTOS_IDENTIFICACION,
       R.IND_SOLICITA_AYUDA,
       R.MTO_CREDITO_ACTUAL,
       R.OBSERVACIONES,
       R.ADICIONADO_POR,
       R.FECHA_ADICION,
       R.MODIFICADO_POR,
       R.FECHA_MODIFICACION,
       R.XCORE_GLOBAL,
       CASE
        WHEN R.ID_CARGA_DIRIGIDA IS NOT NULL THEN 'Carga Dirigida'
        WHEN R.ID_REPRE_CAMPANA_ESPECIALES IS NOT NULL THEN 'Campañas Especiales'
        ELSE ' Represtamo Digital'
    END AS TIPO_PRESTAMO,
    CASE
        WHEN S.EMAIL IS NULL THEN 'No'
        ELSE 'Si'
    END AS CORREO_ELECTRONICO,
       '<a title="Origen Fuente de Datos" href="'||APEX_PAGE.GET_URL(p_page => 79, p_items => 'P79_ID_REPRESTAMO', p_values => R.ID_REPRESTAMO) ||'"><span aria-hidden="true" class="fa fa-table"></span> </a>' AS ORIGEN
  FROM PR_REPRESTAMOS R
  JOIN PR_CARGA_DIRECCIONADA CD ON CD.NO_CREDITO=R.NO_CREDITO AND CD.ESTADO IN('T','F') AND R.FECHA_ADICION>=CD.FECHA_ADICION
  LEFT JOIN PR_SOLICITUD_REPRESTAMO S ON S.ID_REPRESTAMO = R.ID_REPRESTAMO
  LEFT JOIN PR_CREDITOS C ON C.NO_CREDITO=R.NO_CREDITO
  LEFT JOIN PR_CREDITOS_HI H ON H.NO_CREDITO=R.NO_CREDITO
  LEFT JOIN PA.AGENCIA AG ON AG.COD_EMPRESA = R.CODIGO_EMPRESA AND AG.COD_AGENCIA = NVL(C.CODIGO_AGENCIA,H.CODIGO_AGENCIA)
  LEFT JOIN PR.PR_TIPO_CREDITO TC ON TC.TIPO_CREDITO = NVL(S.TIPO_CREDITO,NVL(C.TIPO_CREDITO,H.TIPO_CREDITO))
  LEFT JOIN PR.PR_CANALES_REPRESTAMO A  ON A.ID_REPRESTAMO = R.ID_REPRESTAMO AND A.CANAL = 1
  WHERE CD.ID_CARGA_DIRECCIONADA IS NOT NULL
