SELECT
    R.FECHA_PROCESO,
    R.ID_REPRESTAMO,
    R.CODIGO_CLIENTE,
    PA.OBT_NOMBRE_PERSONA(R.CODIGO_CLIENTE) AS NOMBRES,
    TRUNC(MONTHS_BETWEEN(SYSDATE, PF.FEC_NACIMIENTO) / 12) AS EDAD,
    S.IDENTIFICACION,
    A.VALOR,
    R.NO_CREDITO,
    NVL(C.ESTADO, H.ESTADO) AS ESTADO_CREDITO,
    R.DIAS_ATRASO,
    R.CODIGO_PRECALIFICACION,
    R.MTO_PREAPROBADO,
    (TC.TIPO_CREDITO || ' - ' || TC.DESCRIPCION) AS DESCRIPCON,
    PR.PR_PKG_REPRESTAMOS.F_OBT_DESCRIPCION_ESTADO(R.ESTADO) AS ESTADO,
    R.XCORE_GLOBAL AS XCORE_ADEMI,
    PR.PR_PKG_REPRESTAMOS.F_OBTIENE_DESC_BITACORA(PIDREPRESTAMO => R.ID_REPRESTAMO, PESTADO => 'CLS') || ' ' ||
    PR.PR_PKG_REPRESTAMOS.F_OBTIENE_DESC_BITACORA(PIDREPRESTAMO => R.ID_REPRESTAMO, PESTADO => 'RSB') || ' ' ||
    PR.PR_PKG_REPRESTAMOS.F_OBTIENE_DESC_BITACORA(PIDREPRESTAMO => R.ID_REPRESTAMO, PESTADO => 'RCS') AS CLASIFICACION_SIB,
    NVL(C.CODIGO_AGENCIA, H.CODIGO_AGENCIA) AS CODIGO_AGENCIA,
    AG.DESCRIPCION AS NOMBRE_AGENCIA,
    PA.OBT_NOMBRE_EMPLEADO(NVL(C.codigo_empresa, H.codigo_empresa), NVL(C.CODIGO_EJECUTIVO, H.CODIGO_EJECUTIVO)) AS NOMBRE_OFICIAL,
    NVL(C.CODIGO_EJECUTIVO, H.CODIGO_EJECUTIVO) AS CODIGO_OFICIAL,
    AG.COD_ZONA,
    PA.OBT_DESC_ZONA(1, AG.COD_ZONA) AS ZONA,
    R.CODIGO_EMPRESA,
    R.FECHA_CORTE,
    R.PIN,
    R.INTENTOS_PIN,
    R.INTENTOS_IDENTIFICACION,
    R.IND_SOLICITA_AYUDA,
    R.MTO_CREDITO_ACTUAL,
    R.OBSERVACIONES,
    R.ADICIONADO_POR,
    R.FECHA_ADICION,
    R.MODIFICADO_POR,
    R.FECHA_MODIFICACION,
    R.XCORE_GLOBAL,
    (
        SELECT
            COUNT(*)
        FROM
            PR.PR_REPRESTAMOS
        WHERE
            CODIGO_CLIENTE = R.CODIGO_CLIENTE
    ) AS REPRESTAMOS_CREADOS,
    CASE
        WHEN R.ID_CARGA_DIRIGIDA IS NOT NULL THEN 'Carga Dirigida'
        WHEN R.ID_REPRE_CAMPANA_ESPECIALES IS NOT NULL THEN 'Campañas Especiales'
        ELSE ' Represtamo Digital'
    END AS TIPO_PRESTAMO,
    CASE
        WHEN S.EMAIL IS NULL THEN 'No'
        ELSE 'Si'
    END AS CORREO_ELECTRONICO,
    CASE
        WHEN R.ES_FIADOR = 'N' OR R.ES_FIADOR IS NULL THEN 'No'
        ELSE 'Si'
    END AS ORIGEN_FIADOR
FROM
    PR_REPRESTAMOS R
LEFT JOIN PR_SOLICITUD_REPRESTAMO S
    ON S.ID_REPRESTAMO = R.ID_REPRESTAMO
LEFT JOIN PR_CREDITOS C
    ON C.NO_CREDITO = R.NO_CREDITO AND C.CODIGO_EMPRESA = R.CODIGO_EMPRESA
LEFT JOIN PR_CREDITOS_HI H
    ON H.NO_CREDITO = R.NO_CREDITO AND H.CODIGO_EMPRESA = R.CODIGO_EMPRESA
LEFT JOIN PA.AGENCIA AG
    ON AG.COD_EMPRESA = R.CODIGO_EMPRESA AND AG.COD_AGENCIA = NVL(C.CODIGO_AGENCIA, H.CODIGO_AGENCIA)
LEFT JOIN PR.PR_TIPO_CREDITO TC
    ON TC.CODIGO_EMPRESA = R.CODIGO_EMPRESA AND TC.TIPO_CREDITO = NVL(S.TIPO_CREDITO, NVL(C.TIPO_CREDITO, H.TIPO_CREDITO))
LEFT JOIN PR.PR_CANALES_REPRESTAMO A
    ON A.ID_REPRESTAMO = R.ID_REPRESTAMO AND A.CANAL = 1
LEFT JOIN PA.PERSONAS PER
    ON PER.COD_PERSONA = TO_CHAR(R.CODIGO_CLIENTE)
LEFT JOIN PA.PERSONAS_FISICAS PF
    ON PF.COD_PER_FISICA = PER.COD_PER_FISICA
WHERE
    NOT EXISTS (
        SELECT
            1
        FROM
            PR_CARGA_DIRECCIONADA CD
        WHERE
            CD.NO_CREDITO = R.NO_CREDITO
            AND CD.ESTADO = 'F'
            AND TRUNC(CD.FECHA_ADICION) = TRUNC(R.FECHA_ADICION)
    );
