
  CREATE TABLE "IA"."LOG_ERROR" 
   (	"IDERROR" NUMBER NOT NULL ENABLE, 
	"ERRORDATE" DATE NOT NULL ENABLE, 
	"OWNER" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"PACKAGENAME" VARCHAR2(60 BYTE), 
	"PROGRAMUNIT" VARCHAR2(60 BYTE) NOT NULL ENABLE, 
	"PIECECODENAME" VARCHAR2(60 BYTE), 
	"ERRORDESCRIPTION" VARCHAR2(4000 BYTE) NOT NULL ENABLE, 
	"USERNAME" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"HOSTNAME" VARCHAR2(150 BYTE), 
	"PROGRAMEXECUTOR" VARCHAR2(150 BYTE), 
	"EXECUTIONTIME" NUMBER, 
	"EMAILNOTIFICATION" VARCHAR2(150 BYTE), 
	"STATUSNOTIFICATION" VARCHAR2(1 BYTE), 
	"ERRORTRACE" CLOB, 
	 CONSTRAINT "PK_LOG_ERROR" PRIMARY KEY ("IDERROR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IA_DAT"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IA_DAT" 
 LOB ("ERRORTRACE") STORE AS BASICFILE (
  TABLESPACE "IA_DAT" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "IA"."LOG_ERROR"."IDERROR" IS 'PK Log Error';
   COMMENT ON COLUMN "IA"."LOG_ERROR"."ERRORDATE" IS 'Fecha del Error';
   COMMENT ON COLUMN "IA"."LOG_ERROR"."OWNER" IS 'Schema dueño del programa';
   COMMENT ON COLUMN "IA"."LOG_ERROR"."PACKAGENAME" IS 'Nombre del Paquete de Base de datos';
   COMMENT ON COLUMN "IA"."LOG_ERROR"."PROGRAMUNIT" IS 'Nombre del procedimiento o funcion ';
   COMMENT ON COLUMN "IA"."LOG_ERROR"."PIECECODENAME" IS 'Identificador de Parte del codigo';
   COMMENT ON COLUMN "IA"."LOG_ERROR"."ERRORDESCRIPTION" IS 'Mensaje del error resumido';
   COMMENT ON COLUMN "IA"."LOG_ERROR"."USERNAME" IS 'Usuario que provoca el error';
   COMMENT ON COLUMN "IA"."LOG_ERROR"."HOSTNAME" IS 'Nombre del equipo que provoca el error';
   COMMENT ON COLUMN "IA"."LOG_ERROR"."PROGRAMEXECUTOR" IS 'Nombre del programa que provoca el error';
   COMMENT ON COLUMN "IA"."LOG_ERROR"."EXECUTIONTIME" IS 'Tiempo de ejecucion del programa';
   COMMENT ON COLUMN "IA"."LOG_ERROR"."EMAILNOTIFICATION" IS 'Email de Notificacion del error';
   COMMENT ON COLUMN "IA"."LOG_ERROR"."STATUSNOTIFICATION" IS 'Estatus de la notificacion del email';
   COMMENT ON COLUMN "IA"."LOG_ERROR"."ERRORTRACE" IS 'Rastreo del error por completo';

  CREATE INDEX "IA"."IDX_LOG_ERROR" ON "IA"."LOG_ERROR" ("PIECECODENAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IA_DAT" ;

  CREATE INDEX "IA"."IDX_LOG_ERROR_PACKAGE" ON "IA"."LOG_ERROR" ("OWNER", "PACKAGENAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 MAXSIZE UNLIMITED
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IA_IDX" ;

  CREATE INDEX "IA"."IDX_LOG_ERROR_PIECE" ON "IA"."LOG_ERROR" ("PIECECODENAME", "ERRORDATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 MAXSIZE UNLIMITED
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IA_IDX" ;

  CREATE INDEX "IA"."INDX_LOG_ERROR" ON "IA"."LOG_ERROR" ("ERRORDATE", "OWNER", "PACKAGENAME", "PROGRAMUNIT", "PIECECODENAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 MAXSIZE UNLIMITED
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IA_IDX" ;


  GRANT ALTER ON "IA"."LOG_ERROR" TO PUBLIC;
  GRANT DELETE ON "IA"."LOG_ERROR" TO PUBLIC;
  GRANT INDEX ON "IA"."LOG_ERROR" TO PUBLIC;
  GRANT INSERT ON "IA"."LOG_ERROR" TO PUBLIC;
  GRANT SELECT ON "IA"."LOG_ERROR" TO PUBLIC;
  GRANT UPDATE ON "IA"."LOG_ERROR" TO PUBLIC;
  GRANT REFERENCES ON "IA"."LOG_ERROR" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "IA"."LOG_ERROR" TO PUBLIC;
  GRANT QUERY REWRITE ON "IA"."LOG_ERROR" TO PUBLIC;
  GRANT DEBUG ON "IA"."LOG_ERROR" TO PUBLIC;
  GRANT FLASHBACK ON "IA"."LOG_ERROR" TO PUBLIC;
