WITH LatestBitacora AS (
    SELECT
        B.ID_REPRESTAMO,
        B.CODIGO_ESTADO,
        B.OBSERVACIONES,
        B.ADICIONADO_POR,
        B.FECHA_ADICION,
        ROW_NUMBER() OVER(PARTITION BY B.ID_REPRESTAMO ORDER BY B.ID_BITACORA DESC, B.FECHA_ADICION DESC) AS rn
    FROM
        PR.PR_BITACORA_REPRESTAMO B
), HasCryStatus AS (
    SELECT DISTINCT
        ID_REPRESTAMO
    FROM
        PR.PR_BITACORA_REPRESTAMO
    WHERE
        CODIGO_ESTADO = 'CRY'
)
SELECT
    R.FECHA_PROCESO,
    S.ID_REPRESTAMO,
    R.CODIGO_CLIENTE,
    S.NOMBRES || ' ' || S.APELLIDOS AS Cliente,
    S.IDENTIFICACION,
    A_CANAL.VALOR AS Celular,
    R.NO_CREDITO AS "Credito_Anterior",
    R.MTO_PREAPROBADO,
    (TC.TIPO_CREDITO || ' - ' || TC.DESCRIPCION) AS "Tipo_Credito",
    PR.PR_PKG_REPRESTAMOS.F_OBT_DESCRIPCION_ESTADO(LB.CODIGO_ESTADO) AS Estado,
    C.F_PRIMER_DESEMBOLSO AS "Fecha_Desembolso",
    C.MONTO_DESEMBOLSADO,
    CASE
        WHEN R.ID_CARGA_DIRIGIDA IS NOT NULL THEN 'Carga Dirigida'
        WHEN R.ID_REPRE_CAMPANA_ESPECIALES IS NOT NULL THEN 'Campañas Especiales'
        ELSE 'Represtamo Digital'
    END AS "Tipo_Prestamo",
    CASE
        WHEN S.EMAIL IS NULL THEN 'No'
        ELSE 'Si'
    END AS "Correo_Electronico",
    CASE
        WHEN LB.CODIGO_ESTADO = 'CRD' THEN
            CASE
                WHEN HCS.ID_REPRESTAMO IS NOT NULL THEN 'Digital (con firma)'
                ELSE 'Sucursal (tradicional)'
            END
        ELSE NULL
    END AS "Canal_Desembolso_Determinado",
    NVL(C.CODIGO_AGENCIA, H.CODIGO_AGENCIA) AS "Codigo_Sucursal",
    AG.DESCRIPCION AS "Oficina",
    PA.OBT_DESC_ZONA(1, AG.COD_ZONA) AS "Zona",
    NVL(C.CODIGO_EJECUTIVO, H.CODIGO_EJECUTIVO) AS "Codigo_Oficial",
    PA.OBT_NOMBRE_EMPLEADO(
        NVL(C.CODIGO_EMPRESA, H.CODIGO_EMPRESA),
        NVL(C.CODIGO_EJECUTIVO, H.CODIGO_EJECUTIVO)
    ) AS "Oficial"
FROM
    PA.EMPLEADOS P
JOIN PA.AGENCIA A_EMP
    ON TO_NUMBER(P.COD_EMPRESA) = A_EMP.COD_EMPRESA AND TO_NUMBER(P.COD_AGENCIA_LABORA) = A_EMP.COD_AGENCIA
JOIN PR.PR_SOLICITUD_REPRESTAMO S
    ON TO_NUMBER(P.COD_EMPRESA) = S.CODIGO_EMPRESA AND TO_NUMBER(P.COD_AGENCIA_LABORA) = S.CODIGO_AGENCIA
JOIN PR.PR_REPRESTAMOS R
    ON S.ID_REPRESTAMO = R.ID_REPRESTAMO AND S.CODIGO_EMPRESA = R.CODIGO_EMPRESA
JOIN LatestBitacora LB
    ON S.ID_REPRESTAMO = LB.ID_REPRESTAMO AND LB.rn = 1
LEFT JOIN HasCryStatus HCS
    ON S.ID_REPRESTAMO = HCS.ID_REPRESTAMO
LEFT JOIN PR.PR_CREDITOS C
    ON R.NO_CREDITO = C.NO_CREDITO AND R.CODIGO_EMPRESA = C.CODIGO_EMPRESA
LEFT JOIN PR.PR_CREDITOS_HI H
    ON R.NO_CREDITO = H.NO_CREDITO AND R.CODIGO_EMPRESA = H.CODIGO_EMPRESA
LEFT JOIN PA.AGENCIA AG
    ON AG.COD_EMPRESA = R.CODIGO_EMPRESA AND AG.COD_AGENCIA = NVL(C.CODIGO_AGENCIA, H.CODIGO_AGENCIA)
LEFT JOIN PR.PR_TIPO_CREDITO TC
    ON TC.TIPO_CREDITO = NVL(S.TIPO_CREDITO, NVL(C.TIPO_CREDITO, H.TIPO_CREDITO)) AND TC.CODIGO_EMPRESA = R.CODIGO_EMPRESA
LEFT JOIN PR.PR_CANALES_REPRESTAMO A_CANAL
    ON R.ID_REPRESTAMO = A_CANAL.ID_REPRESTAMO AND A_CANAL.CANAL = 1
WHERE
    -- SUBSTR(P.EMAIL1, 1, INSTR(P.EMAIL1, '@') - 1) = V('APP_USER')
    SUBSTR(P.EMAIL1, 1, INSTR(P.EMAIL1, '@') - 1) = 'MAMATOS'
    AND P.ID_EMPLEADO = A_EMP.GERENTE
    AND P.ESTA_ACTIVO = 'S'
    AND NOT EXISTS (
        SELECT
            1
        FROM
            PR_CARGA_DIRECCIONADA CD
        WHERE
            CD.NO_CREDITO = R.NO_CREDITO
            AND CD.ESTADO = 'F'
            AND TRUNC(CD.FECHA_ADICION) = TRUNC(R.FECHA_ADICION)
    )
ORDER BY
    LB.FECHA_ADICION DESC,
    S.ID_REPRESTAMO DESC;