WITH LatestBitacora AS (
    SELECT
        B.ID_REPRESTAMO,
        B.CODIGO_ESTADO,
        B.OBSERVACIONES,
        B.ADICIONADO_POR,
        B.FECHA_ADICION,
        ROW_NUMBER() OVER(PARTITION BY B.ID_REPRESTAMO ORDER BY B.ID_BITACORA DESC, B.FECHA_ADICION DESC) as rn
    FROM PR.PR_BITACORA_REPRESTAMO B
),
HasCryStatus AS (
    SELECT DISTINCT ID_REPRESTAMO
    FROM PR.PR_BITACORA_REPRESTAMO
    WHERE CODIGO_ESTADO = 'CRY'
)
SELECT
    S.ID_REPRESTAMO,
    S.NOMBRES || ' ' || S.APELLIDOS AS Cliente,
    S.IDENTIFICACION,
    S.TELEFONO_CELULAR,
    LB.ADICIONADO_POR AS "Atendido Por",
    PR.PR_PKG_REPRESTAMOS.F_Obt_Descripcion_Estado(LB.CODIGO_ESTADO) AS Estado,
    LB.CODIGO_ESTADO AS "Codigo Estado Actual",
    LB.OBSERVACIONES AS Comentario,
    LB.FECHA_ADICION AS "Fecha Ultimo Estado",
    R.MTO_PREAPROBADO,
    R.FECHA_PROCESO AS "Fecha Preaprobacion",
    (TRUNC(R.FECHA_PROCESO) + CAST(PR.PR_PKG_REPRESTAMOS.F_OBT_PARAMETRO_REPRESTAMO('DIA_CADUCA_LINK') AS NUMBER)) AS "Fecha Vencimiento Link",
    C.F_PRIMER_DESEMBOLSO AS "Fecha Desembolso",
    C.MONTO_DESEMBOLSADO,
    CASE
        WHEN LB.CODIGO_ESTADO = 'CRD' THEN
            CASE WHEN HCS.ID_REPRESTAMO IS NOT NULL THEN 'Digital (con firma)' ELSE 'Sucursal (tradicional)' END
        ELSE NULL
    END AS "Canal Desembolso Determinado"
FROM
    PA.EMPLEADOS P
JOIN PA.AGENCIA A_EMP
    ON P.COD_EMPRESA = A_EMP.COD_EMPRESA
    AND TO_NUMBER(P.COD_AGENCIA_LABORA) = A_EMP.COD_AGENCIA
JOIN PR.PR_SOLICITUD_REPRESTAMO S
    ON P.COD_EMPRESA = S.CODIGO_EMPRESA
    AND P.COD_AGENCIA_LABORA = S.CODIGO_AGENCIA
JOIN PR.PR_REPRESTAMOS R ON S.ID_REPRESTAMO = R.ID_REPRESTAMO AND S.CODIGO_EMPRESA = R.CODIGO_EMPRESA
JOIN LatestBitacora LB ON S.ID_REPRESTAMO = LB.ID_REPRESTAMO AND LB.rn = 1
LEFT JOIN HasCryStatus HCS ON S.ID_REPRESTAMO = HCS.ID_REPRESTAMO
LEFT JOIN PR.PR_CREDITOS C ON S.NO_CREDITO = C.NO_CREDITO AND S.CODIGO_EMPRESA = C.CODIGO_EMPRESA
WHERE
    ---SUBSTR(P.EMAIL1, 1, INSTR(P.EMAIL1, '@') - 1) = V('APP_USER')
    SUBSTR(P.EMAIL1, 1, INSTR(P.EMAIL1, '@') - 1) = 'MAMATOS'
    AND P.ID_EMPLEADO = A_EMP.GERENTE
    AND P.ESTA_ACTIVO = 'S'
ORDER BY
    LB.FECHA_ADICION DESC,
    S.ID_REPRESTAMO DESC;