CREATE TABLE CD_CONSEC_X_AGENCIA (
    COD_EMPRESA          VARCHAR2(5 BYTE) NOT NULL,
    COD_AGENCIA          VARCHAR2(5 BYTE) NOT NULL,
    COD_MONEDA           VARCHAR2(4 BYTE) NOT NULL,
    VAL_SIGUIENTE        NUMBER(9) NOT NULL,
    VAL_MAXIMO           NUMBER(9) NOT NULL,
    TOT_ANULADOS         NUMBER(7),
    ACTIVA               VARCHAR2(1 BYTE),
    ADICIONADO_POR       VARCHAR2(10 BYTE),
    FEC_ADICION          DATE,
    MODIFICADO_POR       VARCHAR2(10 BYTE),
    FEC_MODIFICACION     DATE,
    CONSTRAINT PK_CD_CONSEC_X_AGENCIA PRIMARY KEY (COD_EMPRESA, COD_AGENCIA, COD_MONEDA)
);