CREATE TABLE AGENCIA (
    COD_EMPRESA              VARCHAR2(5 Byte) NOT NULL,
    COD_AGENCIA              NUMBER(2) NOT NULL,
    DESCRIPCION              VARCHAR2(80 Byte) NOT NULL,
    ES_CENTRAL               VARCHAR2(1 Byte) NOT NULL,
    EST_AGENCIA              VARCHAR2(5 Byte) NOT NULL,
    APARTADO_POSTAL          VARCHAR2(30 Byte),
    COD_POSTAL               VARCHAR2(10 Byte),
    DETALLE_DIR              VARCHAR2(160 Byte),
    TRABAJA_DOM              VARCHAR2(1 Byte),
    TRABAJA_SAB              VARCHAR2(1 Byte),
    COD_PAIS                 VARCHAR2(5 Byte) NOT NULL,
    COD_CAMARA               VARCHAR2(1 Byte),
    COD_PROVINCIA            VARCHAR2(5 Byte) NOT NULL,
    COD_CANTON               VARCHAR2(5 Byte) NOT NULL,
    COD_DISTRITO             VARCHAR2(5 Byte) NOT NULL,
    COD_PUEBLO               VARCHAR2(5 Byte) NOT NULL,
    RECIBE_COMISION          VARCHAR2(1 Byte),
    COD_ZONA                 VARCHAR2(10 Byte),
    GERENTE                  VARCHAR2(10 Byte),
    ES_SUB_AGENCIA           VARCHAR2(1 Byte),
    EMAIL_GERENCIA           VARCHAR2(80 Byte),
    ATIENDE_CLIENTE          VARCHAR2(1 Byte),
    OFICIAL_BACKUP           VARCHAR2(10 Byte),
    OFICIAL_MASIVO           VARCHAR2(10 Byte),
    EMAIL_SUCURSAL           VARCHAR2(80 Byte),
    NUEVO_MODELO_IMPRESION   VARCHAR2(1 Byte) DEFAULT NULL, -- Explicitly NULL as per image
    VICEPRESIDENTE           VARCHAR2(10 Byte),
    COD_CENTROC              VARCHAR2(5 Byte),
    COD_EMISOR_TJT           VARCHAR2(4 Byte),
    LONGITUD                 VARCHAR2(100 Byte),
    LATITUD                  VARCHAR2(100 Byte),
    TIP_OFICINA              NUMBER(1),
    DESC_ENSAM_SECTOR        VARCHAR2(30 Byte),
    FEC_APERTURA_OFIC        DATE,
    FEC_APROBACION           DATE,
    NUM_AUTORIZACION         VARCHAR2(25 Byte),
    COD_AGENCIA_SB           VARCHAR2(10 Byte),
    GESTION_CAJA_LIQUIDA     CHAR(1 Byte),
    COD_AGENCIA_EXON         VARCHAR2(5 Byte) DEFAULT NULL, -- Explicitly NULL as per image
    ENCARGADO                VARCHAR2(10 Byte),
    CONSTRAINT PK_AGENCIA PRIMARY KEY (COD_EMPRESA, COD_AGENCIA)
);