CREATE TABLE MONEDA (
  COD_MONEDA           VARCHAR2(4)   NOT NULL,
  DESCRIPCION          VARCHAR2(60)  NOT NULL,
  OPER_CONVERSION      VARCHAR2(2)   NOT NULL,
  ABREVIATURA          VARCHAR2(4)   NOT NULL,
  COD_PAIS             VARCHAR2(5)   NOT NULL,
  SIGNO                VARCHAR2(2)   NOT NULL,
  MONEDA_ISO           VARCHAR2(3)   NOT NULL,
  SIGLA_SB             VARCHAR2(3),
  COD_MONEDA_TCE       NUMBER(2),
  COD_MONEDA_EVERTEC   NUMBER(4),
  CONSTRAINT PK_MONEDA
    PRIMARY KEY (COD_MONEDA)
);
