-- ============================================================
-- OPT-002 AFTER: Cursores optimizados en Actualiza_Precalificacion
-- Paquete: PR_PKG_REPRESTAMOS (body.sql, QA)
-- ============================================================

-- CURSOR CUR_DE08_SIB (linea ~2640)
-- Cambio: OBT_IDENTIFICACION_PERSONA reemplazado por JOIN a PA.ID_PERSONAS
CURSOR CUR_DE08_SIB IS
    SELECT B.ROWID ID, b.id_represtamo, NVL(A.CLASIFICACION,'NULA') CLASIFICACION
    FROM PA_DE08_SIB A
    JOIN PR_REPRESTAMOS B ON B.ESTADO = 'RE'
    JOIN PA.ID_PERSONAS IP ON IP.COD_PERSONA = TO_CHAR(B.CODIGO_CLIENTE) AND IP.COD_TIPO_ID = '1'
    WHERE A.FECHA_CORTE = TO_DATE('19/11/2024','DD/MM/YYYY')
    AND IP.NUM_ID = A.ID_DEUDOR
    AND PR.PR_PKG_REPRESTAMOS.F_OBT_PARAMETRO_REPRESTAMO ( 'DE08_SIB' ) = 'S' ;

-- CURSOR CUR_DE05_SIB (linea ~2657)
-- Cambio: OBT_IDENTIFICACION_PERSONA reemplazado por JOIN a PA.ID_PERSONAS
CURSOR CUR_DE05_SIB IS
    SELECT B.ROWID ID, b.id_represtamo, A.cedula, a.entidad
    FROM PA_DE05_SIB A
    JOIN PR_REPRESTAMOS B ON B.ESTADO = 'RE'
    JOIN PA.ID_PERSONAS IP ON IP.COD_PERSONA = TO_CHAR(B.CODIGO_CLIENTE) AND IP.COD_TIPO_ID = '1'
    WHERE A.FECHA_CASTIGO = (SELECT MAX(FECHA_CASTIGO) FROM PA_DE05_SIB)
    AND IP.NUM_ID = A.cedula
    AND PR.PR_PKG_REPRESTAMOS.F_OBT_PARAMETRO_REPRESTAMO ( 'CASTIGOS_SIB' ) = 'S';

-- INDICE NUEVO (covering index):
-- CREATE INDEX PA.IDX_DE08_SIB_FECHA_DEUDOR ON PA.PA_DE08_SIB (FECHA_CORTE, ID_DEUDOR, CLASIFICACION);
