DECLARE
    vIdReprestamo         VARCHAR2(50) := '2501254560'; -- ID que se pasa al script
    vNoCredito            VARCHAR2(50);
    vCodigoCliente        VARCHAR2(50);
    vMonto                VARCHAR2(50);
    vPlazo                VARCHAR2(50) := '18'; -- fijo
    vTipoCredito          VARCHAR2(50);
    vMensajeError         VARCHAR2(4000);
 
    -- Variables de salida
    vMontoAprobado        VARCHAR2(50);
    vMontoDescontar       VARCHAR2(50);
    vMontoDepositar       VARCHAR2(50);
    vMontoCuota           VARCHAR2(50);
    vMontoCargo           VARCHAR2(50);
    vSeguroVida           VARCHAR2(50);
    vDesempleo            VARCHAR2(50);
    vMypime               VARCHAR2(50);
    vCuotaTotal           VARCHAR2(50);
    vTasa                 VARCHAR2(50);
    vPlazoOut             VARCHAR2(50);
    vMontoOut             VARCHAR2(50);
    vTipoCreditoOut       VARCHAR2(50);
    vStatus               VARCHAR2(50);
BEGIN
    -- 1. Obtener valores base
    SELECT 
        R.MTO_PREAPROBADO,
        S.TIPO_CREDITO,
        R.NO_CREDITO,
        R.CODIGO_CLIENTE
    INTO 
        vMonto, vTipoCredito, vNoCredito, vCodigoCliente
    FROM 
        PR_REPRESTAMOS R
    JOIN 
        PR_SOLICITUD_REPRESTAMO S ON R.ID_REPRESTAMO = S.ID_REPRESTAMO
    WHERE 
        R.ID_REPRESTAMO = vIdReprestamo;

    -- 2. Calcular opción
    PR.PR_PKG_REPRESTAMOS.P_Calcular_Opcion_Front(
        pIdReprestamo           => vIdReprestamo,
        pMonto                  => vMonto,
        pPlazo                  => vPlazo,
        PCalculaSeguroMypime    => 'S',
        PCalculaSeguroDesempleo => 'S',
        Montoaprobado           => vMontoAprobado,
        Montocancelacion        => vMontoDescontar,
        Montodepositar          => vMontoDepositar,
        Montocuota              => vMontoCuota,
        Montocargo              => vMontoCargo,
        MontoseguroVida         => vSeguroVida,
        Montodesempleo          => vDesempleo,
        MontoMypime             => vMypime,
        Montocuotatotal         => vCuotaTotal,
        Tasa                    => vTasa,
        Plazo                   => vPlazoOut,
        Monto                   => vMontoOut,
        PtipoCredito            => vTipoCreditoOut,
        status                  => vStatus,
        pMensajeError           => vMensajeError
    );
 
    IF vMensajeError IS NULL THEN
        -- 3. Cargar opción
        PR.PR_PKG_REPRESTAMOS.P_Carga_Opcion_Front(
            pIdReprestamo       => vIdReprestamo,
            Plazo               => vPlazo,
            MontoReprestamo     => vMonto,
            MontoDescontar      => vMontoDescontar,
            Montodepositar      => vMontoDepositar,
            Montocuota          => vMontoCuota,
            Montocargo          => vMontoCargo,
            MontoseguroVida     => vSeguroVida,
            Montodesempleo      => vDesempleo,
            Tasa                => vTasa,
            Montocuotatotal     => vCuotaTotal,
            MontoMipyme         => vMypime,
            pMensajeError       => vMensajeError
        );
    END IF;
 
    -- Resultado final
    IF vMensajeError IS NULL THEN
        DBMS_OUTPUT.PUT_LINE(' Proceso completado exitosamente.');
    ELSE
        DBMS_OUTPUT.PUT_LINE(' Error: ' || vMensajeError);
    END IF;
 
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE(' Error inesperado: ' || SQLERRM);
END;


DECLARE 
  PIDREPRESTAMO VARCHAR2(32767);
  PLAZO VARCHAR2(32767);
  MONTOREPRESTAMO VARCHAR2(32767);
  MONTODESCONTAR VARCHAR2(32767);
  MONTODEPOSITAR VARCHAR2(32767);
  MONTOCUOTA VARCHAR2(32767);
  MONTOCARGO VARCHAR2(32767);
  MONTOSEGUROVIDA VARCHAR2(32767);
  MONTODESEMPLEO VARCHAR2(32767);
  TASA VARCHAR2(32767);
  MONTOCUOTATOTAL VARCHAR2(32767);
  MONTOMIPYME VARCHAR2(32767);
  PMENSAJEERROR VARCHAR2(32767);

BEGIN 
  PIDREPRESTAMO := NULL;
  PLAZO := NULL;
  MONTOREPRESTAMO := NULL;
  MONTODESCONTAR := NULL;
  MONTODEPOSITAR := NULL;
  MONTOCUOTA := NULL;
  MONTOCARGO := NULL;
  MONTOSEGUROVIDA := NULL;
  MONTODESEMPLEO := NULL;
  TASA := NULL;
  MONTOCUOTATOTAL := NULL;
  MONTOMIPYME := NULL;
  PMENSAJEERROR := NULL;

  PR.PR_PKG_REPRESTAMOS.P_CARGA_OPCION_FRONT ( :PIDREPRESTAMO, :PLAZO,:MONTOREPRESTAMO, :MONTODESCONTAR, :MONTODEPOSITAR, :MONTOCUOTA, :MONTOCARGO, :MONTOSEGUROVIDA, :MONTODESEMPLEO, :TASA, :MONTOCUOTATOTAL, :MONTOMIPYME, :PMENSAJEERROR );
  COMMIT; 
END; 


DECLARE 
  PIDREPRESTAMO VARCHAR2(32767);
  PMONTO VARCHAR2(32767);
  PPLAZO VARCHAR2(32767);
  PCALCULASEGUROMYPIME VARCHAR2(32767);
  PCALCULASEGURODESEMPLEO VARCHAR2(32767);
  MONTOAPROBADO VARCHAR2(32767);
  MONTOCANCELACION VARCHAR2(32767);
  MONTODEPOSITAR VARCHAR2(32767);
  MONTOCUOTA VARCHAR2(32767);
  MONTOCARGO VARCHAR2(32767);
  MONTOSEGUROVIDA VARCHAR2(32767);
  MONTODESEMPLEO VARCHAR2(32767);
  MONTOMYPIME VARCHAR2(32767);
  MONTOCUOTATOTAL VARCHAR2(32767);
  TASA VARCHAR2(32767);
  PLAZO VARCHAR2(32767);
  MONTO VARCHAR2(32767);
  PTIPOCREDITO VARCHAR2(32767);
  STATUS VARCHAR2(32767);
  PMENSAJEERROR VARCHAR2(32767);

BEGIN 
  PIDREPRESTAMO := NULL;
  PMONTO := NULL;
  PPLAZO := NULL;
  PCALCULASEGUROMYPIME := NULL;
  PCALCULASEGURODESEMPLEO := NULL;
  MONTOAPROBADO := NULL;
  MONTOCANCELACION := NULL;
  MONTODEPOSITAR := NULL;
  MONTOCUOTA := NULL;
  MONTOCARGO := NULL;
  MONTOSEGUROVIDA := NULL;
  MONTODESEMPLEO := NULL;
  MONTOMYPIME := NULL;
  MONTOCUOTATOTAL := NULL;
  TASA := NULL;
  PLAZO := NULL;
  MONTO := NULL;
  PTIPOCREDITO := NULL;
  STATUS := NULL;
  PMENSAJEERROR := NULL;

  PR.PR_PKG_REPRESTAMOS.P_CALCULAR_OPCION_FRONT ( :PIDREPRESTAMO, :PMONTO, :PPLAZO, :PCALCULASEGUROMYPIME, :PCALCULASEGURODESEMPLEO, :MONTOAPROBADO, :MONTOCANCELACION, :MONTODEPOSITAR, :MONTOCUOTA, :MONTOCARGO, :MONTOSEGUROVIDA, :MONTODESEMPLEO, :MONTOMYPIME, :MONTOCUOTATOTAL, :TASA, :PLAZO, :MONTO, :PTIPOCREDITO, :STATUS, :PMENSAJEERROR );
  COMMIT; 
END; 





DECLARE 
  PNOCREDITO VARCHAR2(32767);
  PTIPO_CREDITO VARCHAR2(32767);
  PMONTO VARCHAR2(32767);
  PPLAZO VARCHAR2(32767);
  PCALCULASEGUROMYPIME VARCHAR2(32767);
  PCALCULASEGURODESEMPLEO VARCHAR2(32767);
  MONTOAPROBADO VARCHAR2(32767);
  MONTOCANCELACION VARCHAR2(32767);
  MONTODEPOSITAR VARCHAR2(32767);
  MONTOCUOTA VARCHAR2(32767);
  MONTOCARGO VARCHAR2(32767);
  MONTOSEGUROVIDA VARCHAR2(32767);
  MONTODESEMPLEO VARCHAR2(32767);
  MONTOMYPIME VARCHAR2(32767);
  MONTOCUOTATOTAL VARCHAR2(32767);
  TASA VARCHAR2(32767);
  PLAZO VARCHAR2(32767);
  MONTO VARCHAR2(32767);
  PTIPOCREDITO VARCHAR2(32767);
  STATUS VARCHAR2(32767);
  PMENSAJEERROR VARCHAR2(32767);

BEGIN 
  PNOCREDITO := NULL;
  PTIPO_CREDITO := NULL;
  PMONTO := NULL;
  PPLAZO := NULL;
  PCALCULASEGUROMYPIME := NULL;
  PCALCULASEGURODESEMPLEO := NULL;
  MONTOAPROBADO := NULL;
  MONTOCANCELACION := NULL;
  MONTODEPOSITAR := NULL;
  MONTOCUOTA := NULL;
  MONTOCARGO := NULL;
  MONTOSEGUROVIDA := NULL;
  MONTODESEMPLEO := NULL;
  MONTOMYPIME := NULL;
  MONTOCUOTATOTAL := NULL;
  TASA := NULL;
  PLAZO := NULL;
  MONTO := NULL;
  PTIPOCREDITO := NULL;
  STATUS := NULL;
  PMENSAJEERROR := NULL;

  PR.PR_PKG_REPRESTAMOS.P_ACTUALIZAR_OPCION_FRONT ( :PNOCREDITO, :PTIPO_CREDITO, :PMONTO, :PPLAZO, :PCALCULASEGUROMYPIME, :PCALCULASEGURODESEMPLEO, :MONTOAPROBADO, :MONTOCANCELACION, :MONTODEPOSITAR, :MONTOCUOTA, :MONTOCARGO, :MONTOSEGUROVIDA, :MONTODESEMPLEO, :MONTOMYPIME, :MONTOCUOTATOTAL, :TASA, :PLAZO, :MONTO, :PTIPOCREDITO,:vSeguroMipyme,:vSeguroDesempleo,:STATUS, :PMENSAJEERROR );
  COMMIT; 
END; 




DECLARE 
  PIDREPRESTAMO VARCHAR2(32767);
  PMONTO VARCHAR2(32767);
  PPLAZO VARCHAR2(32767);
  PCALCULASEGUROMYPIME VARCHAR2(32767);
  PCALCULASEGURODESEMPLEO VARCHAR2(32767);
  MONTOAPROBADO VARCHAR2(32767);
  MONTOCANCELACION VARCHAR2(32767);
  MONTODEPOSITAR VARCHAR2(32767);
  MONTOCUOTA VARCHAR2(32767);
  MONTOCARGO VARCHAR2(32767);
  MONTOSEGUROVIDA VARCHAR2(32767);
  MONTODESEMPLEO VARCHAR2(32767);
  MONTOMYPIME VARCHAR2(32767);
  MONTOCUOTATOTAL VARCHAR2(32767);
  TASA VARCHAR2(32767);
  PLAZO VARCHAR2(32767);
  MONTO VARCHAR2(32767);
  PTIPOCREDITO VARCHAR2(32767);
  STATUS VARCHAR2(32767);
  PMENSAJEERROR VARCHAR2(32767);

BEGIN 
  PIDREPRESTAMO := NULL;
  PMONTO := NULL;
  PPLAZO := NULL;
  PCALCULASEGUROMYPIME := NULL;
  PCALCULASEGURODESEMPLEO := NULL;
  MONTOAPROBADO := NULL;
  MONTOCANCELACION := NULL;
  MONTODEPOSITAR := NULL;
  MONTOCUOTA := NULL;
  MONTOCARGO := NULL;
  MONTOSEGUROVIDA := NULL;
  MONTODESEMPLEO := NULL;
  MONTOMYPIME := NULL;
  MONTOCUOTATOTAL := NULL;
  TASA := NULL;
  PLAZO := NULL;
  MONTO := NULL;
  PTIPOCREDITO := NULL;
  STATUS := NULL;
  PMENSAJEERROR := NULL;

  PR.PR_PKG_REPRESTAMOS.P_CALCULAR_OPCION_FRONT ( :PIDREPRESTAMO, :PMONTO, :PPLAZO, :PCALCULASEGUROMYPIME, :PCALCULASEGURODESEMPLEO, :MONTOAPROBADO, :MONTOCANCELACION,:MONTODEPOSITAR,:MONTOCUOTA, :MONTOCARGO, :MONTOSEGUROVIDA, :MONTODESEMPLEO, :MONTOMYPIME, :MONTOCUOTATOTAL, :TASA, :PLAZO, :MONTO, :PTIPOCREDITO, :STATUS, :PMENSAJEERROR );
  COMMIT; 
END; 

PR_CREDITOS_HI



DECLARE 
  PNOCREDITO VARCHAR2(32767);
  PTIPO_CREDITO VARCHAR2(32767);
  PMONTO VARCHAR2(32767);
  PPLAZO VARCHAR2(32767);
  PMENSAJEERROR VARCHAR2(32767);

BEGIN 
  PNOCREDITO := NULL;
  PTIPO_CREDITO := NULL;
  PMONTO := NULL;
  PPLAZO := NULL;
  PMENSAJEERROR := NULL;

  PR.PR_PKG_REPRESTAMOS.P_ACTUALIZAR_OPCION_FRONT ( :PNOCREDITO, :PTIPO_CREDITO, :PMONTO, :PPLAZO, :PMENSAJEERROR );
  COMMIT; 
END; 

SELECT S.NO_CREDITO,S.TIPO_CREDITO,O.MTO_PRESTAMO,S.PLAZO 
FROM PR_SOLICITUD_REPRESTAMO S
LEFT JOIN PR_OPCIONES_REPRESTAMO O ON O.ID_REPRESTAMO = S.ID_REPRESTAMO WHERE S.NO_CREDITO = 1422881



DECLARE 
  PIDREPRESTAMO VARCHAR2(32767);
  PMONTO VARCHAR2(32767);
  PPLAZO VARCHAR2(32767);
  PCALCULASEGUROMYPIME VARCHAR2(32767);
  PCALCULASEGURODESEMPLEO VARCHAR2(32767);
  MONTOAPROBADO VARCHAR2(32767);
  MONTOCANCELACION VARCHAR2(32767);
  MONTODEPOSITAR VARCHAR2(32767);
  MONTOCUOTA VARCHAR2(32767);
  MONTOCARGO VARCHAR2(32767);
  MONTOSEGUROVIDA VARCHAR2(32767);
  MONTODESEMPLEO VARCHAR2(32767);
  MONTOMYPIME VARCHAR2(32767);
  MONTOCUOTATOTAL VARCHAR2(32767);
  TASA VARCHAR2(32767);
  PLAZO VARCHAR2(32767);
  MONTO VARCHAR2(32767);
  PTIPOCREDITO VARCHAR2(32767);
  STATUS VARCHAR2(32767);
  PMENSAJEERROR VARCHAR2(32767);

BEGIN 
  PIDREPRESTAMO := NULL;
  PMONTO := NULL;
  PPLAZO := NULL;
  PCALCULASEGUROMYPIME := NULL;
  PCALCULASEGURODESEMPLEO := NULL;
  MONTOAPROBADO := NULL;
  MONTOCANCELACION := NULL;
  MONTODEPOSITAR := NULL;
  MONTOCUOTA := NULL;
  MONTOCARGO := NULL;
  MONTOSEGUROVIDA := NULL;
  MONTODESEMPLEO := NULL;
  MONTOMYPIME := NULL;
  MONTOCUOTATOTAL := NULL;
  TASA := NULL;
  PLAZO := NULL;
  MONTO := NULL;
  PTIPOCREDITO := NULL;
  STATUS := NULL;
  PMENSAJEERROR := NULL;

  PR.PR_PKG_REPRESTAMOS.P_CALCULAR_OPCION_FRONT ( :PIDREPRESTAMO, :PMONTO, :PPLAZO, :PCALCULASEGUROMYPIME, :PCALCULASEGURODESEMPLEO, :MONTOAPROBADO, :MONTOCANCELACION, :MONTODEPOSITAR, :MONTOCUOTA, :MONTOCARGO, :MONTOSEGUROVIDA, :MONTODESEMPLEO, :MONTOMYPIME, :MONTOCUOTATOTAL, :TASA, :PLAZO, :MONTO, :PTIPOCREDITO, :STATUS, :PMENSAJEERROR );
  COMMIT; 
END; 



-----------------------
BEGIN 
PR_PKG_REPRESTAMOS.P_JOB_CREA_CREDITO;
END;
