SELECT
  R.ID_REPRESTAMO,
  R.FECHA_ADICION,
  PA.OBT_NOMBRE_PERSONA(R.CODIGO_CLIENTE) AS NOMBRES,
  E.DES_ESTADO AS ESTADO,
  R.ESTADO AS CODIGO_ESTADO,
  '<a
      title="Origen Fuente de Datos"
      href="' || APEX_PAGE.GET_URL(p_page => 130, p_items => 'P130_ID_REPRESTAMO', p_values => R.ID_REPRESTAMO) || '"
    >
      <span aria-hidden="true" class="fa fa-pencil-square-o"></span>
    </a>' AS ACTUALIZAR_ESTADO
FROM
  PR.PR_REPRESTAMOS R
  LEFT JOIN PR.PR_ESTADOS_REPRESTAMO E
       ON E.CODIGO_ESTADO = R.ESTADO
WHERE
  R.ESTADO IN (
    SELECT COLUMN_VALUE
    FROM TABLE(PR.PR_PKG_REPRESTAMOS.F_Obt_Valor_Parametros('LISTA_ESTADOS_REPRESTAMOS_VISUALIZAR'))
  )
  AND (
    :P112_BUSQUEDA IS NULL
    OR ID_REPRESTAMO IN (
      SELECT TRIM(REGEXP_SUBSTR(:P112_BUSQUEDA, '[^,]+', 1, LEVEL)) AS SPLIT_VALUE
      FROM DUAL
      CONNECT BY REGEXP_SUBSTR(:P112_BUSQUEDA, '[^,]+', 1, LEVEL) IS NOT NULL
      AND PRIOR DBMS_RANDOM.VALUE IS NOT NULL  -- Ensure a proper loop
      AND LEVEL <= LENGTH(:P112_BUSQUEDA) - LENGTH(REPLACE(:P112_BUSQUEDA, ',', '')) + 1  -- Correct range
    )
  );
