DROP TABLE CD.CD_ESTADO CASCADE CONSTRAINTS;

CREATE TABLE CD.CD_ESTADO
(
  COD_EMPRESA      VARCHAR2(5 BYTE),
  COD_ESTADO       VARCHAR2(1 BYTE),
  DESCRIPCION      VARCHAR2(80 BYTE),
  CALCULA_INTERES  VARCHAR2(2 BYTE),
  USUARIO_ADICION  VARCHAR2(10 BYTE),
  FECHA_ADICION    DATE
)
TABLESPACE CD_DAT
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE INDEX CD.PK_CD_ESTADOS ON CD.CD_ESTADO
(COD_EMPRESA, COD_ESTADO)
LOGGING
TABLESPACE CD_DAT
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE OR REPLACE PUBLIC SYNONYM CD_ESTADO FOR CD.CD_ESTADO;
