-- Entorno: QA02
-- Schema: PA
-- Fecha: 2026-04-24
-- Origen: DDL pegado por el usuario desde QA ADEMI 02 / QA02.
-- Motivo: Caso de borrado del cliente/persona 1202121 con ORA-02292.
-- Observacion: DDL normalizado para consulta del repo. Conserva estructura,
-- constraints, indices, FKs, sinonimo y triggers de impacto directo.

DROP TABLE PA.CLIENTE CASCADE CONSTRAINTS;

CREATE TABLE PA.CLIENTE
(
  COD_EMPRESA             VARCHAR2(5 BYTE),
  COD_CLIENTE             VARCHAR2(15 BYTE),
  NUM_CLIENTE             VARCHAR2(8 BYTE) CONSTRAINT NN_CLIENTE_NUM_CLIENTE NOT NULL,
  COD_AGENCIA             VARCHAR2(5 BYTE) CONSTRAINT NN_CLIENTE_COD_AGENCIA NOT NULL,
  COD_CAT_CLTE            VARCHAR2(3 BYTE),
  COD_GRUPO               VARCHAR2(6 BYTE),
  ESTA_ACTIVO             VARCHAR2(1 BYTE) CONSTRAINT NN_CLIENTE_ESTA_ACTIVO NOT NULL,
  PAGA_IMPTO_RENTA        VARCHAR2(1 BYTE) CONSTRAINT NN_CLIENTE_PAGA_IMPTO_RENTA NOT NULL,
  FEC_INGRESO             DATE,
  CAT_RIESGO              VARCHAR2(3 BYTE),
  COD_OFICIAL             VARCHAR2(10 BYTE),
  COD_PROMOTOR            VARCHAR2(10 BYTE),
  COD_ZONA                VARCHAR2(5 BYTE),
  CLIENTE_ESPECIAL        VARCHAR2(1 BYTE) CONSTRAINT NN_CLIENTE_CLIENTE_ESPECIAL NOT NULL,
  TIPO_DEUDOR             VARCHAR2(5 BYTE),
  CROSS_ESTIMADO          NUMBER(8,4) CONSTRAINT NN_CLIENTE_CROSS_ESTIMADO NOT NULL,
  CROSS_CALCULADO         NUMBER(8,4) CONSTRAINT NN_CLIENTE_CROSS_CALCULADO NOT NULL,
  RENTABILIDAD            NUMBER(18,4) CONSTRAINT NN_CLIENTE_RENTABILIDAD NOT NULL,
  MON_INGRESO_BCO         NUMBER(18,2) CONSTRAINT NN_CLIENTE_MON_INGRESO_BCO NOT NULL,
  MON_EGRESO_BCO          NUMBER(18,2) CONSTRAINT NN_CLIENTE_MON_EGRESO_BCO NOT NULL,
  COD_SUB_AGENCIA         VARCHAR2(5 BYTE),
  ESTADO_CLIENTE          VARCHAR2(1 BYTE),
  COD_NICHO               VARCHAR2(14 BYTE),
  FEC_ACTUALIZA_INGRESOS  DATE,
  COMENTARIO_ACT_INGRESO  VARCHAR2(200 BYTE),
  NUM_CARPETA             NUMBER(10),
  COD_LINEA_CREDITO       VARCHAR2(5 BYTE),
  INCLUIDO_POR            VARCHAR2(10 BYTE),
  FEC_INCLUSION           DATE,
  MODIFICADO_POR          VARCHAR2(10 BYTE),
  FEC_MODIFICACION        DATE
)
TABLESPACE DATA_EFD
LOGGING
NOCOMPRESS
NOCACHE;

COMMENT ON TABLE PA.CLIENTE IS 'Clientes';

CREATE UNIQUE INDEX PA.PK_CLIENTE ON PA.CLIENTE (COD_EMPRESA, COD_CLIENTE) TABLESPACE IND_EFD;
CREATE INDEX PA.IDX_CLIENTE_NUMCLIENTE ON PA.CLIENTE (NUM_CLIENTE, COD_EMPRESA) TABLESPACE IND_EFD;

ALTER TABLE PA.CLIENTE ADD (
  CONSTRAINT CK_CLIENTE_CAT_RIESGO CHECK (CAT_RIESGO IN ('A','B','C','D','E')) ENABLE VALIDATE,
  CONSTRAINT CK_CLIENTE_CLIENTE_ESPECIAL CHECK (CLIENTE_ESPECIAL IN ('S','N')) ENABLE VALIDATE,
  CONSTRAINT CK_CLIENTE_ESTA_ACTIVO CHECK (ESTA_ACTIVO IN ('S','N')) ENABLE VALIDATE,
  CONSTRAINT CK_CLIENTE_PAGA_IMPTO_RENTA CHECK (PAGA_IMPTO_RENTA IN ('S','N')) ENABLE VALIDATE,
  CONSTRAINT CK_ESTADO_CLIENTE CHECK (ESTADO_CLIENTE IN ('A','R','I','N')) ENABLE VALIDATE,
  CONSTRAINT PK_CLIENTE PRIMARY KEY (COD_EMPRESA, COD_CLIENTE) USING INDEX PA.PK_CLIENTE ENABLE VALIDATE,
  CONSTRAINT UK_CLIENTE_NUMCLI UNIQUE (NUM_CLIENTE) USING INDEX PA.IDX_CLIENTE_NUMCLIENTE ENABLE VALIDATE
);

CREATE INDEX PA.CLIENTE_FK1 ON PA.CLIENTE (COD_CAT_CLTE) TABLESPACE PA_IND;
CREATE INDEX PA.CLIENTE_FK10 ON PA.CLIENTE (COD_EMPRESA, COD_ZONA) TABLESPACE PA_IND;
CREATE INDEX PA.CLIENTE_FK8 ON PA.CLIENTE (COD_NICHO) TABLESPACE PA_IND;
CREATE INDEX PA.CLIENTE_FK9 ON PA.CLIENTE (COD_EMPRESA, COD_AGENCIA, COD_SUB_AGENCIA) TABLESPACE PA_IND;
CREATE INDEX PA.IDX_GRUPO ON PA.CLIENTE (COD_GRUPO, COD_EMPRESA) TABLESPACE IND_EFD;
CREATE INDEX PA.IDX_OFICIAL ON PA.CLIENTE (COD_OFICIAL) TABLESPACE IND_EFD;
CREATE INDEX PA.XX ON PA.CLIENTE (COD_CLIENTE) TABLESPACE IND_EFD;

CREATE OR REPLACE TRIGGER PA.TRG_PA_CLIENTE
BEFORE INSERT OR UPDATE ON PA.CLIENTE
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
BEGIN
  IF INSERTING THEN
    :New.Incluido_Por := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'),USER);
    :New.Fec_Inclusion := SYSDATE;
  ELSIF UPDATING THEN
    IF :new.cod_promotor != :new.cod_oficial THEN
      :new.cod_promotor := :new.cod_oficial;
    END IF;
    :New.Modificado_Por := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'),USER);
    :New.Fec_Modificacion := SYSDATE;
    IF :New.Incluido_Por != :Old.Incluido_Por THEN
      :New.Incluido_Por := :Old.Incluido_Por;
    END IF;
    IF :New.Fec_Inclusion != :Old.Fec_Inclusion THEN
      :New.Fec_Inclusion := :Old.Fec_Inclusion;
    END IF;
  END IF;
END;
/

CREATE OR REPLACE PUBLIC SYNONYM CLIENTE FOR PA.CLIENTE;

ALTER TABLE PA.CLIENTE ADD (
  CONSTRAINT FK_CLIENTES_EMPRESA FOREIGN KEY (COD_EMPRESA) REFERENCES PA.EMPRESA (COD_EMPRESA) ENABLE VALIDATE,
  CONSTRAINT FK_CLIENTES_GRUPOS_EMP FOREIGN KEY (COD_GRUPO) REFERENCES PA.GRUPOS_EMP (COD_GRUPO) ENABLE VALIDATE,
  CONSTRAINT FK_CLIENTES_PERSONAS FOREIGN KEY (COD_CLIENTE) REFERENCES PA.PERSONAS (COD_PERSONA) ENABLE VALIDATE,
  CONSTRAINT FK_CLIENTE_AREAS_MERCADO FOREIGN KEY (COD_EMPRESA, COD_ZONA) REFERENCES PA.AREAS_MERCADO (COD_EMPRESA, COD_ZONA) ENABLE VALIDATE,
  CONSTRAINT FK_CLIENTE_NICHO FOREIGN KEY (COD_NICHO) REFERENCES PA.PA_NICHOS (COD_NICHO) ENABLE VALIDATE,
  CONSTRAINT FK_CLIENTE_SUB_AGENCIAS FOREIGN KEY (COD_EMPRESA, COD_AGENCIA, COD_SUB_AGENCIA) REFERENCES PA.SUB_AGENCIAS (COD_EMPRESA, COD_AGENCIA, COD_SUB_AGENCIA) ENABLE VALIDATE,
  CONSTRAINT FK_FK_CLIENTES_CAT_CLIENTES FOREIGN KEY (COD_CAT_CLTE) REFERENCES PA.CAT_CLIENTES (COD_CAT_CLTE) ENABLE VALIDATE
);

