-- Entorno: QA02
-- Schema: PA
-- Fecha: 2026-04-24
-- Origen: DDL pegado por el usuario desde QA ADEMI 02 / QA02.
-- Motivo: Caso de borrado del cliente/persona 1202121 con ORA-02292.
-- Observacion: DDL normalizado para consulta del repo. Conserva estructura,
-- constraints, indices, FKs, sinonimo y triggers de impacto directo.

DROP TABLE PA.DIR_PERSONAS CASCADE CONSTRAINTS;

CREATE TABLE PA.DIR_PERSONAS
(
  COD_PERSONA         VARCHAR2(15 BYTE),
  COD_DIRECCION       VARCHAR2(8 BYTE),
  TIP_DIRECCION       VARCHAR2(1 BYTE) CONSTRAINT NN_DIR_PERSONAS_TIP_DIRECCION NOT NULL,
  APARTADO_POSTAL     VARCHAR2(15 BYTE),
  COD_POSTAL          VARCHAR2(10 BYTE),
  DETALLE             VARCHAR2(160 BYTE),
  COD_PAIS            VARCHAR2(5 BYTE),
  COD_PROVINCIA       VARCHAR2(5 BYTE),
  COD_CANTON          VARCHAR2(5 BYTE),
  COD_DISTRITO        VARCHAR2(5 BYTE),
  COD_PUEBLO          VARCHAR2(5 BYTE),
  ES_DEFAULT          VARCHAR2(1 BYTE) CONSTRAINT NN_DIR_PERSONAS_ES_DEFAULT NOT NULL,
  COLONIA             VARCHAR2(100 BYTE),
  ZONA                VARCHAR2(30 BYTE),
  IND_ESTADO          VARCHAR2(1 BYTE) DEFAULT 'S',
  INCLUIDO_POR        VARCHAR2(10 BYTE) DEFAULT TRIM(SUBSTR(NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'),USER),1,10)),
  FEC_INCLUSION       DATE DEFAULT SYSDATE,
  MODIFICADO_POR      VARCHAR2(10 BYTE) DEFAULT TRIM(SUBSTR(NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'),USER),1,10)),
  FECHA_MODIFICACION  DATE
)
TABLESPACE DATA_EFD
LOGGING
NOCOMPRESS
NOCACHE;

COMMENT ON TABLE PA.DIR_PERSONAS IS 'Direccion de personas';

CREATE UNIQUE INDEX PA.PK_DIRPERSONAS ON PA.DIR_PERSONAS (COD_PERSONA, COD_DIRECCION) TABLESPACE IND_EFD;

ALTER TABLE PA.DIR_PERSONAS ADD (
  CONSTRAINT CK_DIRPERSONAS_ESTADO CHECK (IND_ESTADO IN ('S','N')) ENABLE VALIDATE,
  CONSTRAINT CK_DIRPERSONAS_TIPDIR CHECK (TIP_DIRECCION IN ('1', '2', '3','4')) ENABLE VALIDATE,
  CONSTRAINT CK_DIR_PERSONAS_ES_DEFAULT CHECK (ES_DEFAULT IN ('S','N')) ENABLE VALIDATE,
  CONSTRAINT PK_DIRPERSONAS PRIMARY KEY (COD_PERSONA, COD_DIRECCION) USING INDEX PA.PK_DIRPERSONAS ENABLE VALIDATE
);

CREATE INDEX PA.DIR_PERSONAS_FK2 ON PA.DIR_PERSONAS (COD_PAIS, COD_PROVINCIA, COD_CANTON, COD_DISTRITO, COD_PUEBLO) TABLESPACE PA_IDX;
CREATE INDEX PA.DIR_PERSONAS_FK3 ON PA.DIR_PERSONAS (COD_PAIS, COD_PROVINCIA, COD_CANTON) TABLESPACE PA_IDX;
CREATE INDEX PA.DIR_PERSONAS_FK4 ON PA.DIR_PERSONAS (COD_PAIS) TABLESPACE PA_IDX;
CREATE INDEX PA.DIR_PERSONAS_FK5 ON PA.DIR_PERSONAS (COD_PAIS, COD_PROVINCIA, COD_CANTON, COD_DISTRITO) TABLESPACE PA_IDX;
CREATE INDEX PA.DIR_PERSONAS_FK6 ON PA.DIR_PERSONAS (COD_PAIS, COD_PROVINCIA) TABLESPACE PA_IDX;
CREATE INDEX PA.IDX_DIRP_PER_DEF_DIR ON PA.DIR_PERSONAS (COD_PERSONA, ES_DEFAULT, COD_DIRECCION) TABLESPACE PA_IDX;
CREATE INDEX PA.IND_DIRPERSONAS_CODPERSONA ON PA.DIR_PERSONAS (COD_PERSONA) TABLESPACE IND_EFD;

CREATE OR REPLACE TRIGGER PA.DIR_PERSONAS_NOENTER
BEFORE INSERT OR UPDATE ON PA.DIR_PERSONAS
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
BEGIN
  IF INSERTING OR UPDATING THEN
    :new.detalle := REPLACE(:new.detalle, CHR(13), '');
    :new.detalle := REPLACE(:new.detalle, CHR(10), '');
    :new.detalle := REPLACE(:new.detalle, CHR(39), '');
  END IF;
END;
/

CREATE OR REPLACE TRIGGER PA.DIR_PERSONAS_TRG01
BEFORE INSERT OR UPDATE ON PA.DIR_PERSONAS
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
BEGIN
  IF INSERTING THEN
    :New.incluido_por := TRIM(SUBSTR(NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'),USER),1,10));
    :New.fec_inclusion := SYSDATE;
  ELSIF UPDATING THEN
    :New.modificado_por := TRIM(SUBSTR(NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'),USER),1,10));
    :New.fecha_modificacion := SYSDATE;
    IF :New.incluido_por != :Old.incluido_por THEN
      :New.incluido_por := :Old.incluido_por;
    END IF;
    IF :New.fec_inclusion != :Old.fec_inclusion THEN
      :New.fec_inclusion := :Old.fec_inclusion;
    END IF;
  END IF;
END;
/

CREATE OR REPLACE PUBLIC SYNONYM DIR_PERSONAS FOR PA.DIR_PERSONAS;

ALTER TABLE PA.DIR_PERSONAS ADD (
  CONSTRAINT FK_DIRPERSONAS_PERSONAS FOREIGN KEY (COD_PERSONA) REFERENCES PA.PERSONAS (COD_PERSONA) ENABLE VALIDATE,
  CONSTRAINT FK_DIR_PERSONAS_CANTONES FOREIGN KEY (COD_PAIS, COD_PROVINCIA, COD_CANTON) REFERENCES PA.CANTONES (COD_PAIS, COD_PROVINCIA, COD_CANTON) ENABLE VALIDATE,
  CONSTRAINT FK_DIR_PERSONAS_COD_PAIS FOREIGN KEY (COD_PAIS) REFERENCES PA.PAIS (COD_PAIS) ENABLE VALIDATE,
  CONSTRAINT FK_DIR_PERSONAS_DISTRITOS FOREIGN KEY (COD_PAIS, COD_PROVINCIA, COD_CANTON, COD_DISTRITO) REFERENCES PA.DISTRITOS (COD_PAIS, COD_PROVINCIA, COD_CANTON, COD_DISTRITO) ENABLE VALIDATE,
  CONSTRAINT FK_DIR_PERSONAS_PROVINCIAS FOREIGN KEY (COD_PAIS, COD_PROVINCIA) REFERENCES PA.PROVINCIAS (COD_PAIS, COD_PROVINCIA) ENABLE VALIDATE,
  CONSTRAINT FK_DIR_PERSONAS_PUEBLOS FOREIGN KEY (COD_PAIS, COD_PROVINCIA, COD_CANTON, COD_DISTRITO, COD_PUEBLO) REFERENCES PA.PUEBLOS (COD_PAIS, COD_PROVINCIA, COD_CANTON, COD_DISTRITO, COD_PUEBLO) ENABLE VALIDATE
);

