DROP TABLE PA.PA_REPORTES_AUTOMATICOS_HIST CASCADE CONSTRAINTS;

CREATE TABLE PA.PA_REPORTES_AUTOMATICOS_HIST
(
  CODIGO_REPORTE      NUMBER,
  CODIGO_REFERENCIA   VARCHAR2(200 BYTE),
  FECHA_REPORTE       DATE,
  ID_APLICACION       NUMBER,
  ID_TIPO_DOCUMENTO   VARCHAR2(5 BYTE),
  ORIGEN_PKM          VARCHAR2(100 BYTE),
  URL_REPORTE         VARCHAR2(4000 BYTE),
  FORMATO_DOCUMENTO   VARCHAR2(30 BYTE),
  DIRECTORIO_DESTINO  VARCHAR2(600 BYTE),
  NOMBRE_ARCHIVO      VARCHAR2(100 BYTE),
  ENVIAR_API          VARCHAR2(1 BYTE),
  ESTADO_REPORTE      VARCHAR2(5 BYTE),
  FECHA_PROCESO       DATE,
  ADICIONADO_POR      VARCHAR2(30 BYTE),
  FECHA_ADICION       DATE,
  MODIFICADO_POR      VARCHAR2(30 BYTE),
  FECHA_MODIFICACION  DATE,
  MENSAJE             VARCHAR2(4000 BYTE),
  IDPROCESO           VARCHAR2(150 BYTE)
)
TABLESPACE PA_DAT
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE INDEX PA.ESTADO_TIPO_DOC_IDPROC_IDX_H ON PA.PA_REPORTES_AUTOMATICOS_HIST
(ESTADO_REPORTE, ID_TIPO_DOCUMENTO, IDPROCESO, ORIGEN_PKM)
LOGGING
TABLESPACE PA_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX PA.REP_AUTOM_COD_REF_IDX_H ON PA.PA_REPORTES_AUTOMATICOS_HIST
(CODIGO_REFERENCIA)
LOGGING
TABLESPACE PA_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX PA.REP_AUTOM_ORIGEN_IDX_H ON PA.PA_REPORTES_AUTOMATICOS_HIST
(ORIGEN_PKM)
LOGGING
TABLESPACE PA_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );
