DROP TABLE PA.PA_AUTO_INDEXADO CASCADE CONSTRAINTS;

CREATE TABLE PA.PA_AUTO_INDEXADO
(
  CODIGO_REPORTE       NUMBER,
  APPLICATIONID        NUMBER,
  F_DOCUMENT_TYPE      VARCHAR2(5 BYTE),
  TIPO_IDENTIFICACION  VARCHAR2(4000 BYTE),
  IDENTIFICACION       VARCHAR2(4000 BYTE),
  F_NUM_PRESTAMO       VARCHAR2(4000 BYTE),
  F_PREST_ANTERIOR     VARCHAR2(4000 BYTE),
  TIPO_ARCHIVO         VARCHAR2(100 BYTE),
  ID_TEMPFUD           VARCHAR2(4000 BYTE),
  F_ORIGEN             VARCHAR2(100 BYTE),
  URL_REPORTE          VARCHAR2(4000 BYTE),
  NOMBRE_ARCHIVO       VARCHAR2(100 BYTE),
  CODIGO_REFERENCIA    VARCHAR2(200 BYTE),
  ENVIAR_API           VARCHAR2(1 BYTE),
  CODIGO_AGENCIA       NUMBER,
  NOMBRE_AGENCIA       VARCHAR2(80 BYTE),
  ESTADO_REPORTE       VARCHAR2(5 BYTE),
  PRIMER_NOMBRE        VARCHAR2(25 BYTE),
  SEGUNDO_NOMBRE       VARCHAR2(25 BYTE),
  PRIMER_APELLIDO      VARCHAR2(25 BYTE),
  SEGUNDO_APELLIDO     VARCHAR2(25 BYTE),
  NACIONALIDAD         VARCHAR2(20 BYTE),
  IDPROCESO            VARCHAR2(150 BYTE)
)
TABLESPACE PA_DAT
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE UNIQUE INDEX PA.PK_AUTO_INDEXADO ON PA.PA_AUTO_INDEXADO
(CODIGO_REPORTE)
LOGGING
TABLESPACE PA_DAT
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE PA.PA_AUTO_INDEXADO ADD (
  CONSTRAINT PK_AUTO_INDEXADO
  PRIMARY KEY
  (CODIGO_REPORTE)
  USING INDEX PA.PK_AUTO_INDEXADO
  ENABLE VALIDATE);


CREATE INDEX PA.AUTO_INDEXADO_IDX01 ON PA.PA_AUTO_INDEXADO
(ESTADO_REPORTE, F_DOCUMENT_TYPE, F_ORIGEN)
LOGGING
TABLESPACE PA_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX PA.AUTO_INDEXADO_IDX02 ON PA.PA_AUTO_INDEXADO
(CODIGO_REFERENCIA)
LOGGING
TABLESPACE PA_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX PA.AUTO_INDEXADO_IDX03 ON PA.PA_AUTO_INDEXADO
(F_ORIGEN)
LOGGING
TABLESPACE PA_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE OR REPLACE PUBLIC SYNONYM PA_AUTO_INDEXADO FOR PA.PA_AUTO_INDEXADO;


GRANT SELECT ON PA.PA_AUTO_INDEXADO TO BPR;

GRANT SELECT ON PA.PA_AUTO_INDEXADO TO PR WITH GRANT OPTION;
