-- Entorno: QA02
-- Schema: PA
-- Fecha: 2026-04-24
-- Origen: DDL pegado por el usuario desde QA ADEMI 02 / QA02.
-- Motivo: Caso de borrado del cliente/persona 1202121 con ORA-02292.
-- Observacion: DDL normalizado para consulta del repo. Conserva estructura,
-- constraints, indices, FKs, sinonimo y triggers de impacto directo.

DROP TABLE PA.PERSONAS CASCADE CONSTRAINTS;

CREATE TABLE PA.PERSONAS
(
  COD_PERSONA         VARCHAR2(15 BYTE),
  COD_PER_FISICA      VARCHAR2(15 BYTE),
  COD_PER_JURIDICA    VARCHAR2(15 BYTE),
  ES_FISICA           VARCHAR2(1 BYTE),
  NOMBRE              VARCHAR2(120 BYTE) CONSTRAINT NN_PERSONAS_NOMBRE NOT NULL,
  IND_CLTE_I2000      VARCHAR2(1 BYTE),
  PAGA_IMP_LEY288     VARCHAR2(1 BYTE) DEFAULT 'S',
  BENEF_PAG_LEY288    VARCHAR2(1 BYTE) DEFAULT 'S',
  COD_VINCULACION     VARCHAR2(2 BYTE),
  COD_SEC_CONTABLE    VARCHAR2(6 BYTE),
  ADICIONADO_POR      VARCHAR2(10 BYTE),
  FECHA_ADICION       DATE,
  MODIFICADO_POR      VARCHAR2(10 BYTE),
  FECHA_MODIFICACION  DATE,
  CODIGO_SUSTITUTO    VARCHAR2(15 BYTE),
  ESTADO_PERSONA      VARCHAR2(1 BYTE) DEFAULT 'A',
  COBR_NODGII_132011  VARCHAR2(1 BYTE) DEFAULT 'S',
  LLENO_FATCA         VARCHAR2(1 BYTE),
  IMPRIMIO_FATCA      VARCHAR2(1 BYTE),
  ES_FATCA            VARCHAR2(1 BYTE),
  FEC_ACTUALIZACION   DATE,
  TEL_VERIFICADO      VARCHAR2(1 BYTE) DEFAULT 'N'
)
TABLESPACE DATA_EFD
LOGGING
NOCOMPRESS
NOCACHE;

COMMENT ON TABLE PA.PERSONAS IS 'Esta tabla es utilizada para registrar todas las Persona Fisicas y Juridicas del Sistema';

CREATE UNIQUE INDEX PA.PK_PERSONAS ON PA.PERSONAS (COD_PERSONA) TABLESPACE IND_EFD;

ALTER TABLE PA.PERSONAS ADD (
  CONSTRAINT CK_ESTADO_PERSONAS CHECK (ESTADO_PERSONA IN ('A','R','I','N')) ENABLE VALIDATE,
  CONSTRAINT CK_PERSONAS_BENEFPAGLEY288 CHECK (BENEF_PAG_LEY288 IN ('S', 'N')) ENABLE VALIDATE,
  CONSTRAINT CK_PERSONAS_COBRNODGII CHECK (COBR_NODGII_132011 IN ('S', 'N')) ENABLE VALIDATE,
  CONSTRAINT CK_PERSONAS_ESFATCA CHECK (ES_FATCA IN ('S', 'N')) ENABLE VALIDATE,
  CONSTRAINT CK_PERSONAS_ESFISICA CHECK (ES_FISICA IN ('S','N')) ENABLE VALIDATE,
  CONSTRAINT CK_PERSONAS_IMPRIMIOFATCA CHECK (IMPRIMIO_FATCA IN ('S', 'N')) ENABLE VALIDATE,
  CONSTRAINT CK_PERSONAS_INDCLTEI2000 CHECK (IND_CLTE_I2000 IN ('S', 'N')) ENABLE VALIDATE,
  CONSTRAINT CK_PERSONAS_LLENOFATCA CHECK (LLENO_FATCA IN ('S', 'N')) ENABLE VALIDATE,
  CONSTRAINT CK_PERSONAS_PAGAIMPLEY288 CHECK (PAGA_IMP_LEY288 IN ('S', 'N')) ENABLE VALIDATE,
  CONSTRAINT PK_PERSONAS PRIMARY KEY (COD_PERSONA) USING INDEX PA.PK_PERSONAS ENABLE VALIDATE
);

CREATE INDEX PA.IDX_COBR_NODGII ON PA.PERSONAS (COBR_NODGII_132011, COD_PER_JURIDICA, ES_FISICA) TABLESPACE PA_IND;
CREATE INDEX PA.IDX_PERSONAS_NOMBRE ON PA.PERSONAS (NOMBRE) TABLESPACE IND_EFD;
CREATE INDEX PA.IDX01_PERSONAS ON PA.PERSONAS (TO_NUMBER("COD_PERSONA"), ESTADO_PERSONA) TABLESPACE PA_IDX;
CREATE INDEX PA.IND_PERSONAS_CODPERFISICA ON PA.PERSONAS (COD_PER_FISICA) TABLESPACE IND_EFD;
CREATE INDEX PA.IND_PERSONAS_CODPERJURIDICA ON PA.PERSONAS (COD_PER_JURIDICA) TABLESPACE IND_EFD;
CREATE INDEX PA.PERSONAS_FK2 ON PA.PERSONAS (COD_VINCULACION) TABLESPACE PA_IDX;

CREATE OR REPLACE TRIGGER PA.AUDITORIA_PERSONAS
BEFORE INSERT OR UPDATE ON PA.PERSONAS
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
BEGIN
  IF INSERTING THEN
    :new.adicionado_por := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'),USER);
    :new.fecha_adicion := SYSDATE;
  ELSIF UPDATING THEN
    :new.modificado_por := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'),USER);
    :new.fecha_modificacion := SYSDATE;
  END IF;

  IF (:new.cod_Sec_contable IS NULL OR LENGTH(:new.cod_Sec_contable) = 2)
     AND :new.es_fisica = 'S' THEN
    :new.cod_Sec_contable := '030202';
  END IF;
END;
/

CREATE OR REPLACE TRIGGER PA.ESTADO_CLIENTES
AFTER UPDATE ON PA.PERSONAS
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
BEGIN
  IF :old.estado_persona != :new.estado_persona THEN
    UPDATE cliente
       SET estado_cliente = :new.estado_persona
     WHERE cod_cliente = :new.cod_persona;

    UPDATE clientes_b2000
       SET estado_cliente = :new.estado_persona
     WHERE cod_cliente = :new.cod_persona;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER PA.PERSONAS_NOENTER
BEFORE INSERT OR UPDATE ON PA.PERSONAS
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
BEGIN
  IF INSERTING OR UPDATING THEN
    :new.nombre := REPLACE(:new.nombre, CHR(13), '');
    :new.nombre := REPLACE(:new.nombre, CHR(10), '');
    :new.nombre := REPLACE(:new.nombre, CHR(39), '');

    IF INSERTING AND NVL(:new.es_fisica, 'S') = 'N' THEN
      :new.cobr_nodgii_132011 := 'S';
    END IF;
  END IF;
END;
/

CREATE OR REPLACE PUBLIC SYNONYM PERSONAS FOR PA.PERSONAS;

ALTER TABLE PA.PERSONAS ADD (
  CONSTRAINT FK_PERSONAS_CODVINCULACION FOREIGN KEY (COD_VINCULACION) REFERENCES PA.TIPOS_VINCULACION (COD_VINCULACION) ENABLE VALIDATE,
  CONSTRAINT FK_PERS_PERFISICAS FOREIGN KEY (COD_PER_FISICA) REFERENCES PA.PERSONAS_FISICAS (COD_PER_FISICA) ENABLE VALIDATE,
  CONSTRAINT FK_PERS_PERJURID FOREIGN KEY (COD_PER_JURIDICA) REFERENCES PA.PERSONAS_JURIDICAS (COD_PER_JURIDICA) ENABLE VALIDATE
);

