-- Entorno: QA02
-- Schema: PA
-- Fecha: 2026-04-24
-- Origen: DDL pegado por el usuario desde QA ADEMI 02 / QA02.
-- Motivo: Caso de borrado del cliente/persona 1202121 con ORA-02292.
-- Observacion: DDL normalizado para consulta del repo. Conserva estructura,
-- constraints, indices, FKs, sinonimo y triggers de impacto directo.

DROP TABLE PA.PERSONAS_FISICAS CASCADE CONSTRAINTS;

CREATE TABLE PA.PERSONAS_FISICAS
(
  COD_PER_FISICA        VARCHAR2(15 BYTE),
  EST_CIVIL             VARCHAR2(1 BYTE),
  SEXO                  VARCHAR2(1 BYTE) CONSTRAINT NN_PERS_FIS_SEXO NOT NULL,
  FEC_NACIMIENTO        DATE,
  PRIMER_APELLIDO       VARCHAR2(25 BYTE) CONSTRAINT NN_PERSONASFISICAS_PRIAPELLIDO NOT NULL,
  SEGUNDO_APELLIDO      VARCHAR2(25 BYTE),
  PRIMER_NOMBRE         VARCHAR2(25 BYTE) CONSTRAINT NN_PERSONASFISICAS_PRINOMBRE NOT NULL,
  SEGUNDO_NOMBRE        VARCHAR2(30 BYTE),
  PROFESION             VARCHAR2(5 BYTE),
  IDIOMA_CORREO         VARCHAR2(4 BYTE),
  ES_MAL_DEUDOR         VARCHAR2(1 BYTE),
  CONYUGUE              VARCHAR2(15 BYTE),
  NACIONALIDAD          VARCHAR2(20 BYTE),
  COD_SECTOR            VARCHAR2(3 BYTE),
  ESTATAL               VARCHAR2(1 BYTE),
  EMAIL_USUARIO         VARCHAR2(80 BYTE),
  EMAIL_SERVIDOR        VARCHAR2(30 BYTE),
  NIVEL_ESTUDIOS        VARCHAR2(5 BYTE),
  TIPO_VIVIENDA         VARCHAR2(5 BYTE),
  NUM_HIJOS             NUMBER(3) CONSTRAINT NN_PERS_FIS_NUM_HIJOS NOT NULL,
  NUM_DEPENDIENTES      NUMBER(3) CONSTRAINT NN_PERS_FIS_NUM_DEPENDIENTES NOT NULL,
  ES_RESIDENTE          VARCHAR2(1 BYTE),
  TIEMPO_VIVIEN_ACT     NUMBER(4),
  EVAL_REF_BANCARIA     VARCHAR2(1 BYTE) CONSTRAINT NN_PERS_FIS_EVAL_REF_BANCARIA NOT NULL,
  EVAL_REF_TARJETAS     VARCHAR2(1 BYTE) CONSTRAINT NN_PERS_FIS_EVAL_REF_TARJETAS NOT NULL,
  EVAL_REF_LABORAL      VARCHAR2(1 BYTE) CONSTRAINT NN_PERS_FIS_EVAL_REF_LABORAL NOT NULL,
  TOTAL_INGRESOS        NUMBER(18,2) CONSTRAINT NN_PERS_FIS_TOTAL_INGRESOS NOT NULL,
  COD_PAIS              VARCHAR2(5 BYTE) CONSTRAINT NN_PERS_FISICAS_COD_PAIS NOT NULL,
  INCLUIDO_POR          VARCHAR2(10 BYTE),
  FEC_INCLUSION         DATE CONSTRAINT NN_PERS_FIS_FEC_INCLUSION NOT NULL,
  MODIFICADO_POR        VARCHAR2(10 BYTE),
  FEC_MODIFICACION      DATE,
  SCORING               NUMBER(6),
  ACTIVIDAD             VARCHAR2(200 BYTE),
  RANGO_INGRESOS        NUMBER(2),
  CASADA_APELLIDO       VARCHAR2(15 BYTE),
  ES_FUNCIONARIO        VARCHAR2(1 BYTE),
  ES_PEPS               VARCHAR2(1 BYTE),
  COD_ACTIVIDAD         VARCHAR2(6 BYTE),
  COD_SUBACTIVIDAD      NUMBER,
  TIPO_PERSONA          VARCHAR2(2 BYTE),
  TIPO_CLIENTE          NUMBER(18),
  COD_PAIS_PADRE        VARCHAR2(5 BYTE),
  COD_PAIS_MADRE        VARCHAR2(5 BYTE),
  COD_PAIS_CONYUGUE     VARCHAR2(5 BYTE),
  MAS_180_DIAS_EEUU     VARCHAR2(5 BYTE),
  COD_FINALIDAD         VARCHAR2(3 BYTE),
  PESO                  NUMBER(3),
  ESTATURA              VARCHAR2(5 BYTE),
  ACTIVIDAD_POLIZAH     VARCHAR2(5 BYTE),
  DEPORTE_POLIZAH       VARCHAR2(5 BYTE),
  PESO_POLIZAH          NUMBER(3),
  ESTATURA_POLIZAH      VARCHAR2(5 BYTE),
  APELLIDO_CASADA       VARCHAR2(25 BYTE),
  TERCER_NOMBRE         VARCHAR2(25 BYTE),
  TIPO_SOC_CONYUGAL     VARCHAR2(10 BYTE) DEFAULT 'S',
  IND_FALLECIMIENTO     VARCHAR2(1 BYTE),
  FEC_FALLECIMIENTO     DATE,
  GPO_RIESGO            VARCHAR2(5 BYTE),
  NUM_EMPLEADOS         NUMBER(10),
  VENTAS_INGRESOS       NUMBER(22,2),
  CP_TOTAL_ACTIVO       NUMBER(22,2),
  IND_CLTE_VIP          VARCHAR2(1 BYTE),
  TIPO_GEN_DIVISAS      VARCHAR2(2 BYTE),
  OCUPACION_CLASIF_NAC  VARCHAR2(5 BYTE)
)
TABLESPACE DATA_EFD
LOGGING
NOCOMPRESS
NOCACHE;

COMMENT ON TABLE PA.PERSONAS_FISICAS IS 'Tabla utilizada para Registrar todas las personas de tipo Fisica del Sistema';

CREATE UNIQUE INDEX PA.PK_PERSONASFISICAS ON PA.PERSONAS_FISICAS (COD_PER_FISICA) TABLESPACE IND_EFD;

ALTER TABLE PA.PERSONAS_FISICAS ADD (
  CONSTRAINT CK_PERFIS_ESFUNCIONARIO CHECK (ES_FUNCIONARIO IN ('S', 'N')) ENABLE VALIDATE,
  CONSTRAINT CK_PERFIS_ESPEPS CHECK (ES_PEPS IN ('S', 'N')) ENABLE VALIDATE,
  CONSTRAINT CK_PERSFISICA_TIPSOCONY CHECK (TIPO_SOC_CONYUGAL IN ('S','C')) ENABLE VALIDATE,
  CONSTRAINT CK_PERSONASFISICAS_ESMALDEUDOR CHECK (ES_MAL_DEUDOR IN ('S','N')) ENABLE VALIDATE,
  CONSTRAINT CK_PERSONASFISICAS_ESTCIVIL CHECK (EST_CIVIL IN ('S','V','D','C','U','O')) ENABLE VALIDATE,
  CONSTRAINT CK_PERSONASFISICAS_SEXO CHECK (SEXO IN ('F','M')) ENABLE VALIDATE,
  CONSTRAINT CK_PERS_FIS_ES_RESIDENTE CHECK (ES_RESIDENTE IN ('S','N')) ENABLE VALIDATE,
  CONSTRAINT CK_PERS_FIS_EVAL_REF_BANCARIA CHECK (EVAL_REF_BANCARIA IN ('V','I','M','N','R')) ENABLE VALIDATE,
  CONSTRAINT CK_PERS_FIS_EVAL_REF_LABORAL CHECK (EVAL_REF_LABORAL IN ('C','D','E')) ENABLE VALIDATE,
  CONSTRAINT CK_PERS_FIS_EVAL_REF_TARJETAS CHECK (EVAL_REF_TARJETAS IN ('V','I','M','N','R')) ENABLE VALIDATE,
  CONSTRAINT PK_PERSONASFISICAS PRIMARY KEY (COD_PER_FISICA) USING INDEX PA.PK_PERSONASFISICAS ENABLE VALIDATE
);

CREATE INDEX PA.IDX_PERFIS_NOMCOMPLETO ON PA.PERSONAS_FISICAS (PRIMER_APELLIDO, SEGUNDO_APELLIDO, PRIMER_NOMBRE, SEGUNDO_NOMBRE) TABLESPACE IND_EFD;
CREATE INDEX PA.IND_PERFISI_INCLUIDOPOR ON PA.PERSONAS_FISICAS (INCLUIDO_POR) TABLESPACE IND_EFD;
CREATE INDEX PA.IND_PERFISI_MODIFICAPOR ON PA.PERSONAS_FISICAS (MODIFICADO_POR) TABLESPACE IND_EFD;
CREATE INDEX PA.IND_PERSONASFISICAS_CONYUGUE ON PA.PERSONAS_FISICAS (CONYUGUE) TABLESPACE IND_EFD;
CREATE INDEX PA.PERSONAS_FISICAS_FK1 ON PA.PERSONAS_FISICAS (NIVEL_ESTUDIOS) TABLESPACE PA_IND;
CREATE INDEX PA.PERSONAS_FISICAS_FK10 ON PA.PERSONAS_FISICAS (PROFESION) TABLESPACE PA_IND;
CREATE INDEX PA.PERSONAS_FISICAS_FK11 ON PA.PERSONAS_FISICAS (IDIOMA_CORREO) TABLESPACE PA_IND;
CREATE INDEX PA.PERSONAS_FISICAS_FK2 ON PA.PERSONAS_FISICAS (TIPO_PERSONA) TABLESPACE PA_IND;
CREATE INDEX PA.PERSONAS_FISICAS_FK3 ON PA.PERSONAS_FISICAS (TIPO_CLIENTE) TABLESPACE PA_IND;
CREATE INDEX PA.PERSONAS_FISICAS_FK4 ON PA.PERSONAS_FISICAS (COD_PAIS_PADRE) TABLESPACE PA_IND;
CREATE INDEX PA.PERSONAS_FISICAS_FK5 ON PA.PERSONAS_FISICAS (COD_PAIS) TABLESPACE PA_IND;
CREATE INDEX PA.PERSONAS_FISICAS_FK6 ON PA.PERSONAS_FISICAS (COD_PAIS_MADRE) TABLESPACE PA_IND;
CREATE INDEX PA.PERSONAS_FISICAS_FK7 ON PA.PERSONAS_FISICAS (COD_PAIS_CONYUGUE) TABLESPACE PA_IND;
CREATE INDEX PA.PERSONAS_FISICAS_FK8 ON PA.PERSONAS_FISICAS (TIPO_VIVIENDA) TABLESPACE PA_IND;
CREATE INDEX PA.PERSONAS_FISICAS_FK9 ON PA.PERSONAS_FISICAS (COD_FINALIDAD) TABLESPACE PA_IND;

CREATE OR REPLACE TRIGGER PA.ACTUALIZA_FEC_ING_PER_FIS
BEFORE UPDATE ON PA.PERSONAS_FISICAS
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
BEGIN
  IF UPDATING THEN
    IF NVL(:OLD.RANGO_INGRESOS,0) != NVL(:NEW.RANGO_INGRESOS,0) THEN
      UPDATE PA.CLIENTE
         SET FEC_ACTUALIZA_INGRESOS = TRUNC(SYSDATE)
       WHERE COD_CLIENTE = :new.COD_PER_FISICA;
    END IF;
  END IF;
END ACTUALIZA_FEC_ING_PER_FIS;
/

CREATE OR REPLACE TRIGGER PA.PERSONAS_FISICAS_NOENTER
BEFORE INSERT OR UPDATE ON PA.PERSONAS_FISICAS
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
BEGIN
  IF INSERTING OR UPDATING THEN
    :new.primer_nombre := REPLACE(:new.primer_nombre, CHR(13), '');
    :new.primer_nombre := REPLACE(:new.primer_nombre, CHR(10), '');
    :new.primer_nombre := REPLACE(:new.primer_nombre, CHR(39), '');
    :new.segundo_nombre := REPLACE(:new.segundo_nombre, CHR(13), '');
    :new.segundo_nombre := REPLACE(:new.segundo_nombre, CHR(10), '');
    :new.segundo_nombre := REPLACE(:new.segundo_nombre, CHR(39), '');
    :new.primer_apellido := REPLACE(:new.primer_apellido, CHR(13), '');
    :new.primer_apellido := REPLACE(:new.primer_apellido, CHR(10), '');
    :new.primer_apellido := REPLACE(:new.primer_apellido, CHR(39), '');
    :new.segundo_apellido := REPLACE(:new.segundo_apellido, CHR(13), '');
    :new.segundo_apellido := REPLACE(:new.segundo_apellido, CHR(10), '');
    :new.segundo_apellido := REPLACE(:new.segundo_apellido, CHR(39), '');
    :new.email_usuario := NVL(Email_Validacion(:new.email_usuario), Email_Validacion(:new.email_usuario || :new.email_servidor));
    :new.email_servidor := NULL;

    IF :new.cod_finalidad IS NULL THEN
      :new.cod_finalidad := '011';
    END IF;
  END IF;
END;
/

CREATE OR REPLACE PUBLIC SYNONYM PERSONAS_FISICAS FOR PA.PERSONAS_FISICAS;

ALTER TABLE PA.PERSONAS_FISICAS ADD (
  CONSTRAINT FK_PERFIS_FINALIDAD FOREIGN KEY (COD_FINALIDAD) REFERENCES PA.FINALIDAD_PERSONAS (COD_FINALIDAD) ENABLE VALIDATE,
  CONSTRAINT FK_PERFIS_PAIS FOREIGN KEY (COD_PAIS) REFERENCES PA.PAIS (COD_PAIS) ENABLE VALIDATE,
  CONSTRAINT FK_PERFIS_PAIS_CONYU FOREIGN KEY (COD_PAIS_CONYUGUE) REFERENCES PA.PAIS (COD_PAIS) ENABLE VALIDATE,
  CONSTRAINT FK_PERFIS_PAIS_MADRE FOREIGN KEY (COD_PAIS_MADRE) REFERENCES PA.PAIS (COD_PAIS) ENABLE VALIDATE,
  CONSTRAINT FK_PERFIS_PAIS_PADRE FOREIGN KEY (COD_PAIS_PADRE) REFERENCES PA.PAIS (COD_PAIS) ENABLE VALIDATE,
  CONSTRAINT FK_PERFIS_TIPOCLIENTE FOREIGN KEY (TIPO_CLIENTE) REFERENCES PA.TIPO_CLIENTE (CODIGO) ENABLE VALIDATE,
  CONSTRAINT FK_PERFIS_TIPOPERSONA FOREIGN KEY (TIPO_PERSONA) REFERENCES PA.TIPO_PERSONA (CODIGO) ENABLE VALIDATE,
  CONSTRAINT FK_PERSONASFISICAS_IDIOMAS FOREIGN KEY (IDIOMA_CORREO) REFERENCES PA.IDIOMAS (COD_IDIOMA) ENABLE VALIDATE,
  CONSTRAINT FK_PERS_FIS_CAT_PROFESIONES FOREIGN KEY (PROFESION) REFERENCES PA.CAT_PROFESIONES (COD_PROFESION) ENABLE VALIDATE,
  CONSTRAINT FK_PERS_FIS_NIVEL_ESTUDIOS FOREIGN KEY (NIVEL_ESTUDIOS) REFERENCES PA.NIVEL_ESTUDIOS (COD_NIVEL) ENABLE VALIDATE,
  CONSTRAINT FK_PERS_FIS_PERSONAS_FISICAS FOREIGN KEY (CONYUGUE) REFERENCES PA.PERSONAS_FISICAS (COD_PER_FISICA) ENABLE VALIDATE,
  CONSTRAINT FK_PERS_FIS_TIPOS_VIVIENDA FOREIGN KEY (TIPO_VIVIENDA) REFERENCES PA.TIPOS_VIVIENDA (TIPO_VIVIENDA) ENABLE VALIDATE
);

