
  CREATE TABLE "PR"."PR_CREDITOS" 
   (	"CODIGO_EMPRESA" NUMBER(4,0), 
	"NO_CREDITO" NUMBER(7,0), 
	"CODIGO_AGENCIA" NUMBER(5,0) CONSTRAINT "NN_PR_CREDITOS_CODAGENCIA" NOT NULL ENABLE, 
	"CODIGO_MONEDA" NUMBER(2,0) CONSTRAINT "NN_PR_CREDITOS_CODMONEDA" NOT NULL ENABLE, 
	"CODIGO_CLIENTE" NUMBER(7,0) CONSTRAINT "NN_PR_CREDITOS_CODCLIENTE" NOT NULL ENABLE, 
	"CODIGO_DIRECCION" NUMBER(8,0), 
	"TIPO_CREDITO" NUMBER(3,0) CONSTRAINT "NN_PR_CREDITOS_TIPCREDITO" NOT NULL ENABLE, 
	"ESTADO" VARCHAR2(2 BYTE) CONSTRAINT "NN_PR_CREDITOS_ESTADO" NOT NULL ENABLE, 
	"MONTO_CREDITO" NUMBER(16,2) CONSTRAINT "NN_PR_CREDITOS_MTOCREDITO" NOT NULL ENABLE, 
	"ES_LINEA_CREDITO" VARCHAR2(1 BYTE) CONSTRAINT "NN_PR_CREDITOS_ESLINEACREDITO" NOT NULL ENABLE, 
	"TIPO_LINEA" VARCHAR2(1 BYTE), 
	"MANEJO" NUMBER(1,0), 
	"MODALIDAD_COBRO" VARCHAR2(1 BYTE) CONSTRAINT "NN_PR_CREDITOS_MODALICOBRO" NOT NULL ENABLE, 
	"TIPO_INTERESES" VARCHAR2(1 BYTE) CONSTRAINT "NN_PR_CREDITOS_TIPINTERESES" NOT NULL ENABLE, 
	"TIPO_CALENDARIO" NUMBER(1,0) CONSTRAINT "NN_PR_CREDITOS_TIPCALENDARIO" NOT NULL ENABLE, 
	"TIPO_CUOTA" VARCHAR2(1 BYTE), 
	"CODIGO_PERIODO_CUOTA" VARCHAR2(2 BYTE) NOT NULL ENABLE, 
	"CODIGO_PERIODO_INTERESES" VARCHAR2(2 BYTE), 
	"PERIODO_COMISION_NORMAL" VARCHAR2(2 BYTE), 
	"COMISION_NORMAL" NUMBER(10,4), 
	"CUOTA" NUMBER(16,2) CONSTRAINT "NN_PR_CREDITOS_CUOTA" NOT NULL ENABLE, 
	"MONTO_DESEMBOLSADO" NUMBER(16,2), 
	"MONTO_PAGADO_PRINCIPAL" NUMBER(16,2), 
	"MONTO_PAGADO_INTERESES" NUMBER(16,2), 
	"INTERESES_ACUMULADOS" NUMBER(16,2), 
	"MONTO_REVALORIZACION" NUMBER(16,2), 
	"INTERESES_EN_SUSPENSO" NUMBER(16,2), 
	"CUOTA_ANTERIOR" NUMBER(16,2), 
	"PLAZO" NUMBER(5,0) CONSTRAINT "NN_PR_CREDITOS_PLAZO" NOT NULL ENABLE, 
	"ID_SISTEMA_EXTERNO" VARCHAR2(15 BYTE), 
	"NO_SOLICITUD" NUMBER(7,0), 
	"NO_CREDITO_ORIGEN" NUMBER(7,0), 
	"TIPO_TASA" VARCHAR2(1 BYTE) CONSTRAINT "NN_PR_CREDITOS_TIPTASA" NOT NULL ENABLE, 
	"CODIGO_TIPO_DE_TASA" VARCHAR2(5 BYTE) CONSTRAINT "NN_PR_CREDITOS_CODTIPTASA" NOT NULL ENABLE, 
	"VARIACION_BASE" NUMBER(10,4), 
	"TASA_INTERES" NUMBER(10,4) CONSTRAINT "NN_PR_CREDITOS_TASAINTERES" NOT NULL ENABLE, 
	"TASA_ORIGINAL" NUMBER(10,4) CONSTRAINT "NN_PR_CREDITOS_TASAORIGINAL" NOT NULL ENABLE, 
	"CODIGO_TASA_MORATORIOS" VARCHAR2(5 BYTE), 
	"VARIACION_MORA" NUMBER(10,4), 
	"TASA_MORATORIOS" NUMBER(10,4), 
	"PERIODO_REVISION_TASA" VARCHAR2(2 BYTE), 
	"VARIACION_MAX_REVISION" NUMBER(10,4), 
	"VARIACION_MAX_TOTAL" NUMBER(10,4), 
	"GRACIA_PRINCIPAL" NUMBER(5,0), 
	"GRACIA_MORA" NUMBER(3,0), 
	"CODIGO_ORIGEN" NUMBER(2,0) CONSTRAINT "NN_PR_CREDITOS_CODORIGEN" NOT NULL ENABLE, 
	"NO_PROGRAMA_ASOCIADO" VARCHAR2(20 BYTE), 
	"CODIGO_EJECUTIVO" VARCHAR2(10 BYTE), 
	"COBRADOR" NUMBER(2,0), 
	"CODIGO_REFERENTE" NUMBER(3,0), 
	"CODIGO_ANALISTA" NUMBER(5,0), 
	"CODIGO_NIVEL_APROBACION" NUMBER(2,0) DEFAULT 0, 
	"F_APERTURA" DATE CONSTRAINT "NN_PR_CREDITOS_FAPERTURA" NOT NULL ENABLE, 
	"F_VENCIMIENTO" DATE, 
	"F_CANCELACION" DATE, 
	"F_ADJUDICACION" DATE, 
	"F_ULTIMA_REVISION" DATE, 
	"F_ULTIMO_PAGO_PRINCIPAL" DATE, 
	"F_ULTIMO_PAGO_INTERESES" DATE, 
	"F_PRIMER_DESEMBOLSO" DATE, 
	"F_ULTIMO_DESEMBOLSO" DATE, 
	"F_PROXIMA_COMISION" DATE, 
	"F_APROBACION" DATE, 
	"F_ULTIMO_PAGO_MORA" DATE, 
	"F_RECONOCIM_INTERESES" DATE, 
	"F_PRINCIPAL_ANTERIOR" DATE, 
	"F_INTERESES_ANTERIOR" DATE, 
	"F_MORA_ANTERIOR" DATE, 
	"F_ULTIMA_REVALORIZACION" DATE, 
	"TIPO_ABONO" VARCHAR2(1 BYTE) CONSTRAINT "NN_PR_CREDITOS_TIPABONO" NOT NULL ENABLE, 
	"CUENTA_ABONO" NUMBER(25,0), 
	"TIPO_DESEMBOLSO" VARCHAR2(1 BYTE) CONSTRAINT "NN_PR_CREDITOS_TIPDESEMBOLSO" NOT NULL ENABLE, 
	"CUENTA_DESEM" NUMBER(25,0), 
	"CONTINUA_COBRO_INTERESES" VARCHAR2(1 BYTE) CONSTRAINT "NN_PR_CREDITOS_CONTCOBROINT" NOT NULL ENABLE, 
	"DIA_PAGO" VARCHAR2(2 BYTE), 
	"MARCA_REV_TASA" VARCHAR2(1 BYTE), 
	"REVALORIZA" VARCHAR2(1 BYTE) CONSTRAINT "NN_PR_CREDITOS_REVALORIZA" NOT NULL ENABLE, 
	"OBSERVACIONES1" VARCHAR2(255 BYTE), 
	"OBSERVACIONES2" VARCHAR2(255 BYTE), 
	"ADICIONADO_POR" VARCHAR2(10 BYTE) CONSTRAINT "NN_PR_CREDITOS_ADIPOR" NOT NULL ENABLE, 
	"FECHA_ADICION" DATE CONSTRAINT "NN_PR_CREDITOS_FECADI" NOT NULL ENABLE, 
	"MODIFICADO_POR" VARCHAR2(10 BYTE), 
	"FECHA_MODIFICACION" DATE, 
	"CODIGO_SUB_APLICACION" NUMBER(3,0) CONSTRAINT "NN_PR_CREDITOS_CODSUBAPLI" NOT NULL ENABLE, 
	"MONTO_VARIACION" NUMBER(16,2), 
	"CODIGO_ACTIVIDAD" NUMBER(5,0), 
	"CODIGO_SUBACTIVIDAD" NUMBER(5,0), 
	"CODIGO_CALIFICACION_SISTEMA" VARCHAR2(5 BYTE), 
	"CODIGO_CALIFICACION_MANUAL" VARCHAR2(5 BYTE), 
	"OBSERVACIONES_CALIFICACION" VARCHAR2(255 BYTE), 
	"ATRASO_PROMEDIO" NUMBER(5,0), 
	"TIPO_COMISION" VARCHAR2(1 BYTE), 
	"PLAN_INVERSION" NUMBER(3,0), 
	"PAIS_DESTINO" NUMBER(6,0), 
	"DEPARTAMENTO_DESTINO" NUMBER(6,0), 
	"MUNICIPIO_DESTINO" NUMBER(6,0), 
	"DISTRITO_DESTINO" NUMBER(6,0), 
	"CODIGO_SUB_CLASE" NUMBER(6,0), 
	"TIPO_MORA" VARCHAR2(1 BYTE), 
	"PORCENTAJE_TASA_MORA" NUMBER(7,4), 
	"APROBADO_POR" VARCHAR2(10 BYTE), 
	"CODIGO_PLAZO" NUMBER(2,0) CONSTRAINT "NN_PR_CREDITOS_CODPLAZO" NOT NULL ENABLE, 
	"TASA_ORIGINAL_MORA" NUMBER(10,4), 
	"MONTO_X_DESEMBOLSAR" NUMBER(16,2), 
	"CALIFICADO_POR" VARCHAR2(10 BYTE), 
	"F_ULTIMA_CALIFICACION" DATE, 
	"PLAZO_OPERACIONES" NUMBER(5,0), 
	"PERMITE_SOBREGIRO" VARCHAR2(1 BYTE), 
	"PORCENTAJE_SOBREGIRO" NUMBER(10,4), 
	"F_PRORROGA" DATE, 
	"F_ULTIMO_PAGO_COMISION" DATE, 
	"F_PROXIMA_REVISION" DATE, 
	"F_ULTIMA_REV_MORA" DATE, 
	"OBSERVACIONES3" VARCHAR2(255 BYTE), 
	"OBSERVACIONES4" VARCHAR2(255 BYTE), 
	"BLOQUEO_DESEMBOLSO" VARCHAR2(1 BYTE), 
	"DESC_CARGOS" VARCHAR2(1 BYTE), 
	"DESC_POLIZA" VARCHAR2(1 BYTE), 
	"DESC_CUOTA" VARCHAR2(1 BYTE), 
	"DESC_COMISION" VARCHAR2(1 BYTE), 
	"ACUMULA_INTERESES" VARCHAR2(1 BYTE), 
	"VARIACION_MINIMA" NUMBER(10,4), 
	"VARIACION_MAXIMA" NUMBER(10,4), 
	"TIPO_REVISION" VARCHAR2(1 BYTE), 
	"PERIODOS_GRACIA_PRINCIPAL" NUMBER(2,0), 
	"F_PAGO_COMISION_ATRASADA" DATE, 
	"TIPO_REGRESO_COBRO" VARCHAR2(2 BYTE), 
	"F_PAGO_COBRO_ADMINISTRATIVO" DATE, 
	"BASE_CALCULO_MORATORIOS" NUMBER(3,0), 
	"INTERESES_ANTICIPADOS" NUMBER(16,2), 
	"INTERESES_ANTES_COBRO_JUDICIAL" NUMBER(16,2), 
	"MARCA_COBRO_ADMINISTRATIVO" VARCHAR2(1 BYTE), 
	"PORC_SALDO_NO_UTILIZADO" NUMBER(10,4), 
	"F_ULTIMO_PAGO_INTERESES_VENC" DATE, 
	"F_PROXIMA_MORA_FLAT" DATE, 
	"RENOVACION" NUMBER(2,0), 
	"COD_NOTARIO" VARCHAR2(15 BYTE), 
	"CLIENTE_PROSPECTO" VARCHAR2(1 BYTE), 
	"NUMERO_CF" VARCHAR2(19 BYTE), 
	"DESCUENTA_INTERESES_DESEMBOLSO" VARCHAR2(1 BYTE), 
	"CANTIDAD_CUOTAS_DESCONTAR" NUMBER(5,0), 
	"NO_POLIZA_BCO" VARCHAR2(25 BYTE), 
	"IND_PR_VEHICULO" VARCHAR2(1 BYTE), 
	"CANTIDAD_COBRO_CARGO" NUMBER(5,0), 
	"DESTINO_DE_FONDOS" VARCHAR2(200 BYTE), 
	"COD_PROMOTOR" VARCHAR2(10 BYTE), 
	"F_RESTRUCTURACION" DATE, 
	"F_RESTRUC_A_VIGENTE" DATE, 
	"RES_APR_INMED" VARCHAR2(5 BYTE), 
	"DIR_SUCURSAL" VARCHAR2(200 BYTE), 
	"MTO_INICIAL_COTIZACION" NUMBER(18,2), 
	"MTO_FINANCIADO" NUMBER(18,2), 
	"VENDEDOR" VARCHAR2(120 BYTE), 
	"PORCIENTO_RETENCION" NUMBER(18,4), 
	"NETO_PAGAR" NUMBER(18,2), 
	"NO_COTIZACION" VARCHAR2(120 BYTE), 
	"GASTOS_CIERRE" NUMBER(18,2), 
	"COMISIONPTO15" NUMBER(18,2), 
	"INT_COMPLETIVO_ACUM" NUMBER(18,2) DEFAULT 0, 
	"NUM_GRUPO_MICROCREDITO" NUMBER(15,0), 
	"SEGREGACION_RD" VARCHAR2(6 BYTE), 
	"ESTADO_APROBACION" VARCHAR2(3 BYTE) DEFAULT 'P', 
	"ESVIDA" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"ESVEHICULO" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"ESINCENDIO" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"UNIDAD_PLAZO" VARCHAR2(1 BYTE), 
	"PLAZO_SEGUN_UNIDAD" NUMBER(6,0), 
	"TIPO_TASA_VEHICULOS" VARCHAR2(3 BYTE), 
	"MORA_SUSPENSO_ACUMUL" NUMBER(16,2), 
	"MORA_INTERES_ACUMUL" NUMBER(16,2), 
	"MON_MORA_PAGADO" NUMBER(16,2), 
	"COD_ENTE_UNIVERSIDAD" VARCHAR2(5 BYTE), 
	"IDCARRERA_UNIVERSIDAD" VARCHAR2(4 BYTE), 
	"MORA_INTERES_ACUMUL_RESP" NUMBER(16,2), 
	"FECHA_ULT_CONTA_POLIZA" DATE, 
	"MONTO_PAGOS_INTERESES_SUSPENSO" NUMBER(18,2), 
	"MONTO_PAGOS_MORA_SUSPENSO" NUMBER(16,2), 
	"ESINCENDIO_PYME" VARCHAR2(1 BYTE), 
	"TIPO_REESTRUCTURACION" VARCHAR2(5 BYTE), 
	"FRE_REV_TASA" VARCHAR2(3 BYTE), 
	 CONSTRAINT "MM_PR_CREDITOS_MTOPAGADOINT" CHECK ( MONTO_PAGADO_INTERESES >=  0             ) ENABLE, 
	 CONSTRAINT "MM_PR_CREDITOS_MTOPAGADOPRIN" CHECK ( MONTO_PAGADO_PRINCIPAL >=  0             ) ENABLE, 
	 CONSTRAINT "MM_PR_CREDITOS_MTOREVALORIZA" CHECK ( MONTO_REVALORIZACION >=  0             ) ENABLE, 
	 CONSTRAINT "MM_PR_CREDITOS_PLAZO" CHECK ( PLAZO >  0             ) ENABLE, 
	 CONSTRAINT "MM_PR_CREDITOS_TASAINTERES" CHECK ( TASA_INTERES >=  0             ) ENABLE, 
	 CONSTRAINT "CK_PR_CREDITOS_MODALICOBRO" CHECK ( MODALIDAD_COBRO IN ('V','H')             ) ENABLE, 
	 CONSTRAINT "CK_PR_CREDITOS_ESLINEACREDITO" CHECK ( ES_LINEA_CREDITO IN ('S','N')             ) ENABLE, 
	 CONSTRAINT "MM_PR_CREDITOS_INTERSUSPENSO" CHECK ( INTERESES_EN_SUSPENSO >=  0             ) ENABLE, 
	 CONSTRAINT "CK_PR_CRED_ACUM_INT" CHECK ( ACUMULA_INTERESES IN ('S','N')             ) ENABLE, 
	 CONSTRAINT "MM_PR_CREDITOS_CUOTA" CHECK ( CUOTA >= 0             ) ENABLE, 
	 CONSTRAINT "MM_PR_CREDITOS_GRACIAMORA" CHECK ( GRACIA_MORA >=  0             ) ENABLE, 
	 CONSTRAINT "MM_PR_CREDITOS_GRACIAPRINCI" CHECK ( GRACIA_PRINCIPAL >=  0             ) ENABLE, 
	 CONSTRAINT "MM_PR_CREDITOS_INTERACUMULADOS" CHECK ( INTERESES_ACUMULADOS >=  0             ) ENABLE, 
	 CONSTRAINT "CK_PR_CREDITOS_CONTCOBROINT" CHECK ( CONTINUA_COBRO_INTERESES IN ('S','N')             ) ENABLE, 
	 CONSTRAINT "CK_PR_CREDITOS_TIPINTERESES" CHECK ( TIPO_INTERESES IN ('V','A')             ) ENABLE, 
	 CONSTRAINT "CK_PR_CREDITOS_MANEJO" CHECK ( MANEJO IN ('1','2')             ) ENABLE, 
	 CONSTRAINT "CK_PR_CREDITOS_REVALORIZA" CHECK ( REVALORIZA IN ('S','N')             ) ENABLE, 
	 CONSTRAINT "CK_PR_CREDITOS_TIPABONO" CHECK ( TIPO_ABONO in ('I','A','C','K','O')             ) ENABLE, 
	 CONSTRAINT "CK_PR_CREDITOS_TIPCALENDARIO" CHECK ( TIPO_CALENDARIO IN ('1','2','3','4')             ) ENABLE, 
	 CONSTRAINT "CK_PR_CREDITOS_TIPCUOTA" CHECK ( TIPO_CUOTA IN ('N','P','V','U','L','M')             ) ENABLE, 
	 CONSTRAINT "CK_PR_CREDITOS_TIPLINEA" CHECK ( TIPO_LINEA IN ('R','E')             ) ENABLE, 
	 CONSTRAINT "CK_PR_CREDITOS_TIPDESEMBOLSO" CHECK ( TIPO_DESEMBOLSO IN ('K','C','A')             ) ENABLE, 
	 CONSTRAINT "MM_PR_CREDITOS_MTOCREDITO" CHECK ( MONTO_CREDITO >=  0             ) ENABLE, 
	 CONSTRAINT "MM_PR_CREDITOS_MTODESEMBOLSADO" CHECK ( MONTO_DESEMBOLSADO >=  0             ) ENABLE, 
	 CONSTRAINT "CK_PR_CREDITOS_TIPTASA" CHECK ( TIPO_TASA IN ('F','V')             ) ENABLE, 
	 CONSTRAINT "FK_CREDITOS_TIPOCOMISION" CHECK (TIPO_COMISION IN ('A','V')) ENABLE, 
	 CONSTRAINT "FK_CREDITOS_TIPOMORA" CHECK (TIPO_MORA IN ('1','2')) ENABLE, 
	 CONSTRAINT "FK_CREDITOS_DESCCARGOS" CHECK (DESC_CARGOS IN ('S','N')) ENABLE, 
	 CONSTRAINT "FK_CREDITOS_DESCPOLIZA" CHECK (DESC_POLIZA IN ('S','N')) ENABLE, 
	 CONSTRAINT "FK_CREDITOS_DESCCUOTA" CHECK (DESC_CUOTA IN ('S','N')) ENABLE, 
	 CONSTRAINT "FK_CREDITOS_TIPOREVISION" CHECK (TIPO_REVISION IN ('A','M')) ENABLE, 
	 CONSTRAINT "FK_CREDITOS_MARCACOBROADM" CHECK (MARCA_COBRO_ADMINISTRATIVO IN ('S','N')) ENABLE, 
	 CONSTRAINT "CK_CREDITOS_CLIENTEPROSPECTO" CHECK (CLIENTE_PROSPECTO IN ('P','C')) ENABLE, 
	 CONSTRAINT "CK_CREDITOS_INDPRVEHICULO" CHECK (IND_PR_VEHICULO IN ('S','N')) ENABLE, 
	 CONSTRAINT "CK_CREDITOS_DESCINTERESESDESEM" CHECK (DESCUENTA_INTERESES_DESEMBOLSO IN ('S','N')) ENABLE, 
	 CONSTRAINT "FK_CREDITOS_DESCCOMISION" CHECK (DESC_COMISION IN ('S','N')) ENABLE, 
	 CONSTRAINT "MM_PR_CREDITOS_COMISIONORMAL" CHECK ( COMISION_NORMAL >=  0             ) ENABLE, 
	 CONSTRAINT "MM_PR_CREDITOS_CUOTANTERIOR" CHECK ( CUOTA_ANTERIOR >= 0             ) ENABLE, 
	 CONSTRAINT "PR_CREDITO_INCENDIO_PYMES" CHECK ( Esincendio_Pyme = 'S' Or Esincendio_Pyme Is Null  ) ENABLE, 
	 CONSTRAINT "FK_CREDITOS_REFERENTES" FOREIGN KEY ("CODIGO_REFERENTE")
	  REFERENCES "PR"."PR_REFERENTES" ("CODIGO_REFERENTE") ENABLE, 
	 CONSTRAINT "FK_CREDITOS_NIVELAPROBACION" FOREIGN KEY ("CODIGO_NIVEL_APROBACION")
	  REFERENCES "PR"."PR_NIVELES_APROBACION" ("CODIGO_NIVEL_APROBACION") ENABLE, 
	 CONSTRAINT "FK_CREDITOS_PLANINVERSION" FOREIGN KEY ("CODIGO_EMPRESA", "PLAN_INVERSION")
	  REFERENCES "PR"."PR_PLAN_INVERSION" ("CODIGO_EMPRESA", "PLAN_INVERSION") ENABLE, 
	 CONSTRAINT "FK_CREDITOS_TIPOSPLAZOS" FOREIGN KEY ("CODIGO_PLAZO")
	  REFERENCES "PR"."PR_TIPOS_PLAZOS" ("CODIGO_PLAZO") ENABLE, 
	 CONSTRAINT "FK_CREDITOS_NOTARIO" FOREIGN KEY ("COD_NOTARIO")
	  REFERENCES "PA"."PERSONAS" ("COD_PERSONA") ENABLE, 
	 CONSTRAINT "FK_PRCREDITOS_PAACTECONCIIU" FOREIGN KEY ("SEGREGACION_RD")
	  REFERENCES "PA"."ACTIVIDADES_ECONOMICAS_BC_CIIU" ("SEGREGACION_RD") ENABLE, 
	 CONSTRAINT "FK_CREDITOS_ESTADO" FOREIGN KEY ("ESTADO")
	  REFERENCES "PR"."PR_ESTADOS_CREDITO" ("CODIGO_ESTADO") ENABLE, 
	 CONSTRAINT "FK_PR_CREDITOS_PR_GRPMC" FOREIGN KEY ("CODIGO_EMPRESA", "NUM_GRUPO_MICROCREDITO")
	  REFERENCES "PR"."PR_GRUPO_MICROCREDITO" ("CODIGO_EMPRESA", "NUM_GRUPO") ENABLE, 
	 CONSTRAINT "FK_CREDITOS_TIPOCREDITO" FOREIGN KEY ("CODIGO_EMPRESA", "TIPO_CREDITO")
	  REFERENCES "PR"."PR_TIPO_CREDITO" ("CODIGO_EMPRESA", "TIPO_CREDITO") ENABLE, 
	 CONSTRAINT "FK_CREDITOS_PERIODICIDAD" FOREIGN KEY ("CODIGO_PERIODO_CUOTA")
	  REFERENCES "PR"."PR_PERIODICIDAD" ("CODIGO_PERIODO") ENABLE, 
	 CONSTRAINT "FK_CREDITOS_PERIOD_INT" FOREIGN KEY ("CODIGO_PERIODO_INTERESES")
	  REFERENCES "PR"."PR_PERIODICIDAD" ("CODIGO_PERIODO") ENABLE, 
	 CONSTRAINT "FK_CREDITOS_PERIOD_NORMAL" FOREIGN KEY ("PERIODO_COMISION_NORMAL")
	  REFERENCES "PR"."PR_PERIODICIDAD" ("CODIGO_PERIODO") ENABLE, 
	 CONSTRAINT "FK_CREDITOS_PRORIGENFONDOS" FOREIGN KEY ("CODIGO_ORIGEN")
	  REFERENCES "PR"."PR_ORIGEN_FONDOS" ("CODIGO_ORIGEN") ENABLE, 
	 CONSTRAINT "FK_CLIENTES_PR_CREDITOS" FOREIGN KEY ("CODIGO_CLIENTE", "CODIGO_EMPRESA")
	  REFERENCES "PA"."CLIENTES_B2000" ("CODIGO_CLIENTE", "CODIGO_EMPRESA") ENABLE NOVALIDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 80 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 2097152 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA_EFD" ;
  CREATE UNIQUE INDEX "PR"."PK_PR_CREDITOS" ON "PR"."PR_CREDITOS" ("CODIGO_EMPRESA", "NO_CREDITO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 589824 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IND_EFD" ;
ALTER TABLE "PR"."PR_CREDITOS" ADD CONSTRAINT "PK_PR_CREDITOS" PRIMARY KEY ("CODIGO_EMPRESA", "NO_CREDITO")
  USING INDEX "PR"."PK_PR_CREDITOS"  ENABLE;

   COMMENT ON COLUMN "PR"."PR_CREDITOS"."CODIGO_EMPRESA" IS 'Codigo de la Empresa.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."NO_CREDITO" IS 'Numero de Credito.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."CODIGO_AGENCIA" IS 'Codigo de la Agencia.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."CODIGO_MONEDA" IS 'Codigo de Moneda.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."CODIGO_CLIENTE" IS 'Codigo de Cliente.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."CODIGO_DIRECCION" IS 'Codigo de Direccion del Cliente.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."TIPO_CREDITO" IS 'Tipo de Credito.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."ESTADO" IS 'Estado del Credito.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."MONTO_CREDITO" IS 'Monto del Credito.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."ES_LINEA_CREDITO" IS 'Es Linea de Credito     (S/N).';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."TIPO_LINEA" IS 'Tipo de Linea de Credito:    (E)nvolvente. 
                                           (R)evolvente.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."MANEJO" IS 'Manejo:  (1) Operaciones 
               (2) Movimientos';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."MODALIDAD_COBRO" IS 'Tipo de Modalidad de Cobro:     (H)orizontal. 
                                                  (V)ertical.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."TIPO_INTERESES" IS 'Tipo de Intereses:      (A)nticipados. 
                                 (V)encidos.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."TIPO_CALENDARIO" IS 'Tipo de Calendario:      (1)  Natural/Natural. 
                                    (2)  Natural/Financiero. 
                                    (3)  Financiero/Financiero. 
                                    (4)  Financiero/Natural.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."TIPO_CUOTA" IS 'Tipo de Cuota:    (N) - Nivelada. 
                           (L) - Libre. 
                           (M) - Multiperiodica. 
                           (P) - Principal Nivelado. 
                           (V) - Al Vencimiento. 
                           (U) - Un Solo Pago.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."CODIGO_PERIODO_CUOTA" IS 'Codigo del Periodo de Cobro de la Cuota.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."CODIGO_PERIODO_INTERESES" IS 'Codigo del Periodo de Cobro de los Intereses si el tipo de cuota es Multiperiodica.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."PERIODO_COMISION_NORMAL" IS 'Codigo del Periodo de Cobro de la Comision.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."COMISION_NORMAL" IS 'Porcentaje de Comision a Cobrar.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."CUOTA" IS 'Monto de la Cuota.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."MONTO_DESEMBOLSADO" IS 'Monto Total Desembolsado.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."MONTO_PAGADO_PRINCIPAL" IS 'Monto Pagado en Principal.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."MONTO_PAGADO_INTERESES" IS 'Monto Pagado en Intereses.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."INTERESES_ACUMULADOS" IS 'Total en Intereses Acumulados.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."MONTO_REVALORIZACION" IS 'Monto de Revalorizacion del Credito.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."INTERESES_EN_SUSPENSO" IS 'Total en Intereses en Suspenso.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."CUOTA_ANTERIOR" IS 'Monto de la Cuota Anterior.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."PLAZO" IS 'Cantidad de Dias Plazo';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."ID_SISTEMA_EXTERNO" IS 'Numero de Credito del Sistema Anterior';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."NO_SOLICITUD" IS 'Numero de Solicitud de Credito.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."NO_CREDITO_ORIGEN" IS 'Numero de Credito Origen (Linea de Credito).';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."TIPO_TASA" IS 'Tipo de Tasa de Interes:         (F)ija. 
                                              (V)ariable.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."CODIGO_TIPO_DE_TASA" IS 'Codigo del Tipo de Tasa de Interes.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."VARIACION_BASE" IS 'Variacion de la Tasa de Interes.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."TASA_INTERES" IS 'Tasa de Interes.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."TASA_ORIGINAL" IS 'Tasa Original de Interes.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."CODIGO_TASA_MORATORIOS" IS 'Codigo del Tipo de Tasa de Moratorios.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."VARIACION_MORA" IS 'Variacion  de la Tasa de Moratorios.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."TASA_MORATORIOS" IS 'Tasa de Moratorios.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."PERIODO_REVISION_TASA" IS 'Periodo de Revision de la Tasa de Interes.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."VARIACION_MAX_REVISION" IS 'Variacion Maxima en la Revision de Tasas de Interes.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."VARIACION_MAX_TOTAL" IS 'Variacion Minima en la Revision de Tasas de Interes.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."GRACIA_PRINCIPAL" IS 'Dias de Gracia en Principal.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."GRACIA_MORA" IS 'Dias de Gracia en Moratorios.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."CODIGO_ORIGEN" IS 'Codigo del Origen de los Fondos.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."NO_PROGRAMA_ASOCIADO" IS 'Numero de Programa Asociado.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."CODIGO_EJECUTIVO" IS 'Codigo del Ejecutivo de Credito.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."COBRADOR" IS 'Codigo del Cobrador.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."CODIGO_REFERENTE" IS 'Codigo del Referente del Credito.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."CODIGO_ANALISTA" IS 'Codigo del Analista de Credito.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."CODIGO_NIVEL_APROBACION" IS 'Codigo del Nivel de Aprobacion del Credito.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."F_APERTURA" IS 'Fecha de Apertura del Credito.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."F_VENCIMIENTO" IS 'Fecha de Vencimiento del Credito.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."F_CANCELACION" IS 'Fecha de Cancelacion del Credito.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."F_ADJUDICACION" IS 'Fecha de Adjudicacion del Credito.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."F_ULTIMA_REVISION" IS 'Fecha de Ultima Revision de Tasas de Interes.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."F_ULTIMO_PAGO_PRINCIPAL" IS 'Fecha de Ultimo Pago de Principal.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."F_ULTIMO_PAGO_INTERESES" IS 'Fecha de Ultimo Pago de Intereses.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."F_PRIMER_DESEMBOLSO" IS 'Fecha del Primer Desembolso del Credito.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."F_ULTIMO_DESEMBOLSO" IS 'Fecha del Ultimo Desembolso del Credito.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."F_PROXIMA_COMISION" IS 'Fecha de la Proxima Comision del Credito.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."F_APROBACION" IS 'Fecha de Aprobacion del Credito.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."F_ULTIMO_PAGO_MORA" IS 'Fecha de Ultimo Pago de Moratorios.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."F_RECONOCIM_INTERESES" IS 'Fecha de Reconocimiento de Intereses.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."F_PRINCIPAL_ANTERIOR" IS 'Fecha del Ultimo Pago de Principal Anterior.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."F_INTERESES_ANTERIOR" IS 'Fecha del Ultimo Pago de Interes Anterior.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."F_MORA_ANTERIOR" IS 'Fecha del Ultimo Pago de Mora Anterior.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."F_ULTIMA_REVALORIZACION" IS 'Fecha de Ultima Revalorizacion.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."TIPO_ABONO" IS 'Tipo de Abono:      (I) - Ingreso desde Cajas. 
                              (A) - Cuenta Contable. 
                              (C) - Cuenta Relacionada.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."CUENTA_ABONO" IS 'Cuenta desde donde se Efectuaran los Abonos.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."TIPO_DESEMBOLSO" IS 'Tipo de Desembolso:     (K) - Cheque. 
                                     (A) - Cuenta Contable. 
                                     (C) - Cuenta Relacionada.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."CUENTA_DESEM" IS 'Cuenta a donde se Efectuaran los Desembolsos.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."CONTINUA_COBRO_INTERESES" IS 'Continua el Cobro de Intereses  (S/N).';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."DIA_PAGO" IS 'Dia de Pago del Credito.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."MARCA_REV_TASA" IS 'Marca al Credito para Revision de Tasas de Interes.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."REVALORIZA" IS 'Revaloriza  (S/N).';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."OBSERVACIONES1" IS 'Observaciones #1.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."OBSERVACIONES2" IS 'Observaciones #2.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."ADICIONADO_POR" IS 'Codigo del Usuario que Creo el Registro.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."FECHA_ADICION" IS 'Fecha de Creacion del Registro.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."MODIFICADO_POR" IS 'Codigo del Usuario que Modifico el Registro.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."FECHA_MODIFICACION" IS 'Fecha de Modificacion del Registro.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."CODIGO_SUB_APLICACION" IS 'Codigo de la Sub Aplicacion.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."MONTO_VARIACION" IS 'Monto de Variaciones al Principal.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."CODIGO_ACTIVIDAD" IS 'Codigo de Actividad Economica.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."CODIGO_SUBACTIVIDAD" IS 'Codigo de SubActividad Economica.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."CODIGO_CALIFICACION_SISTEMA" IS 'Codigo de Calificacion dada por el Sistema.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."CODIGO_CALIFICACION_MANUAL" IS 'Codigo de Calificacion dada Manualmente.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."OBSERVACIONES_CALIFICACION" IS 'Observaciones Referentes a la Calificacion.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."ATRASO_PROMEDIO" IS 'Atraso Promedio.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."TIPO_COMISION" IS 'Tipo de Comision.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."PLAN_INVERSION" IS 'Codigo del Plan de Inversion.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."PAIS_DESTINO" IS 'Codigo del Pais Destino.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."DEPARTAMENTO_DESTINO" IS 'Codigo del Departamento Destino.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."MUNICIPIO_DESTINO" IS 'Codigo del Municipio Destino.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."DISTRITO_DESTINO" IS 'Codigo del Distrito Destino.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."CODIGO_SUB_CLASE" IS 'Codigo de la SubClase (SubSubActividad).';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."TIPO_MORA" IS 'Tipo de Mora.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."PORCENTAJE_TASA_MORA" IS 'Porcentaje de Tasa de Mora.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."APROBADO_POR" IS 'Codigo del Usuario que Aprueba el Credito.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."CODIGO_PLAZO" IS 'Codigo del Tipo de Plazo.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."TASA_ORIGINAL_MORA" IS 'Tasa Original de Mora.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."MONTO_X_DESEMBOLSAR" IS 'Monto por Desembolsar.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."CALIFICADO_POR" IS 'Codigo del Usuario que Califico al Credito.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."F_ULTIMA_CALIFICACION" IS 'Fecha de la Ultima Calificacion Efectuada.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."PLAZO_OPERACIONES" IS 'Plazo de las Operaciones Hijas.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."PERMITE_SOBREGIRO" IS 'Permite Sobregiro  (S/N).';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."PORCENTAJE_SOBREGIRO" IS 'Porcentaje de Sobregiro.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."F_PRORROGA" IS 'Fecha de la Prorroga al Vencimiento.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."F_ULTIMO_PAGO_COMISION" IS 'Fecha del Ultimo Pago de la Comision.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."F_PROXIMA_REVISION" IS 'Fecha de la Proxima Revision de Tasas.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."F_ULTIMA_REV_MORA" IS 'Fecha de Ultima Revision de Moratorios.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."OBSERVACIONES3" IS 'Observaciones #3.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."OBSERVACIONES4" IS 'Observaciones #4.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."BLOQUEO_DESEMBOLSO" IS 'Bloqueo sobre el Desembolso.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."DESC_CARGOS" IS 'Descuenta los Cargos en el Desembolso (S/N).';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."DESC_POLIZA" IS 'Descuenta la Poliza en el Desembolso (S/N).';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."DESC_CUOTA" IS 'Descuenta la Cuota en el Desembolso (S/N).';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."DESC_COMISION" IS 'Descuenta la Comision en el Desembolso (S/N).';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."ACUMULA_INTERESES" IS 'Acumula Intereses  (S/N).';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."VARIACION_MINIMA" IS 'Variacion Minima.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."VARIACION_MAXIMA" IS 'Variacion Maxima.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."TIPO_REVISION" IS 'Tipo de Revision: (A)utomatica  (M)anual';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."PERIODOS_GRACIA_PRINCIPAL" IS 'Periodos de Gracia en Principal.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."F_PAGO_COMISION_ATRASADA" IS 'Fecha de Pago de Comision Atrasada.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."TIPO_REGRESO_COBRO" IS 'Tipo de Regreso de Cobro. Valores: C = Cancelacion Total, G = Adjudicación de Garantia, O = Otros Motivos, P = Arreglo de Pago';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."F_PAGO_COBRO_ADMINISTRATIVO" IS 'Fecha de Pago de Cobro Administrativo.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."BASE_CALCULO_MORATORIOS" IS 'Base de Calculo de Moratorios  (360 o 365)';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."INTERESES_ANTICIPADOS" IS 'Intereses Anticipados.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."INTERESES_ANTES_COBRO_JUDICIAL" IS 'Intereses Acumulados antes de Envio a Cobro Judicial.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."MARCA_COBRO_ADMINISTRATIVO" IS 'Cobro Administrativo sin importar atraso (S/N)';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."PORC_SALDO_NO_UTILIZADO" IS 'Porcentaje a cobrarse sobre Desembolsos Parciales de Lineas de Credito.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."F_ULTIMO_PAGO_INTERESES_VENC" IS 'Fecha de ultimo pago de intereses despues del vencimiento del credito';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."F_PROXIMA_MORA_FLAT" IS 'Fecha de proxima generacion de mora flat';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."COD_NOTARIO" IS 'Codigo del abogado notario';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."DESCUENTA_INTERESES_DESEMBOLSO" IS 'Indicador para prestamos que se descuenta los intereses en el desembolso';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."CANTIDAD_CUOTAS_DESCONTAR" IS 'Cantidad de cuotas descontadas en el desembolso';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."NO_POLIZA_BCO" IS 'Numero de polizas para vehiculo';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."IND_PR_VEHICULO" IS 'Indica si el prestamo fue emitido para financiar la compra de vehiculo';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."COD_PROMOTOR" IS 'Codigo de promotor de venta';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."F_RESTRUCTURACION" IS 'Fecha en que se el credito paso de Restructurado a Vigente.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."F_RESTRUC_A_VIGENTE" IS 'Fecha en que el prestamo para se restructurado a vigente';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."RES_APR_INMED" IS 'Codigo del resultado de la aprobacion inmediata. Hace referencia a la tabla PA.PA_RESULT_APR_INMED.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."DIR_SUCURSAL" IS 'Direccion de la Sucursal de la Tienda.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."MTO_INICIAL_COTIZACION" IS 'Monto con que se inicio la cotizacion.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."MTO_FINANCIADO" IS 'Monto financiado por el BSC.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."VENDEDOR" IS 'Nombre del Vendedor.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."PORCIENTO_RETENCION" IS 'Porcentaje de Retencion establecido.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."NETO_PAGAR" IS 'Monto Neto a Pagar.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."NO_COTIZACION" IS 'Numero de la Cotizacion.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."GASTOS_CIERRE" IS 'Monto de gastos para el cierre.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."COMISIONPTO15" IS 'Monto de la comision del 0.15%.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."INT_COMPLETIVO_ACUM" IS 'Acumulado de intereses completivos';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."NUM_GRUPO_MICROCREDITO" IS 'Identificador del grupo de microcredito que se debe utilizar.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."SEGREGACION_RD" IS 'Campo relacionado a la tabla ACTIVIDADES_ECONOMICAS_BC_CIIU.';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."ESTADO_APROBACION" IS 'Estado del proceso de aprobacion, ligado a PA_CATALOGO_CODIGOS con el codigo_gen = 003';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."ESVIDA" IS 'Poliza de Vida S-Si, N-No';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."ESVEHICULO" IS 'Poliza de Vehiculo S-Si, N-No';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."ESINCENDIO" IS 'Poliza de Incendio S-Si, N-No';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."MORA_SUSPENSO_ACUMUL" IS 'Campo que registra el Interes en suspenso acumulado';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."MON_MORA_PAGADO" IS 'Monto de mora pagado';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."MONTO_PAGOS_INTERESES_SUSPENSO" IS 'monto pagado intereses en suspenso';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."MONTO_PAGOS_MORA_SUSPENSO" IS 'monto pagado a interses moratorios en suspenso';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."ESINCENDIO_PYME" IS 'Indica que el crédito posee una poliza por Insendio para PYMES, posibles valores S o NULL ';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."TIPO_REESTRUCTURACION" IS 'RN = Reestructurado conformfe a la definicion dada por el REA,
 RP = Représtamo o Refinancimiento,
 RV = Renovación,
 RT = Reestructurado Temporal de acuerdo a las normativas vigentes en el período,
 RL = Crédito Reestructurado y acogido al proceso de la Ley No.141 -15, Reestructuración
      y Liquidación de Empresas y Personas Físicas Comerciantes del 7 de agosto del 2015,
 NR = No ha sido reestructurado';
   COMMENT ON COLUMN "PR"."PR_CREDITOS"."FRE_REV_TASA" IS 'Campo indicador de Frecuencia de Revisiòn de Tasa';
   COMMENT ON TABLE "PR"."PR_CREDITOS"  IS ' Esta tabla es usada para almacenar la informacion de los creditos, ya sea cuando se generan a partir de una solicitud, o bien, aquellas operaciones registradas directamente, sin necesidad de solicitud. En esta tabla se almacenan los creditos independientes, lineas de credito y las operaciones (desembolsos) pertenecientes a alguna linea';

  CREATE INDEX "PR"."ESTADOPRCREDITOS_IDX" ON "PR"."PR_CREDITOS" ("CODIGO_EMPRESA", "ESTADO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PR_DAT" ;

  CREATE INDEX "PR"."IDX_CREDITOS_FPDESEMB" ON "PR"."PR_CREDITOS" ("F_PRIMER_DESEMBOLSO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PR_DAT" ;

  CREATE INDEX "PR"."IDX_PRCREDITOS_IDSISTEMAEXT" ON "PR"."PR_CREDITOS" ("CODIGO_EMPRESA", "ID_SISTEMA_EXTERNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PR_DAT" ;

  CREATE INDEX "PR"."IDX_PR_CREDITOS1" ON "PR"."PR_CREDITOS" ("CODIGO_EMPRESA", "CODIGO_CLIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IND_EFD" ;

  CREATE INDEX "PR"."IDX_PR_CREDITOS2" ON "PR"."PR_CREDITOS" ("CODIGO_EMPRESA", "NO_CREDITO_ORIGEN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IND_EFD" ;

  CREATE INDEX "PR"."IDX_PR_CREDITOS_CIERRE" ON "PR"."PR_CREDITOS" ("CODIGO_EMPRESA", "NO_CREDITO", "ESTADO", "ES_LINEA_CREDITO", "MANEJO", "TIPO_CREDITO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IND_EFD" ;

  CREATE INDEX "PR"."IDX_PR_CREDITOS_COD_EJEC" ON "PR"."PR_CREDITOS" ("CODIGO_EMPRESA", "CODIGO_EJECUTIVO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PR_DAT" ;

  CREATE INDEX "PR"."IDX_PR_CREDITOS_NO_CREDITO" ON "PR"."PR_CREDITOS" ("NO_CREDITO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PR_DAT" ;

  CREATE INDEX "PR"."I_PR_CREDITO_CIERRE" ON "PR"."PR_CREDITOS" ("CODIGO_EMPRESA", "CODIGO_AGENCIA", "ESTADO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PR_IDX" ;

  CREATE INDEX "PR"."PR_CREDITOS_FK1" ON "PR"."PR_CREDITOS" ("PERIODO_COMISION_NORMAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PR_IDX" ;

  CREATE INDEX "PR"."PR_CREDITOS_FK10" ON "PR"."PR_CREDITOS" ("CODIGO_EMPRESA", "TIPO_CREDITO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PR_IDX" ;

  CREATE INDEX "PR"."PR_CREDITOS_FK11" ON "PR"."PR_CREDITOS" ("CODIGO_PLAZO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PR_IDX" ;

  CREATE INDEX "PR"."PR_CREDITOS_FK12" ON "PR"."PR_CREDITOS" ("CODIGO_EMPRESA", "NUM_GRUPO_MICROCREDITO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PR_IDX" ;

  CREATE INDEX "PR"."PR_CREDITOS_FK13" ON "PR"."PR_CREDITOS" ("CODIGO_PERIODO_CUOTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PR_IDX" ;

  CREATE INDEX "PR"."PR_CREDITOS_FK2" ON "PR"."PR_CREDITOS" ("CODIGO_EMPRESA", "PLAN_INVERSION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PR_IDX" ;

  CREATE INDEX "PR"."PR_CREDITOS_FK3" ON "PR"."PR_CREDITOS" ("CODIGO_ORIGEN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PR_IDX" ;

  CREATE INDEX "PR"."PR_CREDITOS_FK4" ON "PR"."PR_CREDITOS" ("SEGREGACION_RD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PR_IDX" ;

  CREATE INDEX "PR"."PR_CREDITOS_FK5" ON "PR"."PR_CREDITOS" ("CODIGO_NIVEL_APROBACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PR_IDX" ;

  CREATE INDEX "PR"."PR_CREDITOS_FK6" ON "PR"."PR_CREDITOS" ("COD_NOTARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PR_IDX" ;

  CREATE INDEX "PR"."PR_CREDITOS_FK7" ON "PR"."PR_CREDITOS" ("ESTADO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PR_IDX" ;

  CREATE INDEX "PR"."PR_CREDITOS_FK8" ON "PR"."PR_CREDITOS" ("CODIGO_PERIODO_INTERESES") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PR_IDX" ;

  CREATE INDEX "PR"."PR_CREDITOS_FK9" ON "PR"."PR_CREDITOS" ("CODIGO_REFERENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PR_IDX" ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "PR"."TRG_AD_REG_CREDITOS" 
AFTER DELETE
ON PR.PR_CREDITOS REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
  IF DELETING and nvl(:old.estado,'x') = 'N' THEN
     -- Solo entra acá si se borra y el creditos está ANULADO (N)    
      PR.PINSERTAFILEFLOW(:old.no_credito, 'AN', USER, '0');
  END IF;
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/
ALTER TRIGGER "PR"."TRG_AD_REG_CREDITOS" DISABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "PR"."TRG_PR_VALIDA_TASA" 
   BEFORE INSERT 
   ON PR.PR_CREDITOS
   REFERENCING NEW AS New OLD AS Old
   FOR EACH ROW
DECLARE
   
   /******************************************************************************
      NOMBRE:      PR.TRG_VALIDA_TASA
      PROPOSITO:  Crear un Trigger que valide la Tasa del Crédito
                  Buscando la tasa que coresponde por tipo de Proyecto

      Ver        Date         Author                          Description
      ---------  ----------  -----------------------------   --------------------
      1.0        19/11/2021  Ramón Aníbal Paulino Veras     Creacion del Trigger.
      1.5        05/03/2022  Ramón Aníbal Paulino Veras     Ajuste para que también actualice la variación base

      NOTAS: Requerimiento #137068
      Se dispara este trigger cada vez que se cree un préstamo.
      La función PR.F_Obt_Tasa_credito(), se encarga de obtener la Tasa que corresponde según el Tipo Proyecto
      Si la Tasa del Crédito es diferente a la Tasa que trae la Función
      se Actaulizará la Tasa del Crédito con la Tasa Capturada en el Función.
      
      Se valida sólo para el Insert, por si es necesario alguna modificación por cualquier
      canal de COS.

   ******************************************************************************/   
   vTasa_interes_proyecto    NUMBER(10, 4);
   vVariacion_base           NUMBER(10,4);
BEGIN
   BEGIN
      IF ((:NEW.estado = 'R') AND  ( USER = 'IA')) THEN
            BEGIN
            vTasa_interes_proyecto := PR.F_obt_tasa_credito (:NEW.Tipo_credito, vVariacion_base);
            IF :NEW.tasa_interes != vTasa_interes_proyecto THEN
               BEGIN
                  -- Actualiza la TASA_INTERES_CREDITO en PR_CREDITOS con el valor de TASA_INTERES_PROYECTO
                  :NEW.TASA_INTERES   := vTasa_interes_proyecto;
                  :NEW.variacion_base := vVariacion_base;
               END;
            END IF;
         END;
      END IF;
   END;
END TRG_PR_VALIDA_TASA;
/
ALTER TRIGGER "PR"."TRG_PR_VALIDA_TASA" ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "IA"."TRG_CREDITO_REPRESTAMO" 
   BEFORE UPDATE OF ESTADO,ESTADO_APROBACION
   ON PR.PR_CREDITOS
   REFERENCING NEW AS New OLD AS Old
   FOR EACH ROW
DECLARE
   vEstado         PR.PR_ESTADOS_REPRESTAMO.CODIGO_ESTADO%TYPE;
   vIdReprestamo   PR.PR_REPRESTAMOS.ID_REPRESTAMO%TYPE;
   vEstadoRepre    PR.PR_ESTADOS_REPRESTAMO.CODIGO_ESTADO%TYPE;
BEGIN
   BEGIN
      SELECT CASE :NEW.ESTADO 
             WHEN 'R' THEN
                CASE :NEW.ESTADO_APROBACION
                    WHEN 'P' THEN 'CRS' 
                    WHEN 'A' THEN 'CRV'
                    WHEN 'H' THEN 'CRH'
                    WHEN 'Z' THEN 'CRA'
                    END 
            WHEN 'D' THEN 'CRD' 
            WHEN 'N' THEN 'CRN'
            WHEN 'C' THEN 'AN'
            END,
             R.ID_REPRESTAMO,
             r.ESTADO
        INTO vEstado, vIdReprestamo, vEstadoRepre
        FROM PR.PR_SOLICITUD_REPRESTAMO r
       WHERE R.CODIGO_EMPRESA = PR_PKG_REPRESTAMOS.F_OBT_EMPRESA_REPRESTAMO
         AND R.NO_CREDITO = :NEW.NO_CREDITO;
   EXCEPTION
      WHEN OTHERS THEN
         vIdReprestamo := NULL;
         vEstado := NULL;
   END;
   
   IF vEstado = 'AN' AND vIdReprestamo IS NOT NULL AND vEstado <> vEstadoRepre THEN
      PR_PKG_REPRESTAMOS.p_generar_bitacora(vIdReprestamo, NULL, vEstado, NULL, 'Credito anterior cancelado', USER);
   END IF;
   
   IF vEstado IS NOT NULL AND vIdReprestamo IS NOT NULL AND vEstado <> vEstadoRepre THEN
      PR_PKG_REPRESTAMOS.p_generar_bitacora(vIdReprestamo, NULL, vEstado, NULL, 'Cambio de estado File Flow', USER);
   END IF;
END TRG_CREDITO_REPRESTAMO;
/
ALTER TRIGGER "IA"."TRG_CREDITO_REPRESTAMO" ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "PR"."PR_CREDITOS_TRG01" 
    /* ********************************************************************************************
          Efectua: Auditoria a los cambios de los campos mas sensibles e importantes de PR_CREDITOS
                   Inicialmente requerido y habilitado para los campos de estado y estado_aprobacion
         Requiere: N/A
       Creado Por: Haendel Castillo (Excello Technology)
            Fecha: 2016-09-16
         Historia de cambios y mejoras:
         Fecha       Responsable  Detalle
         ----------  -----------  -----------------------------------------------------------------
        13-12-2017  Miguel Almanzar  (Excello Technology) asegurar aprobación en estado_aprobacion 'Z'
      ********************************************************************************************* */
        
      
    BEFORE UPDATE
    ON PR.PR_CREDITOS
    REFERENCING NEW AS New OLD AS Old
    FOR EACH ROW
    
    
    
BEGIN
    --AUDITORIA EL CAMBIO DEL ESTADO DE APROBACION DEL PRESTAMO:
    IF NVL (:OLD.estado_aprobacion, '~') <> NVL (:NEW.estado_aprobacion, '~')
    THEN
        INSERT INTO pr_creditos_audit (CODIGO_EMPRESA,
                                       NO_CREDITO,
                                       SEQ_CAMBIO,
                                       COLUMNA,
                                       VALOR_ANT,
                                       VALOR_POS,
                                       ADICIONADO_POR,
                                       FECHA_ADICION)
             VALUES (:NEW.codigo_empresa,
                     :NEW.no_credito,
                     pr_creditos_audit_sq.NEXTVAL,
                     'ESTADO_APROBACION',
                     :OLD.estado_aprobacion,
                     :NEW.estado_aprobacion,
                     :new.APROBADO_POR,
                     SYSDATE);
    END IF;

    IF NVL (:OLD.estado, '~') <> NVL (:NEW.estado, '~')
    THEN
        INSERT INTO pr_creditos_audit (CODIGO_EMPRESA,
                                       NO_CREDITO,
                                       SEQ_CAMBIO,
                                       COLUMNA,
                                       VALOR_ANT,
                                       VALOR_POS,
                                       ADICIONADO_POR,
                                       FECHA_ADICION)
             VALUES (:NEW.codigo_empresa,
                     :NEW.no_credito,
                     pr_creditos_audit_sq.NEXTVAL,
                     'ESTADO',
                     :OLD.estado,
                     :NEW.estado,
                     USER,
                     SYSDATE);
    END IF;

    IF NVL (:NEW.estado_aprobacion, '~') = 'Z' AND :OLD.ESTADO = 'R'
    THEN
        :NEW.estado := 'A';
    END IF;

 --Proyeccion y notificacion, malmanzar 18-04-2023 req. 149204 Firma Digital  Begin
 declare
    vEstado   PR.PR_CREDITOS_FIRMA.estado%type;
 BEGIN
    IF    NVL (:NEW.estado_aprobacion, '~') = 'Z' AND :OLD.ESTADO = 'R'
       OR :OLD.ESTADO = 'A' AND :NEW.ESTADO = 'D'
       OR  NVL (:NEW.estado_aprobacion, '~') = 'Y' AND  NVL (:OLD.estado_aprobacion, '~') = 'Z'
       OR NVL (:NEW.estado_aprobacion, '~') = 'H' AND :OLD.ESTADO = 'R'  ---malmanzar 03-05-2025
    THEN
    
      if  NVL (:NEW.estado_aprobacion, '~') = 'Y' AND  NVL (:OLD.estado_aprobacion, '~') = 'Z' then
          vEstado := :NEW.estado_aprobacion;
          else
            IF :NEW.ESTADO_APROBACION = 'H' AND :NEW.ESTADO_APROBACION != :OLD.ESTADO_APROBACION THEN  --03-05-2025 BEGIN
              vEstado := :NEW.ESTADO_APROBACION;
              ELSE
              vEstado := :NEW.ESTADO;  
            END IF;  --03-05-2025 END
      end if;
       
        pr_plan_proyeccion.p_inserta_apr (pCodigo_Empresa   => :NEW.CODIGO_EMPRESA,
                                          pNo_credito       => :NEW.NO_CREDITO,
                                          pCodigo_Cliente   => :NEW.CODIGO_CLIENTE,
                                          pEstado           =>  vEstado---:NEW.ESTADO
                                          );
    END IF;
    
   END; 
    --Proyeccion y notificacion, malmanzar 18-04-2023 req. 149204 Firma Digital  End



    IF NVL (:new.estado_aprobacion, '~') = 'Z' AND :NEW.APROBADO_POR IS NULL
    THEN
        :NEW.APROBADO_POR := USER;
    END IF;

    IF NVL (:new.estado_aprobacion, '~') != 'H'
    THEN
        :new.APROBADO_POR := NVL (:old.APROBADO_POR, USER);
    END IF;

    --malmanzar 17-03-2022, para asegurar que permanezca en estado 'E' en caso de regreso de cobro Judicial
    IF    :NEW.TIPO_REESTRUCTURACION IS NOT NULL
       OR :NEW.F_RESTRUCTURACION IS NOT NULL
    THEN
        IF :NEW.ESTADO IN ('D', 'V', 'M')
        THEN                                           ---malmanzar 19-04-2022
            :NEW.ESTADO := 'E';
        END IF;
    END IF;
END PR_CREDITOS_TRG01;
/
ALTER TRIGGER "PR"."PR_CREDITOS_TRG01" ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "PR"."TRG_AUD_PR_CREDITOS" 
   After Update Of estado,
                   monto_credito,
                   monto_desembolsado,
                   f_vencimiento,
                   plazo,
                   codigo_moneda,
                   codigo_periodo_cuota
   On pr.pr_creditos
   Referencing Old As Old New As New
   For Each Row
Declare
   x                             Varchar2( 512 );
Begin
   Begin
      Select program
        Into x
        From v$session
       Where audsid = ( Select Userenv( 'sessionid' )
                         From Dual );
   Exception
      When No_data_found Then
         x                          := 'PROGRAMA DESCONOCIDO';
      When Others Then
         x                          := 'PROGRAMA DESCONOCIDO';
   End;
   If Updating Then
      If (    :Old.estado
           || '|'
           || :Old.monto_credito
           || '|'
           || :Old.monto_desembolsado
           || '|'
           || :Old.f_vencimiento
           || '|'
           || :Old.plazo
           || '|'
           || :Old.codigo_moneda
           || '|'
           || :Old.codigo_periodo_cuota ) !=
            (    :New.estado
              || '|'
              || :New.monto_credito
              || '|'
              || :New.monto_desembolsado
              || '|'
              || :New.f_vencimiento
              || '|'
              || :New.plazo
              || '|'
              || :New.codigo_moneda
              || '|'
              || :New.codigo_periodo_cuota ) Then
         Insert Into pa_audit_dml
                     ( consecutivo, fyh_movimiento, usuario, tipo_mov,
                       hilera_anterior,
                       hilera_nueva,
                       ip_address,
                       terminal,
                       os_user_name, program_name )
              Values ( 393, Systimestamp, User, 'U',
                          '|'
                       || :Old.no_credito
                       || '|'
                       || :Old.estado
                       || '|'
                       || :Old.monto_credito
                       || '|'
                       || :Old.monto_desembolsado
                       || '|'
                       || :Old.f_vencimiento
                       || '|'
                       || :Old.plazo
                       || '|'
                       || :Old.codigo_moneda
                       || '|'
                       || :Old.codigo_periodo_cuota
                       || '|'
                       || :Old.modificado_por
                       || '|'
                       || To_char( :Old.fecha_modificacion, 'dd/mm/yyyy hh24:mi:ss' )
                       || '|'
                       ||  Null 
                       || '|',
                          '|'
                       || :New.no_credito
                       || '|'
                       || :New.estado
                       || '|'
                       || :New.monto_credito
                       || '|'
                       || :New.monto_desembolsado
                       || '|'
                       || :New.f_vencimiento
                       || '|'
                       || :New.plazo
                       || '|'
                       || :New.codigo_moneda
                       || '|'
                       || :New.codigo_periodo_cuota
                       || '|'
                       || Nvl( :New.modificado_por, User )
                       || '|'
                       || To_char( Nvl( :New.fecha_modificacion, Sysdate ),
                                   'dd/mm/yyyy hh24:mi:ss' )
                       || '|'
                       || Sys_context( 'USERENV', 'MODULE' )
                       || '|',
                       Sys_context( 'USERENV', 'IP_ADDRESS' ),
                       Sys_context( 'USERENV', 'TERMINAL' ),
                       Sys_context( 'USERENV', 'OS_USER' ), x );
      End If;
   End If;
End; 
/
ALTER TRIGGER "PR"."TRG_AUD_PR_CREDITOS" ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "PR"."TRG_AUDITA_PR_CREDITOS" 
/******************************************************************************
    Efectua: Envia a la tabla de monitor la informacion de apertura de creditos.
    Requiere:
    Historia: Creacion 22/08/2012 Ana Patricia Inoa
              :  Modificacion 02/09/2013 Enver Francisco 
                 Agregar la descripcion de la tienda e incluir tambien el tipo 
                 de aprobacion de tienda a la tabla de monitor. 
             :   02/09/2013 Enver Francisco -- Modificacion --
                  Agregar la descripcion de la tienda e incluir tambien el tipo 
                  de aprobacion de tienda a la tabla de monitor.  
******************************************************************************/
AFTER INSERT
ON PR.PR_CREDITOS 
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
vCliente varchar2(200);
vEstCliente varchar2(3);
vEjecutivo varchar2(200);
vError varchar2(200);
vDbCr varchar2(2);
vDescTx varchar2(40);
--
--ENF
vTienda varchar2(120) := null;
--ENF
BEGIN

    

       /* begin
            select upper(rtrim(ltrim(nombre))), estado_persona
                into vCliente, vEstCliente
            from personas
            where cod_persona = :new.codigo_cliente;
        exception
            when others then
                vCliente := null;
        end;*/

        /*begin
            select upper(rtrim(ltrim(primer_nombre))||' '||rtrim(ltrim(segundo_nombre))||' '||rtrim(ltrim(primer_apellido))||' '||rtrim(ltrim(segundo_apellido)))
                into vEjecutivo
            from personas_fisicas p, Usuarios U
            where u.cod_usuario = :new.codigo_ejecutivo
            and u.cod_per_fisica = p.cod_per_fisica;            
        exception
            when others then
                vEjecutivo := null;
        end;*/

       --begin
       /*     select tip_movimiento, descripcion
                into vDbCr, vDescTx
            from cat_tip_transac
            where cod_sistema = 'PR'
          and tip_Transaccion = 75;            
        exception
            when others then
                vDbCr := 'O';*/
            vDescTx := 'Apertura de Credito';
       -- end;

     -- Insertar auditoria de transaccion
        Begin
            -- ENF : Verifica si el prestamo tiene referente de tienda.
            /*if :new.codigo_referente is not null then
                begin
                     select descripcion
                     into vTienda
                     from pr_referentes
                     where codigo_referente = :new.codigo_referente;
                exception
                  when no_data_found then
                    vTienda := null;
                end;
            end if;      */     
            
            INSERT INTO PA.BITACORA_MONITOR
            (
               SECUENCIA_LOG, TIPO_REGISTRO,  COD_SISTEMA, ORIGEN_TX, TIPO_TRANSACCION, 
               SUBTIP_TRANSACCION, FECHA, HORA, USUARIO_TX, USUARIO_MODIFICA, USUARIO_REVERSA, 
               USUARIO_AUTORIZA, FECHA_MODIFICA, FECHA_REVERSO, FECHA_AUTORIZACION, TERMINAL, 
               AGENCIA, REFERENCIA, TIPO_CUENTA, NUMERO_CUENTA, MONTO_TX, MONTO_EFECTIVO, 
               MONTO_DOCUMENTO, MONTO_CK_PROPIO, MONTO_CK_OTROS, SALDO_CUENTA, MONTO_DISPONIBLE, 
               INDICADOR_DBCR, INDICADOR_REVERSO, INDICADOR_EMPLEADO, FECHA_APERTURA_CTA, MONEDA_TX, 
               MONEDA_CUENTA, COD_CLIENTE, NOMBRE_CLIENTE, NOMBRE_BENEFICIARIO, NUMERO_DOCUMENTO, 
               CODIGO_CAJERO, TASA_CAMBIO, ESTADO_MOVIMIENTO, DESCRIPCION_TX, NUMERO_AUTORIZACION, 
               COD_PRODUCTO, NUMERO_TARJETA, ESTADO_CUENTA, COD_OFICIAL, NOMBRE_OFICIAL,
               DATO_ANTES_ACTUALIZA, DATO_DESPUES_ACTUALIZA, DATOS_ANTES_CAMBIO, FUERA_HORARIO, 
               ESTADO_CLIENTE
            )
            VALUES
            (
                0, 1, 'PR', 'PR', 75,     
                75, to_char(sysdate, 'YYYYMMDD'), to_char(sysdate, 'HH24MISS'), user,:new.plazo,null,  
                null, to_char(:new.f_vencimiento, 'YYYYMMDD'), null, to_char(:new.f_apertura, 'YYYYMMDD'), :new.dia_pago,
                :new.codigo_agencia, null, null, null, :new.monto_credito, null, 
                null, null, null, :new.monto_credito, null, 
                vDbCr, null, null, null, :new.codigo_moneda, 
                :new.codigo_moneda, :new.codigo_cliente, substr(vCliente,1,60), :new.res_apr_inmed/*null*/, null, 
                null, :new.tasa_interes, null, vDescTx, null, 
                :new.tipo_credito, :new.no_credito, :new.estado, :new.codigo_ejecutivo, vEjecutivo,
                null, null, vTienda/*null*/, null, vEstCliente
        );

        end;

   EXCEPTION
     WHEN OTHERS THEN
        vError:=sqlcode || '>>' || sqlerrm;
        insert into pa.error_bitacora_monitor values(sysdate,vError);
        raise;
END TRG_AUDITA_PR_CREDITOS;
/
ALTER TRIGGER "PR"."TRG_AUDITA_PR_CREDITOS" DISABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "PR"."TRG_PRODUCTOS_CLTE" 
AFTER INSERT
ON PR.PR_CREDITOS REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
vCodError       Varchar2(20);
vAudita         Varchar2(1) := null;
vEstCliente     Varchar2(1) := null; --Asigna el valor del estado del cliente
vCodMoneda      Number;
vCodCliente     Number;
vTipTransac     Number;
--
--ENF
vTienda varchar2(120) := null;
vDbCr varchar2(2);
vEjecutivo varchar2(200);
vDescTx varchar2(40);
vCliente varchar2(200);
vActividad  varchar2(200);
--ENF
/******************************************************************************
   NOMBRE:  CC.PRODUCTOS_CLTE
   PROPOSITO:  Armar un string de tipo: |XX|AA|.... con los Productos que tiene el Cliente

   Ver        Date             Author           Description
   ---------  ----------      ---------------  ------------------------------------
   1.0        10/18/2008   Hans Jorge     Creacion del Trigger.

   NOTAS:
   Se dispara este trigger cada vez que se cree un prestamo.
   La funcion PA_INTERFAZ_APLICACION.InsertaProductosClientes(), se encarga de actualizar el campo Modulos de la tabla Clientes _B2000.
   
   Modificacion 02/09/2013 Enver Francisco 
   Agregar la descripcion de la tienda e incluir tambien el tipo 
   de aprobacion de tienda a la tabla de monitor. 
******************************************************************************/

    v_error VARCHAR2(10);
BEGIN
   v_error:= '1';
   BEGIN
   --
        IF NOT PA_INTERFAZ_APLICACION.InsertaProductosClientes(:new.codigo_cliente,'CC',vCodError) THEN
            PA_INTERFAZ_APLICACION.Inserta_Error(sysdate,'Trigger Productos_CLTE ',:new.codigo_cliente, 'Se produjo un error en PA_INTERFAZ_CONSULTA.InsertaProductosClientes','  >>' || sqlerrm || '<<  ');
        END IF;
   --
   EXCEPTION
     WHEN OTHERS THEN
          PA_INTERFAZ_APLICACION.Inserta_Error(sysdate,'Trigger Productos_CLTE ',:new.codigo_cliente, 'Se produjo un error','  >>' || sqlerrm || '<<  ');
          null;
   END;
   -- ------------------------------------------------------------------------ --
   -- Se agrego este codigo para efectuar el envio de la transaccion a monitor --
   -- [Proyecto Inactivacion de Codigos de Clientes] RCEBALLOS 13-04-2010      --
   -- ------------------------------------------------------------------------ --
   v_error:= '2';
   BEGIN
      -- Buscamos el tipo de transaccion de la Apertura de Creditos
      /*vTipTransac := PA.PARAM.Parametro_x_Empresa(:new.codigo_empresa,'TIP_APER_PRES','PR');
      -- Verificar si la transaccion es auditada por minitor
        begin
           select audita_monitor, tip_movimiento, descripcion
             into vAudita, vDbCr, vDescTx
             from cat_tip_Transac
            where cod_sistema = 'PR'
              and tip_transaccion = to_number(vTipTransac);
        exception
             when others then
                  -- En caso de error se asume que no se audita
                  vAudita := 'N';
         end;*/
        v_error:= '3';
        -- Buscar el estado del cliente
        /*begin
           select pe.Estado_Persona, upper(rtrim(ltrim(nombre)))
             into vEstCliente, vCliente
             from Pa.Personas pe
            where pe.cod_persona  = to_char(:new.codigo_cliente);
        exception
             when others then
                  null;
        end;*/
       --
       -- ENF : Verifica si el prestamo tiene referente de tienda.
        v_error:= '4';
        /*if :new.codigo_referente is not null then
            begin
                select descripcion
                into vTienda
                from pr_referentes
                where codigo_referente = :new.codigo_referente;
            exception
              when no_data_found then
                vTienda := null;
            end;
        end if;*/
        --
        v_error:= '5';
        /*begin
            select upper(rtrim(ltrim(primer_nombre))||' '||rtrim(ltrim(segundo_nombre))||' '||rtrim(ltrim(primer_apellido))||' '||rtrim(ltrim(segundo_apellido)))
                into vEjecutivo
            from personas_fisicas p, Usuarios U
            where u.cod_usuario = :new.codigo_ejecutivo
            and u.cod_per_fisica = p.cod_per_fisica;            
        exception
            when others then
                vEjecutivo := null;
        end;*/
        --
        v_error:= '6';
       /* select ciuu.segregacion_rd || '-'||ciuu.concepto
        into vActividad
        from PA.ACTIVIDADES_ECONOMICAS_BC_CIIU ciuu
        where ciuu.segregacion_rd in(select pf.cod_actividad
                                                from personas_fisicas pf
                                                where pf.cod_per_fisica = to_char(:new.codigo_cliente)
                                                union all
                                                select pj.cod_actividad
                                                from personas_juridicas pj
                                                where pj.cod_per_juridica = to_char(:new.codigo_cliente));*/
        --
        v_error:= '7';
        if vEstCliente = 'N' then -- Enviamos a Monitor todos los clientes con estado (N - nomina)
            if nvl(vAudita,'N') = 'S' then
                --ENF: 02/09/2013: se comento debido a que todos los campos de la tabla de monitor no estan incluidos en el proceso que inserta en ella. A lo cual se agrego estas sentencias.
                BEGIN 
                INSERT INTO PA.BITACORA_MONITOR
                (
                   SECUENCIA_LOG, TIPO_REGISTRO,  COD_SISTEMA, ORIGEN_TX, TIPO_TRANSACCION, 
                   SUBTIP_TRANSACCION, FECHA, HORA, USUARIO_TX, USUARIO_MODIFICA, USUARIO_REVERSA, 
                   USUARIO_AUTORIZA, FECHA_MODIFICA, FECHA_REVERSO, FECHA_AUTORIZACION, TERMINAL, 
                   AGENCIA, REFERENCIA, TIPO_CUENTA, NUMERO_CUENTA, MONTO_TX, MONTO_EFECTIVO, 
                   MONTO_DOCUMENTO, MONTO_CK_PROPIO, MONTO_CK_OTROS, SALDO_CUENTA, MONTO_DISPONIBLE, 
                   INDICADOR_DBCR, INDICADOR_REVERSO, INDICADOR_EMPLEADO, FECHA_APERTURA_CTA, MONEDA_TX, 
                   MONEDA_CUENTA, COD_CLIENTE, NOMBRE_CLIENTE, NOMBRE_BENEFICIARIO, NUMERO_DOCUMENTO, 
                   CODIGO_CAJERO, TASA_CAMBIO, ESTADO_MOVIMIENTO, DESCRIPCION_TX, NUMERO_AUTORIZACION, 
                   COD_PRODUCTO, NUMERO_TARJETA, ESTADO_CUENTA, COD_OFICIAL, NOMBRE_OFICIAL,
                   DATO_ANTES_ACTUALIZA, DATO_DESPUES_ACTUALIZA, DATOS_ANTES_CAMBIO, FUERA_HORARIO, 
                   ESTADO_CLIENTE
                )
                VALUES
                (
                    0, 1, 'PR', 'PR', vTipTransac,     
                    null, to_char(sysdate, 'YYYYMMDD'), to_char(sysdate, 'HH24MISS'), user,:new.plazo,null,  
                    null, to_char(:new.f_vencimiento, 'YYYYMMDD'), null, to_char(:new.f_apertura, 'YYYYMMDD'), :new.dia_pago,
                    :new.codigo_agencia, null, null, null, :new.monto_credito, null, 
                    null, null, null, :new.monto_credito, null, 
                    vDbCr, null, null, null, :new.codigo_moneda, 
                    :new.codigo_moneda, :new.codigo_cliente, substr(vCliente,1,60), :new.res_apr_inmed, /*--ENF: 03/10/2013*/:old.tasa_interes/*null*/, 
                    null, :new.tasa_interes, null, vDescTx, null, 
                    :new.tipo_credito, :new.no_credito, :new.estado, :new.codigo_ejecutivo, vEjecutivo,
                    null, vActividad/*null*/, vTienda, null, vEstCliente
                );
                EXCEPTION 
                    WHEN OTHERS THEN 
                       NULL;  
                END;
                /*PA.AUDITA_TRANSACCION
                (
                 pTipoRegistro     => 1 -- Transaccion
                ,pCodSistema       => 'PR'
                ,pOrigenTx         => 'PR'
                ,pTipoTx           => vTipTransac
                ,pSubTipoTx        => null-- vSubtipTransac
                ,pFechaTx          => to_char(sysdate, 'YYYYMMDD')
                ,pHoraTx           => to_char(sysdate, 'HHMISS')
                ,pUsuarioTx        => :new.adicionado_por
                ,pUsuarioMod       => null
                ,pUsuarioRev       => null
                ,pUsuarioAut       => :new.aprobado_por
                ,pFechaMod         => null
                ,pFechaRev         => null
                ,pFechaAut         => null
                ,pAgencia          => :new.codigo_agencia
                ,pReferencia       => null
                ,pNumCuenta        => null
                ,pMontoTx          => :new.monto_credito
                ,pMontoEfectivo    => 0
                ,pMontoDocumento   => 0
                ,pMontoCkPropio    => null
                ,pMontoCkOtros     => null
                ,pReverso          => null
                ,pMonedaTx         => to_char(:new.codigo_moneda)
                ,pCodCliente       => to_char(:new.codigo_cliente)
                ,pNumeroDocumento  => :new.no_credito
                ,pCodCajero        => null
                ,pTasaCambio       => null
                ,pEstadoMovimiento => :new.estado
                ,pDescripcionTx    => null
                ,pNumAutorizacion  => null
                ,pNumTarjeta       => null
                ,pEstadoCliente    => vEstCliente -- Estado del cliente
                ,pDatosAntes        => vTienda -- Nombre de la Tienda del Prestamo.
                );*/
            end if;
        end if;
   END;

END ;
/
ALTER TRIGGER "PR"."TRG_PRODUCTOS_CLTE" DISABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "PR"."TRG_PR_GENERA_DEPONENTE" 
   BEFORE INSERT 
   ON PR.PR_CREDITOS
   REFERENCING NEW AS New OLD AS Old
   FOR EACH ROW
DECLARE
    
    vCiudad         VARCHAR2(300) := 'Santo Domingo';
    vExiste         PLS_INTEGER := 0;
    vError          VARCHAR2(4000);
BEGIN
   BEGIN
      IF (:NEW.estado = 'R') THEN
            -- Si no es un crédito de Represtamos
            SELECT COUNT(1) INTO vExiste 
              FROM PR.PR_REPRESTAMOS R 
             WHERE R.NO_CREDITO = :NEW.NO_CREDITO;
             
            IF vExiste = 0 THEN
                BEGIN      
                    PR.Generar_reporte_deponente(p_No_Credito       => :NEW.NO_CREDITO,
                                                 p_Codigo_Cliente   => :NEW.CODIGO_CLIENTE,
                                                 p_Ciudad           => vCiudad,
                                                 pError             => vError);
                END;
            END IF;
      END IF;
   END;
END TRG_PR_GENERA_DEPONENTE;
/
ALTER TRIGGER "PR"."TRG_PR_GENERA_DEPONENTE" DISABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "PR"."TRG_BUI_REG_CREDITOS" 
BEFORE INSERT OR UPDATE
ON "PR"."PR_CREDITOS" REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
  v_observaciones  VARCHAR(1000);
BEGIN
  
   --malmanzar 17-01-2023 Begin
   IF :NEW.ESTADO_APROBACION IS NULL THEN
      :NEW.ESTADO_APROBACION := 'P';
   END IF;  --malmanzar 17-01-2023 End
     
   --malmanzar 27-11-2024 req. 27744 REQ.PROUSUARIO  BEGIN
       IF :NEW.ESTADO_APROBACION  = 'R'  
         AND  :NEW.ESTADO_APROBACION !=  :OLD.ESTADO_APROBACION
         THEN
         BEGIN
               pa.pa_pkg_notificacion.p_rechazo_solicitud(1,'PR',:NEW.NO_CREDITO);
               EXCEPTION 
               WHEN OTHERS
                THEN
                p_depura('sqlerrm: '||sqlerrm);  
                 NULL;  --Evaluar registro log errores.
              END;
       END IF;
      --malmanzar 27-11-2024 req. 27744 REQ.PROUSUARIO  END

  IF UPDATING THEN
    IF :new.estado = 'N' and :old.estado != 'N'  THEN
      BEGIN
      -- solo entra acá en caso de que el estado esté pasando de cualquier estado a Anulado(N)
       PR.PINSERTAFILEFLOW(:new.no_credito, 'AN', USER, '0');
      EXCEPTION
        WHEN OTHERS THEN NULL;
      END;
    END IF;    
  END IF;
  IF :new.codigo_calificacion_sistema IS NULL THEN
     :new.codigo_calificacion_sistema := 'A';
  END IF;
  
  IF nvl(:old.codigo_ejecutivo,'x')!=nvl(:new.codigo_ejecutivo,'x') THEN
    BEGIN
       select 'TERMINAL:'||terminal||' | MACHINE:'||machine||' | PROGRAM:'||program||' | OSUSER:'||osuser
       INTO v_observaciones 
        from V$session
        where username = user
        and SID = SYS_CONTEXT ('USERENV', 'SID');
       INSERT INTO PR_CAMBIOS_OFICIAL_PR_CREDITOS
            (CODIGO_EMPRESA, NO_CREDITO, CODIGO_EJECUTIVO_ANT, CODIGO_EJECUTIVO_ACTUAL, ID_USR_CAMBIA, observaciones)
       VALUES
            (:new.codigo_empresa,:new.no_credito,:old.codigo_ejecutivo,:new.codigo_ejecutivo,USER, v_observaciones);
    EXCEPTION
      WHEN OTHERS THEN NULL;
    END;
  END IF; 
END;
/
ALTER TRIGGER "PR"."TRG_BUI_REG_CREDITOS" ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "PR"."TRG_PR_GENERA_REPORTES" 
   BEFORE INSERT 
   ON PR.PR_CREDITOS
   REFERENCING NEW AS New OLD AS Old
   FOR EACH ROW
DECLARE
    vError_reporte  VARCHAR2(4000);
BEGIN
   BEGIN
      IF (:NEW.estado = 'R') THEN
           PR.Generar_Reportes_Prestamo(:New.codigo_empresa,
                                        :New.no_credito, -- pCreditoNuevo      ,
                                        :Old.no_credito, --pCreditoAnterior   ,
                                         false, --pValidaReprestamo  ,
                                         vError_reporte  );
           
      END IF;
   END;
END TRG_PR_GENERA_DEPONENTE;
/
ALTER TRIGGER "PR"."TRG_PR_GENERA_REPORTES" DISABLE;


  GRANT SELECT ON "PR"."PR_CREDITOS" TO "B2000";
  GRANT ALTER ON "PR"."PR_CREDITOS" TO "PA" WITH GRANT OPTION;
  GRANT DELETE ON "PR"."PR_CREDITOS" TO "PA" WITH GRANT OPTION;
  GRANT INDEX ON "PR"."PR_CREDITOS" TO "PA" WITH GRANT OPTION;
  GRANT INSERT ON "PR"."PR_CREDITOS" TO "PA" WITH GRANT OPTION;
  GRANT SELECT ON "PR"."PR_CREDITOS" TO "PA" WITH GRANT OPTION;
  GRANT UPDATE ON "PR"."PR_CREDITOS" TO "PA" WITH GRANT OPTION;
  GRANT REFERENCES ON "PR"."PR_CREDITOS" TO "PA" WITH GRANT OPTION;
  GRANT SELECT ON "PR"."PR_CREDITOS" TO "RT" WITH GRANT OPTION;
  GRANT REFERENCES ON "PR"."PR_CREDITOS" TO PUBLIC;
  GRANT SELECT ON "PR"."PR_CREDITOS" TO "OPERXX";
  GRANT SELECT ON "PR"."PR_CREDITOS" TO "ACL";
  GRANT SELECT ON "PR"."PR_CREDITOS" TO "IVR";
  GRANT SELECT ON "PR"."PR_CREDITOS" TO "DY";
  GRANT SELECT ON "PR"."PR_CREDITOS" TO "CONGEN";
  GRANT SELECT ON "PR"."PR_CREDITOS" TO "BDI";
  GRANT ALTER ON "PR"."PR_CREDITOS" TO "BPR";
  GRANT DELETE ON "PR"."PR_CREDITOS" TO "BPR";
  GRANT INSERT ON "PR"."PR_CREDITOS" TO "BPR";
  GRANT SELECT ON "PR"."PR_CREDITOS" TO "BPR";
  GRANT UPDATE ON "PR"."PR_CREDITOS" TO "BPR";
  GRANT DELETE ON "PR"."PR_CREDITOS" TO "BCG";
  GRANT INSERT ON "PR"."PR_CREDITOS" TO "BCG";
  GRANT SELECT ON "PR"."PR_CREDITOS" TO "BCG";
  GRANT UPDATE ON "PR"."PR_CREDITOS" TO "BCG";
  GRANT SELECT ON "PR"."PR_CREDITOS" TO "DI";
  GRANT SELECT ON "PR"."PR_CREDITOS" TO "CC";
  GRANT SELECT ON "PR"."PR_CREDITOS" TO "SB";
  GRANT REFERENCES ON "PR"."PR_CREDITOS" TO "SB";
  GRANT SELECT ON "PR"."PR_CREDITOS" TO "TF";
  GRANT SELECT ON "PR"."PR_CREDITOS" TO "FC";
  GRANT ALTER ON "PR"."PR_CREDITOS" TO "RH";
  GRANT DELETE ON "PR"."PR_CREDITOS" TO "RH";
  GRANT INDEX ON "PR"."PR_CREDITOS" TO "RH";
  GRANT INSERT ON "PR"."PR_CREDITOS" TO "RH";
  GRANT SELECT ON "PR"."PR_CREDITOS" TO "RH";
  GRANT UPDATE ON "PR"."PR_CREDITOS" TO "RH";
  GRANT REFERENCES ON "PR"."PR_CREDITOS" TO "RH";
  GRANT ON COMMIT REFRESH ON "PR"."PR_CREDITOS" TO "RH";
  GRANT QUERY REWRITE ON "PR"."PR_CREDITOS" TO "RH";
  GRANT DEBUG ON "PR"."PR_CREDITOS" TO "RH";
  GRANT FLASHBACK ON "PR"."PR_CREDITOS" TO "RH";
  GRANT SELECT ON "PR"."PR_CREDITOS" TO PUBLIC;
  GRANT ALTER ON "PR"."PR_CREDITOS" TO "BDI";
  GRANT DELETE ON "PR"."PR_CREDITOS" TO "BDI";
  GRANT INSERT ON "PR"."PR_CREDITOS" TO "BDI";
  GRANT UPDATE ON "PR"."PR_CREDITOS" TO "BDI";
  GRANT ALTER ON "PR"."PR_CREDITOS" TO "BCG";
  GRANT ALTER ON "PR"."PR_CREDITOS" TO "CONGEN";
  GRANT DELETE ON "PR"."PR_CREDITOS" TO "CONGEN";
  GRANT INSERT ON "PR"."PR_CREDITOS" TO "CONGEN";
  GRANT UPDATE ON "PR"."PR_CREDITOS" TO "CONGEN";
  GRANT ALTER ON "PR"."PR_CREDITOS" TO PUBLIC;
  GRANT DELETE ON "PR"."PR_CREDITOS" TO PUBLIC;
  GRANT INSERT ON "PR"."PR_CREDITOS" TO PUBLIC;
  GRANT UPDATE ON "PR"."PR_CREDITOS" TO PUBLIC;
  GRANT DELETE ON "PR"."PR_CREDITOS" TO "BCB";
  GRANT INSERT ON "PR"."PR_CREDITOS" TO "BCB";
  GRANT SELECT ON "PR"."PR_CREDITOS" TO "BCB";
  GRANT UPDATE ON "PR"."PR_CREDITOS" TO "BCB";
  GRANT SELECT ON "PR"."PR_CREDITOS" TO "PS";
  GRANT SELECT ON "PR"."PR_CREDITOS" TO "BCV";
  GRANT SELECT ON "PR"."PR_CREDITOS" TO "CV";
  GRANT SELECT ON "PR"."PR_CREDITOS" TO "ICUEVA";
  GRANT SELECT ON "PR"."PR_CREDITOS" TO "JEGARCIA";
  GRANT SELECT ON "PR"."PR_CREDITOS" TO "OCASTRO";
  GRANT SELECT ON "PR"."PR_CREDITOS" TO "ICUEVAS";
  GRANT SELECT ON "PR"."PR_CREDITOS" TO "BFERNANDEZ";
  GRANT SELECT ON "PR"."PR_CREDITOS" TO "BPA";
  GRANT SELECT ON "PR"."PR_CREDITOS" TO "BTC";
  GRANT SELECT ON "PR"."PR_CREDITOS" TO "CJ";
  GRANT SELECT ON "PR"."PR_CREDITOS" TO "ASEGURA";
  GRANT DELETE ON "PR"."PR_CREDITOS" TO "BPR";
  GRANT INSERT ON "PR"."PR_CREDITOS" TO "BPR";
  GRANT SELECT ON "PR"."PR_CREDITOS" TO "BPR";
  GRANT UPDATE ON "PR"."PR_CREDITOS" TO "BPR";
  GRANT SELECT ON "PR"."PR_CREDITOS" TO "TCAPROBAD1";
  GRANT SELECT ON "PR"."PR_CREDITOS" TO "CB";
  GRANT SELECT ON "PR"."PR_CREDITOS" TO "TCAPROBAD2";
  GRANT SELECT ON "PR"."PR_CREDITOS" TO "TCDIGITADO";
  GRANT SELECT ON "PR"."PR_CREDITOS" TO "TCVERIFFIN";
  GRANT SELECT ON "PR"."PR_CREDITOS" TO "TCVERIFINI";
  GRANT SELECT ON "PR"."PR_CREDITOS" TO "JSANCHEZ";
  GRANT SELECT ON "PR"."PR_CREDITOS" TO "SII";
  GRANT SELECT ON "PR"."PR_CREDITOS" TO "FERMINR";
  GRANT SELECT ON "PR"."PR_CREDITOS" TO "GASANCHEZ";
  GRANT SELECT ON "PR"."PR_CREDITOS" TO PUBLIC;
  GRANT SELECT ON "PR"."PR_CREDITOS" TO "BPA";
  GRANT SELECT ON "PR"."PR_CREDITOS" TO "CDG";
  GRANT SELECT ON "PR"."PR_CREDITOS" TO "CB";
  GRANT SELECT ON "PR"."PR_CREDITOS" TO "IA";
  GRANT SELECT ON "PR"."PR_CREDITOS" TO "USR_APPS";
  GRANT SELECT ON "PR"."PR_CREDITOS" TO "USR_BGP";
