
  CREATE TABLE "PR"."PR_CODIGOS_REPRESTAMO" 
   (	"CODIGO_EMPRESA" NUMBER(4,0) CONSTRAINT "NN_PR_CODIGOS_REPRESTAMO01" NOT NULL ENABLE, 
	"CODIGO_REPRESTAMO" VARCHAR2(2 BYTE) CONSTRAINT "NN_PR_CODIGOS_REPRESTAMO02" NOT NULL ENABLE, 
	"DESCRIPCION" VARCHAR2(100 BYTE) CONSTRAINT "NN_PR_CODIGOS_REPRESTAMO03" NOT NULL ENABLE, 
	"DESDE" NUMBER(5,0) CONSTRAINT "NN_PR_CODIGOS_REPRESTAMO04" NOT NULL ENABLE, 
	"HASTA" NUMBER(5,0) CONSTRAINT "NN_PR_CODIGOS_REPRESTAMO05" NOT NULL ENABLE, 
	"ADICIONADO_POR" VARCHAR2(30 BYTE) DEFAULT USER CONSTRAINT "NN_PR_CODIGOS_REPRESTAMO06" NOT NULL ENABLE, 
	"FECHA_ADICION" DATE DEFAULT SYSDATE CONSTRAINT "NN_PR_CODIGOS_REPRESTAMO07" NOT NULL ENABLE, 
	"MODIFICADO_POR" VARCHAR2(30 BYTE), 
	"FECHA_MODIFICACION" DATE, 
	"FACTOR" NUMBER(5,2) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 MAXSIZE UNLIMITED
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PR_DAT" ;
  CREATE UNIQUE INDEX "PR"."PK_PR_CODIGOS_REPRESTAMO" ON "PR"."PR_CODIGOS_REPRESTAMO" ("CODIGO_EMPRESA", "CODIGO_REPRESTAMO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 MAXSIZE UNLIMITED
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PR_DAT" ;
ALTER TABLE "PR"."PR_CODIGOS_REPRESTAMO" ADD CONSTRAINT "PK_PR_CODIGOS_REPRESTAMO" PRIMARY KEY ("CODIGO_EMPRESA", "CODIGO_REPRESTAMO")
  USING INDEX "PR"."PK_PR_CODIGOS_REPRESTAMO"  ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "PR"."TRG_BUI_PR_CODIGOS_REPRESTAMO" 
BEFORE INSERT OR UPDATE
ON PR.PR_CODIGOS_REPRESTAMO REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
  IF INSERTING THEN
     :new.fecha_adicion := sysdate;
  ELSE 
     :new.fecha_modificacion := sysdate;
  END IF;
END;
/
ALTER TRIGGER "PR"."TRG_BUI_PR_CODIGOS_REPRESTAMO" ENABLE;


  GRANT SELECT ON "PR"."PR_CODIGOS_REPRESTAMO" TO "BPR";
