
  CREATE TABLE "PR"."PR_DOCUMENTOS_REPRESTAMO" 
   (	"ID_DOCUMENTO" NUMBER(14,0) NOT NULL ENABLE, 
	"MIMETYPE" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"NOMBRE_DOCUMENTO" VARCHAR2(256 BYTE) NOT NULL ENABLE, 
	"DESCRIPCION" VARCHAR2(4000 BYTE) NOT NULL ENABLE, 
	"DOCUMENTO" BLOB, 
	"ADICIONADO_POR" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"FECHA_ADICION" DATE NOT NULL ENABLE, 
	"MODIFICADO_POR" VARCHAR2(30 BYTE), 
	"FECHA_MODIFICACION" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 MAXSIZE UNLIMITED
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PR_DAT" 
 LOB ("DOCUMENTO") STORE AS BASICFILE (
  TABLESPACE "PR_DAT" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
  CREATE UNIQUE INDEX "PR"."PK_DOCUMENTOS_REPRESTAMO" ON "PR"."PR_DOCUMENTOS_REPRESTAMO" ("ID_DOCUMENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 MAXSIZE UNLIMITED
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PR_DAT" ;
ALTER TABLE "PR"."PR_DOCUMENTOS_REPRESTAMO" ADD CONSTRAINT "PK_DOCUMENTOS_REPRESTAMO" PRIMARY KEY ("ID_DOCUMENTO")
  USING INDEX "PR"."PK_DOCUMENTOS_REPRESTAMO"  ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "PR"."TRG_BUI_DOCUMENTOS_REPRESTAMO" 
BEFORE INSERT OR UPDATE
ON pr.PR_DOCUMENTOS_REPRESTAMO REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
  IF INSERTING THEN
     :new.id_documento := PR.SEQ_DOCUMENTO_REPRESTAMO.NEXTVAL;
     :new.fecha_adicion := sysdate; 
     if :new.adicionado_por is null THEN
        :new.adicionado_por := user;
     end if;
    
  ELSE 
     :new.fecha_modificacion := sysdate;
     if :new.modificado_por is null THEN
        :new.modificado_por := user;
     end if;
  END IF;
END;
/
ALTER TRIGGER "PR"."TRG_BUI_DOCUMENTOS_REPRESTAMO" ENABLE;


  GRANT ALTER ON "PR"."PR_DOCUMENTOS_REPRESTAMO" TO "BPR";
  GRANT ALTER ON "PR"."PR_DOCUMENTOS_REPRESTAMO" TO "BIA";
  GRANT ALTER ON "PR"."PR_DOCUMENTOS_REPRESTAMO" TO "BPA";
  GRANT DELETE ON "PR"."PR_DOCUMENTOS_REPRESTAMO" TO "BPR";
  GRANT DELETE ON "PR"."PR_DOCUMENTOS_REPRESTAMO" TO "BIA";
  GRANT DELETE ON "PR"."PR_DOCUMENTOS_REPRESTAMO" TO "BPA";
  GRANT INSERT ON "PR"."PR_DOCUMENTOS_REPRESTAMO" TO "BPR";
  GRANT INSERT ON "PR"."PR_DOCUMENTOS_REPRESTAMO" TO "BIA";
  GRANT INSERT ON "PR"."PR_DOCUMENTOS_REPRESTAMO" TO "BPA";
  GRANT SELECT ON "PR"."PR_DOCUMENTOS_REPRESTAMO" TO "BPR";
  GRANT SELECT ON "PR"."PR_DOCUMENTOS_REPRESTAMO" TO "BIA";
  GRANT SELECT ON "PR"."PR_DOCUMENTOS_REPRESTAMO" TO "BPA";
  GRANT UPDATE ON "PR"."PR_DOCUMENTOS_REPRESTAMO" TO "BPR";
  GRANT UPDATE ON "PR"."PR_DOCUMENTOS_REPRESTAMO" TO "BIA";
  GRANT UPDATE ON "PR"."PR_DOCUMENTOS_REPRESTAMO" TO "BPA";
  GRANT ON COMMIT REFRESH ON "PR"."PR_DOCUMENTOS_REPRESTAMO" TO "BPR";
  GRANT ON COMMIT REFRESH ON "PR"."PR_DOCUMENTOS_REPRESTAMO" TO "BIA";
  GRANT ON COMMIT REFRESH ON "PR"."PR_DOCUMENTOS_REPRESTAMO" TO "BPA";
  GRANT QUERY REWRITE ON "PR"."PR_DOCUMENTOS_REPRESTAMO" TO "BPR";
  GRANT QUERY REWRITE ON "PR"."PR_DOCUMENTOS_REPRESTAMO" TO "BIA";
  GRANT QUERY REWRITE ON "PR"."PR_DOCUMENTOS_REPRESTAMO" TO "BPA";
  GRANT DEBUG ON "PR"."PR_DOCUMENTOS_REPRESTAMO" TO "BPR";
  GRANT DEBUG ON "PR"."PR_DOCUMENTOS_REPRESTAMO" TO "BIA";
  GRANT DEBUG ON "PR"."PR_DOCUMENTOS_REPRESTAMO" TO "BPA";
  GRANT FLASHBACK ON "PR"."PR_DOCUMENTOS_REPRESTAMO" TO "BPR";
  GRANT FLASHBACK ON "PR"."PR_DOCUMENTOS_REPRESTAMO" TO "BIA";
  GRANT FLASHBACK ON "PR"."PR_DOCUMENTOS_REPRESTAMO" TO "BPA";
