
  CREATE TABLE "PR"."PR_TIPO_CREDITO_REPRESTAMO" 
   (	"CODIGO_EMPRESA" NUMBER(4,0) NOT NULL ENABLE, 
	"TIPO_CREDITO" NUMBER(3,0) NOT NULL ENABLE, 
	"ESTADO" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	"ADICIONADO_POR" VARCHAR2(30 BYTE) DEFAULT USER NOT NULL ENABLE, 
	"FECHA_ADICION" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"MODIFICADO_POR" VARCHAR2(30 BYTE), 
	"FECHA_MODIFICACION" DATE, 
	"OBSOLETO" NUMBER DEFAULT 0, 
	"CARGA" CHAR(1 BYTE) DEFAULT 'S', 
	"CREDITO_CAMPANA_ESPECIAL" CHAR(1 BYTE) DEFAULT NULL, 
	"CREDITO_FMO" CHAR(1 BYTE), 
	 CONSTRAINT "CK01_TIPO_CREDITO_REPRESTAMO" CHECK (ESTADO in ('A','I')) ENABLE, 
	 CONSTRAINT "FK01_TIPO_CREDITO_REPRESTAMO" FOREIGN KEY ("CODIGO_EMPRESA", "TIPO_CREDITO")
	  REFERENCES "PR"."PR_TIPO_CREDITO" ("CODIGO_EMPRESA", "TIPO_CREDITO") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 MAXSIZE UNLIMITED
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PR_DAT" ;
  CREATE UNIQUE INDEX "PR"."PK01_TIPO_CRED_REPRESTAMO" ON "PR"."PR_TIPO_CREDITO_REPRESTAMO" ("CODIGO_EMPRESA", "TIPO_CREDITO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 MAXSIZE UNLIMITED
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PR_DAT" ;
ALTER TABLE "PR"."PR_TIPO_CREDITO_REPRESTAMO" ADD CONSTRAINT "PK01_TIPO_CRED_REPRESTAMO" PRIMARY KEY ("CODIGO_EMPRESA", "TIPO_CREDITO")
  USING INDEX "PR"."PK01_TIPO_CRED_REPRESTAMO"  ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "PR"."TRG_BUI_TIPO_CRED_REPRESTAMO" 
BEFORE INSERT OR UPDATE
ON PR.PR_tipo_credito_REPRESTAMO REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
  IF INSERTING THEN
     :new.fecha_adicion := sysdate;
     :new.estado := 'A';
  ELSE 
     :new.fecha_modificacion := sysdate;
  END IF;
END;
/
ALTER TRIGGER "PR"."TRG_BUI_TIPO_CRED_REPRESTAMO" ENABLE;


  GRANT SELECT ON "PR"."PR_TIPO_CREDITO_REPRESTAMO" TO "BPR";
