
  CREATE TABLE "PA"."EMPLEADOS" 
   (	"COD_EMPRESA" VARCHAR2(5 BYTE), 
	"ID_EMPLEADO" VARCHAR2(10 BYTE), 
	"COD_PER_FISICA" VARCHAR2(15 BYTE) CONSTRAINT "NN_EMPLEADOS_COD_PER_FISICA" NOT NULL ENABLE, 
	"COD_PUESTO" VARCHAR2(6 BYTE), 
	"COD_AGENCIA" VARCHAR2(5 BYTE) CONSTRAINT "NN_EMPLEADOS_CODAGENCIA" NOT NULL ENABLE, 
	"COD_AGENCIA_LABORA" VARCHAR2(5 BYTE) CONSTRAINT "NN_EMPLEADOS_CODAGENCIALABORA" NOT NULL ENABLE, 
	"ESTA_ACTIVO" VARCHAR2(1 BYTE), 
	"FEC_INGRESO" DATE CONSTRAINT "NN_EMPLEADOS_FECINGRESO" NOT NULL ENABLE, 
	"EXTENSION" NUMBER(5,0), 
	"ATIENDE_QUEJAS" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"ATIENDE_PUBLICO" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"CROSSELLING" NUMBER(8,4), 
	"RENTABILIDAD" NUMBER(8,4), 
	"ES_OFICIAL" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"ES_PROMOTOR" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"ES_EXTERNO" VARCHAR2(1 BYTE), 
	"COD_CANAL" VARCHAR2(3 BYTE), 
	"EMAIL1" VARCHAR2(50 BYTE), 
	"EMAIL2" VARCHAR2(50 BYTE), 
	"SUPERVISOR" VARCHAR2(10 BYTE), 
	"FIRMA_AUTORIZADA" VARCHAR2(1 BYTE), 
	"TIPO_FIRMA" VARCHAR2(1 BYTE), 
	"IMP_CORTE_CTA" VARCHAR2(1 BYTE), 
	"COD_MOTIVO" VARCHAR2(2 BYTE), 
	"ES_OFICIAL_CTA" VARCHAR2(1 BYTE), 
	"IND_AUTOSEGESP" VARCHAR2(1 BYTE), 
	"NIVEL_APROBACION" NUMBER(1,0) DEFAULT 0, 
	"VER_TODOS_REFERIDOS" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"ID_JEFE" VARCHAR2(10 BYTE), 
	"CATEG_EMPLEADOS" VARCHAR2(2 BYTE) DEFAULT 8, 
	"AREA_TRABAJA" VARCHAR2(30 BYTE), 
	"RESPONSAB_EMPLE" VARCHAR2(2 BYTE) DEFAULT 00, 
	"IND_NO_CAMBIO_MASIVO" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"INCLUIDO_POR" VARCHAR2(10 BYTE), 
	"FEC_INCLUSION" DATE, 
	"MODIFICADO_POR" VARCHAR2(10 BYTE), 
	"FEC_MODIFICACION" DATE, 
	"TIPO_EMPLEADO" VARCHAR2(1 BYTE), 
	"FECHA_FIN_CONTRATO" DATE, 
	 CONSTRAINT "CK_EMPLEADOS_ES_PROMOTOR" CHECK ( ES_PROMOTOR IN ('S','N')             ) ENABLE, 
	 CONSTRAINT "CK_EMPLEADOS_ATIENDE_PUBLICO" CHECK ( ATIENDE_PUBLICO IN ('S','N')             ) ENABLE, 
	 CONSTRAINT "CK_EMPLEADOS_ES_OFICIAL" CHECK ( ES_OFICIAL IN ('S','N')             ) ENABLE, 
	 CONSTRAINT "CK_EMPLEADOS_ESEXTERNO" CHECK (ES_EXTERNO  IN ('S', 'N')) ENABLE, 
	 CONSTRAINT "CK_EMPLEADOS_FIRMAAUT" CHECK (FIRMA_AUTORIZADA  IN ('S', 'N')) ENABLE, 
	 CONSTRAINT "CK_EMPLEADOS_TIPOFIRMA" CHECK (TIPO_FIRMA  IN ('A', 'B','C')) ENABLE, 
	 CONSTRAINT "CK_EMPLEADOS_IMPCORTECTA" CHECK (IMP_CORTE_CTA  IN ('S', 'N')) ENABLE, 
	 CONSTRAINT "CK_EMPLEADOS_ES_OFICIAL_CTA" CHECK (ES_OFICIAL_CTA  IN ('S', 'N')) ENABLE, 
	 CONSTRAINT "CK_EMPLEADOS_AUTOSEGESP" CHECK (IND_AUTOSEGESP IN ('S', 'N')) ENABLE, 
	 CONSTRAINT "CK_EMPLEADOS_NIVELAPROB" CHECK (NIVEL_APROBACION IN ('0','1', '2', '3', '4')) ENABLE, 
	 CONSTRAINT "CK_EMPLEADOS_VERREFER" CHECK (VER_TODOS_REFERIDOS IN ('S', 'N')) ENABLE, 
	 CONSTRAINT "CK_EMPLEADOS_ATIENDE_QUEJAS" CHECK ( ATIENDE_QUEJAS IN ('S','N')             ) ENABLE, 
	 CONSTRAINT "CK_EMPLEADOS_ESTA_ACTIVO" CHECK ( ESTA_ACTIVO IN ('S','N')             ) ENABLE, 
	 CONSTRAINT "NN_EMPLEADO_RESPEMP" CHECK (responsab_emple IS NOT NULL) ENABLE, 
	 CONSTRAINT "FK_EMPLEADOS_PERSONAS_FISICAS" FOREIGN KEY ("COD_PER_FISICA")
	  REFERENCES "PA"."PERSONAS_FISICAS" ("COD_PER_FISICA") ENABLE, 
	 CONSTRAINT "FK_EMPLEADOS_CANAL" FOREIGN KEY ("COD_CANAL")
	  REFERENCES "PA"."CANAL_DISTRIBUCION" ("COD_CANAL") ENABLE, 
	 CONSTRAINT "FK_EMPLEADOS_PUESTOS" FOREIGN KEY ("COD_EMPRESA", "COD_PUESTO")
	  REFERENCES "PA"."PUESTOS" ("COD_EMPRESA", "COD_PUESTO") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 80 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA_EFD" ;
  CREATE UNIQUE INDEX "PA"."PK_EMPLEADOS" ON "PA"."EMPLEADOS" ("COD_EMPRESA", "ID_EMPLEADO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IND_EFD" ;
ALTER TABLE "PA"."EMPLEADOS" ADD CONSTRAINT "PK_EMPLEADOS" PRIMARY KEY ("COD_EMPRESA", "ID_EMPLEADO")
  USING INDEX "PA"."PK_EMPLEADOS"  ENABLE;

   COMMENT ON COLUMN "PA"."EMPLEADOS"."COD_EMPRESA" IS 'Codigo de la empresa a la que pertenece la informacion. Esta relacionada a la tabla PA.EMPRESA';
   COMMENT ON COLUMN "PA"."EMPLEADOS"."ID_EMPLEADO" IS 'Id de empleado';
   COMMENT ON COLUMN "PA"."EMPLEADOS"."COD_PER_FISICA" IS 'Codigo de persona fisica';
   COMMENT ON COLUMN "PA"."EMPLEADOS"."COD_PUESTO" IS 'Codigo de puesto';
   COMMENT ON COLUMN "PA"."EMPLEADOS"."COD_AGENCIA" IS 'Codigo agencia';
   COMMENT ON COLUMN "PA"."EMPLEADOS"."COD_AGENCIA_LABORA" IS 'Codigo agencia laboral';
   COMMENT ON COLUMN "PA"."EMPLEADOS"."ESTA_ACTIVO" IS 'Indicador estado activo';
   COMMENT ON COLUMN "PA"."EMPLEADOS"."FEC_INGRESO" IS 'Fecha ingreso';
   COMMENT ON COLUMN "PA"."EMPLEADOS"."EXTENSION" IS 'Extension telefonico';
   COMMENT ON COLUMN "PA"."EMPLEADOS"."ATIENDE_QUEJAS" IS 'Indicador de atiende quejas';
   COMMENT ON COLUMN "PA"."EMPLEADOS"."ATIENDE_PUBLICO" IS 'Indicador de atiende al publico';
   COMMENT ON COLUMN "PA"."EMPLEADOS"."CROSSELLING" IS 'ventas cruzadas';
   COMMENT ON COLUMN "PA"."EMPLEADOS"."RENTABILIDAD" IS 'Rentabilidad expresada en montos';
   COMMENT ON COLUMN "PA"."EMPLEADOS"."ES_OFICIAL" IS 'Indicador de si es oficial';
   COMMENT ON COLUMN "PA"."EMPLEADOS"."ES_PROMOTOR" IS 'Indicador de si es promtor';
   COMMENT ON COLUMN "PA"."EMPLEADOS"."ES_EXTERNO" IS 'Indicador de si es empleado externo';
   COMMENT ON COLUMN "PA"."EMPLEADOS"."COD_CANAL" IS 'Codigo canal';
   COMMENT ON COLUMN "PA"."EMPLEADOS"."EMAIL1" IS 'Primer email';
   COMMENT ON COLUMN "PA"."EMPLEADOS"."EMAIL2" IS 'Segundo email';
   COMMENT ON COLUMN "PA"."EMPLEADOS"."SUPERVISOR" IS 'Sepervisor';
   COMMENT ON COLUMN "PA"."EMPLEADOS"."FIRMA_AUTORIZADA" IS 'Firma autorizada';
   COMMENT ON COLUMN "PA"."EMPLEADOS"."TIPO_FIRMA" IS 'tipo de firma';
   COMMENT ON COLUMN "PA"."EMPLEADOS"."IMP_CORTE_CTA" IS 'Indicador de si imprime corte de cuentas';
   COMMENT ON COLUMN "PA"."EMPLEADOS"."COD_MOTIVO" IS 'Codigo de motivo';
   COMMENT ON COLUMN "PA"."EMPLEADOS"."ES_OFICIAL_CTA" IS 'Indicador de si es oficial de cuenta';
   COMMENT ON COLUMN "PA"."EMPLEADOS"."IND_AUTOSEGESP" IS 'ALTER TABLE PA.EMPLEADOS';
   COMMENT ON COLUMN "PA"."EMPLEADOS"."NIVEL_APROBACION" IS 'Nivel de aprobacion';
   COMMENT ON COLUMN "PA"."EMPLEADOS"."VER_TODOS_REFERIDOS" IS 'Indicador de ver referidos';
   COMMENT ON COLUMN "PA"."EMPLEADOS"."ID_JEFE" IS 'Indica el codigo del jefe del empleado';
   COMMENT ON COLUMN "PA"."EMPLEADOS"."CATEG_EMPLEADOS" IS 'CATEGORÍA DE FUNCIONARIOS, EMPLEADOS Y RELACIONADOS ';
   COMMENT ON COLUMN "PA"."EMPLEADOS"."AREA_TRABAJA" IS 'Área o departamento en que trabaja';
   COMMENT ON COLUMN "PA"."EMPLEADOS"."RESPONSAB_EMPLE" IS 'RESPONSABILIDADES DE FUNCIONARIOS DE LA ENTIDAD';
   COMMENT ON COLUMN "PA"."EMPLEADOS"."IND_NO_CAMBIO_MASIVO" IS 'Valores (S,N). "S" para indicar que NO permite cambios masivos de oficial ';
   COMMENT ON TABLE "PA"."EMPLEADOS"  IS ' Empleados del banco';

  CREATE INDEX "PA"."EMPLEADOS_FK7" ON "PA"."EMPLEADOS" ("COD_CANAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PA_IDX" ;

  CREATE INDEX "PA"."EMPLEADOS_FK8" ON "PA"."EMPLEADOS" ("COD_EMPRESA", "COD_PUESTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PA_IDX" ;

  CREATE INDEX "PA"."IDX_EMPLEADOS_EMAIL_PREFIX" ON "PA"."EMPLEADOS" (SUBSTR("EMAIL1",1,INSTR("EMAIL1",'@')-1)) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PA_DAT" ;

  CREATE INDEX "PA"."IDX_EMPLEADOS_EMP_AG" ON "PA"."EMPLEADOS" ("COD_EMPRESA", "COD_AGENCIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PA_DAT" ;

  CREATE INDEX "PA"."IDX_EMPLEADOS_PERFIS_EMP_ACT" ON "PA"."EMPLEADOS" ("COD_PER_FISICA", "COD_EMPRESA", "ESTA_ACTIVO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PA_DAT" ;

  CREATE INDEX "PA"."IDX_EMPLE_CODEMPCODAGENLAB" ON "PA"."EMPLEADOS" ("COD_EMPRESA", "COD_AGENCIA_LABORA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PA_IND" ;

  CREATE INDEX "PA"."UN_EMPLEADOS_IDEMPLEADO" ON "PA"."EMPLEADOS" ("ID_EMPLEADO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IND_EFD" ;

  CREATE INDEX "PA"."UN_PERSONA_FISICA" ON "PA"."EMPLEADOS" ("COD_PER_FISICA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IND_EFD" ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "PA"."EMPLEADOS_EMPI2000" 
       after insert or delete
       on PA.EMPLEADOS
       referencing new as new old as old
       for each row
DECLARE
  -- Obtiene un indicador de si el empleado es cliente o no
  cursor cliente(pCodEmpleado in varchar2) is
    select 'x'
      from clientes
      where cod_cliente = pCodEmpleado;
  vDummy varchar2(1);
BEGIN
  if inserting then
    open cliente(:new.cod_per_fisica);
      fetch cliente into vDummy;
      if cliente%found then  -- Si es Cliente y Empleado
        update tcli_personas
          set cli_ind_relacion = 'A'
          where cli_cod_persona = :new.cod_per_fisica;
      else  -- Si es solo Empleado
        update tcli_personas
          set cli_ind_relacion = 'E'
          where cli_cod_persona = :new.cod_per_fisica;
      end if;
    close cliente;
  elsif deleting then
    open cliente(:new.cod_per_fisica);
      fetch cliente into vDummy;
      if cliente%found then -- Si va a ser solo Cliente
        update tcli_personas
          set cli_ind_relacion = 'C'
          where cli_cod_persona = :new.cod_per_fisica;
      else  -- Si no va a ser Cliente ni Empleado, entonces es Prospecto
        update tcli_personas
          set cli_ind_relacion = 'P'
          where cli_cod_persona = :new.cod_per_fisica;
      end if;
    close cliente;
  end if;  -- if inserting
END; 





/
ALTER TRIGGER "PA"."EMPLEADOS_EMPI2000" ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "PA"."BUI_EMPLEADOS" 
BEFORE INSERT OR UPDATE
ON pa.empleados REFERENCING NEW AS new OLD AS Old
FOR EACH ROW
BEGIN
  -- Se valida si hay cambios en el estado o en es_oficial.
  IF UPDATING THEN
     IF ((nvl(:old.es_oficial,'x') != nvl(:new.es_oficial,'x')) OR  
          (nvl(:old.esta_Activo,'x') != nvl(:new.esta_activo,'x'))
        ) THEN
        INSERT INTO pa_bit_cambios_empleado
           (COD_EMPRESA,       ID_EMPLEADO,      ES_OFICIAL_ANT,  ES_OFICIAL_ACT,  ESTA_ACTIVO_ANT,  ESTA_ACTIVO_ACT, FECHA_CAMBIO)
         VALUES
            (:new.cod_empresa, :new.id_empleado, :old.es_oficial, :new.es_oficial, :old.esta_Activo, :new.esta_Activo,sysdate);
     END IF;
  END IF;
END;
/
ALTER TRIGGER "PA"."BUI_EMPLEADOS" ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "PA"."TGR_EMPLEADOS_BITACORA" 
BEFORE INSERT OR UPDATE ON "PA"."EMPLEADOS" 
REFERENCING OLD AS OLD NEW AS NEW 
FOR EACH ROW 
BEGIN
    IF UPDATING THEN
        :NEW.MODIFICADO_POR   := USER;
        :NEW.FEC_MODIFICACION := SYSDATE;
    ELSIF INSERTING THEN
        :NEW.INCLUIDO_POR  := USER;
        :NEW.FEC_INCLUSION := SYSDATE;
    END IF;
END;
/
ALTER TRIGGER "PA"."TGR_EMPLEADOS_BITACORA" ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "PA"."TGR_VALIDA_CART_ACTIVA_EMPL" 
BEFORE INSERT OR UPDATE OF COD_AGENCIA,
                           COD_AGENCIA_LABORA ON "PA"."EMPLEADOS" 
REFERENCING OLD AS OLD NEW AS NEW 
FOR EACH ROW 
BEGIN
  IF  (:NEW.COD_AGENCIA != :OLD.COD_AGENCIA OR :NEW.COD_AGENCIA_LABORA != :OLD.COD_AGENCIA_LABORA) 
  AND (NVL(:OLD.ESTA_ACTIVO, 'X') = 'S' AND NVL(:OLD.ES_OFICIAL, 'X') = 'S') THEN
    CASE F_PA_VALIDA_CARTERA_ACTIVA(:OLD.ID_EMPLEADO)
        WHEN 1 THEN
            RAISE_APPLICATION_ERROR(-20001, 'No se puede cambiar de agencia a empleado con cartera activa en créditos.');
        WHEN 2 THEN
            RAISE_APPLICATION_ERROR(-20001, 'No se puede cambiar de agencia a empleado con cartera activa en tarjetas.');
        WHEN 3 THEN
            RAISE_APPLICATION_ERROR(-20001, 'No se puede cambiar de agencia a empleado con cartera activa en créditos y tarjetas.');
        ELSE
            NULL;
    END CASE;
  END IF;
END;
/
ALTER TRIGGER "PA"."TGR_VALIDA_CART_ACTIVA_EMPL" ENABLE;


  GRANT REFERENCES ON "PA"."EMPLEADOS" TO PUBLIC;
  GRANT SELECT ON "PA"."EMPLEADOS" TO "REF";
  GRANT SELECT ON "PA"."EMPLEADOS" TO "B2000TX";
  GRANT SELECT ON "PA"."EMPLEADOS" TO "IVR";
  GRANT SELECT ON "PA"."EMPLEADOS" TO "CONGEN";
  GRANT SELECT ON "PA"."EMPLEADOS" TO "DI";
  GRANT ALTER ON "PA"."EMPLEADOS" TO "MK";
  GRANT DELETE ON "PA"."EMPLEADOS" TO "MK";
  GRANT INDEX ON "PA"."EMPLEADOS" TO "MK";
  GRANT INSERT ON "PA"."EMPLEADOS" TO "MK";
  GRANT SELECT ON "PA"."EMPLEADOS" TO "MK";
  GRANT UPDATE ON "PA"."EMPLEADOS" TO "MK";
  GRANT REFERENCES ON "PA"."EMPLEADOS" TO "MK";
  GRANT ALTER ON "PA"."EMPLEADOS" TO "CC";
  GRANT DELETE ON "PA"."EMPLEADOS" TO "CC";
  GRANT INDEX ON "PA"."EMPLEADOS" TO "CC";
  GRANT INSERT ON "PA"."EMPLEADOS" TO "CC";
  GRANT SELECT ON "PA"."EMPLEADOS" TO "CC";
  GRANT UPDATE ON "PA"."EMPLEADOS" TO "CC";
  GRANT REFERENCES ON "PA"."EMPLEADOS" TO "CC";
  GRANT ON COMMIT REFRESH ON "PA"."EMPLEADOS" TO "CC";
  GRANT QUERY REWRITE ON "PA"."EMPLEADOS" TO "CC";
  GRANT DEBUG ON "PA"."EMPLEADOS" TO "CC";
  GRANT FLASHBACK ON "PA"."EMPLEADOS" TO "CC";
  GRANT SELECT ON "PA"."EMPLEADOS" TO "CD";
  GRANT SELECT ON "PA"."EMPLEADOS" TO "SB";
  GRANT ALTER ON "PA"."EMPLEADOS" TO "RH";
  GRANT DELETE ON "PA"."EMPLEADOS" TO "RH";
  GRANT INDEX ON "PA"."EMPLEADOS" TO "RH";
  GRANT INSERT ON "PA"."EMPLEADOS" TO "RH";
  GRANT SELECT ON "PA"."EMPLEADOS" TO "RH";
  GRANT UPDATE ON "PA"."EMPLEADOS" TO "RH";
  GRANT REFERENCES ON "PA"."EMPLEADOS" TO "RH";
  GRANT ON COMMIT REFRESH ON "PA"."EMPLEADOS" TO "RH";
  GRANT QUERY REWRITE ON "PA"."EMPLEADOS" TO "RH";
  GRANT DEBUG ON "PA"."EMPLEADOS" TO "RH";
  GRANT FLASHBACK ON "PA"."EMPLEADOS" TO "RH";
  GRANT DELETE ON "PA"."EMPLEADOS" TO "BPA";
  GRANT INSERT ON "PA"."EMPLEADOS" TO "BPA";
  GRANT SELECT ON "PA"."EMPLEADOS" TO "BPA";
  GRANT UPDATE ON "PA"."EMPLEADOS" TO "BPA";
  GRANT ALTER ON "PA"."EMPLEADOS" TO PUBLIC;
  GRANT DELETE ON "PA"."EMPLEADOS" TO PUBLIC;
  GRANT INSERT ON "PA"."EMPLEADOS" TO PUBLIC;
  GRANT SELECT ON "PA"."EMPLEADOS" TO PUBLIC;
  GRANT UPDATE ON "PA"."EMPLEADOS" TO PUBLIC;
  GRANT ALTER ON "PA"."EMPLEADOS" TO "BPA";
  GRANT ALTER ON "PA"."EMPLEADOS" TO "CONGEN";
  GRANT DELETE ON "PA"."EMPLEADOS" TO "CONGEN";
  GRANT INSERT ON "PA"."EMPLEADOS" TO "CONGEN";
  GRANT UPDATE ON "PA"."EMPLEADOS" TO "CONGEN";
  GRANT DELETE ON "PA"."EMPLEADOS" TO "BGE";
  GRANT INSERT ON "PA"."EMPLEADOS" TO "BGE";
  GRANT SELECT ON "PA"."EMPLEADOS" TO "BGE";
  GRANT UPDATE ON "PA"."EMPLEADOS" TO "BGE";
  GRANT SELECT ON "PA"."EMPLEADOS" TO "SII";
