
  CREATE TABLE "PA"."PUESTOS" 
   (	"COD_PUESTO" VARCHAR2(6 BYTE), 
	"DESCRIPCION" VARCHAR2(80 BYTE) CONSTRAINT "NN_PUESTOS_DESCRIPCION" NOT NULL ENABLE, 
	"SALARIO_BASE" NUMBER(14,2), 
	"COD_EMPRESA" VARCHAR2(5 BYTE), 
	"COD_MONEDA" VARCHAR2(4 BYTE), 
	 CONSTRAINT "FK_PUESTOS_MONEDAS" FOREIGN KEY ("COD_MONEDA")
	  REFERENCES "PA"."MONEDA" ("COD_MONEDA") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 80 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA_EFD" ;
  CREATE UNIQUE INDEX "PA"."PK_PUESTOS" ON "PA"."PUESTOS" ("COD_EMPRESA", "COD_PUESTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IND_EFD" ;
ALTER TABLE "PA"."PUESTOS" ADD CONSTRAINT "PK_PUESTOS" PRIMARY KEY ("COD_EMPRESA", "COD_PUESTO")
  USING INDEX "PA"."PK_PUESTOS"  ENABLE;

   COMMENT ON COLUMN "PA"."PUESTOS"."COD_PUESTO" IS 'Codigo del puesto';
   COMMENT ON COLUMN "PA"."PUESTOS"."DESCRIPCION" IS 'Descripcion';
   COMMENT ON COLUMN "PA"."PUESTOS"."SALARIO_BASE" IS 'Salario base';
   COMMENT ON COLUMN "PA"."PUESTOS"."COD_EMPRESA" IS 'Codigo de la empresa a la que pertenece la informacion. Esta relacionada a la tabla PA.EMPRESA';
   COMMENT ON COLUMN "PA"."PUESTOS"."COD_MONEDA" IS 'Codigo de moneda';
   COMMENT ON TABLE "PA"."PUESTOS"  IS ' Puestos';

  CREATE INDEX "PA"."PUESTOS_FK4" ON "PA"."PUESTOS" ("COD_MONEDA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PA_IND" ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "PA"."PUESTOS_PUESTOSI2000" 
   After Insert Or Delete Or Update Of cod_puesto, descripcion
   On pa.puestos
   Referencing New As New Old As Old
   For Each Row
Begin
   If Inserting Then
      Begin
         Insert Into tpar_puestos
                     ( par_cod_puesto, par_nom_puesto )
              Values ( :New.cod_puesto, Substr( :New.descripcion, 1, 60 ));
      Exception
         When Others Then
            Null;
      End;
   Elsif Updating Then
      Update tpar_puestos
         Set par_nom_puesto = Substr( :New.descripcion, 1, 60 )
       Where par_cod_puesto = :Old.cod_puesto;
   Elsif Deleting Then
      Delete      tpar_puestos
            Where par_cod_puesto = :Old.cod_puesto;
   End If;
End; 
/
ALTER TRIGGER "PA"."PUESTOS_PUESTOSI2000" ENABLE;


  GRANT REFERENCES ON "PA"."PUESTOS" TO PUBLIC;
  GRANT SELECT ON "PA"."PUESTOS" TO "FVALDES";
  GRANT SELECT ON "PA"."PUESTOS" TO "CONGEN";
  GRANT DELETE ON "PA"."PUESTOS" TO "BPA";
  GRANT INSERT ON "PA"."PUESTOS" TO "BPA";
  GRANT SELECT ON "PA"."PUESTOS" TO "BPA";
  GRANT UPDATE ON "PA"."PUESTOS" TO "BPA";
  GRANT ALTER ON "PA"."PUESTOS" TO "BPA";
  GRANT ALTER ON "PA"."PUESTOS" TO "CONGEN";
  GRANT DELETE ON "PA"."PUESTOS" TO "CONGEN";
  GRANT INSERT ON "PA"."PUESTOS" TO "CONGEN";
  GRANT UPDATE ON "PA"."PUESTOS" TO "CONGEN";
  GRANT ALTER ON "PA"."PUESTOS" TO PUBLIC;
  GRANT DELETE ON "PA"."PUESTOS" TO PUBLIC;
  GRANT INSERT ON "PA"."PUESTOS" TO PUBLIC;
  GRANT SELECT ON "PA"."PUESTOS" TO PUBLIC;
  GRANT UPDATE ON "PA"."PUESTOS" TO PUBLIC;
  GRANT SELECT ON "PA"."PUESTOS" TO "SII";
