
  CREATE TABLE "PA"."SUB_AGENCIAS" 
   (	"COD_EMPRESA" VARCHAR2(5 BYTE), 
	"COD_AGENCIA" VARCHAR2(5 BYTE), 
	"COD_SUB_AGENCIA" VARCHAR2(5 BYTE), 
	"DESCRIPCION" VARCHAR2(80 BYTE) CONSTRAINT "NN_SUB_AGENCIAS_DESCRIPCION" NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 80 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA_EFD" ;
  CREATE UNIQUE INDEX "PA"."PK_SUB_AGENCIAS" ON "PA"."SUB_AGENCIAS" ("COD_EMPRESA", "COD_AGENCIA", "COD_SUB_AGENCIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IND_EFD" ;
ALTER TABLE "PA"."SUB_AGENCIAS" ADD CONSTRAINT "PK_SUB_AGENCIAS" PRIMARY KEY ("COD_EMPRESA", "COD_AGENCIA", "COD_SUB_AGENCIA")
  USING INDEX "PA"."PK_SUB_AGENCIAS"  ENABLE;

   COMMENT ON COLUMN "PA"."SUB_AGENCIAS"."COD_EMPRESA" IS 'Codigo de la empresa a la que pertenece la informacion. Esta relacionada a la tabla PA.EMPRESA';
   COMMENT ON COLUMN "PA"."SUB_AGENCIAS"."COD_AGENCIA" IS 'Codigo agencia';
   COMMENT ON COLUMN "PA"."SUB_AGENCIAS"."COD_SUB_AGENCIA" IS 'Codigo de la Sub Agencia';
   COMMENT ON COLUMN "PA"."SUB_AGENCIAS"."DESCRIPCION" IS 'Descripcion';
   COMMENT ON TABLE "PA"."SUB_AGENCIAS"  IS ' Tabla que contienes las suba agencias de la empresa.';


  GRANT REFERENCES ON "PA"."SUB_AGENCIAS" TO PUBLIC;
  GRANT SELECT ON "PA"."SUB_AGENCIAS" TO "CONGEN";
  GRANT DELETE ON "PA"."SUB_AGENCIAS" TO "BPA";
  GRANT INSERT ON "PA"."SUB_AGENCIAS" TO "BPA";
  GRANT SELECT ON "PA"."SUB_AGENCIAS" TO "BPA";
  GRANT UPDATE ON "PA"."SUB_AGENCIAS" TO "BPA";
  GRANT ALTER ON "PA"."SUB_AGENCIAS" TO PUBLIC;
  GRANT DELETE ON "PA"."SUB_AGENCIAS" TO PUBLIC;
  GRANT INSERT ON "PA"."SUB_AGENCIAS" TO PUBLIC;
  GRANT SELECT ON "PA"."SUB_AGENCIAS" TO PUBLIC;
  GRANT UPDATE ON "PA"."SUB_AGENCIAS" TO PUBLIC;
  GRANT ALTER ON "PA"."SUB_AGENCIAS" TO "BPA";
  GRANT ALTER ON "PA"."SUB_AGENCIAS" TO "CONGEN";
  GRANT DELETE ON "PA"."SUB_AGENCIAS" TO "CONGEN";
  GRANT INSERT ON "PA"."SUB_AGENCIAS" TO "CONGEN";
  GRANT UPDATE ON "PA"."SUB_AGENCIAS" TO "CONGEN";
  GRANT SELECT ON "PA"."SUB_AGENCIAS" TO "SII";
