CREATE TABLE PA.PA_DE08_SIB
(
    ID_DEUDOR      VARCHAR2(30 BYTE),
    FECHA_CORTE    DATE,
    NOMBRE         VARCHAR2(150 BYTE),
    TIPO_DEUDOR    VARCHAR2(30 BYTE),
    CLASIFICACION  VARCHAR2(5 BYTE),
    FECHA_PROCESO  DATE DEFAULT TRUNC(SYSDATE)
)
TABLESPACE PA_DAT;

-- Sinonimo publico
CREATE OR REPLACE PUBLIC SYNONYM PA_DE08_SIB FOR PA.PA_DE08_SIB;

-- Grants
GRANT SELECT, INSERT, UPDATE, DELETE ON PA.PA_DE08_SIB TO BCC;
GRANT SELECT, INSERT, UPDATE, DELETE ON PA.PA_DE08_SIB TO BGC;
GRANT SELECT, INSERT, UPDATE, DELETE ON PA.PA_DE08_SIB TO BIA;
GRANT SELECT, INSERT, UPDATE, DELETE ON PA.PA_DE08_SIB TO BPA;
GRANT SELECT, INSERT, UPDATE, DELETE ON PA.PA_DE08_SIB TO BPR;
