
  CREATE TABLE "SROBLES"."PLSQL_PROFILER_UNITS" 
   (	"RUNID" NUMBER, 
	"UNIT_NUMBER" NUMBER, 
	"UNIT_TYPE" VARCHAR2(128 BYTE), 
	"UNIT_OWNER" VARCHAR2(128 BYTE), 
	"UNIT_NAME" VARCHAR2(128 BYTE), 
	"UNIT_TIMESTAMP" DATE, 
	"TOTAL_TIME" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	 PRIMARY KEY ("RUNID", "UNIT_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 FOREIGN KEY ("RUNID")
	  REFERENCES "SROBLES"."PLSQL_PROFILER_RUNS" ("RUNID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON TABLE "SROBLES"."PLSQL_PROFILER_UNITS"  IS 'Information about each library unit in a run';


  GRANT DELETE ON "SROBLES"."PLSQL_PROFILER_UNITS" TO PUBLIC;
  GRANT INSERT ON "SROBLES"."PLSQL_PROFILER_UNITS" TO PUBLIC;
  GRANT SELECT ON "SROBLES"."PLSQL_PROFILER_UNITS" TO PUBLIC;
  GRANT UPDATE ON "SROBLES"."PLSQL_PROFILER_UNITS" TO PUBLIC;
