
  CREATE TABLE "SROBLES"."PLSQL_PROFILER_RUNS" 
   (	"RUNID" NUMBER, 
	"RELATED_RUN" NUMBER, 
	"RUN_OWNER" VARCHAR2(128 BYTE), 
	"RUN_DATE" DATE, 
	"RUN_COMMENT" VARCHAR2(2047 BYTE), 
	"RUN_TOTAL_TIME" NUMBER, 
	"RUN_SYSTEM_INFO" VARCHAR2(2047 BYTE), 
	"RUN_COMMENT1" VARCHAR2(2047 BYTE), 
	"SPARE1" VARCHAR2(256 BYTE), 
	 PRIMARY KEY ("RUNID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON TABLE "SROBLES"."PLSQL_PROFILER_RUNS"  IS 'Run-specific information for the PL/SQL profiler';


  GRANT DELETE ON "SROBLES"."PLSQL_PROFILER_RUNS" TO PUBLIC;
  GRANT INSERT ON "SROBLES"."PLSQL_PROFILER_RUNS" TO PUBLIC;
  GRANT SELECT ON "SROBLES"."PLSQL_PROFILER_RUNS" TO PUBLIC;
  GRANT UPDATE ON "SROBLES"."PLSQL_PROFILER_RUNS" TO PUBLIC;
