
  CREATE TABLE "SROBLES"."PLSQL_PROFILER_DATA" 
   (	"RUNID" NUMBER, 
	"UNIT_NUMBER" NUMBER, 
	"LINE#" NUMBER NOT NULL ENABLE, 
	"TEXT" VARCHAR2(4000 BYTE), 
	"TOTAL_OCCUR" NUMBER, 
	"TOTAL_TIME" NUMBER, 
	"MIN_TIME" NUMBER, 
	"MAX_TIME" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" NUMBER, 
	"SPARE4" NUMBER, 
	 PRIMARY KEY ("RUNID", "UNIT_NUMBER", "LINE#")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 FOREIGN KEY ("RUNID", "UNIT_NUMBER")
	  REFERENCES "SROBLES"."PLSQL_PROFILER_UNITS" ("RUNID", "UNIT_NUMBER") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON TABLE "SROBLES"."PLSQL_PROFILER_DATA"  IS 'Accumulated data from all profiler runs';


  GRANT DELETE ON "SROBLES"."PLSQL_PROFILER_DATA" TO PUBLIC;
  GRANT INSERT ON "SROBLES"."PLSQL_PROFILER_DATA" TO PUBLIC;
  GRANT SELECT ON "SROBLES"."PLSQL_PROFILER_DATA" TO PUBLIC;
  GRANT UPDATE ON "SROBLES"."PLSQL_PROFILER_DATA" TO PUBLIC;
