
  CREATE TABLE "SROBLES"."PRESTAMOS_SR" 
   (	"NUM_PRESTAMO" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"TIPO_PRESTAMO" NUMBER(1,0) NOT NULL ENABLE, 
	"CLIENTE" NUMBER NOT NULL ENABLE, 
	"TASA" NUMBER(5,2) NOT NULL ENABLE, 
	"MONTO" NUMBER(15,2) NOT NULL ENABLE, 
	"ESTADO" CHAR(1 BYTE) NOT NULL ENABLE, 
	"FECHA_CREACION" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"FECHA_MODIFICACION" DATE, 
	 CHECK (tipo_prestamo IN (1, 2, 3)) ENABLE, 
	 CHECK (estado IN ('A', 'I')) ENABLE, 
	 PRIMARY KEY ("NUM_PRESTAMO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_CLIENTE" FOREIGN KEY ("CLIENTE")
	  REFERENCES "SROBLES"."CLIENTE" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

