
  CREATE TABLE "PR"."PR_BITACORA_REPRESTAMO" 
   (	"CODIGO_EMPRESA" NUMBER(4,0) NOT NULL ENABLE, 
	"ID_REPRESTAMO" NUMBER(14,0) NOT NULL ENABLE, 
	"ID_BITACORA" NUMBER(10,0) NOT NULL ENABLE, 
	"FECHA_BITACORA" DATE NOT NULL ENABLE, 
	"CODIGO_ESTADO" VARCHAR2(5 BYTE) NOT NULL ENABLE, 
	"STEP" VARCHAR2(2 BYTE), 
	"OBSERVACIONES" VARCHAR2(500 BYTE), 
	"CANAL" VARCHAR2(2 BYTE), 
	"ADICIONADO_POR" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"FECHA_ADICION" DATE NOT NULL ENABLE, 
	"MODIFICADO_POR" VARCHAR2(30 BYTE), 
	"FECHA_MODIFICACION" DATE, 
	 CONSTRAINT "FK_BITACORA_REPRESTAMO" FOREIGN KEY ("CODIGO_EMPRESA", "ID_REPRESTAMO")
	  REFERENCES "PR"."PR_REPRESTAMOS" ("CODIGO_EMPRESA", "ID_REPRESTAMO") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 MAXSIZE UNLIMITED
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PR_DAT" ;
  CREATE UNIQUE INDEX "PR"."PK_BITACORA_REPRESTAMO" ON "PR"."PR_BITACORA_REPRESTAMO" ("CODIGO_EMPRESA", "ID_REPRESTAMO", "ID_BITACORA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 MAXSIZE UNLIMITED
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PR_DAT" ;
ALTER TABLE "PR"."PR_BITACORA_REPRESTAMO" ADD CONSTRAINT "PK_BITACORA_REPRESTAMO" PRIMARY KEY ("CODIGO_EMPRESA", "ID_REPRESTAMO", "ID_BITACORA")
  USING INDEX "PR"."PK_BITACORA_REPRESTAMO"  ENABLE;

  CREATE INDEX "PR"."IDX_BITREPRE_CODESTADO_ID" ON "PR"."PR_BITACORA_REPRESTAMO" ("CODIGO_ESTADO", "ID_REPRESTAMO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PR_DAT" ;

  CREATE INDEX "PR"."IDX_BITREPRE_ID_IDBIT_FEC" ON "PR"."PR_BITACORA_REPRESTAMO" ("ID_REPRESTAMO", "ID_BITACORA" DESC, "FECHA_ADICION" DESC) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PR_DAT" ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "PR"."TRG_BUI_PR_BITACORA_REPRESTAMO" 
BEFORE INSERT OR UPDATE
ON pr.pr_bitacora_represtamo REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
  IF INSERTING THEN
     :new.fecha_adicion := sysdate;  
     if :new.adicionado_por is null THEN
        :new.adicionado_por := user;
     end if;
  ELSE 
     :new.fecha_modificacion := sysdate;
     if :new.modificado_por is null THEN
        :new.modificado_por := user;
     end if;
  END IF;
END;
/
ALTER TRIGGER "PR"."TRG_BUI_PR_BITACORA_REPRESTAMO" ENABLE;


  GRANT SELECT ON "PR"."PR_BITACORA_REPRESTAMO" TO "BPR";
