
  CREATE TABLE "PR"."PR_BITACORA_CIERRE" 
   (	"COD_LINEA" NUMBER NOT NULL ENABLE, 
	"NOM_PROCESO" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"NOM_SUBPROCESO" VARCHAR2(100 BYTE), 
	"FEC_SISTEMA" DATE, 
	"FEC_CIERRE" DATE, 
	"FEC_ADICION" DATE, 
	"USER_APLICA" VARCHAR2(50 BYTE), 
	"COD_EMPRESA" NUMBER(5,0), 
	"COD_AGENCIA" NUMBER(5,0), 
	"NO_CREDITO" NUMBER(18,0), 
	"ERRM_USUARIO" VARCHAR2(3000 BYTE), 
	"ERRM_SISTEMA" VARCHAR2(3000 BYTE), 
	"DESC_BACKTRACE" VARCHAR2(3000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PR_DAT" ;
  CREATE UNIQUE INDEX "PR"."PK_PR_BITACORA_CIERRE" ON "PR"."PR_BITACORA_CIERRE" ("COD_LINEA", "COD_EMPRESA", "NOM_PROCESO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PR_DAT" ;
ALTER TABLE "PR"."PR_BITACORA_CIERRE" ADD CONSTRAINT "PK_PR_BITACORA_CIERRE" PRIMARY KEY ("COD_LINEA", "COD_EMPRESA", "NOM_PROCESO")
  USING INDEX "PR"."PK_PR_BITACORA_CIERRE"  ENABLE;

   COMMENT ON COLUMN "PR"."PR_BITACORA_CIERRE"."COD_LINEA" IS 'Consecutivo de línea.';
   COMMENT ON COLUMN "PR"."PR_BITACORA_CIERRE"."NOM_PROCESO" IS 'Nombre del proceso del paquete que ejecuta.';
   COMMENT ON COLUMN "PR"."PR_BITACORA_CIERRE"."NOM_SUBPROCESO" IS 'Nombre del subproceso, este es solo si él provoco el error.';
   COMMENT ON COLUMN "PR"."PR_BITACORA_CIERRE"."FEC_SISTEMA" IS 'Fecha del sistema.';
   COMMENT ON COLUMN "PR"."PR_BITACORA_CIERRE"."FEC_CIERRE" IS 'Fecha del cierre.';
   COMMENT ON COLUMN "PR"."PR_BITACORA_CIERRE"."FEC_ADICION" IS 'Fecha de adición del proceso';
   COMMENT ON COLUMN "PR"."PR_BITACORA_CIERRE"."USER_APLICA" IS 'Usuario que realiza ejecución.';
   COMMENT ON COLUMN "PR"."PR_BITACORA_CIERRE"."COD_EMPRESA" IS 'Código de empresa.';
   COMMENT ON COLUMN "PR"."PR_BITACORA_CIERRE"."COD_AGENCIA" IS 'Código de agencia.';
   COMMENT ON COLUMN "PR"."PR_BITACORA_CIERRE"."NO_CREDITO" IS 'Número de operación de crédito.';
   COMMENT ON COLUMN "PR"."PR_BITACORA_CIERRE"."ERRM_USUARIO" IS 'Error contralado por el usuario.';
   COMMENT ON COLUMN "PR"."PR_BITACORA_CIERRE"."ERRM_SISTEMA" IS 'Error no controlado.';
   COMMENT ON COLUMN "PR"."PR_BITACORA_CIERRE"."DESC_BACKTRACE" IS 'Descripción del proceso y línea de caída.';


  GRANT ALTER ON "PR"."PR_BITACORA_CIERRE" TO PUBLIC;
  GRANT DELETE ON "PR"."PR_BITACORA_CIERRE" TO PUBLIC;
  GRANT INSERT ON "PR"."PR_BITACORA_CIERRE" TO PUBLIC;
  GRANT SELECT ON "PR"."PR_BITACORA_CIERRE" TO PUBLIC;
  GRANT UPDATE ON "PR"."PR_BITACORA_CIERRE" TO PUBLIC;
  GRANT SELECT ON "PR"."PR_BITACORA_CIERRE" TO "SII";
