
  CREATE TABLE "PR"."PR_CAMPANA_ESPECIALES" 
   (	"CODIGO_EMPRESA" NUMBER(4,0) DEFAULT 1, 
	"CODIGO_CLIENTE" NUMBER(7,0) NOT NULL ENABLE, 
	"NOMBRES" VARCHAR2(65 BYTE), 
	"CELULAR" VARCHAR2(11 BYTE) NOT NULL ENABLE, 
	"NO_CREDITO" NUMBER(7,0) NOT NULL ENABLE, 
	"MTO_PREAPROBADO" NUMBER(18,2) NOT NULL ENABLE, 
	"AGENCIA" VARCHAR2(65 BYTE), 
	"OFICIAL" VARCHAR2(65 BYTE), 
	"ZONA" VARCHAR2(65 BYTE), 
	"ESTADO" VARCHAR2(5 BYTE) DEFAULT 'P', 
	"OBSERVACIONES" VARCHAR2(500 BYTE), 
	"ADICIONADO_POR" VARCHAR2(30 BYTE) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'),USER), 
	"FECHA_ADICION" DATE DEFAULT SYSDATE, 
	"MODIFICADO_POR" VARCHAR2(30 BYTE), 
	"FECHA_MODIFICACION" DATE, 
	"ID_CAMPANA_ESPECIALES" NUMBER, 
	"TIPO_CREDITO" NUMBER(10,0) NOT NULL ENABLE, 
	"COMENTARIO" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PR_DAT" ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "PR"."PR_CAMPANA_ESPECIALE" 
BEFORE INSERT ON PR.PR_CAMPANA_ESPECIALES 
FOR EACH ROW
BEGIN
    SELECT PR.PR_PKG_REPRESTAMOS.F_Genera_Secuencia_Campana_Especiales  INTO :NEW.ID_CAMPANA_ESPECIALES FROM DUAL;
END;
/
ALTER TRIGGER "PR"."PR_CAMPANA_ESPECIALE" ENABLE;

