
  CREATE TABLE "PR"."PR_OPCIONES_REPRESTAMO" 
   (	"CODIGO_EMPRESA" NUMBER(4,0) NOT NULL ENABLE, 
	"ID_REPRESTAMO" NUMBER(14,0) NOT NULL ENABLE, 
	"PLAZO" NUMBER(5,0) NOT NULL ENABLE, 
	"MTO_PRESTAMO" NUMBER(18,2) NOT NULL ENABLE, 
	"MTO_DESCONTAR" NUMBER(18,2) NOT NULL ENABLE, 
	"MTO_DEPOSITAR" NUMBER(18,2) NOT NULL ENABLE, 
	"MTO_CUOTA" NUMBER(18,2) NOT NULL ENABLE, 
	"MTO_CARGOS" NUMBER(18,2) NOT NULL ENABLE, 
	"MTO_SEGURO_VIDA" NUMBER(18,2) NOT NULL ENABLE, 
	"MTO_SEGURO_DESEMPLEO" NUMBER(18,2) NOT NULL ENABLE, 
	"TASA" NUMBER(5,2) NOT NULL ENABLE, 
	"ORDEN" NUMBER(5,0), 
	"ESTADO" VARCHAR2(5 BYTE) NOT NULL ENABLE, 
	"ADICIONADO_POR" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"FECHA_ADICION" DATE NOT NULL ENABLE, 
	"MODIFICADO_POR" VARCHAR2(30 BYTE), 
	"FECHA_MODIFICACION" DATE, 
	"MTO_CUOTA_TOTAL" NUMBER(18,2), 
	"MTO_SEGURO_MIPYME" NUMBER(18,2), 
	 CONSTRAINT "FK_OPCIONES_REPRESTAMO" FOREIGN KEY ("CODIGO_EMPRESA", "ID_REPRESTAMO")
	  REFERENCES "PR"."PR_REPRESTAMOS" ("CODIGO_EMPRESA", "ID_REPRESTAMO") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 MAXSIZE UNLIMITED
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PR_DAT" ;
  CREATE UNIQUE INDEX "PR"."PK_PR_OPCIONES_REPRESTAMOS" ON "PR"."PR_OPCIONES_REPRESTAMO" ("CODIGO_EMPRESA", "ID_REPRESTAMO", "PLAZO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 MAXSIZE UNLIMITED
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PR_DAT" ;
ALTER TABLE "PR"."PR_OPCIONES_REPRESTAMO" ADD CONSTRAINT "PK_PR_OPCIONES_REPRESTAMOS" PRIMARY KEY ("CODIGO_EMPRESA", "ID_REPRESTAMO", "PLAZO")
  USING INDEX "PR"."PK_PR_OPCIONES_REPRESTAMOS"  ENABLE;

   COMMENT ON COLUMN "PR"."PR_OPCIONES_REPRESTAMO"."ID_REPRESTAMO" IS 'Identificacion del Represtamo';
   COMMENT ON COLUMN "PR"."PR_OPCIONES_REPRESTAMO"."PLAZO" IS 'Numero de plazo de la opción.';
   COMMENT ON COLUMN "PR"."PR_OPCIONES_REPRESTAMO"."MTO_PRESTAMO" IS 'Monto del Represtamo.';
   COMMENT ON COLUMN "PR"."PR_OPCIONES_REPRESTAMO"."MTO_DESCONTAR" IS 'Monto pendiente a descontar del préstamo anterior.';
   COMMENT ON COLUMN "PR"."PR_OPCIONES_REPRESTAMO"."MTO_DEPOSITAR" IS 'Monto a desembolsar del représtamo.';
   COMMENT ON COLUMN "PR"."PR_OPCIONES_REPRESTAMO"."MTO_CUOTA" IS 'Monto la cuota del représtamo.';
   COMMENT ON COLUMN "PR"."PR_OPCIONES_REPRESTAMO"."MTO_CARGOS" IS 'Monto de cargos y gastos de cierre.';
   COMMENT ON COLUMN "PR"."PR_OPCIONES_REPRESTAMO"."MTO_SEGURO_VIDA" IS 'Monto del seguro de vida.';
   COMMENT ON COLUMN "PR"."PR_OPCIONES_REPRESTAMO"."MTO_SEGURO_DESEMPLEO" IS 'Monto del seguro de desempleo.';
   COMMENT ON COLUMN "PR"."PR_OPCIONES_REPRESTAMO"."TASA" IS 'Tasa del représtamo de acuerdo al tipo de crédito.';
   COMMENT ON COLUMN "PR"."PR_OPCIONES_REPRESTAMO"."ORDEN" IS 'Orden en que se va a mostrar la opción.';
   COMMENT ON COLUMN "PR"."PR_OPCIONES_REPRESTAMO"."ESTADO" IS 'Estado de la opción.';

  CREATE OR REPLACE EDITIONABLE TRIGGER "PR"."TRG_BUI_PR_OPCIONES_REPRESTAMO" 
BEFORE INSERT OR UPDATE
ON PR.PR_OPCIONES_REPRESTAMO REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
  IF INSERTING THEN
     :new.fecha_adicion := sysdate;  
     if :new.adicionado_por is null THEN
        :new.adicionado_por := user;
     end if;
  ELSE 
     :new.fecha_modificacion := sysdate;
     if :new.modificado_por is null THEN
        :new.modificado_por := user;
     end if;
  END IF;
END;
/
ALTER TRIGGER "PR"."TRG_BUI_PR_OPCIONES_REPRESTAMO" ENABLE;


  GRANT ALTER ON "PR"."PR_OPCIONES_REPRESTAMO" TO "BPR";
  GRANT DELETE ON "PR"."PR_OPCIONES_REPRESTAMO" TO "BPR";
  GRANT INSERT ON "PR"."PR_OPCIONES_REPRESTAMO" TO "BPR";
  GRANT SELECT ON "PR"."PR_OPCIONES_REPRESTAMO" TO "BPR";
  GRANT UPDATE ON "PR"."PR_OPCIONES_REPRESTAMO" TO "BPR";
  GRANT ON COMMIT REFRESH ON "PR"."PR_OPCIONES_REPRESTAMO" TO "BPR";
  GRANT QUERY REWRITE ON "PR"."PR_OPCIONES_REPRESTAMO" TO "BPR";
  GRANT DEBUG ON "PR"."PR_OPCIONES_REPRESTAMO" TO "BPR";
  GRANT FLASHBACK ON "PR"."PR_OPCIONES_REPRESTAMO" TO "BPR";
