
  CREATE TABLE "PR"."PR_PLAZO_CREDITO_REPRESTAMO" 
   (	"CODIGO_EMPRESA" NUMBER(4,0) NOT NULL ENABLE, 
	"TIPO_CREDITO" NUMBER(3,0) NOT NULL ENABLE, 
	"PLAZO" NUMBER(5,0) NOT NULL ENABLE, 
	"MONTO_MIN" NUMBER(18,2) NOT NULL ENABLE, 
	"MONTO_MAX" NUMBER(18,2) NOT NULL ENABLE, 
	"ADICIONADO_POR" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"FECHA_ADICION" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"MODIFICADO_POR" VARCHAR2(30 BYTE), 
	"FECHA_MODIFICACION" DATE, 
	 CONSTRAINT "FK01_PR_PLAZO_REPRESTAMO" FOREIGN KEY ("CODIGO_EMPRESA", "TIPO_CREDITO")
	  REFERENCES "PR"."PR_TIPO_CREDITO_REPRESTAMO" ("CODIGO_EMPRESA", "TIPO_CREDITO") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 MAXSIZE UNLIMITED
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PR_DAT" ;
  CREATE UNIQUE INDEX "PR"."PK_PR_PLAZO_REPRESTAMO" ON "PR"."PR_PLAZO_CREDITO_REPRESTAMO" ("CODIGO_EMPRESA", "TIPO_CREDITO", "PLAZO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 MAXSIZE UNLIMITED
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PR_DAT" ;
ALTER TABLE "PR"."PR_PLAZO_CREDITO_REPRESTAMO" ADD CONSTRAINT "PK_PR_PLAZO_REPRESTAMO" PRIMARY KEY ("CODIGO_EMPRESA", "TIPO_CREDITO", "PLAZO")
  USING INDEX "PR"."PK_PR_PLAZO_REPRESTAMO"  ENABLE;

  CREATE INDEX "PR"."PK_PR_PLAZO_REPRE_MONTO" ON "PR"."PR_PLAZO_CREDITO_REPRESTAMO" ("CODIGO_EMPRESA", "TIPO_CREDITO", "MONTO_MIN", "MONTO_MAX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 MAXSIZE UNLIMITED
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PR_IDX" ;


  GRANT SELECT ON "PR"."PR_PLAZO_CREDITO_REPRESTAMO" TO "BPR";
