
  CREATE TABLE "PR"."PR_REPRESTAMO_CAMPANA" 
   (	"CODIGO_EMPRESA" NUMBER(4,0), 
	"CODIGO_CAMPANA" NUMBER, 
	"NOMBRE" VARCHAR2(65 BYTE), 
	"DESCRIPCION" VARCHAR2(100 BYTE), 
	"ESTADO" VARCHAR2(5 BYTE), 
	"ADICIONADO_POR" VARCHAR2(30 BYTE) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'),USER), 
	"FECHA_ADICION" DATE DEFAULT SYSDATE, 
	"MODIFICADO_POR" VARCHAR2(30 BYTE), 
	"FECHA_MODIFICACION" DATE, 
	 CONSTRAINT "PK_PR_REPRESTAMO_CAMPANA" PRIMARY KEY ("CODIGO_CAMPANA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PR_DAT"  ENABLE, 
	 CONSTRAINT "FK_CAMPANA_CAMPANA_ESTADO" FOREIGN KEY ("ESTADO")
	  REFERENCES "PR"."PR_REPRESTAMO_CAMPANA_ESTADO" ("CODIGO") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PR_DAT" ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "IA"."TRG_PR_REPRESTAMO_CAMPANA" 
BEFORE INSERT ON PR.PR_REPRESTAMO_CAMPANA
FOR EACH ROW
  BEGIN
    SELECT PR_REPRESTAMO_CAMPANA_SEQ.NEXTVAL
    INTO :NEW.CODIGO_CAMPANA
    FROM DUAL;
  END;
/
ALTER TRIGGER "IA"."TRG_PR_REPRESTAMO_CAMPANA" ENABLE;

