  CREATE TABLE "PR"."PR_REPRESTAMOS" 
   (	"CODIGO_EMPRESA" NUMBER(4,0) CONSTRAINT "NN_PR_REPRESTAMOS01" NOT NULL ENABLE, 
	"ID_REPRESTAMO" NUMBER(14,0) CONSTRAINT "NN_PR_REPRESTAMOS02" NOT NULL ENABLE, 
	"CODIGO_CLIENTE" NUMBER(7,0) CONSTRAINT "NN_PR_REPRESTAMOS03" NOT NULL ENABLE, 
	"FECHA_CORTE" DATE CONSTRAINT "NN_PR_REPRESTAMOS04" NOT NULL ENABLE, 
	"NO_CREDITO" NUMBER(7,0) CONSTRAINT "NN_PR_REPRESTAMOS05" NOT NULL ENABLE, 
	"ESTADO" VARCHAR2(3 BYTE) CONSTRAINT "NN_PR_REPRESTAMOS06" NOT NULL ENABLE, 
	"CODIGO_PRECALIFICACION" VARCHAR2(2 BYTE), 
	"DIAS_ATRASO" NUMBER(10,0) CONSTRAINT "NN_PR_REPRESTAMOS08" NOT NULL ENABLE, 
	"FECHA_PROCESO" DATE CONSTRAINT "NN_PR_REPRESTAMOS09" NOT NULL ENABLE, 
	"PIN" NUMBER(6,0) NOT NULL ENABLE, 
	"INTENTOS_PIN" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"INTENTOS_IDENTIFICACION" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"IND_SOLICITA_AYUDA" VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL ENABLE, 
	"MTO_CREDITO_ACTUAL" NUMBER(18,2) NOT NULL ENABLE, 
	"MTO_PREAPROBADO" NUMBER(18,2) NOT NULL ENABLE, 
	"OBSERVACIONES" VARCHAR2(4000 BYTE), 
	"ADICIONADO_POR" VARCHAR2(30 BYTE) CONSTRAINT "NN_PR_REPRESTAMOS10" NOT NULL ENABLE, 
	"FECHA_ADICION" DATE CONSTRAINT "NN_PR_REPRESTAMOS11" NOT NULL ENABLE, 
	"MODIFICADO_POR" VARCHAR2(30 BYTE), 
	"FECHA_MODIFICACION" DATE, 
	"ESTADO_ORIGINAL" VARCHAR2(3 BYTE), 
	"XCORE_GLOBAL" NUMBER(7,2), 
	"XCORE_CUSTOM" NUMBER(7,2), 
	"ID_CARGA_DIRIGIDA" NUMBER, 
	"ID_REPRE_CAMPANA_ESPECIALES" NUMBER, 
	"ES_FIADOR" VARCHAR2(30 BYTE) DEFAULT 'N'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 MAXSIZE UNLIMITED
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PR_DAT" ;
  CREATE UNIQUE INDEX "PR"."PK_REPRESTAMOS" ON "PR"."PR_REPRESTAMOS" ("CODIGO_EMPRESA", "ID_REPRESTAMO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 MAXSIZE UNLIMITED
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PR_DAT" ;
ALTER TABLE "PR"."PR_REPRESTAMOS" ADD CONSTRAINT "PK_REPRESTAMOS" PRIMARY KEY ("CODIGO_EMPRESA", "ID_REPRESTAMO")
  USING INDEX "PR"."PK_REPRESTAMOS"  ENABLE;

  CREATE INDEX "PR"."IND01_PR_REPRESTAMOS" ON "PR"."PR_REPRESTAMOS" ("CODIGO_EMPRESA", "NO_CREDITO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 MAXSIZE UNLIMITED
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PR_DAT" ;

  CREATE INDEX "PR"."IND02_PR_REPRESTAMOS" ON "PR"."PR_REPRESTAMOS" ("CODIGO_EMPRESA", "ESTADO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 MAXSIZE UNLIMITED
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PR_DAT" ;

  CREATE INDEX "PR"."IND3_PR_REPRESTAMO" ON "PR"."PR_REPRESTAMOS" ("CODIGO_CLIENTE", "ESTADO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PR_DAT" ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "PR"."TRG_BUI_PR_REPRESTAMOS" 
BEFORE INSERT OR UPDATE
ON PR.PR_REPRESTAMOS REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
  IF INSERTING THEN
     :new.fecha_adicion := sysdate;
     --PR_PKG_REPRESTAMOS.p_generar_bitacora(:new.ID_REPRESTAMO,NULL,'RE',NULL,'Carga inicial');
  ELSE 
     :new.fecha_modificacion := sysdate;
     UPDATE PR.PR_SOLICITUD_REPRESTAMO S
       SET S.ESTADO = NVL(:NEW.ESTADO, :OLD.ESTADO)
     WHERE S.CODIGO_EMPRESA = :NEW.CODIGO_EMPRESA
       AND S.ID_REPRESTAMO = NVL(:NEW.ID_REPRESTAMO, :OLD.ID_REPRESTAMO);
  END IF;
END;
/
ALTER TRIGGER "PR"."TRG_BUI_PR_REPRESTAMOS" ENABLE;


  GRANT SELECT ON "PR"."PR_REPRESTAMOS" TO "CDG";
  GRANT SELECT ON "PR"."PR_REPRESTAMOS" TO "BPR";
  GRANT SELECT ON "PR"."PR_REPRESTAMOS" TO PUBLIC;
  GRANT SELECT ON "PR"."PR_REPRESTAMOS" TO "PA" WITH GRANT OPTION;
