
  CREATE TABLE "PR"."PR_REPRESTAMO_PASO" 
   (	"ID_REPRESTAMO_PASO" NUMBER NOT NULL ENABLE, 
	"CODIGO_EMPRESA" NUMBER NOT NULL ENABLE, 
	"ID_REPRESTAMO" NUMBER, 
	"ID_APLICACION_PASO" NUMBER NOT NULL ENABLE, 
	"ID_ESTADO" NUMBER NOT NULL ENABLE, 
	"ADICIONADO_POR" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"FECHA_ADICION" DATE NOT NULL ENABLE, 
	"MODIFICADO_POR" VARCHAR2(30 BYTE), 
	"FECHA_MODIFICACION" DATE, 
	"AVANCE" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"INTENTOS" NUMBER DEFAULT 0, 
	"FECHA_ULTIMA_EJECUCION" DATE, 
	"MENSAJES" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 MAXSIZE UNLIMITED
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PR_DAT" ;
  CREATE UNIQUE INDEX "PR"."PR_REPRESTAMO_PASO_PK" ON "PR"."PR_REPRESTAMO_PASO" ("ID_REPRESTAMO_PASO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 MAXSIZE UNLIMITED
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PR_DAT" ;
ALTER TABLE "PR"."PR_REPRESTAMO_PASO" ADD CONSTRAINT "PR_REPRESTAMO_PASO_PK" PRIMARY KEY ("ID_REPRESTAMO_PASO")
  USING INDEX "PR"."PR_REPRESTAMO_PASO_PK"  ENABLE;

