CREATE TABLE PRODUCTOS
(
  COD_CAT_PRODUCTO      VARCHAR2(2)     NOT NULL,
  COD_PRODUCTO          VARCHAR2(4)     NOT NULL,
  COD_MONEDA            VARCHAR2(4)     NOT NULL,
  DESCRIPCION           VARCHAR2(80)    NOT NULL,
  COD_EMPRESA           VARCHAR2(5)     NOT NULL,
  DETALLE               VARCHAR2(1000),
  CLTE_PROSPECTO        VARCHAR2(500),
  NOM_FILTRO            VARCHAR2(10),
  NOM_IMAGEN            VARCHAR2(12),
  ABREVIATURA           VARCHAR2(5),
  REQUERIMIENTOS        VARCHAR2(500),
  COD_PRODUCTO_SB       VARCHAR2(5),
  TIPO_PERSONA          VARCHAR2(1),
  TIPO_INSTRUMENTO_SB   VARCHAR2(3),
  CONSTRAINT PK_PRODUCTOS
    PRIMARY KEY (COD_EMPRESA, COD_PRODUCTO)
);
