
  CREATE TABLE "PA"."MIMETYPES_LISTADO" 
   (	"ID" NUMBER(10,0) NOT NULL ENABLE, 
	"EXTENSION" VARCHAR2(15 BYTE) NOT NULL ENABLE, 
	"DESCRIPCION" VARCHAR2(600 BYTE), 
	"MIMETYPE_NOMBRE" VARCHAR2(600 BYTE), 
	"ADICIONADO_POR" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"FECHA_ADICION" DATE NOT NULL ENABLE, 
	"MODIFICADO_POR" VARCHAR2(30 BYTE), 
	"FECHA_MODIFICACION" DATE, 
	 CONSTRAINT "PK_MIMETYPES_LISTADO" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PA_DAT"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PA_DAT" ;

  CREATE INDEX "PA"."IDX_MIMETYPE_LISTADO" ON "PA"."MIMETYPES_LISTADO" ("EXTENSION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PA_IDX" ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "PR"."TRG_MIMETYPES_LISTADO" BEFORE INSERT OR UPDATE ON  PA.MIMETYPES_LISTADO REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW
BEGIN
   IF (INSERTING) THEN
      :NEW.ADICIONADO_POR := nvl(sys_context('APEX$SESSION','APP_USER'),user);
      :NEW.FECHA_ADICION := SYSDATE;
      :NEW.ID := PA.MIMETYPES_LISTADO_SEQ.NEXTVAL;
   ELSIF (UPDATING) THEN
      :NEW.MODIFICADO_POR := nvl(sys_context('APEX$SESSION','APP_USER'),user);
      :NEW.FECHA_MODIFICACION := SYSDATE;
   END IF;   
END;
/
ALTER TRIGGER "PR"."TRG_MIMETYPES_LISTADO" ENABLE;


  GRANT SELECT ON "PA"."MIMETYPES_LISTADO" TO "BPA";
