
  CREATE TABLE "PA"."PA_PARAMETROS_MVP" 
   (	"CODIGO_EMPRESA" NUMBER(4,0) NOT NULL ENABLE, 
	"CODIGO_MVP" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"CODIGO_PARAMETRO" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"DES_PARAMETRO" VARCHAR2(500 BYTE) NOT NULL ENABLE, 
	"VALOR" VARCHAR2(4000 BYTE), 
	"ADICIONADO_POR" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"FECHA_ADICION" DATE NOT NULL ENABLE, 
	"MODIFICADO_POR" VARCHAR2(30 BYTE), 
	"FECHA_MODIFICACION" DATE, 
	"VALOR_RAW" RAW(2000)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 MAXSIZE UNLIMITED
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PA_DAT" ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "PR"."TRG_BUI_PA_PARAMETROS_MVP" 
BEFORE INSERT OR UPDATE
ON pa.pa_parametros_MVP REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
  IF INSERTING THEN
     :new.fecha_adicion := sysdate;
     if :new.adicionado_por is null THEN
        :new.adicionado_por := user;
     end if;
  ELSE 
     :new.fecha_modificacion := sysdate;
     if :new.modificado_por is null THEN
        :new.modificado_por := user;
     end if;
  END IF;
END;
/
ALTER TRIGGER "PR"."TRG_BUI_PA_PARAMETROS_MVP" ENABLE;


  GRANT DELETE ON "PA"."PA_PARAMETROS_MVP" TO "PR" WITH GRANT OPTION;
  GRANT INSERT ON "PA"."PA_PARAMETROS_MVP" TO "PR" WITH GRANT OPTION;
  GRANT SELECT ON "PA"."PA_PARAMETROS_MVP" TO "PR" WITH GRANT OPTION;
  GRANT UPDATE ON "PA"."PA_PARAMETROS_MVP" TO "PR" WITH GRANT OPTION;
  GRANT SELECT ON "PA"."PA_PARAMETROS_MVP" TO "BPR";
