
  CREATE TABLE "PA"."PA_REPORTES_AUTOMATICOS" 
   (	"CODIGO_REPORTE" NUMBER, 
	"CODIGO_REFERENCIA" VARCHAR2(200 BYTE), 
	"FECHA_REPORTE" DATE, 
	"ID_APLICACION" NUMBER, 
	"ID_TIPO_DOCUMENTO" VARCHAR2(5 BYTE), 
	"ORIGEN_PKM" VARCHAR2(100 BYTE), 
	"URL_REPORTE" VARCHAR2(4000 BYTE), 
	"FORMATO_DOCUMENTO" VARCHAR2(30 BYTE), 
	"DIRECTORIO_DESTINO" VARCHAR2(600 BYTE), 
	"NOMBRE_ARCHIVO" VARCHAR2(100 BYTE), 
	"ENVIAR_API" VARCHAR2(1 BYTE), 
	"ESTADO_REPORTE" VARCHAR2(5 BYTE), 
	"FECHA_PROCESO" DATE, 
	"ADICIONADO_POR" VARCHAR2(30 BYTE), 
	"FECHA_ADICION" DATE, 
	"MODIFICADO_POR" VARCHAR2(30 BYTE), 
	"FECHA_MODIFICACION" DATE, 
	"MENSAJE" VARCHAR2(4000 BYTE), 
	"IDPROCESO" VARCHAR2(150 BYTE), 
	"ID_DOCS_REUTILIZAR" VARCHAR2(20 BYTE), 
	 CONSTRAINT "PK_REPORTES_AUTOMATICOS" PRIMARY KEY ("CODIGO_REPORTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PA_DAT"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PA_DAT" ;

  CREATE INDEX "PA"."ESTADO_TIPO_DOC_IDPROC_IDX" ON "PA"."PA_REPORTES_AUTOMATICOS" ("ESTADO_REPORTE", "ID_TIPO_DOCUMENTO", "IDPROCESO", "ORIGEN_PKM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PA_IDX" ;

  CREATE INDEX "PA"."REP_AUTOM_COD_REF_IDX" ON "PA"."PA_REPORTES_AUTOMATICOS" ("CODIGO_REFERENCIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PA_IDX" ;

  CREATE INDEX "PA"."REP_AUTOM_ORIGEN_IDX" ON "PA"."PA_REPORTES_AUTOMATICOS" ("ORIGEN_PKM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PA_IDX" ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "PA"."TRG_REPORTES_AUTOMATICOS" BEFORE INSERT OR UPDATE ON PA.PA_REPORTES_AUTOMATICOS REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW
BEGIN
   IF (INSERTING) THEN
      :NEW.ADICIONADO_POR := NVL(V('APP_USER'),USER);
      :NEW.FECHA_ADICION := SYSDATE;
      :NEW.CODIGO_REPORTE := PA.seq_REPORTES_AUTOMATICOS.NEXTVAL;
   ELSIF (UPDATING) THEN
      :NEW.MODIFICADO_POR := USER;
      :NEW.FECHA_MODIFICACION := SYSDATE;
   END IF;   
END;
/
ALTER TRIGGER "PA"."TRG_REPORTES_AUTOMATICOS" ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "PA"."TRG_REP_AUTOMATICOS" 
    BEFORE INSERT OR UPDATE
    ON PA.PA_REPORTES_AUTOMATICOS
    REFERENCING NEW AS NEW OLD AS OLD
    FOR EACH ROW
BEGIN
    IF (INSERTING) THEN
        :NEW.ADICIONADO_POR := NVL (SYS_CONTEXT ('APEX$SESSION', 'APP_USER'), USER);
        :NEW.FECHA_ADICION := SYSDATE;
        :NEW.MENSAJE := 'PENDIENTE';
    ELSIF (UPDATING) THEN
        :NEW.MODIFICADO_POR := NVL (SYS_CONTEXT ('APEX$SESSION', 'APP_USER'), USER);
        :NEW.FECHA_MODIFICACION := SYSDATE;
    END IF;

    PA.Bitacora_Reportes_Automaticos (pCodigoReporte   => :NEW.CODIGO_REPORTE,
                                      pNombreArchivo   => :NEW.NOMBRE_ARCHIVO,
                                      pEstado          => :NEW.ESTADO_REPORTE,
                                      pMensaje         => :NEW.MENSAJE,
                                      pIdProceso       => :NEW.IDPROCESO);
END;
/
ALTER TRIGGER "PA"."TRG_REP_AUTOMATICOS" ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "PA"."TRG_CREDITO_CONTROL_HELADO" 
   BEFORE UPDATE OF ESTADO_REPORTE
   ON PA.PA_REPORTES_AUTOMATICOS
   REFERENCING NEW AS New OLD AS Old
   FOR EACH ROW  
BEGIN
  IF :new.origen_pkm = 'Normal' AND :OLD.ESTADO_REPORTE = 'SP' AND :new.ESTADO_REPORTE = 'SP' THEN  
    -- Si esto ocurre es porque otro hilo de proceso está tomando el mismo registro
     PA.Bitacora_Reportes_Automaticos (pCodigoReporte   => :NEW.CODIGO_REPORTE,
                                      pNombreArchivo   => :NEW.NOMBRE_ARCHIVO,
                                      pEstado          => :NEW.ESTADO_REPORTE,
                                      pMensaje         => 'CONTROL. NO ENVIADO A PKM PARA NO DUPLICAR.' ,
                                      pIdProceso       => :NEW.IDPROCESO);
    RAISE_application_error(-20002,:new.codigo_reporte||'-No se permite cambiar de estado SP a SP nuevamente.'); 
  END IF; 
END;
/
ALTER TRIGGER "PA"."TRG_CREDITO_CONTROL_HELADO" ENABLE;


  GRANT SELECT ON "PA"."PA_REPORTES_AUTOMATICOS" TO "PR" WITH GRANT OPTION;
  GRANT SELECT ON "PA"."PA_REPORTES_AUTOMATICOS" TO "BPR";
