
  CREATE TABLE "PA"."PRODUCTOS_X_AGENCIA" 
   (	"COD_EMPRESA" VARCHAR2(5 BYTE), 
	"COD_AGENCIA" VARCHAR2(5 BYTE), 
	"COD_PRODUCTO" VARCHAR2(4 BYTE), 
	"ESTA_ACTIVO" VARCHAR2(1 BYTE), 
	 CONSTRAINT "CK_PRODUCTOSXAGENCIA_ESTAACTIV" CHECK ( ESTA_ACTIVO in ('S','N')             ) DISABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 80 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 196608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA_EFD" ;
  CREATE UNIQUE INDEX "PA"."PK_PRODUCTOSXAGENCIA" ON "PA"."PRODUCTOS_X_AGENCIA" ("COD_EMPRESA", "COD_AGENCIA", "COD_PRODUCTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 196608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IND_EFD" ;
ALTER TABLE "PA"."PRODUCTOS_X_AGENCIA" ADD CONSTRAINT "PK_PRODUCTOSXAGENCIA" PRIMARY KEY ("COD_EMPRESA", "COD_AGENCIA", "COD_PRODUCTO")
  USING INDEX "PA"."PK_PRODUCTOSXAGENCIA"  ENABLE;

   COMMENT ON COLUMN "PA"."PRODUCTOS_X_AGENCIA"."COD_EMPRESA" IS 'Codigo de la empresa a la que pertenece la informacion. Esta relacionada a la tabla PA.EMPRESA';
   COMMENT ON COLUMN "PA"."PRODUCTOS_X_AGENCIA"."COD_AGENCIA" IS 'Codigo agencia';
   COMMENT ON COLUMN "PA"."PRODUCTOS_X_AGENCIA"."COD_PRODUCTO" IS 'Codigo de producto';
   COMMENT ON COLUMN "PA"."PRODUCTOS_X_AGENCIA"."ESTA_ACTIVO" IS 'Indicador de si esta activo';
   COMMENT ON TABLE "PA"."PRODUCTOS_X_AGENCIA"  IS ' Productos por agencias';


  GRANT REFERENCES ON "PA"."PRODUCTOS_X_AGENCIA" TO PUBLIC;
  GRANT SELECT ON "PA"."PRODUCTOS_X_AGENCIA" TO "CONGEN";
  GRANT DELETE ON "PA"."PRODUCTOS_X_AGENCIA" TO "BPA";
  GRANT INSERT ON "PA"."PRODUCTOS_X_AGENCIA" TO "BPA";
  GRANT SELECT ON "PA"."PRODUCTOS_X_AGENCIA" TO "BPA";
  GRANT UPDATE ON "PA"."PRODUCTOS_X_AGENCIA" TO "BPA";
  GRANT ALTER ON "PA"."PRODUCTOS_X_AGENCIA" TO "BPA";
  GRANT ALTER ON "PA"."PRODUCTOS_X_AGENCIA" TO PUBLIC;
  GRANT DELETE ON "PA"."PRODUCTOS_X_AGENCIA" TO PUBLIC;
  GRANT INSERT ON "PA"."PRODUCTOS_X_AGENCIA" TO PUBLIC;
  GRANT SELECT ON "PA"."PRODUCTOS_X_AGENCIA" TO PUBLIC;
  GRANT UPDATE ON "PA"."PRODUCTOS_X_AGENCIA" TO PUBLIC;
  GRANT ALTER ON "PA"."PRODUCTOS_X_AGENCIA" TO "CONGEN";
  GRANT DELETE ON "PA"."PRODUCTOS_X_AGENCIA" TO "CONGEN";
  GRANT INSERT ON "PA"."PRODUCTOS_X_AGENCIA" TO "CONGEN";
  GRANT UPDATE ON "PA"."PRODUCTOS_X_AGENCIA" TO "CONGEN";
  GRANT SELECT ON "PA"."PRODUCTOS_X_AGENCIA" TO "SII";
